// Command emberc generates a deterministic prepared Go bundle from an explicit
// module manifest.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/besmpl/ember"
)

const (
	maxManifestBytes   = 1 << 20
	maxManifestModules = 4096
	maxSourceBytes     = 64 << 20
	maxParallelism     = 256
)

type compilerManifest struct {
	Package     string               `json:"package"`
	Output      string               `json:"output"`
	Entrypoints []compilerEntrypoint `json:"entrypoints"`
	Modules     []compilerModule     `json:"modules"`
	MaxBytes    int                  `json:"max_bytes,omitempty"`
	Parallelism int                  `json:"parallelism,omitempty"`
}

type compilerEntrypoint struct {
	Name   string `json:"name"`
	Module string `json:"module"`
}

type compilerModule struct {
	ID     string `json:"id"`
	Source string `json:"source"`
}

type compilerLoader map[string]ember.Source

func (loader compilerLoader) LoadModule(_ context.Context, id ember.ModuleID) (ember.Source, error) {
	source, ok := loader[id.String()]
	if !ok {
		return ember.Source{}, fmt.Errorf("module %s is not declared in the manifest", id)
	}
	return source, nil
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "emberc:", err)
		os.Exit(1)
	}
}

func run(arguments []string) error {
	flags := flag.NewFlagSet("emberc", flag.ContinueOnError)
	flags.SetOutput(io.Discard)
	check := flags.Bool("check", false, "verify that the generated output is fresh")
	if err := flags.Parse(arguments); err != nil {
		return err
	}
	if flags.NArg() != 1 {
		return fmt.Errorf("usage: emberc [-check] manifest.json")
	}
	manifestPath, err := filepath.Abs(flags.Arg(0))
	if err != nil {
		return fmt.Errorf("resolve manifest path: %w", err)
	}
	manifest, err := readCompilerManifest(manifestPath)
	if err != nil {
		return err
	}
	program, outputPath, err := loadCompilerProgram(context.Background(), manifestPath, manifest)
	if err != nil {
		return err
	}
	var generated bytes.Buffer
	if err := program.WritePreparedGo(&generated, ember.PreparedGoOptions{
		Package:  manifest.Package,
		MaxBytes: manifest.MaxBytes,
	}); err != nil {
		return fmt.Errorf("generate %s: %w", outputPath, err)
	}
	if *check {
		return checkCompilerOutput(outputPath, manifestPath, generated.Bytes())
	}
	return writeCompilerOutput(outputPath, generated.Bytes())
}

func readCompilerManifest(path string) (compilerManifest, error) {
	data, err := readBoundedFile(path, maxManifestBytes)
	if err != nil {
		return compilerManifest{}, fmt.Errorf("read manifest: %w", err)
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var manifest compilerManifest
	if err := decoder.Decode(&manifest); err != nil {
		return compilerManifest{}, fmt.Errorf("decode manifest: %w", err)
	}
	if err := requireJSONEnd(decoder); err != nil {
		return compilerManifest{}, fmt.Errorf("decode manifest: %w", err)
	}
	if err := validateCompilerManifest(manifest); err != nil {
		return compilerManifest{}, err
	}
	return manifest, nil
}

func requireJSONEnd(decoder *json.Decoder) error {
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		if err == nil {
			return fmt.Errorf("multiple JSON values")
		}
		return err
	}
	return nil
}

func validateCompilerManifest(manifest compilerManifest) error {
	if manifest.Package == "" {
		return fmt.Errorf("manifest package is required")
	}
	if manifest.Output == "" {
		return fmt.Errorf("manifest output is required")
	}
	if len(manifest.Entrypoints) == 0 {
		return fmt.Errorf("manifest entrypoints are required")
	}
	if len(manifest.Modules) == 0 {
		return fmt.Errorf("manifest modules are required")
	}
	if len(manifest.Modules) > maxManifestModules {
		return fmt.Errorf("manifest has %d modules, limit is %d", len(manifest.Modules), maxManifestModules)
	}
	if len(manifest.Entrypoints) > maxManifestModules {
		return fmt.Errorf("manifest has %d entrypoints, limit is %d", len(manifest.Entrypoints), maxManifestModules)
	}
	if manifest.MaxBytes < 0 {
		return fmt.Errorf("manifest max_bytes is negative")
	}
	if manifest.Parallelism < 0 || manifest.Parallelism > maxParallelism {
		return fmt.Errorf("manifest parallelism %d is outside 0..%d", manifest.Parallelism, maxParallelism)
	}
	return nil
}

func loadCompilerProgram(
	ctx context.Context,
	manifestPath string,
	manifest compilerManifest,
) (*ember.Program, string, error) {
	base := filepath.Dir(manifestPath)
	outputPath, err := resolveManifestPath(base, manifest.Output)
	if err != nil {
		return nil, "", fmt.Errorf("resolve manifest output: %w", err)
	}
	if outputPath == manifestPath {
		return nil, "", fmt.Errorf("manifest output cannot overwrite the manifest")
	}
	loader := make(compilerLoader, len(manifest.Modules))
	moduleIDs := make(map[string]ember.ModuleID, len(manifest.Modules))
	totalSourceBytes := 0
	for index, module := range manifest.Modules {
		id, err := parseManifestModuleID(module.ID)
		if err != nil {
			return nil, "", fmt.Errorf("manifest module %d: %w", index, err)
		}
		if module.Source == "" {
			return nil, "", fmt.Errorf("manifest module %s source is required", module.ID)
		}
		if _, duplicate := loader[id.String()]; duplicate {
			return nil, "", fmt.Errorf("manifest module %s is duplicated", module.ID)
		}
		sourcePath, err := resolveManifestPath(base, module.Source)
		if err != nil {
			return nil, "", fmt.Errorf("resolve module %s source: %w", module.ID, err)
		}
		if sourcePath == outputPath {
			return nil, "", fmt.Errorf("manifest output cannot overwrite module source %s", module.Source)
		}
		remaining := maxSourceBytes - totalSourceBytes
		data, err := readBoundedFile(sourcePath, remaining)
		if err != nil {
			return nil, "", fmt.Errorf("read module %s from %s: %w", module.ID, module.Source, err)
		}
		totalSourceBytes += len(data)
		loader[id.String()] = ember.Source{Name: module.ID, Text: string(data)}
		moduleIDs[id.String()] = id
	}
	entrypoints := make([]ember.Entrypoint, len(manifest.Entrypoints))
	entrypointNames := make(map[string]bool, len(manifest.Entrypoints))
	for index, entrypoint := range manifest.Entrypoints {
		if entrypoint.Name == "" {
			return nil, "", fmt.Errorf("manifest entrypoint %d name is required", index)
		}
		if entrypointNames[entrypoint.Name] {
			return nil, "", fmt.Errorf("manifest entrypoint name %q is duplicated", entrypoint.Name)
		}
		id, err := parseManifestModuleID(entrypoint.Module)
		if err != nil {
			return nil, "", fmt.Errorf("manifest entrypoint %q: %w", entrypoint.Name, err)
		}
		declared, ok := moduleIDs[id.String()]
		if !ok {
			return nil, "", fmt.Errorf("manifest entrypoint %q module %s is not declared", entrypoint.Name, id)
		}
		entrypointNames[entrypoint.Name] = true
		entrypoints[index] = ember.Entrypoint{Name: entrypoint.Name, Module: declared}
	}
	parallelism := manifest.Parallelism
	if parallelism == 0 {
		parallelism = 1
	}
	program, _, err := ember.LoadProgram(ctx, loader, ember.ProgramOptions{
		Entrypoints: entrypoints,
		Parallelism: parallelism,
		Limits: ember.ProgramLimits{
			MaxModules:          uint64(len(manifest.Modules)),
			MaxTotalSourceBytes: uint64(maxSourceBytes),
		},
	})
	if err != nil {
		return nil, "", fmt.Errorf("load Program: %w", err)
	}
	return program, outputPath, nil
}

func parseManifestModuleID(text string) (ember.ModuleID, error) {
	kind, path, ok := strings.Cut(text, ":")
	if !ok || path == "" {
		return ember.ModuleID{}, fmt.Errorf("invalid module ID %q", text)
	}
	var id ember.ModuleID
	switch kind {
	case string(ember.ModuleLogical):
		id = ember.LogicalModule(path)
	case string(ember.ModuleHost):
		id = ember.HostModule(path)
	default:
		return ember.ModuleID{}, fmt.Errorf("invalid module kind %q", kind)
	}
	if id.String() != text {
		return ember.ModuleID{}, fmt.Errorf("invalid module ID %q", text)
	}
	return id, nil
}

func resolveManifestPath(base, path string) (string, error) {
	if !filepath.IsAbs(path) {
		path = filepath.Join(base, path)
	}
	resolved, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	return resolved, nil
}

func readBoundedFile(path string, limit int) ([]byte, error) {
	if limit < 0 {
		return nil, fmt.Errorf("size limit exceeded")
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	data, err := io.ReadAll(io.LimitReader(file, int64(limit)+1))
	if err != nil {
		return nil, err
	}
	if len(data) > limit {
		return nil, fmt.Errorf("file exceeds %d-byte limit", limit)
	}
	return data, nil
}

func checkCompilerOutput(path, manifestPath string, expected []byte) error {
	metadata, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("read output %s: %w", path, err)
	}
	stale := func() error {
		return fmt.Errorf("%s is stale; run emberc %s", path, manifestPath)
	}
	if metadata.Size() != int64(len(expected)) {
		return stale()
	}
	actual, err := readBoundedFile(path, len(expected))
	if err != nil {
		return fmt.Errorf("read output %s: %w", path, err)
	}
	if !bytes.Equal(actual, expected) {
		return stale()
	}
	return nil
}

func writeCompilerOutput(path string, content []byte) error {
	directory := filepath.Dir(path)
	temporary, err := os.CreateTemp(directory, ".emberc-*.tmp")
	if err != nil {
		return fmt.Errorf("create temporary output for %s: %w", path, err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o644); err != nil {
		temporary.Close()
		return fmt.Errorf("set output permissions: %w", err)
	}
	if _, err := temporary.Write(content); err != nil {
		temporary.Close()
		return fmt.Errorf("write temporary output: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close temporary output: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("replace output %s: %w", path, err)
	}
	return nil
}
