// Code generated by Ember's prepared compiler; DO NOT EDIT.

package preparedfixture

import (
	emberapi "github.com/besmpl/ember"
	"math"
)

func externalUpdate() (float64, bool) {
	var v6 float64
	var v7 float64
	var v8 float64
	var v9 float64
	var v11 float64
	var v12 float64
	var v13 float64
	var v14 float64
	var v15 float64
	var v16 float64
	var v17 float64
	v11 = math.Float64frombits(0x0000000000000000)
	v12 = math.Float64frombits(0x3ff0000000000000)
	v13 = math.Float64frombits(0x4050000000000000)
	v14 = math.Float64frombits(0x3ff0000000000000)
	v6 = v11
	v7 = v12
	v8 = v13
	v9 = v14
	goto b1
b1:
	if math.IsNaN(v7) {
		return 0, false
	}
	if math.IsNaN(v8) {
		return 0, false
	}
	if math.IsNaN(v9) {
		return 0, false
	}
	if (v9 > 0 && v7 > v8) || (v9 <= 0 && v7 < v8) {
		goto b3
	}
	goto b2
b2:
	v15 = v7
	v16 = v6 + v15
	v17 = v7 + v9
	v6 = v16
	v7 = v17
	v8 = v8
	v9 = v9
	goto b1
b3:
	return v6, true
}

func externalUpdatePreparedBody(context emberapi.PreparedContext) emberapi.PreparedExit {
	var v6 float64
	var v7 float64
	var v8 float64
	var v9 float64
	var v11 float64
	var v12 float64
	var v13 float64
	var v14 float64
	var v15 float64
	var v16 float64
	var v17 float64
	v11 = math.Float64frombits(0x0000000000000000)
	v12 = math.Float64frombits(0x3ff0000000000000)
	v13 = math.Float64frombits(0x4050000000000000)
	v14 = math.Float64frombits(0x3ff0000000000000)
	v6 = v11
	v7 = v12
	v8 = v13
	v9 = v14
	goto b1
b1:
	if math.IsNaN(v7) {
		exit := context.ReplayBeforeOperation(4, 4)
		context.SpillNumber(0, 0, v6)
		context.SpillNumber(1, 1, v7)
		context.SpillNumber(2, 2, v8)
		context.SpillNumber(3, 3, v9)
		return exit
	}
	if math.IsNaN(v8) {
		exit := context.ReplayBeforeOperation(4, 4)
		context.SpillNumber(0, 0, v6)
		context.SpillNumber(1, 1, v7)
		context.SpillNumber(2, 2, v8)
		context.SpillNumber(3, 3, v9)
		return exit
	}
	if math.IsNaN(v9) {
		exit := context.ReplayBeforeOperation(4, 4)
		context.SpillNumber(0, 0, v6)
		context.SpillNumber(1, 1, v7)
		context.SpillNumber(2, 2, v8)
		context.SpillNumber(3, 3, v9)
		return exit
	}
	if (v9 > 0 && v7 > v8) || (v9 <= 0 && v7 < v8) {
		goto b3
	}
	goto b2
b2:
	v15 = v7
	v16 = v6 + v15
	v17 = v7 + v9
	v6 = v16
	v7 = v17
	v8 = v8
	v9 = v9
	goto b1
b3:
	return emberapi.PreparedReturnOneNumber(v6)
}

func externalUpdatePrepared(context emberapi.PreparedContext) emberapi.PreparedExit {
	return externalUpdatePreparedBody(context)
}

var Bundle = emberapi.NewPreparedBundle(1, 1, [32]byte{0x91, 0xf5, 0xd7, 0x5e, 0x90, 0x25, 0xf3, 0xb9, 0x2d, 0x12, 0x8a, 0xd4, 0x1b, 0xd8, 0x81, 0x82, 0x19, 0x39, 0xf1, 0x6e, 0x22, 0xc1, 0x20, 0xff, 0x69, 0x8f, 0xe3, 0xef, 0x98, 0xdd, 0x7a, 0x12}, [][]emberapi.PreparedFunction{{nil, externalUpdatePrepared}})
