// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedProjectileSweep(p0 float64) (float64, bool) {
	var v1 float64
	var v39 float64
	var v40 float64
	var v41 float64
	var v42 float64
	var v72 float64
	var v73 float64
	var v74 float64
	var v75 float64
	var v105 float64
	var v106 float64
	var v107 float64
	var v108 float64
	var v112 float64
	var v138 float64
	var v139 float64
	var v140 float64
	var v141 float64
	var v145 float64
	var v168 bool
	var v171 float64
	var v172 float64
	var v173 float64
	var v174 float64
	var v178 float64
	var v204 float64
	var v234 float64
	var v235 float64
	var v236 float64
	var v237 float64
	var v238 float64
	var v239 float64
	var v240 bool
	var v242 float64
	var v243 float64
	var v244 float64
	var v245 float64
	var v246 float64
	var v247 bool
	var v249 float64
	var v250 float64
	var v251 float64
	var v252 float64
	var v253 float64
	var v254 bool
	var v256 float64
	var v257 float64
	var v258 float64
	var v259 float64
	var v260 float64
	var v261 bool
	var v264 float64
	var v265 float64
	var v266 float64
	var v267 float64
	var v269 float64
	var v270 float64
	var v271 float64
	var v272 float64
	var v274 float64
	var v275 float64
	var v276 float64
	var v277 float64
	var v279 float64
	var v280 float64
	var v281 float64
	var v282 float64
	var v283 float64
	var v287 float64
	var v288 float64
	var v289 float64
	var v295 float64
	var v296 bool
	var v297 float64
	var v298 float64
	var v299 float64
	var v300 float64
	var v301 float64
	var v302 float64
	var v308 float64
	var v309 float64
	var v310 float64
	var v311 float64
	var v312 float64
	var v313 float64
	var v314 float64
	var v315 float64
	var v316 float64
	var v317 float64
	var v318 float64
	var v319 float64
	var v320 float64
	var v321 float64
	var v322 float64
	var v323 float64
	var v324 float64
	var v325 float64
	var v326 float64
	var v327 float64
	var v328 float64
	var v329 bool
	var v330 float64
	var v331 float64
	var v332 float64
	var v333 float64
	var v334 float64
	var v335 float64
	var v336 bool
	var v337 float64
	var v338 float64
	var v339 bool
	var v340 bool
	var v341 float64
	var v347 float64
	var v348 float64
	var v349 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r0_4 float64
	_ = r0_4
	var r0_5 bool
	_ = r0_5
	var r1_0 float64
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r1_3 float64
	_ = r1_3
	var r1_4 float64
	_ = r1_4
	var r1_5 bool
	_ = r1_5
	var r2_0 float64
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 float64
	_ = r2_2
	var r2_3 float64
	_ = r2_3
	var r2_4 float64
	_ = r2_4
	var r2_5 bool
	_ = r2_5
	var r3_0 float64
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r3_2 float64
	_ = r3_2
	var r3_3 float64
	_ = r3_3
	var r3_4 float64
	_ = r3_4
	var r3_5 bool
	_ = r3_5
	var r4_0 float64
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r4_2 float64
	_ = r4_2
	var r4_3 float64
	_ = r4_3
	var r5_0 float64
	_ = r5_0
	var r5_1 float64
	_ = r5_1
	var r5_2 float64
	_ = r5_2
	var r5_3 float64
	_ = r5_3
	var r6_0 float64
	_ = r6_0
	var r6_1 float64
	_ = r6_1
	var r6_2 float64
	_ = r6_2
	var r6_3 float64
	_ = r6_3
	var r7_0 float64
	_ = r7_0
	var r7_1 float64
	_ = r7_1
	var r7_2 float64
	_ = r7_2
	var r7_3 float64
	_ = r7_3
	var ra0_0 [4]float64
	var ra0_1 [4]float64
	var ra0_2 [4]float64
	var ra0_3 [4]float64
	var ra0_4 [4]float64
	var ra0_5 [4]bool
	var ri0 int
	_ = ri0
	var ra1_0 [4]float64
	var ra1_1 [4]float64
	var ra1_2 [4]float64
	var ra1_3 [4]float64
	var ri1 int
	_ = ri1
	v1 = p0
	v234 = v1
	v235 = v234 - math.Floor(v234/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	r0_0 = v235
	v236 = math.Float64frombits(0x0000000000000000)
	r0_1 = v236
	v237 = math.Float64frombits(0x4008000000000000)
	r0_2 = v237
	v238 = math.Float64frombits(0x3ff0000000000000)
	r0_3 = v238
	v239 = math.Float64frombits(0x4028000000000000)
	r0_4 = v239
	v240 = true
	r0_5 = v240
	ra0_0[0] = r0_0
	ra0_1[0] = r0_1
	ra0_2[0] = r0_2
	ra0_3[0] = r0_3
	ra0_4[0] = r0_4
	ra0_5[0] = r0_5
	v242 = math.Float64frombits(0x4014000000000000)
	r1_0 = v242
	v243 = math.Float64frombits(0xc000000000000000)
	r1_1 = v243
	v244 = math.Float64frombits(0x4000000000000000)
	r1_2 = v244
	v245 = math.Float64frombits(0x4000000000000000)
	r1_3 = v245
	v246 = math.Float64frombits(0x4022000000000000)
	r1_4 = v246
	v247 = true
	r1_5 = v247
	ra0_0[1] = r1_0
	ra0_1[1] = r1_1
	ra0_2[1] = r1_2
	ra0_3[1] = r1_3
	ra0_4[1] = r1_4
	ra0_5[1] = r1_5
	v249 = math.Float64frombits(0xc010000000000000)
	r2_0 = v249
	v250 = math.Float64frombits(0x4008000000000000)
	r2_1 = v250
	v251 = math.Float64frombits(0x4010000000000000)
	r2_2 = v251
	v252 = math.Float64frombits(0xbff0000000000000)
	r2_3 = v252
	v253 = math.Float64frombits(0x402e000000000000)
	r2_4 = v253
	v254 = true
	r2_5 = v254
	ra0_0[2] = r2_0
	ra0_1[2] = r2_1
	ra0_2[2] = r2_2
	ra0_3[2] = r2_3
	ra0_4[2] = r2_4
	ra0_5[2] = r2_5
	v256 = math.Float64frombits(0x4020000000000000)
	r3_0 = v256
	v257 = math.Float64frombits(0x3ff0000000000000)
	r3_1 = v257
	v258 = math.Float64frombits(0x3ff0000000000000)
	r3_2 = v258
	v259 = math.Float64frombits(0x4008000000000000)
	r3_3 = v259
	v260 = math.Float64frombits(0x401c000000000000)
	r3_4 = v260
	v261 = true
	r3_5 = v261
	ra0_0[3] = r3_0
	ra0_1[3] = r3_1
	ra0_2[3] = r3_2
	ra0_3[3] = r3_3
	ra0_4[3] = r3_4
	ra0_5[3] = r3_5
	v264 = math.Float64frombits(0x4038000000000000)
	r4_0 = v264
	v265 = math.Float64frombits(0x4020000000000000)
	r4_1 = v265
	v266 = math.Float64frombits(0x4014000000000000)
	r4_2 = v266
	v267 = math.Float64frombits(0x4054000000000000)
	r4_3 = v267
	ra1_0[0] = r4_0
	ra1_1[0] = r4_1
	ra1_2[0] = r4_2
	ra1_3[0] = r4_3
	v269 = math.Float64frombits(0x4043000000000000)
	r5_0 = v269
	v270 = math.Float64frombits(0x4030000000000000)
	r5_1 = v270
	v271 = math.Float64frombits(0x4010000000000000)
	r5_2 = v271
	v272 = math.Float64frombits(0x4051800000000000)
	r5_3 = v272
	ra1_0[1] = r5_0
	ra1_1[1] = r5_1
	ra1_2[1] = r5_2
	ra1_3[1] = r5_3
	v274 = math.Float64frombits(0x404a000000000000)
	r6_0 = v274
	v275 = math.Float64frombits(0x4032000000000000)
	r6_1 = v275
	v276 = math.Float64frombits(0x4018000000000000)
	r6_2 = v276
	v277 = math.Float64frombits(0x405b800000000000)
	r6_3 = v277
	ra1_0[2] = r6_0
	ra1_1[2] = r6_1
	ra1_2[2] = r6_2
	ra1_3[2] = r6_3
	v279 = math.Float64frombits(0x4050000000000000)
	r7_0 = v279
	v280 = math.Float64frombits(0x403c000000000000)
	r7_1 = v280
	v281 = math.Float64frombits(0x4014000000000000)
	r7_2 = v281
	v282 = math.Float64frombits(0x4056800000000000)
	r7_3 = v282
	ra1_0[3] = r7_0
	ra1_1[3] = r7_1
	ra1_2[3] = r7_2
	ra1_3[3] = r7_3
	v283 = math.Float64frombits(0x0000000000000000)
	v287 = math.Float64frombits(0x3ff0000000000000)
	v288 = math.Float64frombits(0x403e000000000000)
	v289 = math.Float64frombits(0x3ff0000000000000)
	v39 = v283
	v40 = v287
	v41 = v288
	v42 = v289
	goto b1
b1:
	if math.IsNaN(v40) {
		return 0, false
	}
	if math.IsNaN(v41) {
		return 0, false
	}
	if math.IsNaN(v42) {
		return 0, false
	}
	if (v42 > 0 && v40 > v41) || (v42 <= 0 && v40 < v41) {
		goto b16
	}
	goto b2
b2:
	ri0 = 0
	v72 = v39
	v73 = v40
	v74 = v41
	v75 = v42
	goto b3
b3:
	if ri0 >= 4 {
		goto b15
	}
	v295 = float64(ri0 + 1)
	ri0++
	goto b4
b4:
	if v295 < 1 || v295 > 4 {
		return 0, false
	}
	v296 = ra0_5[int(v295)-1]
	if !v296 {
		v72 = v72
		v73 = v73
		v74 = v74
		v75 = v75
		goto b3
	}
	goto b5
b5:
	if v295 < 1 || v295 > 4 {
		return 0, false
	}
	v297 = ra0_0[int(v295)-1]
	if v295 < 1 || v295 > 4 {
		return 0, false
	}
	v298 = ra0_2[int(v295)-1]
	v299 = v297 + v298
	if v295 < 1 || v295 > 4 {
		return 0, false
	}
	ra0_0[int(v295)-1] = v299
	if v295 < 1 || v295 > 4 {
		return 0, false
	}
	v300 = ra0_1[int(v295)-1]
	if v295 < 1 || v295 > 4 {
		return 0, false
	}
	v301 = ra0_3[int(v295)-1]
	v302 = v300 + v301
	if v295 < 1 || v295 > 4 {
		return 0, false
	}
	ra0_1[int(v295)-1] = v302
	ri1 = 0
	v105 = v72
	v106 = v73
	v107 = v74
	v108 = v75
	v112 = v295
	goto b6
b6:
	if ri1 >= 4 {
		v138 = v105
		v139 = v106
		v140 = v107
		v141 = v108
		v145 = v112
		goto b10
	}
	v308 = float64(ri1 + 1)
	ri1++
	goto b7
b7:
	if v308 < 1 || v308 > 4 {
		return 0, false
	}
	v309 = ra1_3[int(v308)-1]
	if math.IsNaN(v309) {
		return 0, false
	}
	if !(v309 > math.Float64frombits(0x0000000000000000)) {
		v105 = v105
		v106 = v106
		v107 = v107
		v108 = v108
		v112 = v112
		goto b6
	}
	goto b8
b8:
	if v112 < 1 || v112 > 4 {
		return 0, false
	}
	v310 = ra0_0[int(v112)-1]
	if v308 < 1 || v308 > 4 {
		return 0, false
	}
	v311 = ra1_0[int(v308)-1]
	v312 = v310 - v311
	if v112 < 1 || v112 > 4 {
		return 0, false
	}
	v313 = ra0_1[int(v112)-1]
	if v308 < 1 || v308 > 4 {
		return 0, false
	}
	v314 = ra1_1[int(v308)-1]
	v315 = v313 - v314
	v316 = v312
	v317 = v312
	v318 = v316 * v317
	v319 = v315
	v320 = v315
	v321 = v319 * v320
	v322 = v318 + v321
	if v308 < 1 || v308 > 4 {
		return 0, false
	}
	v323 = ra1_2[int(v308)-1]
	if v308 < 1 || v308 > 4 {
		return 0, false
	}
	v324 = ra1_2[int(v308)-1]
	v325 = v323 * v324
	if math.IsNaN(v322) {
		return 0, false
	}
	if math.IsNaN(v325) {
		return 0, false
	}
	if v322 > v325 {
		v105 = v105
		v106 = v106
		v107 = v107
		v108 = v108
		v112 = v112
		goto b6
	}
	goto b9
b9:
	if v308 < 1 || v308 > 4 {
		return 0, false
	}
	v326 = ra1_3[int(v308)-1]
	if v112 < 1 || v112 > 4 {
		return 0, false
	}
	v327 = ra0_4[int(v112)-1]
	v328 = v326 - v327
	if v308 < 1 || v308 > 4 {
		return 0, false
	}
	ra1_3[int(v308)-1] = v328
	v329 = false
	if v112 < 1 || v112 > 4 {
		return 0, false
	}
	ra0_5[int(v112)-1] = v329
	if v308 < 1 || v308 > 4 {
		return 0, false
	}
	v330 = ra1_3[int(v308)-1]
	v331 = v105 + v330
	v332 = v106
	v333 = v331 + v332
	v138 = v333
	v139 = v106
	v140 = v107
	v141 = v108
	v145 = v112
	goto b10
b10:
	if v145 < 1 || v145 > 4 {
		return 0, false
	}
	v334 = ra0_0[int(v145)-1]
	v335 = math.Float64frombits(0x4054000000000000)
	if math.IsNaN(v334) {
		return 0, false
	}
	if math.IsNaN(v335) {
		return 0, false
	}
	v336 = v334 > v335
	if !v336 {
		goto b12
	}
	goto b11
b11:
	v168 = v336
	v171 = v138
	v172 = v139
	v173 = v140
	v174 = v141
	v178 = v145
	goto b13
b12:
	if v145 < 1 || v145 > 4 {
		return 0, false
	}
	v337 = ra0_1[int(v145)-1]
	v338 = math.Float64frombits(0x4044000000000000)
	if math.IsNaN(v337) {
		return 0, false
	}
	if math.IsNaN(v338) {
		return 0, false
	}
	v339 = v337 > v338
	v168 = v339
	v171 = v138
	v172 = v139
	v173 = v140
	v174 = v141
	v178 = v145
	goto b13
b13:
	if !v168 {
		v72 = v171
		v73 = v172
		v74 = v173
		v75 = v174
		goto b3
	}
	goto b14
b14:
	v340 = false
	if v178 < 1 || v178 > 4 {
		return 0, false
	}
	ra0_5[int(v178)-1] = v340
	v72 = v171
	v73 = v172
	v74 = v173
	v75 = v174
	goto b3
b15:
	v341 = v73 + v75
	v39 = v72
	v40 = v341
	v41 = v74
	v42 = v75
	goto b1
b16:
	ri1 = 0
	v204 = v39
	goto b17
b17:
	if ri1 >= 4 {
		goto b19
	}
	v347 = float64(ri1 + 1)
	ri1++
	goto b18
b18:
	if v347 < 1 || v347 > 4 {
		return 0, false
	}
	v348 = ra1_3[int(v347)-1]
	v349 = v204 + v348
	v204 = v349
	goto b17
b19:
	return v204, true
}

func backendGeneratedProjectileSweepPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v39 float64
	var v40 float64
	var v41 float64
	var v42 float64
	var v72 float64
	var v73 float64
	var v74 float64
	var v75 float64
	var v105 float64
	var v106 float64
	var v107 float64
	var v108 float64
	var v112 float64
	var v138 float64
	var v139 float64
	var v140 float64
	var v141 float64
	var v145 float64
	var v168 bool
	var v171 float64
	var v172 float64
	var v173 float64
	var v174 float64
	var v178 float64
	var v204 float64
	var v234 float64
	var v235 float64
	var v236 float64
	var v237 float64
	var v238 float64
	var v239 float64
	var v240 bool
	var v242 float64
	var v243 float64
	var v244 float64
	var v245 float64
	var v246 float64
	var v247 bool
	var v249 float64
	var v250 float64
	var v251 float64
	var v252 float64
	var v253 float64
	var v254 bool
	var v256 float64
	var v257 float64
	var v258 float64
	var v259 float64
	var v260 float64
	var v261 bool
	var v264 float64
	var v265 float64
	var v266 float64
	var v267 float64
	var v269 float64
	var v270 float64
	var v271 float64
	var v272 float64
	var v274 float64
	var v275 float64
	var v276 float64
	var v277 float64
	var v279 float64
	var v280 float64
	var v281 float64
	var v282 float64
	var v283 float64
	var v287 float64
	var v288 float64
	var v289 float64
	var v295 float64
	var v296 bool
	var v297 float64
	var v298 float64
	var v299 float64
	var v300 float64
	var v301 float64
	var v302 float64
	var v308 float64
	var v309 float64
	var v310 float64
	var v311 float64
	var v312 float64
	var v313 float64
	var v314 float64
	var v315 float64
	var v316 float64
	var v317 float64
	var v318 float64
	var v319 float64
	var v320 float64
	var v321 float64
	var v322 float64
	var v323 float64
	var v324 float64
	var v325 float64
	var v326 float64
	var v327 float64
	var v328 float64
	var v329 bool
	var v330 float64
	var v331 float64
	var v332 float64
	var v333 float64
	var v334 float64
	var v335 float64
	var v336 bool
	var v337 float64
	var v338 float64
	var v339 bool
	var v340 bool
	var v341 float64
	var v347 float64
	var v348 float64
	var v349 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r0_4 float64
	_ = r0_4
	var r0_5 bool
	_ = r0_5
	var r1_0 float64
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r1_3 float64
	_ = r1_3
	var r1_4 float64
	_ = r1_4
	var r1_5 bool
	_ = r1_5
	var r2_0 float64
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 float64
	_ = r2_2
	var r2_3 float64
	_ = r2_3
	var r2_4 float64
	_ = r2_4
	var r2_5 bool
	_ = r2_5
	var r3_0 float64
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r3_2 float64
	_ = r3_2
	var r3_3 float64
	_ = r3_3
	var r3_4 float64
	_ = r3_4
	var r3_5 bool
	_ = r3_5
	var r4_0 float64
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r4_2 float64
	_ = r4_2
	var r4_3 float64
	_ = r4_3
	var r5_0 float64
	_ = r5_0
	var r5_1 float64
	_ = r5_1
	var r5_2 float64
	_ = r5_2
	var r5_3 float64
	_ = r5_3
	var r6_0 float64
	_ = r6_0
	var r6_1 float64
	_ = r6_1
	var r6_2 float64
	_ = r6_2
	var r6_3 float64
	_ = r6_3
	var r7_0 float64
	_ = r7_0
	var r7_1 float64
	_ = r7_1
	var r7_2 float64
	_ = r7_2
	var r7_3 float64
	_ = r7_3
	var ra0_0 [4]float64
	var ra0_1 [4]float64
	var ra0_2 [4]float64
	var ra0_3 [4]float64
	var ra0_4 [4]float64
	var ra0_5 [4]bool
	var ri0 int
	_ = ri0
	var ra1_0 [4]float64
	var ra1_1 [4]float64
	var ra1_2 [4]float64
	var ra1_3 [4]float64
	var ri1 int
	_ = ri1
	v1 = p0
	v234 = v1
	v235 = v234 - math.Floor(v234/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	r0_0 = v235
	v236 = math.Float64frombits(0x0000000000000000)
	r0_1 = v236
	v237 = math.Float64frombits(0x4008000000000000)
	r0_2 = v237
	v238 = math.Float64frombits(0x3ff0000000000000)
	r0_3 = v238
	v239 = math.Float64frombits(0x4028000000000000)
	r0_4 = v239
	v240 = true
	r0_5 = v240
	ra0_0[0] = r0_0
	ra0_1[0] = r0_1
	ra0_2[0] = r0_2
	ra0_3[0] = r0_3
	ra0_4[0] = r0_4
	ra0_5[0] = r0_5
	v242 = math.Float64frombits(0x4014000000000000)
	r1_0 = v242
	v243 = math.Float64frombits(0xc000000000000000)
	r1_1 = v243
	v244 = math.Float64frombits(0x4000000000000000)
	r1_2 = v244
	v245 = math.Float64frombits(0x4000000000000000)
	r1_3 = v245
	v246 = math.Float64frombits(0x4022000000000000)
	r1_4 = v246
	v247 = true
	r1_5 = v247
	ra0_0[1] = r1_0
	ra0_1[1] = r1_1
	ra0_2[1] = r1_2
	ra0_3[1] = r1_3
	ra0_4[1] = r1_4
	ra0_5[1] = r1_5
	v249 = math.Float64frombits(0xc010000000000000)
	r2_0 = v249
	v250 = math.Float64frombits(0x4008000000000000)
	r2_1 = v250
	v251 = math.Float64frombits(0x4010000000000000)
	r2_2 = v251
	v252 = math.Float64frombits(0xbff0000000000000)
	r2_3 = v252
	v253 = math.Float64frombits(0x402e000000000000)
	r2_4 = v253
	v254 = true
	r2_5 = v254
	ra0_0[2] = r2_0
	ra0_1[2] = r2_1
	ra0_2[2] = r2_2
	ra0_3[2] = r2_3
	ra0_4[2] = r2_4
	ra0_5[2] = r2_5
	v256 = math.Float64frombits(0x4020000000000000)
	r3_0 = v256
	v257 = math.Float64frombits(0x3ff0000000000000)
	r3_1 = v257
	v258 = math.Float64frombits(0x3ff0000000000000)
	r3_2 = v258
	v259 = math.Float64frombits(0x4008000000000000)
	r3_3 = v259
	v260 = math.Float64frombits(0x401c000000000000)
	r3_4 = v260
	v261 = true
	r3_5 = v261
	ra0_0[3] = r3_0
	ra0_1[3] = r3_1
	ra0_2[3] = r3_2
	ra0_3[3] = r3_3
	ra0_4[3] = r3_4
	ra0_5[3] = r3_5
	v264 = math.Float64frombits(0x4038000000000000)
	r4_0 = v264
	v265 = math.Float64frombits(0x4020000000000000)
	r4_1 = v265
	v266 = math.Float64frombits(0x4014000000000000)
	r4_2 = v266
	v267 = math.Float64frombits(0x4054000000000000)
	r4_3 = v267
	ra1_0[0] = r4_0
	ra1_1[0] = r4_1
	ra1_2[0] = r4_2
	ra1_3[0] = r4_3
	v269 = math.Float64frombits(0x4043000000000000)
	r5_0 = v269
	v270 = math.Float64frombits(0x4030000000000000)
	r5_1 = v270
	v271 = math.Float64frombits(0x4010000000000000)
	r5_2 = v271
	v272 = math.Float64frombits(0x4051800000000000)
	r5_3 = v272
	ra1_0[1] = r5_0
	ra1_1[1] = r5_1
	ra1_2[1] = r5_2
	ra1_3[1] = r5_3
	v274 = math.Float64frombits(0x404a000000000000)
	r6_0 = v274
	v275 = math.Float64frombits(0x4032000000000000)
	r6_1 = v275
	v276 = math.Float64frombits(0x4018000000000000)
	r6_2 = v276
	v277 = math.Float64frombits(0x405b800000000000)
	r6_3 = v277
	ra1_0[2] = r6_0
	ra1_1[2] = r6_1
	ra1_2[2] = r6_2
	ra1_3[2] = r6_3
	v279 = math.Float64frombits(0x4050000000000000)
	r7_0 = v279
	v280 = math.Float64frombits(0x403c000000000000)
	r7_1 = v280
	v281 = math.Float64frombits(0x4014000000000000)
	r7_2 = v281
	v282 = math.Float64frombits(0x4056800000000000)
	r7_3 = v282
	ra1_0[3] = r7_0
	ra1_1[3] = r7_1
	ra1_2[3] = r7_2
	ra1_3[3] = r7_3
	v283 = math.Float64frombits(0x0000000000000000)
	v287 = math.Float64frombits(0x3ff0000000000000)
	v288 = math.Float64frombits(0x403e000000000000)
	v289 = math.Float64frombits(0x3ff0000000000000)
	v39 = v283
	v40 = v287
	v41 = v288
	v42 = v289
	goto b1
b1:
	if math.IsNaN(v40) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v41) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v42) {
		return machinePreparedReplayEntry()
	}
	if (v42 > 0 && v40 > v41) || (v42 <= 0 && v40 < v41) {
		goto b16
	}
	goto b2
b2:
	ri0 = 0
	v72 = v39
	v73 = v40
	v74 = v41
	v75 = v42
	goto b3
b3:
	if ri0 >= 4 {
		goto b15
	}
	v295 = float64(ri0 + 1)
	ri0++
	goto b4
b4:
	if v295 < 1 || v295 > 4 {
		return machinePreparedReplayEntry()
	}
	v296 = ra0_5[int(v295)-1]
	if !v296 {
		v72 = v72
		v73 = v73
		v74 = v74
		v75 = v75
		goto b3
	}
	goto b5
b5:
	if v295 < 1 || v295 > 4 {
		return machinePreparedReplayEntry()
	}
	v297 = ra0_0[int(v295)-1]
	if v295 < 1 || v295 > 4 {
		return machinePreparedReplayEntry()
	}
	v298 = ra0_2[int(v295)-1]
	v299 = v297 + v298
	if v295 < 1 || v295 > 4 {
		return machinePreparedReplayEntry()
	}
	ra0_0[int(v295)-1] = v299
	if v295 < 1 || v295 > 4 {
		return machinePreparedReplayEntry()
	}
	v300 = ra0_1[int(v295)-1]
	if v295 < 1 || v295 > 4 {
		return machinePreparedReplayEntry()
	}
	v301 = ra0_3[int(v295)-1]
	v302 = v300 + v301
	if v295 < 1 || v295 > 4 {
		return machinePreparedReplayEntry()
	}
	ra0_1[int(v295)-1] = v302
	ri1 = 0
	v105 = v72
	v106 = v73
	v107 = v74
	v108 = v75
	v112 = v295
	goto b6
b6:
	if ri1 >= 4 {
		v138 = v105
		v139 = v106
		v140 = v107
		v141 = v108
		v145 = v112
		goto b10
	}
	v308 = float64(ri1 + 1)
	ri1++
	goto b7
b7:
	if v308 < 1 || v308 > 4 {
		return machinePreparedReplayEntry()
	}
	v309 = ra1_3[int(v308)-1]
	if math.IsNaN(v309) {
		return machinePreparedReplayEntry()
	}
	if !(v309 > math.Float64frombits(0x0000000000000000)) {
		v105 = v105
		v106 = v106
		v107 = v107
		v108 = v108
		v112 = v112
		goto b6
	}
	goto b8
b8:
	if v112 < 1 || v112 > 4 {
		return machinePreparedReplayEntry()
	}
	v310 = ra0_0[int(v112)-1]
	if v308 < 1 || v308 > 4 {
		return machinePreparedReplayEntry()
	}
	v311 = ra1_0[int(v308)-1]
	v312 = v310 - v311
	if v112 < 1 || v112 > 4 {
		return machinePreparedReplayEntry()
	}
	v313 = ra0_1[int(v112)-1]
	if v308 < 1 || v308 > 4 {
		return machinePreparedReplayEntry()
	}
	v314 = ra1_1[int(v308)-1]
	v315 = v313 - v314
	v316 = v312
	v317 = v312
	v318 = v316 * v317
	v319 = v315
	v320 = v315
	v321 = v319 * v320
	v322 = v318 + v321
	if v308 < 1 || v308 > 4 {
		return machinePreparedReplayEntry()
	}
	v323 = ra1_2[int(v308)-1]
	if v308 < 1 || v308 > 4 {
		return machinePreparedReplayEntry()
	}
	v324 = ra1_2[int(v308)-1]
	v325 = v323 * v324
	if math.IsNaN(v322) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v325) {
		return machinePreparedReplayEntry()
	}
	if v322 > v325 {
		v105 = v105
		v106 = v106
		v107 = v107
		v108 = v108
		v112 = v112
		goto b6
	}
	goto b9
b9:
	if v308 < 1 || v308 > 4 {
		return machinePreparedReplayEntry()
	}
	v326 = ra1_3[int(v308)-1]
	if v112 < 1 || v112 > 4 {
		return machinePreparedReplayEntry()
	}
	v327 = ra0_4[int(v112)-1]
	v328 = v326 - v327
	if v308 < 1 || v308 > 4 {
		return machinePreparedReplayEntry()
	}
	ra1_3[int(v308)-1] = v328
	v329 = false
	if v112 < 1 || v112 > 4 {
		return machinePreparedReplayEntry()
	}
	ra0_5[int(v112)-1] = v329
	if v308 < 1 || v308 > 4 {
		return machinePreparedReplayEntry()
	}
	v330 = ra1_3[int(v308)-1]
	v331 = v105 + v330
	v332 = v106
	v333 = v331 + v332
	v138 = v333
	v139 = v106
	v140 = v107
	v141 = v108
	v145 = v112
	goto b10
b10:
	if v145 < 1 || v145 > 4 {
		return machinePreparedReplayEntry()
	}
	v334 = ra0_0[int(v145)-1]
	v335 = math.Float64frombits(0x4054000000000000)
	if math.IsNaN(v334) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v335) {
		return machinePreparedReplayEntry()
	}
	v336 = v334 > v335
	if !v336 {
		goto b12
	}
	goto b11
b11:
	v168 = v336
	v171 = v138
	v172 = v139
	v173 = v140
	v174 = v141
	v178 = v145
	goto b13
b12:
	if v145 < 1 || v145 > 4 {
		return machinePreparedReplayEntry()
	}
	v337 = ra0_1[int(v145)-1]
	v338 = math.Float64frombits(0x4044000000000000)
	if math.IsNaN(v337) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v338) {
		return machinePreparedReplayEntry()
	}
	v339 = v337 > v338
	v168 = v339
	v171 = v138
	v172 = v139
	v173 = v140
	v174 = v141
	v178 = v145
	goto b13
b13:
	if !v168 {
		v72 = v171
		v73 = v172
		v74 = v173
		v75 = v174
		goto b3
	}
	goto b14
b14:
	v340 = false
	if v178 < 1 || v178 > 4 {
		return machinePreparedReplayEntry()
	}
	ra0_5[int(v178)-1] = v340
	v72 = v171
	v73 = v172
	v74 = v173
	v75 = v174
	goto b3
b15:
	v341 = v73 + v75
	v39 = v72
	v40 = v341
	v41 = v74
	v42 = v75
	goto b1
b16:
	ri1 = 0
	v204 = v39
	goto b17
b17:
	if ri1 >= 4 {
		goto b19
	}
	v347 = float64(ri1 + 1)
	ri1++
	goto b18
b18:
	if v347 < 1 || v347 > 4 {
		return machinePreparedReplayEntry()
	}
	v348 = ra1_3[int(v347)-1]
	v349 = v204 + v348
	v204 = v349
	goto b17
b19:
	return machinePreparedReturnOneNumber(v204)
}

func backendGeneratedProjectileSweepPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedProjectileSweepPreparedFixtureBody(context, p0)
}
