// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

func backendGeneratedEventHeal(r0 *float64, p1 float64) (float64, bool) {
	if r0 == nil {
		return 0, false
	}
	var v2 float64
	var v6 float64
	var v7 float64
	var v8 float64
	var v9 float64
	v2 = p1
	v6 = v2
	v7 = *r0
	v8 = v7 + v6
	*r0 = v8
	v9 = *r0
	return v9, true
}
