// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedNumericCallKernel(p0 float64) (float64, bool) {
	var v1 float64
	var v10 float64
	var v11 float64
	var v12 float64
	var v13 float64
	var v16 float64
	var v20 float64
	var v21 float64
	var v22 float64
	var v23 float64
	var v24 float64
	var v25 float64
	var v26 float64
	var ok10 bool
	v1 = p0
	v16 = v1
	v20 = math.Float64frombits(0x3ff0000000000000)
	v21 = math.Float64frombits(0x4050000000000000)
	v22 = math.Float64frombits(0x3ff0000000000000)
	v10 = v16
	v11 = v20
	v12 = v21
	v13 = v22
	goto b1
b1:
	if math.IsNaN(v11) {
		return 0, false
	}
	if math.IsNaN(v12) {
		return 0, false
	}
	if math.IsNaN(v13) {
		return 0, false
	}
	if (v13 > 0 && v11 > v12) || (v13 <= 0 && v11 < v12) {
		goto b3
	}
	goto b2
b2:
	v23 = v10
	v24, ok10 = backendGeneratedNumericCallAdd(v23)
	if !ok10 {
		return 0, false
	}
	v25 = v24
	v26 = v11 + v13
	v10 = v25
	v11 = v26
	v12 = v12
	v13 = v13
	goto b1
b3:
	return v10, true
}

func backendGeneratedNumericCallPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v10 float64
	var v11 float64
	var v12 float64
	var v13 float64
	var v16 float64
	var v20 float64
	var v21 float64
	var v22 float64
	var v23 float64
	var v24 float64
	var v25 float64
	var v26 float64
	var ok10 bool
	v1 = p0
	v16 = v1
	v20 = math.Float64frombits(0x3ff0000000000000)
	v21 = math.Float64frombits(0x4050000000000000)
	v22 = math.Float64frombits(0x3ff0000000000000)
	v10 = v16
	v11 = v20
	v12 = v21
	v13 = v22
	goto b1
b1:
	if math.IsNaN(v11) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v12) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v13) {
		return machinePreparedReplayEntry()
	}
	if (v13 > 0 && v11 > v12) || (v13 <= 0 && v11 < v12) {
		goto b3
	}
	goto b2
b2:
	v23 = v10
	v24, ok10 = backendGeneratedNumericCallAdd(v23)
	if !ok10 {
		return machinePreparedReplayEntry()
	}
	v25 = v24
	v26 = v11 + v13
	v10 = v25
	v11 = v26
	v12 = v12
	v13 = v13
	goto b1
b3:
	return machinePreparedReturnOneNumber(v10)
}

func backendGeneratedNumericCallPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedNumericCallPreparedFixtureBody(context, p0)
}
