// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedSparseGrid(p0 float64) (float64, bool) {
	var v1 float64
	var v49 float64
	var v50 float64
	var v51 float64
	var v52 float64
	var v90 float64
	var v91 float64
	var v92 float64
	var v93 float64
	var v94 float64
	var v95 float64
	var v96 float64
	var v131 float64
	var v132 float64
	var v133 float64
	var v134 float64
	var v135 float64
	var v136 float64
	var v137 float64
	var v138 float64
	var v139 float64
	var v140 float64
	var v172 float64
	var v173 float64
	var v174 float64
	var v175 float64
	var v176 float64
	var v177 float64
	var v178 float64
	var v179 float64
	var v180 float64
	var v181 float64
	var v184 float64
	var v213 float64
	var v214 float64
	var v215 float64
	var v216 float64
	var v217 float64
	var v218 float64
	var v219 float64
	var v220 float64
	var v221 float64
	var v222 float64
	var v225 float64
	var v235 float64
	var v237 float64
	var v254 float64
	var v255 float64
	var v256 float64
	var v257 float64
	var v258 float64
	var v259 float64
	var v260 float64
	var v261 float64
	var v262 float64
	var v263 float64
	var v290 float64
	var v324 float64
	var v331 float64
	var v365 float64
	var v372 float64
	var v406 float64
	var v413 float64
	var v447 float64
	var v454 float64
	var v455 float64
	var v456 float64
	var v457 float64
	var v458 float64
	var v461 float64
	var v462 float64
	var v465 float64
	var v466 float64
	var v469 float64
	var v470 float64
	var v473 float64
	var v474 float64
	var v478 float64
	var v479 float64
	var v481 float64
	var v482 float64
	var v484 float64
	var v485 float64
	var v487 float64
	var v488 float64
	var v490 float64
	var v494 float64
	var v495 float64
	var v496 float64
	var v497 float64
	var v498 float64
	var v499 float64
	var v500 float64
	var v501 float64
	var v502 float64
	var v503 float64
	var v504 float64
	var v505 backendPreparedStringKey
	var v506 backendPreparedStringKey
	var v507 float64
	var v508 float64
	var v510 bool
	var v516 float64
	var v517 float64
	var v518 float64
	var v519 float64
	var v520 float64
	var v521 float64
	var v522 float64
	var v523 backendPreparedStringKey
	var v524 backendPreparedStringKey
	var v525 float64
	var v526 float64
	var v528 bool
	var v529 float64
	var v530 float64
	var v531 float64
	var v532 float64
	var v533 float64
	var v534 float64
	var v535 float64
	var v536 float64
	var v537 float64
	var v538 float64
	var v539 float64
	var v540 float64
	var v541 float64
	var v542 float64
	var v543 float64
	var v545 float64
	var v546 float64
	var v547 float64
	var v548 float64
	var v549 float64
	var v550 float64
	var v551 float64
	var v552 float64
	var v553 float64
	var v554 backendPreparedStringKey
	var v555 backendPreparedStringKey
	var v556 float64
	var v557 float64
	var v558 float64
	var v559 float64
	var v560 float64
	var v561 float64
	var v562 float64
	var v564 float64
	var v566 float64
	var v567 float64
	var v568 float64
	var v569 float64
	var v571 float64
	var v573 float64
	var v574 float64
	var v575 float64
	var v576 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r1_0 float64
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r2_0 float64
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r3_0 float64
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r4_0 float64
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r5_0 float64
	_ = r5_0
	var r5_1 float64
	_ = r5_1
	var r6_0 float64
	_ = r6_0
	var r6_1 float64
	_ = r6_1
	var r7_0 float64
	_ = r7_0
	var r7_1 float64
	_ = r7_1
	var r8_0 float64
	_ = r8_0
	var r8_1 float64
	_ = r8_1
	var r9_0 float64
	_ = r9_0
	var r9_1 float64
	_ = r9_1
	var mk0 [128]backendPreparedStringKey
	var mu0 [128]bool
	var mf0_0 [128]float64
	var mf0_1 [128]float64
	var ra0_0 [4]float64
	var ra0_1 [4]float64
	var ri0 int
	_ = ri0
	var ok83 bool
	var ok99 bool
	v1 = p0
	v454 = math.Float64frombits(0x3ff0000000000000)
	r0_0 = v454
	v455 = math.Float64frombits(0x4014000000000000)
	v456 = v1
	v457 = v456 - math.Floor(v456/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v458 = v455 + v457
	r0_1 = v458
	{
		rk10 := backendPreparedStringKey{first: 0, second: 0}
		rs10 := (uint32(rk10.first)*0x9e3779b1 ^ uint32(rk10.second)*0x85ebca6b) & 127
		rok10 := false
		for rp10 := 0; rp10 < 128; rp10++ {
			rx10 := int((rs10 + uint32(rp10)) & 127)
			if !mu0[rx10] {
				mu0[rx10] = true
				mk0[rx10] = rk10
			}
			if mk0[rx10] == rk10 {
				mf0_0[rx10] = r0_0
				mf0_1[rx10] = r0_1
				rok10 = true
				break
			}
		}
		if !rok10 {
			return 0, false
		}
	}
	v461 = math.Float64frombits(0x4000000000000000)
	r1_0 = v461
	v462 = math.Float64frombits(0x4008000000000000)
	r1_1 = v462
	{
		rk17 := backendPreparedStringKey{first: 1, second: 0}
		rs17 := (uint32(rk17.first)*0x9e3779b1 ^ uint32(rk17.second)*0x85ebca6b) & 127
		rok17 := false
		for rp17 := 0; rp17 < 128; rp17++ {
			rx17 := int((rs17 + uint32(rp17)) & 127)
			if !mu0[rx17] {
				mu0[rx17] = true
				mk0[rx17] = rk17
			}
			if mk0[rx17] == rk17 {
				mf0_0[rx17] = r1_0
				mf0_1[rx17] = r1_1
				rok17 = true
				break
			}
		}
		if !rok17 {
			return 0, false
		}
	}
	v465 = math.Float64frombits(0x3ff0000000000000)
	r2_0 = v465
	v466 = math.Float64frombits(0x401c000000000000)
	r2_1 = v466
	{
		rk24 := backendPreparedStringKey{first: 2, second: 1}
		rs24 := (uint32(rk24.first)*0x9e3779b1 ^ uint32(rk24.second)*0x85ebca6b) & 127
		rok24 := false
		for rp24 := 0; rp24 < 128; rp24++ {
			rx24 := int((rs24 + uint32(rp24)) & 127)
			if !mu0[rx24] {
				mu0[rx24] = true
				mk0[rx24] = rk24
			}
			if mk0[rx24] == rk24 {
				mf0_0[rx24] = r2_0
				mf0_1[rx24] = r2_1
				rok24 = true
				break
			}
		}
		if !rok24 {
			return 0, false
		}
	}
	v469 = math.Float64frombits(0x4008000000000000)
	r3_0 = v469
	v470 = math.Float64frombits(0x4000000000000000)
	r3_1 = v470
	{
		rk31 := backendPreparedStringKey{first: 3, second: 2}
		rs31 := (uint32(rk31.first)*0x9e3779b1 ^ uint32(rk31.second)*0x85ebca6b) & 127
		rok31 := false
		for rp31 := 0; rp31 < 128; rp31++ {
			rx31 := int((rs31 + uint32(rp31)) & 127)
			if !mu0[rx31] {
				mu0[rx31] = true
				mk0[rx31] = rk31
			}
			if mk0[rx31] == rk31 {
				mf0_0[rx31] = r3_0
				mf0_1[rx31] = r3_1
				rok31 = true
				break
			}
		}
		if !rok31 {
			return 0, false
		}
	}
	v473 = math.Float64frombits(0x4000000000000000)
	r4_0 = v473
	v474 = math.Float64frombits(0x4022000000000000)
	r4_1 = v474
	{
		rk38 := backendPreparedStringKey{first: 4, second: 4}
		rs38 := (uint32(rk38.first)*0x9e3779b1 ^ uint32(rk38.second)*0x85ebca6b) & 127
		rok38 := false
		for rp38 := 0; rp38 < 128; rp38++ {
			rx38 := int((rs38 + uint32(rp38)) & 127)
			if !mu0[rx38] {
				mu0[rx38] = true
				mk0[rx38] = rk38
			}
			if mk0[rx38] == rk38 {
				mf0_0[rx38] = r4_0
				mf0_1[rx38] = r4_1
				rok38 = true
				break
			}
		}
		if !rok38 {
			return 0, false
		}
	}
	v478 = math.Float64frombits(0x3ff0000000000000)
	r5_0 = v478
	v479 = math.Float64frombits(0x0000000000000000)
	r5_1 = v479
	ra0_0[0] = r5_0
	ra0_1[0] = r5_1
	v481 = math.Float64frombits(0xbff0000000000000)
	r6_0 = v481
	v482 = math.Float64frombits(0x0000000000000000)
	r6_1 = v482
	ra0_0[1] = r6_0
	ra0_1[1] = r6_1
	v484 = math.Float64frombits(0x0000000000000000)
	r7_0 = v484
	v485 = math.Float64frombits(0x3ff0000000000000)
	r7_1 = v485
	ra0_0[2] = r7_0
	ra0_1[2] = r7_1
	v487 = math.Float64frombits(0x0000000000000000)
	r8_0 = v487
	v488 = math.Float64frombits(0xbff0000000000000)
	r8_1 = v488
	ra0_0[3] = r8_0
	ra0_1[3] = r8_1
	v490 = math.Float64frombits(0x0000000000000000)
	v494 = math.Float64frombits(0x3ff0000000000000)
	v495 = math.Float64frombits(0x4042000000000000)
	v496 = math.Float64frombits(0x3ff0000000000000)
	v49 = v490
	v50 = v494
	v51 = v495
	v52 = v496
	goto b1
b1:
	if math.IsNaN(v50) {
		return 0, false
	}
	if math.IsNaN(v51) {
		return 0, false
	}
	if math.IsNaN(v52) {
		return 0, false
	}
	if (v52 > 0 && v50 > v51) || (v52 <= 0 && v50 < v51) {
		goto b18
	}
	goto b2
b2:
	v497 = math.Float64frombits(0x0000000000000000)
	v498 = math.Float64frombits(0x4010000000000000)
	v499 = math.Float64frombits(0x3ff0000000000000)
	v90 = v49
	v91 = v50
	v92 = v51
	v93 = v52
	v94 = v497
	v95 = v498
	v96 = v499
	goto b3
b3:
	if math.IsNaN(v94) {
		return 0, false
	}
	if math.IsNaN(v95) {
		return 0, false
	}
	if math.IsNaN(v96) {
		return 0, false
	}
	if (v96 > 0 && v94 > v95) || (v96 <= 0 && v94 < v95) {
		goto b17
	}
	goto b4
b4:
	v500 = math.Float64frombits(0x0000000000000000)
	v501 = math.Float64frombits(0x4010000000000000)
	v502 = math.Float64frombits(0x3ff0000000000000)
	v131 = v90
	v132 = v91
	v133 = v92
	v134 = v93
	v135 = v94
	v136 = v95
	v137 = v96
	v138 = v500
	v139 = v501
	v140 = v502
	goto b5
b5:
	if math.IsNaN(v138) {
		return 0, false
	}
	if math.IsNaN(v139) {
		return 0, false
	}
	if math.IsNaN(v140) {
		return 0, false
	}
	if (v140 > 0 && v138 > v139) || (v140 <= 0 && v138 < v139) {
		goto b16
	}
	goto b6
b6:
	v503 = v135
	v504 = v138
	v505, ok83 = backendGeneratedStructuralStringKey(v503, v504)
	if !ok83 {
		return 0, false
	}
	v506 = v505
	v507 = 0
	{
		rk85 := v506
		rs85 := (uint32(rk85.first)*0x9e3779b1 ^ uint32(rk85.second)*0x85ebca6b) & 127
		for rp85 := 0; rp85 < 128; rp85++ {
			rx85 := int((rs85 + uint32(rp85)) & 127)
			if !mu0[rx85] {
				break
			}
			if mk0[rx85] == rk85 {
				v507 = float64(rx85 + 1)
				break
			}
		}
	}
	v508 = v507
	v510 = v508 != 0
	if !v510 {
		v254 = v131
		v255 = v132
		v256 = v133
		v257 = v134
		v258 = v135
		v259 = v136
		v260 = v137
		v261 = v138
		v262 = v139
		v263 = v140
		goto b15
	}
	goto b7
b7:
	ri0 = 0
	v172 = v131
	v173 = v132
	v174 = v133
	v175 = v134
	v176 = v135
	v177 = v136
	v178 = v137
	v179 = v138
	v180 = v139
	v181 = v140
	v184 = v507
	goto b8
b8:
	if ri0 >= 4 {
		v254 = v172
		v255 = v173
		v256 = v174
		v257 = v175
		v258 = v176
		v259 = v177
		v260 = v178
		v261 = v179
		v262 = v180
		v263 = v181
		goto b15
	}
	v516 = float64(ri0 + 1)
	ri0++
	goto b9
b9:
	v517 = v176
	if v516 < 1 || v516 > 4 {
		return 0, false
	}
	v518 = ra0_0[int(v516)-1]
	v519 = v517 + v518
	v520 = v179
	if v516 < 1 || v516 > 4 {
		return 0, false
	}
	v521 = ra0_1[int(v516)-1]
	v522 = v520 + v521
	v523, ok99 = backendGeneratedStructuralStringKey(v519, v522)
	if !ok99 {
		return 0, false
	}
	v524 = v523
	v525 = 0
	{
		rk101 := v524
		rs101 := (uint32(rk101.first)*0x9e3779b1 ^ uint32(rk101.second)*0x85ebca6b) & 127
		for rp101 := 0; rp101 < 128; rp101++ {
			rx101 := int((rs101 + uint32(rp101)) & 127)
			if !mu0[rx101] {
				break
			}
			if mk0[rx101] == rk101 {
				v525 = float64(rx101 + 1)
				break
			}
		}
	}
	v526 = v525
	v528 = v526 != 0
	if !v528 {
		goto b13
	}
	goto b10
b10:
	if v184 < 1 || v184 > 128 {
		return 0, false
	}
	v529 = mf0_1[int(v184)-1]
	if v525 < 1 || v525 > 128 {
		return 0, false
	}
	v530 = mf0_1[int(v525)-1]
	v531 = v529 - v530
	if math.IsNaN(v531) {
		return 0, false
	}
	if !(v531 < math.Float64frombits(0x0000000000000000)) {
		v213 = v172
		v214 = v173
		v215 = v174
		v216 = v175
		v217 = v176
		v218 = v177
		v219 = v178
		v220 = v179
		v221 = v180
		v222 = v181
		v225 = v184
		v235 = v525
		v237 = v531
		goto b12
	}
	goto b11
b11:
	v532 = -v531
	v213 = v172
	v214 = v173
	v215 = v174
	v216 = v175
	v217 = v176
	v218 = v177
	v219 = v178
	v220 = v179
	v221 = v180
	v222 = v181
	v225 = v184
	v235 = v525
	v237 = v532
	goto b12
b12:
	if v225 < 1 || v225 > 128 {
		return 0, false
	}
	v533 = mf0_1[int(v225)-1]
	v534 = v214
	v535 = v534 - math.Floor(v534/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v536 = v533 + v535
	if v235 < 1 || v235 > 128 {
		return 0, false
	}
	v537 = mf0_0[int(v235)-1]
	v538 = v536 - v537
	if v225 < 1 || v225 > 128 {
		return 0, false
	}
	mf0_1[int(v225)-1] = v538
	v539 = v237
	v540 = v213 + v539
	if v225 < 1 || v225 > 128 {
		return 0, false
	}
	v541 = mf0_1[int(v225)-1]
	v542 = v540 + v541
	v172 = v542
	v173 = v214
	v174 = v215
	v175 = v216
	v176 = v217
	v177 = v218
	v178 = v219
	v179 = v220
	v180 = v221
	v181 = v222
	v184 = v225
	goto b8
b13:
	v543 = v173 - math.Floor(v173/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	if v543 != math.Float64frombits(0x0000000000000000) {
		v172 = v172
		v173 = v173
		v174 = v174
		v175 = v175
		v176 = v176
		v177 = v177
		v178 = v178
		v179 = v179
		v180 = v180
		v181 = v181
		v184 = v184
		goto b8
	}
	goto b14
b14:
	v545 = v173
	v546 = v545 - math.Floor(v545/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v547 = v546 + math.Float64frombits(0x3ff0000000000000)
	r9_0 = v547
	v548 = v176
	v549 = v179
	v550 = v548 + v549
	v551 = v173
	v552 = v551 - math.Floor(v551/math.Float64frombits(0x4010000000000000))*math.Float64frombits(0x4010000000000000)
	v553 = v550 + v552
	r9_1 = v553
	v554 = v523
	{
		rk138 := v554
		rs138 := (uint32(rk138.first)*0x9e3779b1 ^ uint32(rk138.second)*0x85ebca6b) & 127
		rok138 := false
		for rp138 := 0; rp138 < 128; rp138++ {
			rx138 := int((rs138 + uint32(rp138)) & 127)
			if !mu0[rx138] {
				mu0[rx138] = true
				mk0[rx138] = rk138
			}
			if mk0[rx138] == rk138 {
				mf0_0[rx138] = r9_0
				mf0_1[rx138] = r9_1
				rok138 = true
				break
			}
		}
		if !rok138 {
			return 0, false
		}
	}
	v555 = v523
	v556 = 0
	{
		rk140 := v555
		rs140 := (uint32(rk140.first)*0x9e3779b1 ^ uint32(rk140.second)*0x85ebca6b) & 127
		for rp140 := 0; rp140 < 128; rp140++ {
			rx140 := int((rs140 + uint32(rp140)) & 127)
			if !mu0[rx140] {
				break
			}
			if mk0[rx140] == rk140 {
				v556 = float64(rx140 + 1)
				break
			}
		}
	}
	if v556 < 1 || v556 > 128 {
		return 0, false
	}
	v557 = mf0_1[int(v556)-1]
	v558 = v172 + v557
	v172 = v558
	v173 = v173
	v174 = v174
	v175 = v175
	v176 = v176
	v177 = v177
	v178 = v178
	v179 = v179
	v180 = v180
	v181 = v181
	v184 = v184
	goto b8
b15:
	v559 = v261 + v263
	v131 = v254
	v132 = v255
	v133 = v256
	v134 = v257
	v135 = v258
	v136 = v259
	v137 = v260
	v138 = v559
	v139 = v262
	v140 = v263
	goto b5
b16:
	v560 = v135 + v137
	v90 = v131
	v91 = v132
	v92 = v133
	v93 = v134
	v94 = v560
	v95 = v136
	v96 = v137
	goto b3
b17:
	v561 = v91 + v93
	v49 = v90
	v50 = v561
	v51 = v92
	v52 = v93
	goto b1
b18:
	v562 = v49
	v564 = 0
	{
		rk149 := backendPreparedStringKey{first: 2, second: 2}
		rs149 := (uint32(rk149.first)*0x9e3779b1 ^ uint32(rk149.second)*0x85ebca6b) & 127
		for rp149 := 0; rp149 < 128; rp149++ {
			rx149 := int((rs149 + uint32(rp149)) & 127)
			if !mu0[rx149] {
				break
			}
			if mk0[rx149] == rk149 {
				v564 = float64(rx149 + 1)
				break
			}
		}
	}
	if v564 == 0 {
		v290 = v564
		v324 = v562
		goto b20
	}
	goto b19
b19:
	v566 = 0
	{
		rk152 := backendPreparedStringKey{first: 2, second: 2}
		rs152 := (uint32(rk152.first)*0x9e3779b1 ^ uint32(rk152.second)*0x85ebca6b) & 127
		for rp152 := 0; rp152 < 128; rp152++ {
			rx152 := int((rs152 + uint32(rp152)) & 127)
			if !mu0[rx152] {
				break
			}
			if mk0[rx152] == rk152 {
				v566 = float64(rx152 + 1)
				break
			}
		}
	}
	if v566 < 1 || v566 > 128 {
		return 0, false
	}
	v567 = mf0_1[int(v566)-1]
	v290 = v567
	v324 = v562
	goto b20
b20:
	if false {
		goto b22
	}
	goto b21
b21:
	v331 = v290
	v365 = v324
	goto b23
b22:
	v568 = math.Float64frombits(0x0000000000000000)
	v331 = v568
	v365 = v324
	goto b23
b23:
	v569 = v365 + v331
	v571 = 0
	{
		rk159 := backendPreparedStringKey{first: 4, second: 4}
		rs159 := (uint32(rk159.first)*0x9e3779b1 ^ uint32(rk159.second)*0x85ebca6b) & 127
		for rp159 := 0; rp159 < 128; rp159++ {
			rx159 := int((rs159 + uint32(rp159)) & 127)
			if !mu0[rx159] {
				break
			}
			if mk0[rx159] == rk159 {
				v571 = float64(rx159 + 1)
				break
			}
		}
	}
	if v571 == 0 {
		v372 = v571
		v406 = v569
		goto b25
	}
	goto b24
b24:
	v573 = 0
	{
		rk162 := backendPreparedStringKey{first: 4, second: 4}
		rs162 := (uint32(rk162.first)*0x9e3779b1 ^ uint32(rk162.second)*0x85ebca6b) & 127
		for rp162 := 0; rp162 < 128; rp162++ {
			rx162 := int((rs162 + uint32(rp162)) & 127)
			if !mu0[rx162] {
				break
			}
			if mk0[rx162] == rk162 {
				v573 = float64(rx162 + 1)
				break
			}
		}
	}
	if v573 < 1 || v573 > 128 {
		return 0, false
	}
	v574 = mf0_1[int(v573)-1]
	v372 = v574
	v406 = v569
	goto b25
b25:
	if false {
		goto b27
	}
	goto b26
b26:
	v413 = v372
	v447 = v406
	goto b28
b27:
	v575 = math.Float64frombits(0x0000000000000000)
	v413 = v575
	v447 = v406
	goto b28
b28:
	v576 = v447 + v413
	return v576, true
}

func backendGeneratedSparseGridPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v49 float64
	var v50 float64
	var v51 float64
	var v52 float64
	var v90 float64
	var v91 float64
	var v92 float64
	var v93 float64
	var v94 float64
	var v95 float64
	var v96 float64
	var v131 float64
	var v132 float64
	var v133 float64
	var v134 float64
	var v135 float64
	var v136 float64
	var v137 float64
	var v138 float64
	var v139 float64
	var v140 float64
	var v172 float64
	var v173 float64
	var v174 float64
	var v175 float64
	var v176 float64
	var v177 float64
	var v178 float64
	var v179 float64
	var v180 float64
	var v181 float64
	var v184 float64
	var v213 float64
	var v214 float64
	var v215 float64
	var v216 float64
	var v217 float64
	var v218 float64
	var v219 float64
	var v220 float64
	var v221 float64
	var v222 float64
	var v225 float64
	var v235 float64
	var v237 float64
	var v254 float64
	var v255 float64
	var v256 float64
	var v257 float64
	var v258 float64
	var v259 float64
	var v260 float64
	var v261 float64
	var v262 float64
	var v263 float64
	var v290 float64
	var v324 float64
	var v331 float64
	var v365 float64
	var v372 float64
	var v406 float64
	var v413 float64
	var v447 float64
	var v454 float64
	var v455 float64
	var v456 float64
	var v457 float64
	var v458 float64
	var v461 float64
	var v462 float64
	var v465 float64
	var v466 float64
	var v469 float64
	var v470 float64
	var v473 float64
	var v474 float64
	var v478 float64
	var v479 float64
	var v481 float64
	var v482 float64
	var v484 float64
	var v485 float64
	var v487 float64
	var v488 float64
	var v490 float64
	var v494 float64
	var v495 float64
	var v496 float64
	var v497 float64
	var v498 float64
	var v499 float64
	var v500 float64
	var v501 float64
	var v502 float64
	var v503 float64
	var v504 float64
	var v505 backendPreparedStringKey
	var v506 backendPreparedStringKey
	var v507 float64
	var v508 float64
	var v510 bool
	var v516 float64
	var v517 float64
	var v518 float64
	var v519 float64
	var v520 float64
	var v521 float64
	var v522 float64
	var v523 backendPreparedStringKey
	var v524 backendPreparedStringKey
	var v525 float64
	var v526 float64
	var v528 bool
	var v529 float64
	var v530 float64
	var v531 float64
	var v532 float64
	var v533 float64
	var v534 float64
	var v535 float64
	var v536 float64
	var v537 float64
	var v538 float64
	var v539 float64
	var v540 float64
	var v541 float64
	var v542 float64
	var v543 float64
	var v545 float64
	var v546 float64
	var v547 float64
	var v548 float64
	var v549 float64
	var v550 float64
	var v551 float64
	var v552 float64
	var v553 float64
	var v554 backendPreparedStringKey
	var v555 backendPreparedStringKey
	var v556 float64
	var v557 float64
	var v558 float64
	var v559 float64
	var v560 float64
	var v561 float64
	var v562 float64
	var v564 float64
	var v566 float64
	var v567 float64
	var v568 float64
	var v569 float64
	var v571 float64
	var v573 float64
	var v574 float64
	var v575 float64
	var v576 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r1_0 float64
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r2_0 float64
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r3_0 float64
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r4_0 float64
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r5_0 float64
	_ = r5_0
	var r5_1 float64
	_ = r5_1
	var r6_0 float64
	_ = r6_0
	var r6_1 float64
	_ = r6_1
	var r7_0 float64
	_ = r7_0
	var r7_1 float64
	_ = r7_1
	var r8_0 float64
	_ = r8_0
	var r8_1 float64
	_ = r8_1
	var r9_0 float64
	_ = r9_0
	var r9_1 float64
	_ = r9_1
	var mk0 [128]backendPreparedStringKey
	var mu0 [128]bool
	var mf0_0 [128]float64
	var mf0_1 [128]float64
	var ra0_0 [4]float64
	var ra0_1 [4]float64
	var ri0 int
	_ = ri0
	var ok83 bool
	var ok99 bool
	v1 = p0
	v454 = math.Float64frombits(0x3ff0000000000000)
	r0_0 = v454
	v455 = math.Float64frombits(0x4014000000000000)
	v456 = v1
	v457 = v456 - math.Floor(v456/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v458 = v455 + v457
	r0_1 = v458
	{
		rk10 := backendPreparedStringKey{first: 0, second: 0}
		rs10 := (uint32(rk10.first)*0x9e3779b1 ^ uint32(rk10.second)*0x85ebca6b) & 127
		rok10 := false
		for rp10 := 0; rp10 < 128; rp10++ {
			rx10 := int((rs10 + uint32(rp10)) & 127)
			if !mu0[rx10] {
				mu0[rx10] = true
				mk0[rx10] = rk10
			}
			if mk0[rx10] == rk10 {
				mf0_0[rx10] = r0_0
				mf0_1[rx10] = r0_1
				rok10 = true
				break
			}
		}
		if !rok10 {
			return machinePreparedReplayEntry()
		}
	}
	v461 = math.Float64frombits(0x4000000000000000)
	r1_0 = v461
	v462 = math.Float64frombits(0x4008000000000000)
	r1_1 = v462
	{
		rk17 := backendPreparedStringKey{first: 1, second: 0}
		rs17 := (uint32(rk17.first)*0x9e3779b1 ^ uint32(rk17.second)*0x85ebca6b) & 127
		rok17 := false
		for rp17 := 0; rp17 < 128; rp17++ {
			rx17 := int((rs17 + uint32(rp17)) & 127)
			if !mu0[rx17] {
				mu0[rx17] = true
				mk0[rx17] = rk17
			}
			if mk0[rx17] == rk17 {
				mf0_0[rx17] = r1_0
				mf0_1[rx17] = r1_1
				rok17 = true
				break
			}
		}
		if !rok17 {
			return machinePreparedReplayEntry()
		}
	}
	v465 = math.Float64frombits(0x3ff0000000000000)
	r2_0 = v465
	v466 = math.Float64frombits(0x401c000000000000)
	r2_1 = v466
	{
		rk24 := backendPreparedStringKey{first: 2, second: 1}
		rs24 := (uint32(rk24.first)*0x9e3779b1 ^ uint32(rk24.second)*0x85ebca6b) & 127
		rok24 := false
		for rp24 := 0; rp24 < 128; rp24++ {
			rx24 := int((rs24 + uint32(rp24)) & 127)
			if !mu0[rx24] {
				mu0[rx24] = true
				mk0[rx24] = rk24
			}
			if mk0[rx24] == rk24 {
				mf0_0[rx24] = r2_0
				mf0_1[rx24] = r2_1
				rok24 = true
				break
			}
		}
		if !rok24 {
			return machinePreparedReplayEntry()
		}
	}
	v469 = math.Float64frombits(0x4008000000000000)
	r3_0 = v469
	v470 = math.Float64frombits(0x4000000000000000)
	r3_1 = v470
	{
		rk31 := backendPreparedStringKey{first: 3, second: 2}
		rs31 := (uint32(rk31.first)*0x9e3779b1 ^ uint32(rk31.second)*0x85ebca6b) & 127
		rok31 := false
		for rp31 := 0; rp31 < 128; rp31++ {
			rx31 := int((rs31 + uint32(rp31)) & 127)
			if !mu0[rx31] {
				mu0[rx31] = true
				mk0[rx31] = rk31
			}
			if mk0[rx31] == rk31 {
				mf0_0[rx31] = r3_0
				mf0_1[rx31] = r3_1
				rok31 = true
				break
			}
		}
		if !rok31 {
			return machinePreparedReplayEntry()
		}
	}
	v473 = math.Float64frombits(0x4000000000000000)
	r4_0 = v473
	v474 = math.Float64frombits(0x4022000000000000)
	r4_1 = v474
	{
		rk38 := backendPreparedStringKey{first: 4, second: 4}
		rs38 := (uint32(rk38.first)*0x9e3779b1 ^ uint32(rk38.second)*0x85ebca6b) & 127
		rok38 := false
		for rp38 := 0; rp38 < 128; rp38++ {
			rx38 := int((rs38 + uint32(rp38)) & 127)
			if !mu0[rx38] {
				mu0[rx38] = true
				mk0[rx38] = rk38
			}
			if mk0[rx38] == rk38 {
				mf0_0[rx38] = r4_0
				mf0_1[rx38] = r4_1
				rok38 = true
				break
			}
		}
		if !rok38 {
			return machinePreparedReplayEntry()
		}
	}
	v478 = math.Float64frombits(0x3ff0000000000000)
	r5_0 = v478
	v479 = math.Float64frombits(0x0000000000000000)
	r5_1 = v479
	ra0_0[0] = r5_0
	ra0_1[0] = r5_1
	v481 = math.Float64frombits(0xbff0000000000000)
	r6_0 = v481
	v482 = math.Float64frombits(0x0000000000000000)
	r6_1 = v482
	ra0_0[1] = r6_0
	ra0_1[1] = r6_1
	v484 = math.Float64frombits(0x0000000000000000)
	r7_0 = v484
	v485 = math.Float64frombits(0x3ff0000000000000)
	r7_1 = v485
	ra0_0[2] = r7_0
	ra0_1[2] = r7_1
	v487 = math.Float64frombits(0x0000000000000000)
	r8_0 = v487
	v488 = math.Float64frombits(0xbff0000000000000)
	r8_1 = v488
	ra0_0[3] = r8_0
	ra0_1[3] = r8_1
	v490 = math.Float64frombits(0x0000000000000000)
	v494 = math.Float64frombits(0x3ff0000000000000)
	v495 = math.Float64frombits(0x4042000000000000)
	v496 = math.Float64frombits(0x3ff0000000000000)
	v49 = v490
	v50 = v494
	v51 = v495
	v52 = v496
	goto b1
b1:
	if math.IsNaN(v50) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v51) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v52) {
		return machinePreparedReplayEntry()
	}
	if (v52 > 0 && v50 > v51) || (v52 <= 0 && v50 < v51) {
		goto b18
	}
	goto b2
b2:
	v497 = math.Float64frombits(0x0000000000000000)
	v498 = math.Float64frombits(0x4010000000000000)
	v499 = math.Float64frombits(0x3ff0000000000000)
	v90 = v49
	v91 = v50
	v92 = v51
	v93 = v52
	v94 = v497
	v95 = v498
	v96 = v499
	goto b3
b3:
	if math.IsNaN(v94) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v95) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v96) {
		return machinePreparedReplayEntry()
	}
	if (v96 > 0 && v94 > v95) || (v96 <= 0 && v94 < v95) {
		goto b17
	}
	goto b4
b4:
	v500 = math.Float64frombits(0x0000000000000000)
	v501 = math.Float64frombits(0x4010000000000000)
	v502 = math.Float64frombits(0x3ff0000000000000)
	v131 = v90
	v132 = v91
	v133 = v92
	v134 = v93
	v135 = v94
	v136 = v95
	v137 = v96
	v138 = v500
	v139 = v501
	v140 = v502
	goto b5
b5:
	if math.IsNaN(v138) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v139) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v140) {
		return machinePreparedReplayEntry()
	}
	if (v140 > 0 && v138 > v139) || (v140 <= 0 && v138 < v139) {
		goto b16
	}
	goto b6
b6:
	v503 = v135
	v504 = v138
	v505, ok83 = backendGeneratedStructuralStringKey(v503, v504)
	if !ok83 {
		return machinePreparedReplayEntry()
	}
	v506 = v505
	v507 = 0
	{
		rk85 := v506
		rs85 := (uint32(rk85.first)*0x9e3779b1 ^ uint32(rk85.second)*0x85ebca6b) & 127
		for rp85 := 0; rp85 < 128; rp85++ {
			rx85 := int((rs85 + uint32(rp85)) & 127)
			if !mu0[rx85] {
				break
			}
			if mk0[rx85] == rk85 {
				v507 = float64(rx85 + 1)
				break
			}
		}
	}
	v508 = v507
	v510 = v508 != 0
	if !v510 {
		v254 = v131
		v255 = v132
		v256 = v133
		v257 = v134
		v258 = v135
		v259 = v136
		v260 = v137
		v261 = v138
		v262 = v139
		v263 = v140
		goto b15
	}
	goto b7
b7:
	ri0 = 0
	v172 = v131
	v173 = v132
	v174 = v133
	v175 = v134
	v176 = v135
	v177 = v136
	v178 = v137
	v179 = v138
	v180 = v139
	v181 = v140
	v184 = v507
	goto b8
b8:
	if ri0 >= 4 {
		v254 = v172
		v255 = v173
		v256 = v174
		v257 = v175
		v258 = v176
		v259 = v177
		v260 = v178
		v261 = v179
		v262 = v180
		v263 = v181
		goto b15
	}
	v516 = float64(ri0 + 1)
	ri0++
	goto b9
b9:
	v517 = v176
	if v516 < 1 || v516 > 4 {
		return machinePreparedReplayEntry()
	}
	v518 = ra0_0[int(v516)-1]
	v519 = v517 + v518
	v520 = v179
	if v516 < 1 || v516 > 4 {
		return machinePreparedReplayEntry()
	}
	v521 = ra0_1[int(v516)-1]
	v522 = v520 + v521
	v523, ok99 = backendGeneratedStructuralStringKey(v519, v522)
	if !ok99 {
		return machinePreparedReplayEntry()
	}
	v524 = v523
	v525 = 0
	{
		rk101 := v524
		rs101 := (uint32(rk101.first)*0x9e3779b1 ^ uint32(rk101.second)*0x85ebca6b) & 127
		for rp101 := 0; rp101 < 128; rp101++ {
			rx101 := int((rs101 + uint32(rp101)) & 127)
			if !mu0[rx101] {
				break
			}
			if mk0[rx101] == rk101 {
				v525 = float64(rx101 + 1)
				break
			}
		}
	}
	v526 = v525
	v528 = v526 != 0
	if !v528 {
		goto b13
	}
	goto b10
b10:
	if v184 < 1 || v184 > 128 {
		return machinePreparedReplayEntry()
	}
	v529 = mf0_1[int(v184)-1]
	if v525 < 1 || v525 > 128 {
		return machinePreparedReplayEntry()
	}
	v530 = mf0_1[int(v525)-1]
	v531 = v529 - v530
	if math.IsNaN(v531) {
		return machinePreparedReplayEntry()
	}
	if !(v531 < math.Float64frombits(0x0000000000000000)) {
		v213 = v172
		v214 = v173
		v215 = v174
		v216 = v175
		v217 = v176
		v218 = v177
		v219 = v178
		v220 = v179
		v221 = v180
		v222 = v181
		v225 = v184
		v235 = v525
		v237 = v531
		goto b12
	}
	goto b11
b11:
	v532 = -v531
	v213 = v172
	v214 = v173
	v215 = v174
	v216 = v175
	v217 = v176
	v218 = v177
	v219 = v178
	v220 = v179
	v221 = v180
	v222 = v181
	v225 = v184
	v235 = v525
	v237 = v532
	goto b12
b12:
	if v225 < 1 || v225 > 128 {
		return machinePreparedReplayEntry()
	}
	v533 = mf0_1[int(v225)-1]
	v534 = v214
	v535 = v534 - math.Floor(v534/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v536 = v533 + v535
	if v235 < 1 || v235 > 128 {
		return machinePreparedReplayEntry()
	}
	v537 = mf0_0[int(v235)-1]
	v538 = v536 - v537
	if v225 < 1 || v225 > 128 {
		return machinePreparedReplayEntry()
	}
	mf0_1[int(v225)-1] = v538
	v539 = v237
	v540 = v213 + v539
	if v225 < 1 || v225 > 128 {
		return machinePreparedReplayEntry()
	}
	v541 = mf0_1[int(v225)-1]
	v542 = v540 + v541
	v172 = v542
	v173 = v214
	v174 = v215
	v175 = v216
	v176 = v217
	v177 = v218
	v178 = v219
	v179 = v220
	v180 = v221
	v181 = v222
	v184 = v225
	goto b8
b13:
	v543 = v173 - math.Floor(v173/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	if v543 != math.Float64frombits(0x0000000000000000) {
		v172 = v172
		v173 = v173
		v174 = v174
		v175 = v175
		v176 = v176
		v177 = v177
		v178 = v178
		v179 = v179
		v180 = v180
		v181 = v181
		v184 = v184
		goto b8
	}
	goto b14
b14:
	v545 = v173
	v546 = v545 - math.Floor(v545/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v547 = v546 + math.Float64frombits(0x3ff0000000000000)
	r9_0 = v547
	v548 = v176
	v549 = v179
	v550 = v548 + v549
	v551 = v173
	v552 = v551 - math.Floor(v551/math.Float64frombits(0x4010000000000000))*math.Float64frombits(0x4010000000000000)
	v553 = v550 + v552
	r9_1 = v553
	v554 = v523
	{
		rk138 := v554
		rs138 := (uint32(rk138.first)*0x9e3779b1 ^ uint32(rk138.second)*0x85ebca6b) & 127
		rok138 := false
		for rp138 := 0; rp138 < 128; rp138++ {
			rx138 := int((rs138 + uint32(rp138)) & 127)
			if !mu0[rx138] {
				mu0[rx138] = true
				mk0[rx138] = rk138
			}
			if mk0[rx138] == rk138 {
				mf0_0[rx138] = r9_0
				mf0_1[rx138] = r9_1
				rok138 = true
				break
			}
		}
		if !rok138 {
			return machinePreparedReplayEntry()
		}
	}
	v555 = v523
	v556 = 0
	{
		rk140 := v555
		rs140 := (uint32(rk140.first)*0x9e3779b1 ^ uint32(rk140.second)*0x85ebca6b) & 127
		for rp140 := 0; rp140 < 128; rp140++ {
			rx140 := int((rs140 + uint32(rp140)) & 127)
			if !mu0[rx140] {
				break
			}
			if mk0[rx140] == rk140 {
				v556 = float64(rx140 + 1)
				break
			}
		}
	}
	if v556 < 1 || v556 > 128 {
		return machinePreparedReplayEntry()
	}
	v557 = mf0_1[int(v556)-1]
	v558 = v172 + v557
	v172 = v558
	v173 = v173
	v174 = v174
	v175 = v175
	v176 = v176
	v177 = v177
	v178 = v178
	v179 = v179
	v180 = v180
	v181 = v181
	v184 = v184
	goto b8
b15:
	v559 = v261 + v263
	v131 = v254
	v132 = v255
	v133 = v256
	v134 = v257
	v135 = v258
	v136 = v259
	v137 = v260
	v138 = v559
	v139 = v262
	v140 = v263
	goto b5
b16:
	v560 = v135 + v137
	v90 = v131
	v91 = v132
	v92 = v133
	v93 = v134
	v94 = v560
	v95 = v136
	v96 = v137
	goto b3
b17:
	v561 = v91 + v93
	v49 = v90
	v50 = v561
	v51 = v92
	v52 = v93
	goto b1
b18:
	v562 = v49
	v564 = 0
	{
		rk149 := backendPreparedStringKey{first: 2, second: 2}
		rs149 := (uint32(rk149.first)*0x9e3779b1 ^ uint32(rk149.second)*0x85ebca6b) & 127
		for rp149 := 0; rp149 < 128; rp149++ {
			rx149 := int((rs149 + uint32(rp149)) & 127)
			if !mu0[rx149] {
				break
			}
			if mk0[rx149] == rk149 {
				v564 = float64(rx149 + 1)
				break
			}
		}
	}
	if v564 == 0 {
		v290 = v564
		v324 = v562
		goto b20
	}
	goto b19
b19:
	v566 = 0
	{
		rk152 := backendPreparedStringKey{first: 2, second: 2}
		rs152 := (uint32(rk152.first)*0x9e3779b1 ^ uint32(rk152.second)*0x85ebca6b) & 127
		for rp152 := 0; rp152 < 128; rp152++ {
			rx152 := int((rs152 + uint32(rp152)) & 127)
			if !mu0[rx152] {
				break
			}
			if mk0[rx152] == rk152 {
				v566 = float64(rx152 + 1)
				break
			}
		}
	}
	if v566 < 1 || v566 > 128 {
		return machinePreparedReplayEntry()
	}
	v567 = mf0_1[int(v566)-1]
	v290 = v567
	v324 = v562
	goto b20
b20:
	if false {
		goto b22
	}
	goto b21
b21:
	v331 = v290
	v365 = v324
	goto b23
b22:
	v568 = math.Float64frombits(0x0000000000000000)
	v331 = v568
	v365 = v324
	goto b23
b23:
	v569 = v365 + v331
	v571 = 0
	{
		rk159 := backendPreparedStringKey{first: 4, second: 4}
		rs159 := (uint32(rk159.first)*0x9e3779b1 ^ uint32(rk159.second)*0x85ebca6b) & 127
		for rp159 := 0; rp159 < 128; rp159++ {
			rx159 := int((rs159 + uint32(rp159)) & 127)
			if !mu0[rx159] {
				break
			}
			if mk0[rx159] == rk159 {
				v571 = float64(rx159 + 1)
				break
			}
		}
	}
	if v571 == 0 {
		v372 = v571
		v406 = v569
		goto b25
	}
	goto b24
b24:
	v573 = 0
	{
		rk162 := backendPreparedStringKey{first: 4, second: 4}
		rs162 := (uint32(rk162.first)*0x9e3779b1 ^ uint32(rk162.second)*0x85ebca6b) & 127
		for rp162 := 0; rp162 < 128; rp162++ {
			rx162 := int((rs162 + uint32(rp162)) & 127)
			if !mu0[rx162] {
				break
			}
			if mk0[rx162] == rk162 {
				v573 = float64(rx162 + 1)
				break
			}
		}
	}
	if v573 < 1 || v573 > 128 {
		return machinePreparedReplayEntry()
	}
	v574 = mf0_1[int(v573)-1]
	v372 = v574
	v406 = v569
	goto b25
b25:
	if false {
		goto b27
	}
	goto b26
b26:
	v413 = v372
	v447 = v406
	goto b28
b27:
	v575 = math.Float64frombits(0x0000000000000000)
	v413 = v575
	v447 = v406
	goto b28
b28:
	v576 = v447 + v413
	return machinePreparedReturnOneNumber(v576)
}

func backendGeneratedSparseGridPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchangedAt(2, 1) {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchangedAt(2, 5) {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedSparseGridPreparedFixtureBody(context, p0)
}
