// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedProcgenRoomScoring(p0 float64) (float64, bool) {
	var v1 float64
	var v29 float64
	var v30 float64
	var v31 float64
	var v32 float64
	var v33 float64
	var v53 float64
	var v54 float64
	var v55 float64
	var v56 float64
	var v57 float64
	var v58 float64
	var v59 float64
	var v75 uint32
	var v77 float64
	var v78 float64
	var v79 float64
	var v80 float64
	var v81 float64
	var v82 float64
	var v83 float64
	var v86 float64
	var v90 float64
	var v99 uint32
	var v101 float64
	var v102 float64
	var v103 float64
	var v104 float64
	var v105 float64
	var v106 float64
	var v107 float64
	var v110 float64
	var v114 float64
	var v197 float64
	var v198 float64
	var v199 float64
	var v200 float64
	var v201 float64
	var v202 float64
	var v203 float64
	var v206 float64
	var v210 float64
	var v221 float64
	var v222 float64
	var v223 float64
	var v224 float64
	var v225 float64
	var v245 float64
	var v246 float64
	var v247 float64
	var v248 float64
	var v249 float64
	var v267 uint32
	var v268 float64
	var v269 float64
	var v270 float64
	var v271 float64
	var v273 uint32
	var v274 float64
	var v275 float64
	var v276 float64
	var v277 float64
	var v279 uint32
	var v280 float64
	var v281 float64
	var v282 float64
	var v283 float64
	var v285 uint32
	var v286 float64
	var v287 float64
	var v288 float64
	var v289 float64
	var v291 uint32
	var v292 float64
	var v293 float64
	var v294 float64
	var v295 float64
	var v296 float64
	var v297 float64
	var v298 float64
	var v302 float64
	var v303 float64
	var v304 float64
	var v305 float64
	var v306 float64
	var v311 float64
	var v312 float64
	var v313 float64
	var v314 float64
	var v315 float64
	var v316 float64
	var v317 float64
	var v318 float64
	var v319 float64
	var v320 float64
	var v321 float64
	var v322 float64
	var v323 float64
	var v324 float64
	var v325 float64
	var v326 uint32
	var v327 float64
	var v328 float64
	var v329 float64
	var v330 bool
	var v331 float64
	var v332 float64
	var v333 float64
	var v356 float64
	var v357 float64
	var v358 float64
	var v359 float64
	var v360 float64
	var v361 float64
	var v362 float64
	var v363 float64
	var v364 float64
	var v365 float64
	var v366 float64
	var v367 float64
	var v368 float64
	var v369 float64
	var v370 float64
	var v371 float64
	var v372 float64
	var v373 float64
	var v374 float64
	var v375 float64
	var v376 float64
	var v377 float64
	var v378 float64
	var v379 float64
	var v380 float64
	var r0_0 uint32
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r0_4 float64
	_ = r0_4
	var r1_0 uint32
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r1_3 float64
	_ = r1_3
	var r1_4 float64
	_ = r1_4
	var r2_0 uint32
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 float64
	_ = r2_2
	var r2_3 float64
	_ = r2_3
	var r2_4 float64
	_ = r2_4
	var r3_0 uint32
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r3_2 float64
	_ = r3_2
	var r3_3 float64
	_ = r3_3
	var r3_4 float64
	_ = r3_4
	var r4_0 uint32
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r4_2 float64
	_ = r4_2
	var r4_3 float64
	_ = r4_3
	var r4_4 float64
	_ = r4_4
	var ra0_0 [5]uint32
	var ra0_1 [5]float64
	var ra0_2 [5]float64
	var ra0_3 [5]float64
	var ra0_4 [5]float64
	var ri0 int
	_ = ri0
	v1 = p0
	v267 = uint32(1)
	r0_0 = v267
	v268 = math.Float64frombits(0x4000000000000000)
	r0_1 = v268
	v269 = math.Float64frombits(0x3ff0000000000000)
	r0_2 = v269
	v270 = math.Float64frombits(0x0000000000000000)
	r0_3 = v270
	v271 = math.Float64frombits(0x4010000000000000)
	r0_4 = v271
	ra0_0[0] = r0_0
	ra0_1[0] = r0_1
	ra0_2[0] = r0_2
	ra0_3[0] = r0_3
	ra0_4[0] = r0_4
	v273 = uint32(7)
	r1_0 = v273
	v274 = math.Float64frombits(0x4008000000000000)
	r1_1 = v274
	v275 = math.Float64frombits(0x4008000000000000)
	r1_2 = v275
	v276 = math.Float64frombits(0x401c000000000000)
	r1_3 = v276
	v277 = math.Float64frombits(0x4018000000000000)
	r1_4 = v277
	ra0_0[1] = r1_0
	ra0_1[1] = r1_1
	ra0_2[1] = r1_2
	ra0_3[1] = r1_3
	ra0_4[1] = r1_4
	v279 = uint32(8)
	r2_0 = v279
	v280 = math.Float64frombits(0x3ff0000000000000)
	r2_1 = v280
	v281 = math.Float64frombits(0x4022000000000000)
	r2_2 = v281
	v282 = math.Float64frombits(0x4008000000000000)
	r2_3 = v282
	v283 = math.Float64frombits(0x4008000000000000)
	r2_4 = v283
	ra0_0[2] = r2_0
	ra0_1[2] = r2_1
	ra0_2[2] = r2_2
	ra0_3[2] = r2_3
	ra0_4[2] = r2_4
	v285 = uint32(9)
	r3_0 = v285
	v286 = math.Float64frombits(0x4000000000000000)
	r3_1 = v286
	v287 = math.Float64frombits(0x4014000000000000)
	r3_2 = v287
	v288 = math.Float64frombits(0x4000000000000000)
	r3_3 = v288
	v289 = math.Float64frombits(0x4014000000000000)
	r3_4 = v289
	ra0_0[3] = r3_0
	ra0_1[3] = r3_1
	ra0_2[3] = r3_2
	ra0_3[3] = r3_3
	ra0_4[3] = r3_4
	v291 = uint32(10)
	r4_0 = v291
	v292 = math.Float64frombits(0x3ff0000000000000)
	r4_1 = v292
	v293 = math.Float64frombits(0x4028000000000000)
	r4_2 = v293
	v294 = math.Float64frombits(0x4028000000000000)
	r4_3 = v294
	v295 = math.Float64frombits(0x4020000000000000)
	r4_4 = v295
	ra0_0[4] = r4_0
	ra0_1[4] = r4_1
	ra0_2[4] = r4_2
	ra0_3[4] = r4_3
	ra0_4[4] = r4_4
	v296 = math.Float64frombits(0x0000000000000000)
	v297 = v1
	v298 = v297 - math.Floor(v297/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v302 = math.Float64frombits(0x3ff0000000000000)
	v303 = math.Float64frombits(0x4051800000000000)
	v304 = math.Float64frombits(0x3ff0000000000000)
	v29 = v296
	v30 = v298
	v31 = v302
	v32 = v303
	v33 = v304
	goto b1
b1:
	if math.IsNaN(v31) {
		return 0, false
	}
	if math.IsNaN(v32) {
		return 0, false
	}
	if math.IsNaN(v33) {
		return 0, false
	}
	if (v33 > 0 && v31 > v32) || (v33 <= 0 && v31 < v32) {
		goto b33
	}
	goto b2
b2:
	v305 = math.Float64frombits(0xc08f380000000000)
	v306 = math.Float64frombits(0x3ff0000000000000)
	ri0 = 0
	v53 = v29
	v54 = v30
	v55 = v31
	v56 = v32
	v57 = v33
	v58 = v305
	v59 = v306
	goto b3
b3:
	if ri0 >= 5 {
		goto b28
	}
	v311 = float64(ri0 + 1)
	v312 = v311
	ri0++
	goto b4
b4:
	if v312 < 1 || v312 > 5 {
		return 0, false
	}
	v313 = ra0_2[int(v312)-1]
	v314 = v313 * math.Float64frombits(0x4014000000000000)
	if v312 < 1 || v312 > 5 {
		return 0, false
	}
	v315 = ra0_1[int(v312)-1]
	v316 = v315 * math.Float64frombits(0x4020000000000000)
	v317 = v314 + v316
	if v312 < 1 || v312 > 5 {
		return 0, false
	}
	v318 = ra0_4[int(v312)-1]
	v319 = v318 * math.Float64frombits(0x4000000000000000)
	v320 = v317 + v319
	if v312 < 1 || v312 > 5 {
		return 0, false
	}
	v321 = ra0_3[int(v312)-1]
	v322 = v321 * math.Float64frombits(0x4008000000000000)
	v323 = v320 - v322
	v324 = v54
	v325 = v323 - v324
	goto b5
b5:
	if v312 < 1 || v312 > 5 {
		return 0, false
	}
	v326 = ra0_0[int(v312)-1]
	if v326 != uint32(7) {
		v75 = v326
		v77 = v53
		v78 = v54
		v79 = v55
		v80 = v56
		v81 = v57
		v82 = v58
		v83 = v59
		v86 = v311
		v90 = v325
		goto b8
	}
	goto b6
b6:
	v327 = v55
	v328 = v327 - math.Floor(v327/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v329 = math.Float64frombits(0x0000000000000000)
	v330 = v328 == v329
	if !v330 {
		v75 = v326
		v77 = v53
		v78 = v54
		v79 = v55
		v80 = v56
		v81 = v57
		v82 = v58
		v83 = v59
		v86 = v311
		v90 = v325
		goto b8
	}
	goto b7
b7:
	v331 = v325 + math.Float64frombits(0x4028000000000000)
	v197 = v53
	v198 = v54
	v199 = v55
	v200 = v56
	v201 = v57
	v202 = v58
	v203 = v59
	v206 = v311
	v210 = v331
	goto b26
b8:
	if v75 != uint32(8) {
		v99 = v75
		v101 = v77
		v102 = v78
		v103 = v79
		v104 = v80
		v105 = v81
		v106 = v82
		v107 = v83
		v110 = v86
		v114 = v90
		goto b11
	}
	goto b9
b9:
	if math.IsNaN(v78) {
		return 0, false
	}
	if !(v78 > math.Float64frombits(0x4020000000000000)) {
		v99 = v75
		v101 = v77
		v102 = v78
		v103 = v79
		v104 = v80
		v105 = v81
		v106 = v82
		v107 = v83
		v110 = v86
		v114 = v90
		goto b11
	}
	goto b10
b10:
	v332 = v90 + math.Float64frombits(0x4032000000000000)
	v197 = v77
	v198 = v78
	v199 = v79
	v200 = v80
	v201 = v81
	v202 = v82
	v203 = v83
	v206 = v86
	v210 = v332
	goto b26
b11:
	if v99 != uint32(10) {
		v197 = v101
		v198 = v102
		v199 = v103
		v200 = v104
		v201 = v105
		v202 = v106
		v203 = v107
		v206 = v110
		v210 = v114
		goto b26
	}
	goto b12
b12:
	if math.IsNaN(v102) {
		return 0, false
	}
	if !(v102 < math.Float64frombits(0x4024000000000000)) {
		v197 = v101
		v198 = v102
		v199 = v103
		v200 = v104
		v201 = v105
		v202 = v106
		v203 = v107
		v206 = v110
		v210 = v114
		goto b26
	}
	goto b13
b13:
	v333 = v114 - math.Float64frombits(0x403e000000000000)
	v197 = v101
	v198 = v102
	v199 = v103
	v200 = v104
	v201 = v105
	v202 = v106
	v203 = v107
	v206 = v110
	v210 = v333
	goto b26
b26:
	if math.IsNaN(v210) {
		return 0, false
	}
	if math.IsNaN(v202) {
		return 0, false
	}
	if !(v210 > v202) {
		v53 = v197
		v54 = v198
		v55 = v199
		v56 = v200
		v57 = v201
		v58 = v202
		v59 = v203
		goto b3
	}
	goto b27
b27:
	v356 = v210
	v357 = v206
	v53 = v197
	v54 = v198
	v55 = v199
	v56 = v200
	v57 = v201
	v58 = v356
	v59 = v357
	goto b3
b28:
	v358 = v59
	v359 = 0
	if v358 >= 1 && v358 <= 5 && v358 == math.Trunc(v358) {
		v359 = v358
	}
	v360 = v58
	v361 = v53 + v360
	if v359 < 1 || v359 > 5 {
		return 0, false
	}
	v362 = ra0_2[int(v359)-1]
	v363 = v361 + v362
	if v359 < 1 || v359 > 5 {
		return 0, false
	}
	v364 = ra0_1[int(v359)-1]
	v365 = v54 + v364
	if v359 < 1 || v359 > 5 {
		return 0, false
	}
	v366 = ra0_3[int(v359)-1]
	v367 = v55
	v368 = v367 - math.Floor(v367/math.Float64frombits(0x4010000000000000))*math.Float64frombits(0x4010000000000000)
	v369 = v366 + v368
	if v359 < 1 || v359 > 5 {
		return 0, false
	}
	ra0_3[int(v359)-1] = v369
	v370 = math.Float64frombits(0x3ff0000000000000)
	if v359 < 1 || v359 > 5 {
		return 0, false
	}
	v371 = ra0_2[int(v359)-1]
	v372 = v371 - v370
	if v359 < 1 || v359 > 5 {
		return 0, false
	}
	ra0_2[int(v359)-1] = v372
	if v359 < 1 || v359 > 5 {
		return 0, false
	}
	v373 = ra0_2[int(v359)-1]
	if math.IsNaN(v373) {
		return 0, false
	}
	if !(v373 < math.Float64frombits(0x0000000000000000)) {
		v221 = v363
		v222 = v365
		v223 = v55
		v224 = v56
		v225 = v57
		goto b30
	}
	goto b29
b29:
	v374 = v55
	v375 = v374 - math.Floor(v374/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	if v359 < 1 || v359 > 5 {
		return 0, false
	}
	ra0_2[int(v359)-1] = v375
	v221 = v363
	v222 = v365
	v223 = v55
	v224 = v56
	v225 = v57
	goto b30
b30:
	if math.IsNaN(v222) {
		return 0, false
	}
	if !(v222 > math.Float64frombits(0x4034000000000000)) {
		v245 = v221
		v246 = v222
		v247 = v223
		v248 = v224
		v249 = v225
		goto b32
	}
	goto b31
b31:
	v376 = v222 - math.Float64frombits(0x4026000000000000)
	v245 = v221
	v246 = v376
	v247 = v223
	v248 = v224
	v249 = v225
	goto b32
b32:
	v377 = v247 + v249
	v29 = v245
	v30 = v246
	v31 = v377
	v32 = v248
	v33 = v249
	goto b1
b33:
	v378 = v29
	v379 = v30
	v380 = v378 + v379
	return v380, true
}

func backendGeneratedProcgenRoomScoringPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v29 float64
	var v30 float64
	var v31 float64
	var v32 float64
	var v33 float64
	var v53 float64
	var v54 float64
	var v55 float64
	var v56 float64
	var v57 float64
	var v58 float64
	var v59 float64
	var v75 uint32
	var v77 float64
	var v78 float64
	var v79 float64
	var v80 float64
	var v81 float64
	var v82 float64
	var v83 float64
	var v86 float64
	var v90 float64
	var v99 uint32
	var v101 float64
	var v102 float64
	var v103 float64
	var v104 float64
	var v105 float64
	var v106 float64
	var v107 float64
	var v110 float64
	var v114 float64
	var v197 float64
	var v198 float64
	var v199 float64
	var v200 float64
	var v201 float64
	var v202 float64
	var v203 float64
	var v206 float64
	var v210 float64
	var v221 float64
	var v222 float64
	var v223 float64
	var v224 float64
	var v225 float64
	var v245 float64
	var v246 float64
	var v247 float64
	var v248 float64
	var v249 float64
	var v267 uint32
	var v268 float64
	var v269 float64
	var v270 float64
	var v271 float64
	var v273 uint32
	var v274 float64
	var v275 float64
	var v276 float64
	var v277 float64
	var v279 uint32
	var v280 float64
	var v281 float64
	var v282 float64
	var v283 float64
	var v285 uint32
	var v286 float64
	var v287 float64
	var v288 float64
	var v289 float64
	var v291 uint32
	var v292 float64
	var v293 float64
	var v294 float64
	var v295 float64
	var v296 float64
	var v297 float64
	var v298 float64
	var v302 float64
	var v303 float64
	var v304 float64
	var v305 float64
	var v306 float64
	var v311 float64
	var v312 float64
	var v313 float64
	var v314 float64
	var v315 float64
	var v316 float64
	var v317 float64
	var v318 float64
	var v319 float64
	var v320 float64
	var v321 float64
	var v322 float64
	var v323 float64
	var v324 float64
	var v325 float64
	var v326 uint32
	var v327 float64
	var v328 float64
	var v329 float64
	var v330 bool
	var v331 float64
	var v332 float64
	var v333 float64
	var v356 float64
	var v357 float64
	var v358 float64
	var v359 float64
	var v360 float64
	var v361 float64
	var v362 float64
	var v363 float64
	var v364 float64
	var v365 float64
	var v366 float64
	var v367 float64
	var v368 float64
	var v369 float64
	var v370 float64
	var v371 float64
	var v372 float64
	var v373 float64
	var v374 float64
	var v375 float64
	var v376 float64
	var v377 float64
	var v378 float64
	var v379 float64
	var v380 float64
	var r0_0 uint32
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r0_4 float64
	_ = r0_4
	var r1_0 uint32
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r1_3 float64
	_ = r1_3
	var r1_4 float64
	_ = r1_4
	var r2_0 uint32
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 float64
	_ = r2_2
	var r2_3 float64
	_ = r2_3
	var r2_4 float64
	_ = r2_4
	var r3_0 uint32
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r3_2 float64
	_ = r3_2
	var r3_3 float64
	_ = r3_3
	var r3_4 float64
	_ = r3_4
	var r4_0 uint32
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r4_2 float64
	_ = r4_2
	var r4_3 float64
	_ = r4_3
	var r4_4 float64
	_ = r4_4
	var ra0_0 [5]uint32
	var ra0_1 [5]float64
	var ra0_2 [5]float64
	var ra0_3 [5]float64
	var ra0_4 [5]float64
	var ri0 int
	_ = ri0
	v1 = p0
	v267 = uint32(1)
	r0_0 = v267
	v268 = math.Float64frombits(0x4000000000000000)
	r0_1 = v268
	v269 = math.Float64frombits(0x3ff0000000000000)
	r0_2 = v269
	v270 = math.Float64frombits(0x0000000000000000)
	r0_3 = v270
	v271 = math.Float64frombits(0x4010000000000000)
	r0_4 = v271
	ra0_0[0] = r0_0
	ra0_1[0] = r0_1
	ra0_2[0] = r0_2
	ra0_3[0] = r0_3
	ra0_4[0] = r0_4
	v273 = uint32(7)
	r1_0 = v273
	v274 = math.Float64frombits(0x4008000000000000)
	r1_1 = v274
	v275 = math.Float64frombits(0x4008000000000000)
	r1_2 = v275
	v276 = math.Float64frombits(0x401c000000000000)
	r1_3 = v276
	v277 = math.Float64frombits(0x4018000000000000)
	r1_4 = v277
	ra0_0[1] = r1_0
	ra0_1[1] = r1_1
	ra0_2[1] = r1_2
	ra0_3[1] = r1_3
	ra0_4[1] = r1_4
	v279 = uint32(8)
	r2_0 = v279
	v280 = math.Float64frombits(0x3ff0000000000000)
	r2_1 = v280
	v281 = math.Float64frombits(0x4022000000000000)
	r2_2 = v281
	v282 = math.Float64frombits(0x4008000000000000)
	r2_3 = v282
	v283 = math.Float64frombits(0x4008000000000000)
	r2_4 = v283
	ra0_0[2] = r2_0
	ra0_1[2] = r2_1
	ra0_2[2] = r2_2
	ra0_3[2] = r2_3
	ra0_4[2] = r2_4
	v285 = uint32(9)
	r3_0 = v285
	v286 = math.Float64frombits(0x4000000000000000)
	r3_1 = v286
	v287 = math.Float64frombits(0x4014000000000000)
	r3_2 = v287
	v288 = math.Float64frombits(0x4000000000000000)
	r3_3 = v288
	v289 = math.Float64frombits(0x4014000000000000)
	r3_4 = v289
	ra0_0[3] = r3_0
	ra0_1[3] = r3_1
	ra0_2[3] = r3_2
	ra0_3[3] = r3_3
	ra0_4[3] = r3_4
	v291 = uint32(10)
	r4_0 = v291
	v292 = math.Float64frombits(0x3ff0000000000000)
	r4_1 = v292
	v293 = math.Float64frombits(0x4028000000000000)
	r4_2 = v293
	v294 = math.Float64frombits(0x4028000000000000)
	r4_3 = v294
	v295 = math.Float64frombits(0x4020000000000000)
	r4_4 = v295
	ra0_0[4] = r4_0
	ra0_1[4] = r4_1
	ra0_2[4] = r4_2
	ra0_3[4] = r4_3
	ra0_4[4] = r4_4
	v296 = math.Float64frombits(0x0000000000000000)
	v297 = v1
	v298 = v297 - math.Floor(v297/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v302 = math.Float64frombits(0x3ff0000000000000)
	v303 = math.Float64frombits(0x4051800000000000)
	v304 = math.Float64frombits(0x3ff0000000000000)
	v29 = v296
	v30 = v298
	v31 = v302
	v32 = v303
	v33 = v304
	goto b1
b1:
	if math.IsNaN(v31) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v32) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v33) {
		return machinePreparedReplayEntry()
	}
	if (v33 > 0 && v31 > v32) || (v33 <= 0 && v31 < v32) {
		goto b33
	}
	goto b2
b2:
	v305 = math.Float64frombits(0xc08f380000000000)
	v306 = math.Float64frombits(0x3ff0000000000000)
	ri0 = 0
	v53 = v29
	v54 = v30
	v55 = v31
	v56 = v32
	v57 = v33
	v58 = v305
	v59 = v306
	goto b3
b3:
	if ri0 >= 5 {
		goto b28
	}
	v311 = float64(ri0 + 1)
	v312 = v311
	ri0++
	goto b4
b4:
	if v312 < 1 || v312 > 5 {
		return machinePreparedReplayEntry()
	}
	v313 = ra0_2[int(v312)-1]
	v314 = v313 * math.Float64frombits(0x4014000000000000)
	if v312 < 1 || v312 > 5 {
		return machinePreparedReplayEntry()
	}
	v315 = ra0_1[int(v312)-1]
	v316 = v315 * math.Float64frombits(0x4020000000000000)
	v317 = v314 + v316
	if v312 < 1 || v312 > 5 {
		return machinePreparedReplayEntry()
	}
	v318 = ra0_4[int(v312)-1]
	v319 = v318 * math.Float64frombits(0x4000000000000000)
	v320 = v317 + v319
	if v312 < 1 || v312 > 5 {
		return machinePreparedReplayEntry()
	}
	v321 = ra0_3[int(v312)-1]
	v322 = v321 * math.Float64frombits(0x4008000000000000)
	v323 = v320 - v322
	v324 = v54
	v325 = v323 - v324
	goto b5
b5:
	if v312 < 1 || v312 > 5 {
		return machinePreparedReplayEntry()
	}
	v326 = ra0_0[int(v312)-1]
	if v326 != uint32(7) {
		v75 = v326
		v77 = v53
		v78 = v54
		v79 = v55
		v80 = v56
		v81 = v57
		v82 = v58
		v83 = v59
		v86 = v311
		v90 = v325
		goto b8
	}
	goto b6
b6:
	v327 = v55
	v328 = v327 - math.Floor(v327/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v329 = math.Float64frombits(0x0000000000000000)
	v330 = v328 == v329
	if !v330 {
		v75 = v326
		v77 = v53
		v78 = v54
		v79 = v55
		v80 = v56
		v81 = v57
		v82 = v58
		v83 = v59
		v86 = v311
		v90 = v325
		goto b8
	}
	goto b7
b7:
	v331 = v325 + math.Float64frombits(0x4028000000000000)
	v197 = v53
	v198 = v54
	v199 = v55
	v200 = v56
	v201 = v57
	v202 = v58
	v203 = v59
	v206 = v311
	v210 = v331
	goto b26
b8:
	if v75 != uint32(8) {
		v99 = v75
		v101 = v77
		v102 = v78
		v103 = v79
		v104 = v80
		v105 = v81
		v106 = v82
		v107 = v83
		v110 = v86
		v114 = v90
		goto b11
	}
	goto b9
b9:
	if math.IsNaN(v78) {
		return machinePreparedReplayEntry()
	}
	if !(v78 > math.Float64frombits(0x4020000000000000)) {
		v99 = v75
		v101 = v77
		v102 = v78
		v103 = v79
		v104 = v80
		v105 = v81
		v106 = v82
		v107 = v83
		v110 = v86
		v114 = v90
		goto b11
	}
	goto b10
b10:
	v332 = v90 + math.Float64frombits(0x4032000000000000)
	v197 = v77
	v198 = v78
	v199 = v79
	v200 = v80
	v201 = v81
	v202 = v82
	v203 = v83
	v206 = v86
	v210 = v332
	goto b26
b11:
	if v99 != uint32(10) {
		v197 = v101
		v198 = v102
		v199 = v103
		v200 = v104
		v201 = v105
		v202 = v106
		v203 = v107
		v206 = v110
		v210 = v114
		goto b26
	}
	goto b12
b12:
	if math.IsNaN(v102) {
		return machinePreparedReplayEntry()
	}
	if !(v102 < math.Float64frombits(0x4024000000000000)) {
		v197 = v101
		v198 = v102
		v199 = v103
		v200 = v104
		v201 = v105
		v202 = v106
		v203 = v107
		v206 = v110
		v210 = v114
		goto b26
	}
	goto b13
b13:
	v333 = v114 - math.Float64frombits(0x403e000000000000)
	v197 = v101
	v198 = v102
	v199 = v103
	v200 = v104
	v201 = v105
	v202 = v106
	v203 = v107
	v206 = v110
	v210 = v333
	goto b26
b26:
	if math.IsNaN(v210) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v202) {
		return machinePreparedReplayEntry()
	}
	if !(v210 > v202) {
		v53 = v197
		v54 = v198
		v55 = v199
		v56 = v200
		v57 = v201
		v58 = v202
		v59 = v203
		goto b3
	}
	goto b27
b27:
	v356 = v210
	v357 = v206
	v53 = v197
	v54 = v198
	v55 = v199
	v56 = v200
	v57 = v201
	v58 = v356
	v59 = v357
	goto b3
b28:
	v358 = v59
	v359 = 0
	if v358 >= 1 && v358 <= 5 && v358 == math.Trunc(v358) {
		v359 = v358
	}
	v360 = v58
	v361 = v53 + v360
	if v359 < 1 || v359 > 5 {
		return machinePreparedReplayEntry()
	}
	v362 = ra0_2[int(v359)-1]
	v363 = v361 + v362
	if v359 < 1 || v359 > 5 {
		return machinePreparedReplayEntry()
	}
	v364 = ra0_1[int(v359)-1]
	v365 = v54 + v364
	if v359 < 1 || v359 > 5 {
		return machinePreparedReplayEntry()
	}
	v366 = ra0_3[int(v359)-1]
	v367 = v55
	v368 = v367 - math.Floor(v367/math.Float64frombits(0x4010000000000000))*math.Float64frombits(0x4010000000000000)
	v369 = v366 + v368
	if v359 < 1 || v359 > 5 {
		return machinePreparedReplayEntry()
	}
	ra0_3[int(v359)-1] = v369
	v370 = math.Float64frombits(0x3ff0000000000000)
	if v359 < 1 || v359 > 5 {
		return machinePreparedReplayEntry()
	}
	v371 = ra0_2[int(v359)-1]
	v372 = v371 - v370
	if v359 < 1 || v359 > 5 {
		return machinePreparedReplayEntry()
	}
	ra0_2[int(v359)-1] = v372
	if v359 < 1 || v359 > 5 {
		return machinePreparedReplayEntry()
	}
	v373 = ra0_2[int(v359)-1]
	if math.IsNaN(v373) {
		return machinePreparedReplayEntry()
	}
	if !(v373 < math.Float64frombits(0x0000000000000000)) {
		v221 = v363
		v222 = v365
		v223 = v55
		v224 = v56
		v225 = v57
		goto b30
	}
	goto b29
b29:
	v374 = v55
	v375 = v374 - math.Floor(v374/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	if v359 < 1 || v359 > 5 {
		return machinePreparedReplayEntry()
	}
	ra0_2[int(v359)-1] = v375
	v221 = v363
	v222 = v365
	v223 = v55
	v224 = v56
	v225 = v57
	goto b30
b30:
	if math.IsNaN(v222) {
		return machinePreparedReplayEntry()
	}
	if !(v222 > math.Float64frombits(0x4034000000000000)) {
		v245 = v221
		v246 = v222
		v247 = v223
		v248 = v224
		v249 = v225
		goto b32
	}
	goto b31
b31:
	v376 = v222 - math.Float64frombits(0x4026000000000000)
	v245 = v221
	v246 = v376
	v247 = v223
	v248 = v224
	v249 = v225
	goto b32
b32:
	v377 = v247 + v249
	v29 = v245
	v30 = v246
	v31 = v377
	v32 = v248
	v33 = v249
	goto b1
b33:
	v378 = v29
	v379 = v30
	v380 = v378 + v379
	return machinePreparedReturnOneNumber(v380)
}

func backendGeneratedProcgenRoomScoringPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedProcgenRoomScoringPreparedFixtureBody(context, p0)
}
