package ember

import (
	"fmt"
	"go/format"
	"go/token"
	"strings"
)

type backendGoNumericOptions struct {
	packageName          string
	functionName         string
	preparedFunctionName string
	directTargets        []backendGoNumericTarget
	selfRecursive        bool
	fixedVarargCount     int
}

type backendGoNumericTarget struct {
	ir               *backendProtoIR
	functionName     string
	selfRecursive    bool
	fixedVarargCount int
}

type backendGoNumericPlan struct {
	tags []backendTagMask
	used []bool
	// scalarReplacedValues have no canonical Machine value in prepared code.
	scalarReplacedValues []bool
	// replayEntry marks exits whose exact spill would require one of those values.
	replayEntry []bool
	tables      backendGoScalarTablePlan
	closures    backendGoScalarClosurePlan
}

type backendGoNumericEmitter struct {
	ir        *backendProtoIR
	plan      backendGoNumericPlan
	body      strings.Builder
	needsMath bool
	prepared  bool
	options   backendGoNumericOptions
}

func emitBackendGoNumericProof(ir *backendProtoIR, options backendGoNumericOptions) ([]byte, error) {
	if err := verifyBackendProtoIR(ir); err != nil {
		return nil, fmt.Errorf("emit backend Go numeric proof: %w", err)
	}
	if !token.IsIdentifier(options.packageName) || token.Lookup(options.packageName).IsKeyword() {
		return nil, fmt.Errorf("emit backend Go numeric proof: invalid package name %q", options.packageName)
	}
	if !token.IsIdentifier(options.functionName) || token.Lookup(options.functionName).IsKeyword() {
		return nil, fmt.Errorf("emit backend Go numeric proof: invalid function name %q", options.functionName)
	}
	if options.preparedFunctionName != "" &&
		(!token.IsIdentifier(options.preparedFunctionName) || token.Lookup(options.preparedFunctionName).IsKeyword()) {
		return nil, fmt.Errorf("emit backend Go numeric proof: invalid prepared function name %q", options.preparedFunctionName)
	}
	if options.preparedFunctionName != "" && len(ir.upvalues) != 0 {
		return nil, fmt.Errorf("emit backend Go numeric proof: prepared entry has %d upvalues", len(ir.upvalues))
	}
	if options.preparedFunctionName != "" && ir.variadic {
		return nil, fmt.Errorf("emit backend Go numeric proof: prepared entry is variadic")
	}
	parameterCount, ok := backendGoNumericArgumentCount(ir, options.fixedVarargCount)
	if !ok {
		return nil, fmt.Errorf("emit backend Go numeric proof: invalid fixed vararg count %d", options.fixedVarargCount)
	}
	if options.selfRecursive && !backendGoNumericSelfRecursiveTarget(ir) {
		return nil, fmt.Errorf("emit backend Go numeric proof: function is not a bounded self-recursive target")
	}
	if err := verifyBackendGoNumericTargets(options.directTargets); err != nil {
		return nil, err
	}
	plan, err := buildBackendGoNumericPlan(ir, options)
	if err != nil {
		return nil, err
	}
	directEmitter := backendGoNumericEmitter{ir: ir, plan: plan, options: options}
	if err := directEmitter.emitBody(); err != nil {
		return nil, err
	}
	if options.selfRecursive {
		directEmitter.needsMath = true
	}
	preparedEmitter := backendGoNumericEmitter{ir: ir, plan: plan, prepared: true, options: options}
	if options.preparedFunctionName != "" {
		if err := preparedEmitter.emitBody(); err != nil {
			return nil, err
		}
	}

	var source strings.Builder
	source.WriteString("// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.\n\n")
	fmt.Fprintf(&source, "package %s\n\n", options.packageName)
	if directEmitter.needsMath || preparedEmitter.needsMath {
		source.WriteString("import \"math\"\n\n")
	}
	pointerUpvalues := len(ir.upvalues)
	if options.selfRecursive {
		pointerUpvalues = 0
	}
	if options.selfRecursive {
		fmt.Fprintf(
			&source,
			"func %s(p0 float64) (float64, bool) {\n\tif math.IsNaN(p0) || p0 > %d {\n\t\treturn 0, false\n\t}\n\treturn %sBody(p0), true\n}\n\n",
			options.functionName,
			backendGoMaxPreparedRecursiveArgument,
			options.functionName,
		)
		fmt.Fprintf(&source, "func %sBody(p0 float64) float64 {\n", options.functionName)
	} else {
		fmt.Fprintf(&source, "func %s(", options.functionName)
		for upvalue := 0; upvalue < pointerUpvalues; upvalue++ {
			if upvalue != 0 {
				source.WriteString(", ")
			}
			fmt.Fprintf(&source, "u%d *float64", upvalue)
		}
		for parameter := 0; parameter < parameterCount; parameter++ {
			if pointerUpvalues != 0 || parameter != 0 {
				source.WriteString(", ")
			}
			fmt.Fprintf(&source, "p%d float64", parameter)
		}
		source.WriteString(") (float64, bool) {\n")
		for upvalue := 0; upvalue < pointerUpvalues; upvalue++ {
			fmt.Fprintf(&source, "\tif u%d == nil {\n\t\treturn 0, false\n\t}\n", upvalue)
		}
	}
	for valueIndex := range ir.values {
		if !plan.used[valueIndex] {
			continue
		}
		if plan.tags[valueIndex] == backendTagNil {
			continue
		}
		goType, ok := backendGoNumericType(plan.tags[valueIndex])
		if !ok {
			return nil, fmt.Errorf("emit backend Go numeric proof: SSA value %d has unsupported tags %x", valueIndex+1, plan.tags[valueIndex])
		}
		fmt.Fprintf(&source, "\tvar v%d %s\n", valueIndex+1, goType)
	}
	for fieldIndex, field := range plan.tables.fields {
		goType, ok := backendGoNumericType(field.tags)
		if !ok {
			continue
		}
		fmt.Fprintf(&source, "\tvar f%d %s\n", fieldIndex, goType)
		fmt.Fprintf(&source, "\t_ = f%d\n", fieldIndex)
	}
	for arrayIndex, array := range plan.tables.arrays {
		goType, ok := backendGoNumericType(array.tags)
		if !ok {
			return nil, fmt.Errorf("emit backend Go numeric proof: scalar array %d has unsupported tags %x", arrayIndex, array.tags)
		}
		fmt.Fprintf(&source, "\tvar a%d [%d]%s\n", arrayIndex, array.capacity, goType)
		fmt.Fprintf(&source, "\t_ = a%d\n", arrayIndex)
		if array.mutable {
			fmt.Fprintf(&source, "\tvar h%d int\n", arrayIndex)
			fmt.Fprintf(&source, "\t_ = h%d\n", arrayIndex)
			fmt.Fprintf(&source, "\tvar n%d = %d\n", arrayIndex, array.length)
			fmt.Fprintf(&source, "\t_ = n%d\n", arrayIndex)
			fmt.Fprintf(&source, "\tvar t%d int\n", arrayIndex)
			fmt.Fprintf(&source, "\t_ = t%d\n", arrayIndex)
		}
		fmt.Fprintf(&source, "\tvar i%d int\n", arrayIndex)
		fmt.Fprintf(&source, "\t_ = i%d\n", arrayIndex)
	}
	for cell := 0; cell < plan.closures.cellCount; cell++ {
		fmt.Fprintf(&source, "\tvar c%d float64\n", cell)
		fmt.Fprintf(&source, "\t_ = c%d\n", cell)
		fmt.Fprintf(&source, "\tvar s%d float64\n", cell)
		fmt.Fprintf(&source, "\t_ = s%d\n", cell)
	}
	for pc := range ir.ops {
		operation := &ir.ops[pc]
		if _, _, factory := plan.closures.factory(operation); factory {
			continue
		}
		if !backendGoNumericOperationDead(plan, operation) &&
			operation.op == opCallLocalOne {
			fmt.Fprintf(&source, "\tvar ok%d bool\n", operation.pc)
		}
	}
	for parameter := 0; parameter < ir.params; parameter++ {
		id := ir.initial[parameter]
		if plan.used[id-1] {
			fmt.Fprintf(&source, "\tv%d = p%d\n", id, parameter)
		}
	}
	source.WriteString(directEmitter.body.String())
	source.WriteString("}\n")
	if options.preparedFunctionName != "" {
		bodyName := options.preparedFunctionName + "Body"
		fmt.Fprintf(&source, "\nfunc %s(context machinePreparedContext", bodyName)
		for parameter := 0; parameter < ir.params; parameter++ {
			fmt.Fprintf(&source, ", p%d float64", parameter)
		}
		source.WriteString(") machinePreparedExit {\n")
		for valueIndex := range ir.values {
			if !plan.used[valueIndex] || plan.tags[valueIndex] == backendTagNil {
				continue
			}
			goType, ok := backendGoNumericType(plan.tags[valueIndex])
			if !ok {
				return nil, fmt.Errorf("emit backend Go numeric proof: SSA value %d has unsupported tags %x", valueIndex+1, plan.tags[valueIndex])
			}
			fmt.Fprintf(&source, "\tvar v%d %s\n", valueIndex+1, goType)
		}
		for fieldIndex, field := range plan.tables.fields {
			goType, ok := backendGoNumericType(field.tags)
			if !ok {
				continue
			}
			fmt.Fprintf(&source, "\tvar f%d %s\n", fieldIndex, goType)
			fmt.Fprintf(&source, "\t_ = f%d\n", fieldIndex)
		}
		for arrayIndex, array := range plan.tables.arrays {
			goType, ok := backendGoNumericType(array.tags)
			if !ok {
				return nil, fmt.Errorf("emit backend Go numeric proof: scalar array %d has unsupported tags %x", arrayIndex, array.tags)
			}
			fmt.Fprintf(&source, "\tvar a%d [%d]%s\n", arrayIndex, array.capacity, goType)
			fmt.Fprintf(&source, "\t_ = a%d\n", arrayIndex)
			if array.mutable {
				fmt.Fprintf(&source, "\tvar h%d int\n", arrayIndex)
				fmt.Fprintf(&source, "\t_ = h%d\n", arrayIndex)
				fmt.Fprintf(&source, "\tvar n%d = %d\n", arrayIndex, array.length)
				fmt.Fprintf(&source, "\t_ = n%d\n", arrayIndex)
				fmt.Fprintf(&source, "\tvar t%d int\n", arrayIndex)
				fmt.Fprintf(&source, "\t_ = t%d\n", arrayIndex)
			}
			fmt.Fprintf(&source, "\tvar i%d int\n", arrayIndex)
			fmt.Fprintf(&source, "\t_ = i%d\n", arrayIndex)
		}
		for cell := 0; cell < plan.closures.cellCount; cell++ {
			fmt.Fprintf(&source, "\tvar c%d float64\n", cell)
			fmt.Fprintf(&source, "\t_ = c%d\n", cell)
			fmt.Fprintf(&source, "\tvar s%d float64\n", cell)
			fmt.Fprintf(&source, "\t_ = s%d\n", cell)
		}
		for pc := range ir.ops {
			operation := &ir.ops[pc]
			if _, _, factory := plan.closures.factory(operation); factory {
				continue
			}
			if !backendGoNumericOperationDead(plan, operation) &&
				operation.op == opCallLocalOne {
				fmt.Fprintf(&source, "\tvar ok%d bool\n", operation.pc)
			}
		}
		for parameter := 0; parameter < ir.params; parameter++ {
			id := ir.initial[parameter]
			if plan.used[id-1] {
				fmt.Fprintf(&source, "\tv%d = p%d\n", id, parameter)
			}
		}
		source.WriteString(preparedEmitter.body.String())
		source.WriteString("}\n")

		fmt.Fprintf(&source, "\nfunc %s(context machinePreparedContext) machinePreparedExit {\n", options.preparedFunctionName)
		for parameter := 0; parameter < ir.params; parameter++ {
			fmt.Fprintf(&source, "\tp%d, ok := context.numberParameter(%d)\n", parameter, parameter)
			source.WriteString("\tif !ok {\n\t\treturn machinePreparedReplayEntry()\n\t}\n")
		}
		for pc := range ir.ops {
			operation := &ir.ops[pc]
			if operation.op != opFastCall {
				continue
			}
			if _, _, _, ok := plan.tables.arrayOperation(ir, operation); !ok {
				continue
			}
			fmt.Fprintf(&source, "\tif !context.intrinsicUnchanged(%d) {\n", operation.pc)
			source.WriteString("\t\treturn machinePreparedReplayEntry()\n\t}\n")
		}
		for protoID, target := range options.directTargets {
			if target.ir == nil {
				continue
			}
			for pc := range target.ir.ops {
				operation := &target.ir.ops[pc]
				if !backendGoNumericFixedVarargSelect(
					target.ir,
					target.fixedVarargCount,
					operation,
				) {
					continue
				}
				fmt.Fprintf(
					&source,
					"\tif !context.intrinsicUnchangedAt(%d, %d) {\n",
					protoID,
					operation.pc,
				)
				source.WriteString("\t\treturn machinePreparedReplayEntry()\n\t}\n")
			}
		}
		source.WriteString("\treturn ")
		source.WriteString(bodyName)
		source.WriteString("(context")
		for parameter := 0; parameter < ir.params; parameter++ {
			fmt.Fprintf(&source, ", p%d", parameter)
		}
		source.WriteString(")\n}\n")
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("emit backend Go numeric proof: format generated source: %w", err)
	}
	return formatted, nil
}

func verifyBackendGoNumericTargets(targets []backendGoNumericTarget) error {
	for protoID, target := range targets {
		if target.ir == nil && target.functionName == "" {
			continue
		}
		if target.ir == nil ||
			!token.IsIdentifier(target.functionName) ||
			token.Lookup(target.functionName).IsKeyword() {
			return fmt.Errorf("emit backend Go numeric proof: invalid direct target Proto %d", protoID)
		}
		if err := verifyBackendProtoIR(target.ir); err != nil {
			return fmt.Errorf("emit backend Go numeric proof: direct target Proto %d: %w", protoID, err)
		}
		if _, ok := backendGoNumericArgumentCount(target.ir, target.fixedVarargCount); !ok {
			return fmt.Errorf("emit backend Go numeric proof: direct target Proto %d has invalid fixed vararg count", protoID)
		}
		targetOptions := backendGoNumericOptions{
			functionName:     target.functionName,
			selfRecursive:    target.selfRecursive,
			fixedVarargCount: target.fixedVarargCount,
		}
		if target.selfRecursive && !backendGoNumericSelfRecursiveTarget(target.ir) {
			return fmt.Errorf("emit backend Go numeric proof: direct target Proto %d is not bounded self recursion", protoID)
		}
		if _, err := buildBackendGoNumericPlan(target.ir, targetOptions); err != nil {
			if _, ok := backendGoNumericClosureFactory(target.ir, targets); !ok {
				return fmt.Errorf("emit backend Go numeric proof: direct target Proto %d is not a numeric leaf or closure factory: %w", protoID, err)
			}
		}
	}
	return nil
}

func buildBackendGoNumericPlan(ir *backendProtoIR, options backendGoNumericOptions) (backendGoNumericPlan, error) {
	tables, err := analyzeBackendGoScalarTables(ir)
	if err != nil {
		return backendGoNumericPlan{}, err
	}
	closures, err := analyzeBackendGoScalarClosures(ir, options)
	if err != nil {
		return backendGoNumericPlan{}, err
	}
	plan := backendGoNumericPlan{
		tags:                 make([]backendTagMask, len(ir.values)),
		used:                 make([]bool, len(ir.values)),
		scalarReplacedValues: make([]bool, len(ir.values)),
		replayEntry:          make([]bool, len(ir.ops)),
		tables:               tables,
		closures:             closures,
	}
	for register, id := range ir.initial {
		if register < ir.params {
			plan.tags[id-1] = backendTagNumber
		} else {
			plan.tags[id-1] = backendTagNil
		}
	}
	for {
		changed := false
		for valueIndex := range ir.values {
			value := &ir.values[valueIndex]
			var tags backendTagMask
			switch value.kind {
			case backendValueUndef, backendValueParameter:
				continue
			case backendValuePhi:
				block := &ir.blocks[value.block]
				phi := block.phis[value.register]
				for inputIndex, input := range phi.inputs {
					if !ir.blocks[block.predecessors[inputIndex]].reachable {
						continue
					}
					tags |= plan.tags[input-1]
				}
			case backendValueOperation:
				operation := &ir.ops[value.pc]
				if !ir.blocks[operation.block].reachable {
					continue
				}
				switch operation.op {
				case opLoadConst:
					if operation.b >= 0 && int(operation.b) < len(ir.constants) {
						tags = backendTagForValueKind(ir.constants[operation.b].kind)
					}
				case opMove:
					source := backendOperationUse(operation, operation.b)
					if source != invalidBackendValueID {
						tags = plan.tags[source-1]
					}
				case opAdd, opSub, opMul, opDiv, opMod, opIDiv, opPow, opNeg,
					opAddK, opSubK, opMulK, opDivK, opModK, opIDivK,
					opNumericForLoop:
					tags = backendTagNumber
				case opEqual, opNotEqual, opLess, opLessEqual, opGreater, opGreaterEqual:
					tags = backendTagBool
				case opClosure:
					tags = backendTagFunction
				case opNewTable:
					if plan.tables.root(value.id) != invalidBackendValueID {
						tags = backendTagTable
					}
				case opGetStringField:
					_, field, ok := plan.tables.operationField(ir, operation)
					if ok {
						if field.child != invalidBackendValueID {
							tags = backendTagTable
						} else {
							tags = field.tags
						}
					}
				case opPrepareIter:
					if value.register == operation.a {
						if _, _, _, ok := plan.tables.arrayOperation(ir, operation); ok {
							tags = backendTagTable
						}
					}
				case opArrayNextJump2:
					_, array, _, ok := plan.tables.arrayOperation(ir, operation)
					if ok {
						switch value.register {
						case operation.a:
							tags = backendTagNumber
						case operation.a + 1:
							tags = array.tags
						}
					}
				case opFastCall:
					if backendGoNumericFixedVarargSelect(ir, options.fixedVarargCount, operation) {
						tags = backendTagNumber
					} else if _, array, _, ok := plan.tables.arrayOperation(ir, operation); ok {
						switch nativeFuncID(operation.nativeID) {
						case nativeFuncTableInsert:
							tags = backendTagNil
						case nativeFuncTableRemove:
							tags = array.tags
						case nativeFuncRawLen:
							tags = backendTagNumber
						}
					}
				case opVararg:
					if _, ok := backendGoNumericVarargIndex(
						ir,
						options.fixedVarargCount,
						operation,
						value.register,
					); ok {
						tags = backendTagNumber
					}
				case opCallLocalOne:
					if _, _, ok := plan.closures.factory(operation); ok {
						tags = backendTagFunction
					} else if _, ok := plan.closures.call(operation); ok {
						tags = backendTagNumber
					} else if _, ok := backendGoNumericDirectTarget(options, operation); ok {
						tags = backendTagNumber
					}
				case opCallUpvalueOne:
					if options.selfRecursive && operation.b == 0 {
						tags = backendTagNumber
					}
				case opGetUpvalue:
					tags = backendTagNumber
				default:
					return backendGoNumericPlan{}, fmt.Errorf("emit backend Go numeric proof: PC %d writes through unsupported opcode %s", value.pc, opcodeName(operation.op))
				}
			}
			next := plan.tags[valueIndex] | tags
			if next != plan.tags[valueIndex] {
				plan.tags[valueIndex] = next
				changed = true
			}
		}
		if !changed {
			break
		}
	}
	var markScalarReplaced func(backendValueID)
	markScalarReplaced = func(id backendValueID) {
		if !ir.validBackendValue(id) || plan.scalarReplacedValues[id-1] {
			return
		}
		plan.scalarReplacedValues[id-1] = true
		for _, origin := range ir.values[id-1].origins {
			markScalarReplaced(origin)
		}
	}
	for pc := range ir.ops {
		operation := &ir.ops[pc]
		if backendGoNumericScalarReplacedCall(ir, options, operation) {
			markScalarReplaced(backendOperationUse(operation, operation.b))
			plan.replayEntry[pc] = true
		}
		if _, _, ok := plan.closures.factory(operation); ok {
			markScalarReplaced(backendOperationUse(operation, operation.b))
		}
		if _, ok := plan.closures.call(operation); ok {
			markScalarReplaced(backendOperationUse(operation, operation.b))
			plan.replayEntry[pc] = true
		}
	}
	for valueIndex, scalar := range plan.closures.scalarClosures {
		if scalar {
			markScalarReplaced(backendValueID(valueIndex + 1))
		}
	}
	for valueIndex, root := range plan.tables.roots {
		if root != invalidBackendValueID {
			markScalarReplaced(backendValueID(valueIndex + 1))
		}
	}
	for valueIndex, token := range plan.tables.iteratorValues {
		if token {
			markScalarReplaced(backendValueID(valueIndex + 1))
		}
	}
	for pc := range ir.ops {
		operation := &ir.ops[pc]
		for _, spill := range operation.spillValues {
			if plan.scalarReplacedValues[spill.value-1] {
				// The numeric lowerer is effect-free, so replaying the whole
				// function is exact when a scalar-replaced closure is live.
				plan.replayEntry[pc] = true
				break
			}
		}
	}
	work := make([]backendValueID, 0, len(ir.values))
	markUsed := func(id backendValueID) {
		if id == invalidBackendValueID || plan.scalarReplacedValues[id-1] || plan.used[id-1] {
			return
		}
		plan.used[id-1] = true
		work = append(work, id)
	}
	for blockIndex := range ir.blocks {
		block := &ir.blocks[blockIndex]
		if !block.reachable {
			continue
		}
		for pc := block.first; pc < block.last; pc++ {
			operation := &ir.ops[pc]
			if !plan.replayEntry[pc] {
				for _, spill := range operation.spillValues {
					markUsed(spill.value)
				}
			}
			if backendGoNumericPureProducer(operation.op) {
				continue
			}
			for _, use := range operation.uses {
				if operation.op == opCallLocalOne &&
					use.register == operation.b &&
					(backendGoNumericScalarReplacedCall(ir, options, operation) ||
						plan.closures.scalarValue(use.value)) {
					continue
				}
				markUsed(use.value)
			}
			for _, definition := range operation.defs {
				markUsed(definition.value)
			}
		}
	}
	for len(work) != 0 {
		id := work[len(work)-1]
		work = work[:len(work)-1]
		value := &ir.values[id-1]
		switch value.kind {
		case backendValuePhi:
			block := &ir.blocks[value.block]
			phi := block.phis[value.register]
			for inputIndex, input := range phi.inputs {
				if ir.blocks[block.predecessors[inputIndex]].reachable {
					markUsed(input)
				}
			}
		case backendValueOperation:
			operation := &ir.ops[value.pc]
			for _, use := range operation.uses {
				if operation.op == opCallLocalOne &&
					use.register == operation.b &&
					(backendGoNumericScalarReplacedCall(ir, options, operation) ||
						plan.closures.scalarValue(use.value)) {
					continue
				}
				markUsed(use.value)
			}
		}
	}
	for blockIndex := range ir.blocks {
		block := &ir.blocks[blockIndex]
		if !block.reachable {
			continue
		}
		for pc := block.first; pc < block.last; pc++ {
			operation := &ir.ops[pc]
			if backendGoNumericOperationDead(plan, operation) {
				continue
			}
			if err := verifyBackendGoNumericOperation(ir, plan, options, operation); err != nil {
				return backendGoNumericPlan{}, err
			}
		}
	}
	for valueIndex, used := range plan.used {
		if !used {
			continue
		}
		if plan.tags[valueIndex] != backendTagNil {
			if _, ok := backendGoNumericType(plan.tags[valueIndex]); ok {
				continue
			}
			return backendGoNumericPlan{}, fmt.Errorf("emit backend Go numeric proof: SSA value %d has nonnumeric union %x", valueIndex+1, plan.tags[valueIndex])
		}
	}
	return plan, nil
}

func backendGoNumericDirectTarget(options backendGoNumericOptions, operation *backendOperationIR) (backendGoNumericTarget, bool) {
	if operation == nil ||
		operation.call.kind != backendCallDirectProto ||
		operation.call.targetProto < 0 ||
		int(operation.call.targetProto) >= len(options.directTargets) {
		return backendGoNumericTarget{}, false
	}
	target := options.directTargets[operation.call.targetProto]
	return target, target.ir != nil && target.functionName != ""
}

func backendGoNumericScalarReplacedCall(
	ir *backendProtoIR,
	options backendGoNumericOptions,
	operation *backendOperationIR,
) bool {
	if ir == nil || operation == nil || operation.op != opCallLocalOne {
		return false
	}
	target, ok := backendGoNumericDirectTarget(options, operation)
	if !ok {
		return false
	}
	argumentCount, ok := backendGoNumericArgumentCount(target.ir, target.fixedVarargCount)
	if !ok || operation.callArgCount != int32(argumentCount) {
		return false
	}
	valueID := backendOperationUse(operation, operation.b)
	if !ir.validBackendValue(valueID) {
		return false
	}
	value := &ir.values[valueID-1]
	if value.object != backendObjectClosure ||
		value.escapes ||
		value.targetUnknown ||
		len(value.targetProtos) != 1 ||
		value.targetProtos[0] != operation.call.targetProto {
		return false
	}
	if target.selfRecursive {
		return backendGoNumericSelfClosure(ir, valueID, target.ir)
	}
	return len(target.ir.upvalues) == 0
}

func backendGoNumericPureProducer(op opcode) bool {
	switch op {
	case opLoadConst, opMove,
		opAdd, opSub, opMul, opDiv, opMod, opIDiv, opPow, opNeg,
		opAddK, opSubK, opMulK, opDivK, opModK, opIDivK,
		opClosure, opNewTable, opGetStringField, opGetUpvalue, opVararg:
		return true
	default:
		return false
	}
}

func backendGoNumericOperationDead(plan backendGoNumericPlan, operation *backendOperationIR) bool {
	if operation == nil || !backendGoNumericPureProducer(operation.op) {
		return false
	}
	for _, definition := range operation.defs {
		if plan.used[definition.value-1] {
			return false
		}
	}
	return true
}

func verifyBackendGoNumericOperation(
	ir *backendProtoIR,
	plan backendGoNumericPlan,
	options backendGoNumericOptions,
	operation *backendOperationIR,
) error {
	require := func(register int32, want backendTagMask) error {
		id := backendOperationUse(operation, register)
		if id == invalidBackendValueID {
			return fmt.Errorf("emit backend Go numeric proof: PC %d register %d has no SSA use", operation.pc, register)
		}
		if plan.tags[id-1] != want {
			return fmt.Errorf("emit backend Go numeric proof: PC %d register %d has tags %x, want %x", operation.pc, register, plan.tags[id-1], want)
		}
		return nil
	}
	switch operation.op {
	case opLoadConst:
		if operation.b < 0 || int(operation.b) >= len(ir.constants) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has invalid constant", operation.pc)
		}
		switch ir.constants[operation.b].kind {
		case NumberKind, BoolKind:
			return nil
		default:
			return fmt.Errorf("emit backend Go numeric proof: PC %d loads unsupported %s constant", operation.pc, ir.constants[operation.b].kind)
		}
	case opMove:
		return nil
	case opClosure:
		for _, definition := range operation.defs {
			if plan.used[definition.value-1] {
				return fmt.Errorf("emit backend Go numeric proof: PC %d closure escapes scalar replacement", operation.pc)
			}
		}
		return nil
	case opNewTable:
		for _, definition := range operation.defs {
			if plan.tables.root(definition.value) == invalidBackendValueID {
				return fmt.Errorf("emit backend Go numeric proof: PC %d table is not scalar replaceable", operation.pc)
			}
		}
		return nil
	case opSetStringField:
		_, field, ok := plan.tables.operationField(ir, operation)
		if !ok {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar field", operation.pc)
		}
		source := backendOperationUse(operation, operation.c)
		if field.child != invalidBackendValueID {
			if plan.tables.root(source) != field.child {
				return fmt.Errorf("emit backend Go numeric proof: PC %d changes scalar table identity", operation.pc)
			}
			return nil
		}
		return require(operation.c, field.tags)
	case opSetField:
		_, array, _, ok := plan.tables.arrayOperation(ir, operation)
		if !ok {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar array element", operation.pc)
		}
		return require(operation.c, array.tags)
	case opGetStringField:
		_, field, ok := plan.tables.operationField(ir, operation)
		if !ok {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar field", operation.pc)
		}
		if field.child != invalidBackendValueID {
			for _, definition := range operation.defs {
				if plan.tables.root(definition.value) != field.child {
					return fmt.Errorf("emit backend Go numeric proof: PC %d loses scalar table identity", operation.pc)
				}
			}
		}
		return nil
	case opPrepareIter:
		_, _, _, ok := plan.tables.arrayOperation(ir, operation)
		if !ok {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar array iterator", operation.pc)
		}
		for _, definition := range operation.defs {
			if definition.register == operation.a {
				if plan.tables.root(definition.value) == invalidBackendValueID {
					return fmt.Errorf("emit backend Go numeric proof: PC %d loses scalar array identity", operation.pc)
				}
				continue
			}
			if !plan.tables.iteratorValue(definition.value) {
				return fmt.Errorf("emit backend Go numeric proof: PC %d has materialized iterator state", operation.pc)
			}
		}
		return nil
	case opArrayNextJump2:
		_, array, _, ok := plan.tables.arrayOperation(ir, operation)
		if !ok {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar array iterator", operation.pc)
		}
		if !plan.tables.iteratorValue(backendOperationUse(operation, operation.c)) ||
			!plan.tables.iteratorValue(backendOperationUse(operation, operation.a)) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has materialized iterator control", operation.pc)
		}
		for _, definition := range operation.defs {
			switch definition.register {
			case operation.a:
				if !plan.tables.iteratorValue(definition.value) {
					return fmt.Errorf("emit backend Go numeric proof: PC %d materializes iterator key", operation.pc)
				}
			case operation.a + 1:
				if plan.tags[definition.value-1] != array.tags {
					return fmt.Errorf("emit backend Go numeric proof: PC %d changes scalar array element tags", operation.pc)
				}
			}
		}
		return nil
	case opFastCall:
		if backendGoNumericFixedVarargSelect(ir, options.fixedVarargCount, operation) {
			if len(operation.defs) != 1 ||
				operation.defs[0].register != operation.a ||
				plan.tags[operation.defs[0].value-1] != backendTagNumber {
				return fmt.Errorf("emit backend Go numeric proof: PC %d changes fixed select result", operation.pc)
			}
			return nil
		}
		_, array, _, ok := plan.tables.arrayOperation(ir, operation)
		if !ok {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar array intrinsic", operation.pc)
		}
		switch nativeFuncID(operation.nativeID) {
		case nativeFuncTableInsert:
			if operation.c != 2 || operation.d != 1 {
				return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported table.insert shape", operation.pc)
			}
			if err := require(operation.a+1, array.tags); err != nil {
				return err
			}
			for _, definition := range operation.defs {
				if plan.tags[definition.value-1] != backendTagNil {
					return fmt.Errorf("emit backend Go numeric proof: PC %d table.insert result is not nil", operation.pc)
				}
			}
			return nil
		case nativeFuncTableRemove:
			if operation.c != 2 || operation.d != 1 ||
				!backendGoStaticNumberEquals(ir, backendOperationUse(operation, operation.a+1), 1) {
				return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported table.remove shape", operation.pc)
			}
			for _, definition := range operation.defs {
				if plan.tags[definition.value-1] != array.tags {
					return fmt.Errorf("emit backend Go numeric proof: PC %d changes table.remove result tags", operation.pc)
				}
			}
			return nil
		case nativeFuncRawLen:
			if operation.c != 1 || operation.d != 1 {
				return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported rawlen shape", operation.pc)
			}
			for _, definition := range operation.defs {
				if plan.tags[definition.value-1] != backendTagNumber {
					return fmt.Errorf("emit backend Go numeric proof: PC %d changes rawlen result tags", operation.pc)
				}
			}
			return nil
		default:
			return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported scalar array intrinsic", operation.pc)
		}
	case opVararg:
		if operation.b < 0 || len(operation.defs) != int(operation.b) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported open vararg shape", operation.pc)
		}
		for _, definition := range operation.defs {
			if _, ok := backendGoNumericVarargIndex(
				ir,
				options.fixedVarargCount,
				operation,
				definition.register,
			); !ok || plan.tags[definition.value-1] != backendTagNumber {
				return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported fixed vararg result", operation.pc)
			}
		}
		return nil
	case opAdd, opSub, opMul, opDiv, opMod, opIDiv, opPow:
		if err := require(operation.b, backendTagNumber); err != nil {
			return err
		}
		return require(operation.c, backendTagNumber)
	case opAddK, opSubK, opMulK, opDivK, opModK, opIDivK:
		if err := require(operation.b, backendTagNumber); err != nil {
			return err
		}
		return verifyBackendGoNumericConstant(ir, operation, operation.c)
	case opNeg:
		return require(operation.b, backendTagNumber)
	case opEqual, opNotEqual:
		left := backendOperationUse(operation, operation.b)
		right := backendOperationUse(operation, operation.c)
		if left == invalidBackendValueID || right == invalidBackendValueID ||
			plan.tags[left-1] != plan.tags[right-1] ||
			(plan.tags[left-1] != backendTagNumber && plan.tags[left-1] != backendTagBool) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported equality operands", operation.pc)
		}
		return nil
	case opLess, opLessEqual, opGreater, opGreaterEqual:
		if err := require(operation.b, backendTagNumber); err != nil {
			return err
		}
		return require(operation.c, backendTagNumber)
	case opJumpIfNotLess, opJumpIfNotGreater, opJumpIfLess, opJumpIfGreater:
		if err := require(operation.a, backendTagNumber); err != nil {
			return err
		}
		return require(operation.b, backendTagNumber)
	case opNumericForCheck:
		if err := require(operation.a, backendTagNumber); err != nil {
			return err
		}
		if err := require(operation.b, backendTagNumber); err != nil {
			return err
		}
		return require(operation.c, backendTagNumber)
	case opNumericForLoop:
		if err := require(operation.a, backendTagNumber); err != nil {
			return err
		}
		return require(operation.b, backendTagNumber)
	case opGetUpvalue:
		if operation.b < 0 || int(operation.b) >= len(ir.upvalues) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d reads invalid upvalue %d", operation.pc, operation.b)
		}
		for _, definition := range operation.defs {
			if plan.tags[definition.value-1] != backendTagNumber {
				return fmt.Errorf("emit backend Go numeric proof: PC %d reads a nonnumeric upvalue", operation.pc)
			}
		}
		return nil
	case opSetUpvalue:
		if operation.a < 0 || int(operation.a) >= len(ir.upvalues) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d writes invalid upvalue %d", operation.pc, operation.a)
		}
		return require(operation.b, backendTagNumber)
	case opJumpIfNotEqualK, opJumpIfNotLessK, opJumpIfNotGreaterK, opJumpIfLessK, opJumpIfGreaterK:
		if err := require(operation.a, backendTagNumber); err != nil {
			return err
		}
		return verifyBackendGoNumericConstant(ir, operation, operation.b)
	case opJumpIfFalse:
		id := backendOperationUse(operation, operation.a)
		if id == invalidBackendValueID ||
			(plan.tags[id-1] != backendTagNumber && plan.tags[id-1] != backendTagBool) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported truthy operand", operation.pc)
		}
		return nil
	case opJump:
		return nil
	case opCallLocalOne:
		if factory, _, ok := plan.closures.factory(operation); ok {
			if factory.captureArgument < 0 ||
				factory.captureArgument >= operation.callArgCount {
				return fmt.Errorf("emit backend Go numeric proof: PC %d has invalid closure capture argument", operation.pc)
			}
			return require(operation.callArgStart+factory.captureArgument, backendTagNumber)
		}
		if call, ok := plan.closures.call(operation); ok {
			if len(call.target.ir.upvalues) != 1 ||
				call.target.ir.variadic ||
				operation.callArgCount != int32(call.target.ir.params) ||
				operation.callArgCount < 0 {
				return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported scalar closure call shape", operation.pc)
			}
			for register := operation.callArgStart; register < operation.callArgStart+operation.callArgCount; register++ {
				if err := require(register, backendTagNumber); err != nil {
					return err
				}
			}
			return nil
		}
		target, ok := backendGoNumericDirectTarget(options, operation)
		if !ok || !backendGoNumericScalarReplacedCall(ir, options, operation) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has no direct numeric target", operation.pc)
		}
		argumentCount, ok := backendGoNumericArgumentCount(target.ir, target.fixedVarargCount)
		if !ok ||
			!target.selfRecursive && len(target.ir.upvalues) != 0 ||
			operation.callArgCount != int32(argumentCount) ||
			operation.callArgCount < 0 {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported direct call shape", operation.pc)
		}
		for register := operation.callArgStart; register < operation.callArgStart+operation.callArgCount; register++ {
			if err := require(register, backendTagNumber); err != nil {
				return err
			}
		}
		return nil
	case opCallUpvalueOne:
		if !options.selfRecursive ||
			operation.b != 0 ||
			operation.callArgCount != int32(ir.params) ||
			operation.callArgCount != 1 {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported recursive call shape", operation.pc)
		}
		return require(operation.callArgStart, backendTagNumber)
	case opReturnOne:
		return require(operation.a, backendTagNumber)
	case opReturn:
		if operation.returnCount != 1 {
			return fmt.Errorf("emit backend Go numeric proof: PC %d returns %d values, want 1", operation.pc, operation.returnCount)
		}
		return require(operation.a, backendTagNumber)
	default:
		return fmt.Errorf("emit backend Go numeric proof: PC %d uses unsupported opcode %s", operation.pc, opcodeName(operation.op))
	}
}

func verifyBackendGoNumericConstant(ir *backendProtoIR, operation *backendOperationIR, index int32) error {
	if index < 0 || int(index) >= len(ir.constants) || ir.constants[index].kind != NumberKind {
		return fmt.Errorf("emit backend Go numeric proof: PC %d requires a numeric constant", operation.pc)
	}
	return nil
}

func backendGoNumericType(tags backendTagMask) (string, bool) {
	switch tags {
	case backendTagNumber:
		return "float64", true
	case backendTagBool:
		return "bool", true
	default:
		return "", false
	}
}

func (emitter *backendGoNumericEmitter) emitBody() error {
	for blockIndex := range emitter.ir.blocks {
		block := &emitter.ir.blocks[blockIndex]
		if !block.reachable {
			continue
		}
		if blockIndex != 0 {
			fmt.Fprintf(&emitter.body, "b%d:\n", blockIndex)
		}
		terminated := false
		for pc := block.first; pc < block.last; pc++ {
			operation := &emitter.ir.ops[pc]
			var err error
			terminated, err = emitter.emitOperation(operation, block)
			if err != nil {
				return err
			}
			if terminated {
				break
			}
		}
		if terminated {
			continue
		}
		if len(block.successors) != 1 {
			return fmt.Errorf("emit backend Go numeric proof: block %d has no terminator and %d successors", blockIndex, len(block.successors))
		}
		emitter.emitGoto(int32(blockIndex), block.successors[0], 1)
	}
	return nil
}

func (emitter *backendGoNumericEmitter) emitOperation(operation *backendOperationIR, block *backendBlockIR) (bool, error) {
	if backendGoNumericOperationDead(emitter.plan, operation) {
		return false, nil
	}
	definition := func(register int32) (backendValueID, error) {
		for _, candidate := range operation.defs {
			if candidate.register == register {
				return candidate.value, nil
			}
		}
		return invalidBackendValueID, fmt.Errorf("emit backend Go numeric proof: PC %d has no definition for register %d", operation.pc, register)
	}
	use := func(register int32) (backendValueID, error) {
		id := backendOperationUse(operation, register)
		if id == invalidBackendValueID {
			return id, fmt.Errorf("emit backend Go numeric proof: PC %d has no use for register %d", operation.pc, register)
		}
		return id, nil
	}
	switch operation.op {
	case opLoadConst:
		destination, err := definition(operation.a)
		if err != nil {
			return false, err
		}
		constant := emitter.ir.constants[operation.b]
		switch constant.kind {
		case NumberKind:
			emitter.needsMath = true
			fmt.Fprintf(&emitter.body, "\tv%d = math.Float64frombits(0x%016x)\n", destination, constant.bits)
		case BoolKind:
			fmt.Fprintf(&emitter.body, "\tv%d = %t\n", destination, constant.bits != 0)
		}
	case opMove:
		destination, err := definition(operation.a)
		if err != nil {
			return false, err
		}
		source, err := use(operation.b)
		if err != nil {
			return false, err
		}
		fmt.Fprintf(&emitter.body, "\tv%d = v%d\n", destination, source)
	case opNewTable:
		return false, nil
	case opSetStringField:
		fieldIndex, field, ok := emitter.plan.tables.operationField(emitter.ir, operation)
		if !ok {
			return false, fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar field", operation.pc)
		}
		if field.child != invalidBackendValueID {
			return false, nil
		}
		source, err := use(operation.c)
		if err != nil {
			return false, err
		}
		fmt.Fprintf(&emitter.body, "\tf%d = v%d\n", fieldIndex, source)
	case opSetField:
		arrayIndex, _, element, ok := emitter.plan.tables.arrayOperation(emitter.ir, operation)
		if !ok {
			return false, fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar array element", operation.pc)
		}
		source, err := use(operation.c)
		if err != nil {
			return false, err
		}
		fmt.Fprintf(&emitter.body, "\ta%d[%d] = v%d\n", arrayIndex, element-1, source)
	case opGetStringField:
		fieldIndex, field, ok := emitter.plan.tables.operationField(emitter.ir, operation)
		if !ok {
			return false, fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar field", operation.pc)
		}
		if field.child != invalidBackendValueID {
			return false, nil
		}
		destination, err := definition(operation.a)
		if err != nil {
			return false, err
		}
		fmt.Fprintf(&emitter.body, "\tv%d = f%d\n", destination, fieldIndex)
	case opPrepareIter:
		arrayIndex, _, _, ok := emitter.plan.tables.arrayOperation(emitter.ir, operation)
		if !ok {
			return false, fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar array iterator", operation.pc)
		}
		fmt.Fprintf(&emitter.body, "\ti%d = 0\n", arrayIndex)
	case opArrayNextJump2:
		arrayIndex, _, _, ok := emitter.plan.tables.arrayOperation(emitter.ir, operation)
		if !ok {
			return false, fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar array iterator", operation.pc)
		}
		value, err := definition(operation.a + 1)
		if err != nil {
			return false, err
		}
		target := emitter.ir.pcToBlock[operation.targetPC]
		fmt.Fprintf(&emitter.body, "\tif i%d >= len(a%d) {\n", arrayIndex, arrayIndex)
		emitter.emitGoto(int32(block.id), target, 2)
		emitter.body.WriteString("\t}\n")
		fmt.Fprintf(&emitter.body, "\tv%d = a%d[i%d]\n", value, arrayIndex, arrayIndex)
		fmt.Fprintf(&emitter.body, "\ti%d++\n", arrayIndex)
		nextBlock := int32(-1)
		if int(block.last) < len(emitter.ir.ops) {
			nextBlock = emitter.ir.pcToBlock[block.last]
		}
		emitter.emitGoto(int32(block.id), nextBlock, 1)
		return true, nil
	case opFastCall:
		if backendGoNumericFixedVarargSelect(emitter.ir, emitter.options.fixedVarargCount, operation) {
			destination, err := definition(operation.a)
			if err != nil {
				return false, err
			}
			fmt.Fprintf(&emitter.body, "\tv%d = %d\n", destination, emitter.options.fixedVarargCount)
			return false, nil
		}
		arrayIndex, _, _, ok := emitter.plan.tables.arrayOperation(emitter.ir, operation)
		if !ok {
			return false, fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar array intrinsic", operation.pc)
		}
		switch nativeFuncID(operation.nativeID) {
		case nativeFuncTableInsert:
			source, err := use(operation.a + 1)
			if err != nil {
				return false, err
			}
			fmt.Fprintf(&emitter.body, "\tif n%d >= len(a%d) {\n", arrayIndex, arrayIndex)
			emitter.emitReplayEntry(2)
			emitter.body.WriteString("\t}\n")
			fmt.Fprintf(&emitter.body, "\tt%d = h%d + n%d\n", arrayIndex, arrayIndex, arrayIndex)
			fmt.Fprintf(&emitter.body, "\tif t%d >= len(a%d) {\n", arrayIndex, arrayIndex)
			fmt.Fprintf(&emitter.body, "\t\tt%d -= len(a%d)\n", arrayIndex, arrayIndex)
			emitter.body.WriteString("\t}\n")
			fmt.Fprintf(&emitter.body, "\tif uint(t%d) >= uint(len(a%d)) {\n", arrayIndex, arrayIndex)
			emitter.emitReplayEntry(2)
			emitter.body.WriteString("\t}\n")
			fmt.Fprintf(&emitter.body, "\ta%d[t%d] = v%d\n", arrayIndex, arrayIndex, source)
			fmt.Fprintf(&emitter.body, "\tn%d++\n", arrayIndex)
		case nativeFuncTableRemove:
			destination, err := definition(operation.a)
			if err != nil {
				return false, err
			}
			position, err := use(operation.a + 1)
			if err != nil {
				return false, err
			}
			fmt.Fprintf(&emitter.body, "\t_ = v%d\n", position)
			fmt.Fprintf(&emitter.body, "\tif n%d == 0 {\n", arrayIndex)
			emitter.emitReplayEntry(2)
			emitter.body.WriteString("\t}\n")
			fmt.Fprintf(&emitter.body, "\tif uint(h%d) >= uint(len(a%d)) {\n", arrayIndex, arrayIndex)
			emitter.emitReplayEntry(2)
			emitter.body.WriteString("\t}\n")
			fmt.Fprintf(&emitter.body, "\tv%d = a%d[h%d]\n", destination, arrayIndex, arrayIndex)
			fmt.Fprintf(&emitter.body, "\th%d++\n", arrayIndex)
			fmt.Fprintf(&emitter.body, "\tif h%d == len(a%d) {\n", arrayIndex, arrayIndex)
			fmt.Fprintf(&emitter.body, "\t\th%d = 0\n", arrayIndex)
			emitter.body.WriteString("\t}\n")
			fmt.Fprintf(&emitter.body, "\tn%d--\n", arrayIndex)
		case nativeFuncRawLen:
			destination, err := definition(operation.a)
			if err != nil {
				return false, err
			}
			fmt.Fprintf(&emitter.body, "\tv%d = float64(n%d)\n", destination, arrayIndex)
		default:
			return false, fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported scalar array intrinsic", operation.pc)
		}
	case opVararg:
		for _, result := range operation.defs {
			parameter, ok := backendGoNumericVarargIndex(
				emitter.ir,
				emitter.options.fixedVarargCount,
				operation,
				result.register,
			)
			if !ok {
				return false, fmt.Errorf("emit backend Go numeric proof: PC %d has no fixed vararg parameter", operation.pc)
			}
			fmt.Fprintf(&emitter.body, "\tv%d = p%d\n", result.value, parameter)
		}
	case opAdd, opSub, opMul, opDiv, opMod, opIDiv, opPow:
		destination, _ := definition(operation.a)
		left, _ := use(operation.b)
		right, _ := use(operation.c)
		emitter.emitNumericBinary(destination, left, fmt.Sprintf("v%d", right), operation.op)
	case opAddK, opSubK, opMulK, opDivK, opModK, opIDivK:
		destination, _ := definition(operation.a)
		left, _ := use(operation.b)
		right := emitter.numericConstant(operation.c)
		emitter.emitNumericBinary(destination, left, right, operation.op)
	case opNeg:
		destination, _ := definition(operation.a)
		source, _ := use(operation.b)
		fmt.Fprintf(&emitter.body, "\tv%d = -v%d\n", destination, source)
	case opGetUpvalue:
		destination, err := definition(operation.a)
		if err != nil {
			return false, err
		}
		fmt.Fprintf(&emitter.body, "\tv%d = *u%d\n", destination, operation.b)
	case opSetUpvalue:
		source, err := use(operation.b)
		if err != nil {
			return false, err
		}
		fmt.Fprintf(&emitter.body, "\t*u%d = v%d\n", operation.a, source)
	case opEqual, opNotEqual, opLess, opLessEqual, opGreater, opGreaterEqual:
		destination, _ := definition(operation.a)
		left, _ := use(operation.b)
		right, _ := use(operation.c)
		if operation.op != opEqual && operation.op != opNotEqual {
			emitter.emitNaNGuard(operation, 1, left, right)
		}
		fmt.Fprintf(&emitter.body, "\tv%d = v%d %s v%d\n", destination, left, backendGoComparisonOperator(operation.op), right)
	case opNumericForCheck:
		loop, _ := use(operation.a)
		limit, _ := use(operation.b)
		step, _ := use(operation.c)
		emitter.emitNaNGuard(operation, 1, loop, limit, step)
		condition := fmt.Sprintf("(v%d > 0 && v%d > v%d) || (v%d <= 0 && v%d < v%d)", step, loop, limit, step, loop, limit)
		emitter.emitBranch(int32(block.id), operation.targetPC, condition, 1)
		return true, nil
	case opNumericForLoop:
		destination, _ := definition(operation.a)
		loop, _ := use(operation.a)
		step, _ := use(operation.b)
		fmt.Fprintf(&emitter.body, "\tv%d = v%d + v%d\n", destination, loop, step)
		emitter.emitGoto(int32(block.id), emitter.ir.pcToBlock[operation.targetPC], 1)
		return true, nil
	case opJumpIfNotEqualK:
		left, _ := use(operation.a)
		emitter.emitBranch(int32(block.id), operation.targetPC, fmt.Sprintf("v%d != %s", left, emitter.numericConstant(operation.b)), 1)
		return true, nil
	case opJumpIfNotLessK, opJumpIfNotGreaterK, opJumpIfLessK, opJumpIfGreaterK:
		left, _ := use(operation.a)
		emitter.emitNaNGuard(operation, 1, left)
		operator := backendGoComparisonOperator(operation.op)
		condition := fmt.Sprintf("v%d %s %s", left, operator, emitter.numericConstant(operation.b))
		if operation.op == opJumpIfNotLessK || operation.op == opJumpIfNotGreaterK {
			condition = "!(" + condition + ")"
		}
		emitter.emitBranch(int32(block.id), operation.targetPC, condition, 1)
		return true, nil
	case opJumpIfNotLess, opJumpIfNotGreater, opJumpIfLess, opJumpIfGreater:
		left, _ := use(operation.a)
		right, _ := use(operation.b)
		emitter.emitNaNGuard(operation, 1, left, right)
		condition := fmt.Sprintf("v%d %s v%d", left, backendGoComparisonOperator(operation.op), right)
		if operation.op == opJumpIfNotLess || operation.op == opJumpIfNotGreater {
			condition = "!(" + condition + ")"
		}
		emitter.emitBranch(int32(block.id), operation.targetPC, condition, 1)
		return true, nil
	case opJumpIfFalse:
		condition, _ := use(operation.a)
		expression := "false"
		if emitter.plan.tags[condition-1] == backendTagBool {
			expression = fmt.Sprintf("!v%d", condition)
		}
		emitter.emitBranch(int32(block.id), operation.targetPC, expression, 1)
		return true, nil
	case opJump:
		emitter.emitGoto(int32(block.id), emitter.ir.pcToBlock[operation.targetPC], 1)
		return true, nil
	case opCallUpvalueOne:
		if !emitter.options.selfRecursive || operation.b != 0 {
			return false, fmt.Errorf("emit backend Go numeric proof: PC %d has no recursive self target", operation.pc)
		}
		destination, err := definition(operation.a)
		if err != nil {
			return false, err
		}
		fmt.Fprintf(&emitter.body, "\tv%d = %sBody(", destination, emitter.options.functionName)
		for argument := int32(0); argument < operation.callArgCount; argument++ {
			if argument != 0 {
				emitter.body.WriteString(", ")
			}
			value, err := use(operation.callArgStart + argument)
			if err != nil {
				return false, err
			}
			fmt.Fprintf(&emitter.body, "v%d", value)
		}
		emitter.body.WriteString(")\n")
	case opCallLocalOne:
		if factory, cell, ok := emitter.plan.closures.factory(operation); ok {
			source, err := use(operation.callArgStart + factory.captureArgument)
			if err != nil {
				return false, err
			}
			fmt.Fprintf(&emitter.body, "\tc%d = v%d\n", cell, source)
			return false, nil
		}
		if call, ok := emitter.plan.closures.call(operation); ok {
			destination, err := definition(operation.a)
			if err != nil {
				return false, err
			}
			fmt.Fprintf(&emitter.body, "\ts%d = c%d\n", call.cell, call.cell)
			fmt.Fprintf(&emitter.body, "\tv%d, ok%d = %s(&s%d", destination, operation.pc, call.target.functionName, call.cell)
			for argument := int32(0); argument < operation.callArgCount; argument++ {
				value, err := use(operation.callArgStart + argument)
				if err != nil {
					return false, err
				}
				fmt.Fprintf(&emitter.body, ", v%d", value)
			}
			emitter.body.WriteString(")\n")
			fmt.Fprintf(&emitter.body, "\tif !ok%d {\n", operation.pc)
			emitter.emitReplayEntry(2)
			emitter.body.WriteString("\t}\n")
			fmt.Fprintf(&emitter.body, "\tc%d = s%d\n", call.cell, call.cell)
			return false, nil
		}
		target, ok := backendGoNumericDirectTarget(emitter.options, operation)
		if !ok || !backendGoNumericScalarReplacedCall(emitter.ir, emitter.options, operation) {
			return false, fmt.Errorf("emit backend Go numeric proof: PC %d has no scalar-replaced direct target", operation.pc)
		}
		destination, err := definition(operation.a)
		if err != nil {
			return false, err
		}
		fmt.Fprintf(&emitter.body, "\tv%d, ok%d = %s(", destination, operation.pc, target.functionName)
		for argument := int32(0); argument < operation.callArgCount; argument++ {
			if argument != 0 {
				emitter.body.WriteString(", ")
			}
			value, err := use(operation.callArgStart + argument)
			if err != nil {
				return false, err
			}
			fmt.Fprintf(&emitter.body, "v%d", value)
		}
		emitter.body.WriteString(")\n")
		fmt.Fprintf(&emitter.body, "\tif !ok%d {\n", operation.pc)
		if emitter.prepared {
			emitter.body.WriteString("\t\treturn machinePreparedReplayEntry()\n")
		} else {
			emitter.body.WriteString("\t\treturn 0, false\n")
		}
		emitter.body.WriteString("\t}\n")
	case opReturnOne, opReturn:
		result, _ := use(operation.a)
		if emitter.options.selfRecursive {
			fmt.Fprintf(&emitter.body, "\treturn v%d\n", result)
		} else if emitter.prepared {
			fmt.Fprintf(&emitter.body, "\treturn machinePreparedReturnOneNumber(v%d)\n", result)
		} else {
			fmt.Fprintf(&emitter.body, "\treturn v%d, true\n", result)
		}
		return true, nil
	default:
		return false, fmt.Errorf("emit backend Go numeric proof: PC %d uses unsupported opcode %s", operation.pc, opcodeName(operation.op))
	}
	return false, nil
}

func (emitter *backendGoNumericEmitter) emitNumericBinary(destination, left backendValueID, right string, op opcode) {
	switch op {
	case opAdd, opAddK:
		fmt.Fprintf(&emitter.body, "\tv%d = v%d + %s\n", destination, left, right)
	case opSub, opSubK:
		fmt.Fprintf(&emitter.body, "\tv%d = v%d - %s\n", destination, left, right)
	case opMul, opMulK:
		fmt.Fprintf(&emitter.body, "\tv%d = v%d * %s\n", destination, left, right)
	case opDiv, opDivK:
		fmt.Fprintf(&emitter.body, "\tv%d = v%d / %s\n", destination, left, right)
	case opMod, opModK:
		emitter.needsMath = true
		fmt.Fprintf(&emitter.body, "\tv%d = v%d - math.Floor(v%d/%s)*%s\n", destination, left, left, right, right)
	case opIDiv, opIDivK:
		emitter.needsMath = true
		fmt.Fprintf(&emitter.body, "\tv%d = math.Floor(v%d / %s)\n", destination, left, right)
	case opPow:
		emitter.needsMath = true
		fmt.Fprintf(&emitter.body, "\tv%d = math.Pow(v%d, %s)\n", destination, left, right)
	}
}

func (emitter *backendGoNumericEmitter) numericConstant(index int32) string {
	emitter.needsMath = true
	return fmt.Sprintf("math.Float64frombits(0x%016x)", emitter.ir.constants[index].bits)
}

func (emitter *backendGoNumericEmitter) emitNaNGuard(operation *backendOperationIR, indent int, values ...backendValueID) {
	emitter.needsMath = true
	if emitter.options.selfRecursive {
		return
	}
	prefix := strings.Repeat("\t", indent)
	for _, value := range values {
		fmt.Fprintf(&emitter.body, "%sif math.IsNaN(v%d) {\n", prefix, value)
		if emitter.prepared {
			emitter.emitReplayBeforeOperation(operation, indent+1)
		} else {
			fmt.Fprintf(&emitter.body, "%s\treturn 0, false\n", prefix)
		}
		fmt.Fprintf(&emitter.body, "%s}\n", prefix)
	}
}

func (emitter *backendGoNumericEmitter) emitReplayBeforeOperation(operation *backendOperationIR, indent int) {
	prefix := strings.Repeat("\t", indent)
	if emitter.plan.replayEntry[operation.pc] {
		fmt.Fprintf(&emitter.body, "%sreturn machinePreparedReplayEntry()\n", prefix)
		return
	}
	fmt.Fprintf(&emitter.body, "%sexit := context.replayBeforeOperation(%d, %d)\n", prefix, operation.pc, len(operation.spillValues))
	for spillIndex, spill := range operation.spillValues {
		switch emitter.plan.tags[spill.value-1] {
		case backendTagNil:
			fmt.Fprintf(&emitter.body, "%scontext.spillNil(%d, %d)\n", prefix, spillIndex, spill.register)
		case backendTagBool:
			fmt.Fprintf(&emitter.body, "%scontext.spillBool(%d, %d, v%d)\n", prefix, spillIndex, spill.register, spill.value)
		case backendTagNumber:
			fmt.Fprintf(&emitter.body, "%scontext.spillNumber(%d, %d, v%d)\n", prefix, spillIndex, spill.register, spill.value)
		default:
			fmt.Fprintf(&emitter.body, "%sreturn machinePreparedExit{}\n", prefix)
			return
		}
	}
	fmt.Fprintf(&emitter.body, "%sreturn exit\n", prefix)
}

func (emitter *backendGoNumericEmitter) emitReplayEntry(indent int) {
	prefix := strings.Repeat("\t", indent)
	if emitter.prepared {
		fmt.Fprintf(&emitter.body, "%sreturn machinePreparedReplayEntry()\n", prefix)
		return
	}
	fmt.Fprintf(&emitter.body, "%sreturn 0, false\n", prefix)
}

func (emitter *backendGoNumericEmitter) emitBranch(from int32, targetPC int32, condition string, indent int) {
	target := emitter.ir.pcToBlock[targetPC]
	nextBlock := int32(-1)
	block := &emitter.ir.blocks[from]
	if int(block.last) < len(emitter.ir.ops) {
		nextBlock = emitter.ir.pcToBlock[block.last]
	}
	prefix := strings.Repeat("\t", indent)
	fmt.Fprintf(&emitter.body, "%sif %s {\n", prefix, condition)
	emitter.emitGoto(from, target, indent+1)
	fmt.Fprintf(&emitter.body, "%s}\n", prefix)
	emitter.emitGoto(from, nextBlock, indent)
}

func (emitter *backendGoNumericEmitter) emitGoto(from, to int32, indent int) {
	prefix := strings.Repeat("\t", indent)
	for edgeIndex := range emitter.ir.edges {
		edge := &emitter.ir.edges[edgeIndex]
		if edge.from != from || edge.to != to {
			continue
		}
		for _, copy := range edge.phiCopies {
			if !emitter.plan.used[copy.destination-1] {
				continue
			}
			fmt.Fprintf(&emitter.body, "%sv%d = v%d\n", prefix, copy.destination, copy.source)
		}
		fmt.Fprintf(&emitter.body, "%sgoto b%d\n", prefix, to)
		return
	}
	if emitter.prepared {
		fmt.Fprintf(&emitter.body, "%sreturn machinePreparedExit{}\n", prefix)
	} else {
		fmt.Fprintf(&emitter.body, "%sreturn 0, false\n", prefix)
	}
}

func backendGoComparisonOperator(op opcode) string {
	switch op {
	case opEqual:
		return "=="
	case opNotEqual, opJumpIfNotEqualK:
		return "!="
	case opLess, opJumpIfLess, opJumpIfNotLess, opJumpIfLessK, opJumpIfNotLessK:
		return "<"
	case opLessEqual:
		return "<="
	case opGreater, opJumpIfGreater, opJumpIfNotGreater, opJumpIfGreaterK, opJumpIfNotGreaterK:
		return ">"
	case opGreaterEqual:
		return ">="
	default:
		return "=="
	}
}
