// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedNumericCallAdd(p0 float64) (float64, bool) {
	var v1 float64
	var v4 float64
	var v5 float64
	var v6 float64
	var v7 float64
	v1 = p0
	if math.IsNaN(v1) {
		return 0, false
	}
	if !(v1 < math.Float64frombits(0x426d1a94a2000000)) {
		goto b2
	}
	goto b1
b1:
	v4 = v1
	v5 = v4 + math.Float64frombits(0x3ff0000000000000)
	return v5, true
b2:
	v6 = v1
	v7 = v6 + math.Float64frombits(0x3ff0000000000000)
	return v7, true
}
