// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedDirtyMetatableNewIndex(r0 *float64, r1 *float64, r2 *float64, r3 *float64, r4 *float64, r5 *float64, r6 *float64, r7 *float64, r8 *float64, r9 *float64, p1 uint32, p2 float64) bool {
	if r0 == nil {
		return false
	}
	if r1 == nil {
		return false
	}
	if r2 == nil {
		return false
	}
	if r3 == nil {
		return false
	}
	if r4 == nil {
		return false
	}
	if r5 == nil {
		return false
	}
	if r6 == nil {
		return false
	}
	if r7 == nil {
		return false
	}
	if r8 == nil {
		return false
	}
	if r9 == nil {
		return false
	}
	var v2 uint32
	var v3 float64
	var v12 uint32
	var v13 float64
	var v14 float64
	var v22 uint32
	var v23 float64
	var vp23 bool
	_ = v23
	_ = vp23
	var v24 float64
	var v25 float64
	var v27 uint32
	var v28 float64
	var v30 uint32
	v2 = p1
	v3 = p2
	v22 = v2
	vp23 = false
	switch v22 {
	case uint32(1):
		v23 = *r0
		vp23 = true
	case uint32(2):
		v23 = *r1
		vp23 = true
	case uint32(3):
		v23 = *r2
		vp23 = true
	case uint32(4):
		v23 = *r3
		vp23 = true
	case uint32(5):
		v23 = *r4
		vp23 = true
	}
	if !vp23 {
		goto b2
	}
	goto b1
b1:
	v12 = v2
	v13 = v3
	v14 = v23
	goto b3
b2:
	v24 = math.Float64frombits(0x0000000000000000)
	v12 = v2
	v13 = v3
	v14 = v24
	goto b3
b3:
	v25 = v14 + math.Float64frombits(0x3ff0000000000000)
	v27 = v12
	switch v27 {
	case uint32(1):
		*r0 = v25
	case uint32(2):
		*r1 = v25
	case uint32(3):
		*r2 = v25
	case uint32(4):
		*r3 = v25
	case uint32(5):
		*r4 = v25
	default:
		return false
	}
	v28 = v13
	v30 = v12
	switch v30 {
	case uint32(1):
		*r5 = v28
	case uint32(2):
		*r6 = v28
	case uint32(3):
		*r7 = v28
	case uint32(4):
		*r8 = v28
	case uint32(5):
		*r9 = v28
	default:
		return false
	}
	return true
}
