// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedStructuralStringKey(p0 float64, p1 float64) (backendPreparedStringKey, bool) {
	var v1 float64
	var v2 float64
	var v8 float64
	var v12 float64
	var v15 backendPreparedStringKey
	v1 = p0
	v2 = p1
	v8 = v1
	v12 = v2
	if math.IsNaN(v8) || math.IsInf(v8, 0) || v8 != math.Trunc(v8) || v8 < -2147483648 || v8 > 2147483647 || v8 == 0 && math.Signbit(v8) {
		return backendPreparedStringKey{}, false
	}
	if math.IsNaN(v12) || math.IsInf(v12, 0) || v12 != math.Trunc(v12) || v12 < -2147483648 || v12 > 2147483647 || v12 == 0 && math.Signbit(v12) {
		return backendPreparedStringKey{}, false
	}
	v15 = backendPreparedStringKey{first: int32(v8), second: int32(v12)}
	return v15, true
}
