package ember

import (
	"bytes"
	"context"
	"os"
	"testing"

	"github.com/besmpl/ember/internal/preparedworkerfixture"
)

const preparedWorkerFixtureUpdateEnvironment = "EMBER_UPDATE_PREPARED_WORKER_FIXTURE"

func TestPreparedWorkerFixtureIsFresh(t *testing.T) {
	loader := machineRuntimeTestLoader{
		preparedworkerfixture.MainModule:    preparedworkerfixture.MainSource,
		preparedworkerfixture.NumericModule: preparedworkerfixture.NumericSource,
		preparedworkerfixture.SharedModule:  preparedworkerfixture.SharedSource,
	}
	program, _, err := LoadProgram(context.Background(), loader, ProgramOptions{
		Entrypoints: []Entrypoint{{
			Name:   "main",
			Module: LogicalModule("prepared-worker/main"),
		}},
		Parallelism: 1,
	})
	if err != nil {
		t.Fatal(err)
	}
	var generated bytes.Buffer
	if err := program.WritePreparedGo(&generated, PreparedGoOptions{
		Package: "preparedworkerfixturegenerated",
	}); err != nil {
		t.Fatal(err)
	}
	const path = "internal/preparedworkerfixture/generated/prepared_generated.go"
	if os.Getenv(preparedWorkerFixtureUpdateEnvironment) == "1" {
		if err := os.WriteFile(path, generated.Bytes(), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	onDisk, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(onDisk, generated.Bytes()) {
		t.Fatalf(
			"prepared worker fixture is stale; rerun with %s=1",
			preparedWorkerFixtureUpdateEnvironment,
		)
	}
	if !bytes.Contains(generated.Bytes(), []byte("{nil, emberPreparedM1PreparedProto1}")) {
		t.Fatal("prepared worker fixture does not bind its numeric workload to generated AOT code")
	}
}
