// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedCapturedEntry(u0 *float64, p0 float64, p1 float64) (float64, bool) {
	if u0 == nil {
		return 0, false
	}
	var v1 float64
	var v2 float64
	var v11 float64
	var v12 float64
	var v13 float64
	var v14 float64
	var v15 float64
	var v19 float64
	var v20 float64
	var v21 float64
	var v22 float64
	var v23 float64
	var v24 float64
	var v25 float64
	var v26 float64
	var v27 float64
	var v28 float64
	var v29 float64
	var v30 float64
	var v31 float64
	var v32 float64
	var v33 float64
	var v34 float64
	var ok9 bool
	v1 = p0
	v2 = p1
	v19 = math.Float64frombits(0x0000000000000000)
	v20 = v1
	v21 = math.Float64frombits(0x3ff0000000000000)
	v22 = v20 + math.Float64frombits(0x0000000000000000)
	v23 = math.Float64frombits(0x3ff0000000000000)
	v11 = v2
	v12 = v19
	v13 = v21
	v14 = v22
	v15 = v23
	goto b1
b1:
	if math.IsNaN(v13) {
		return 0, false
	}
	if math.IsNaN(v14) {
		return 0, false
	}
	if math.IsNaN(v15) {
		return 0, false
	}
	if (v15 > 0 && v13 > v14) || (v15 <= 0 && v13 < v14) {
		goto b3
	}
	goto b2
b2:
	v24 = v11
	v25 = v13
	v26 = v24 + v25
	v27, ok9 = backendGeneratedCapturedTargetProto1(v26)
	if !ok9 {
		return 0, false
	}
	v28 = v27
	v29 = v13
	v30 = v29 - math.Floor(v29/math.Float64frombits(0x401c000000000000))*math.Float64frombits(0x401c000000000000)
	v31 = v30 + math.Float64frombits(0x3ff0000000000000)
	v32 = v28 * v31
	v33 = v12 + v32
	v34 = v13 + v15
	v12 = v33
	v13 = v34
	goto b1
b3:
	return v12, true
}

func backendGeneratedCapturedPreparedBody(context machinePreparedContext, p0 float64, p1 float64) machinePreparedExit {
	var v1 float64
	var v2 float64
	var v11 float64
	var v12 float64
	var v13 float64
	var v14 float64
	var v15 float64
	var v19 float64
	var v20 float64
	var v21 float64
	var v22 float64
	var v23 float64
	var v24 float64
	var v25 float64
	var v26 float64
	var v27 float64
	var v28 float64
	var v29 float64
	var v30 float64
	var v31 float64
	var v32 float64
	var v33 float64
	var v34 float64
	var ok9 bool
	v1 = p0
	v2 = p1
	v19 = math.Float64frombits(0x0000000000000000)
	v20 = v1
	v21 = math.Float64frombits(0x3ff0000000000000)
	v22 = v20 + math.Float64frombits(0x0000000000000000)
	v23 = math.Float64frombits(0x3ff0000000000000)
	v11 = v2
	v12 = v19
	v13 = v21
	v14 = v22
	v15 = v23
	goto b1
b1:
	if math.IsNaN(v13) {
		exit := context.replayBeforeOperation(5, 5)
		context.spillNumber(0, 1, v11)
		context.spillNumber(1, 2, v12)
		context.spillNumber(2, 3, v13)
		context.spillNumber(3, 4, v14)
		context.spillNumber(4, 5, v15)
		return exit
	}
	if math.IsNaN(v14) {
		exit := context.replayBeforeOperation(5, 5)
		context.spillNumber(0, 1, v11)
		context.spillNumber(1, 2, v12)
		context.spillNumber(2, 3, v13)
		context.spillNumber(3, 4, v14)
		context.spillNumber(4, 5, v15)
		return exit
	}
	if math.IsNaN(v15) {
		exit := context.replayBeforeOperation(5, 5)
		context.spillNumber(0, 1, v11)
		context.spillNumber(1, 2, v12)
		context.spillNumber(2, 3, v13)
		context.spillNumber(3, 4, v14)
		context.spillNumber(4, 5, v15)
		return exit
	}
	if (v15 > 0 && v13 > v14) || (v15 <= 0 && v13 < v14) {
		goto b3
	}
	goto b2
b2:
	v24 = v11
	v25 = v13
	v26 = v24 + v25
	v27, ok9 = backendGeneratedCapturedTargetProto1(v26)
	if !ok9 {
		return machinePreparedReplayEntry()
	}
	v28 = v27
	v29 = v13
	v30 = v29 - math.Floor(v29/math.Float64frombits(0x401c000000000000))*math.Float64frombits(0x401c000000000000)
	v31 = v30 + math.Float64frombits(0x3ff0000000000000)
	v32 = v28 * v31
	v33 = v12 + v32
	v34 = v13 + v15
	v12 = v33
	v13 = v34
	goto b1
b3:
	return machinePreparedReturnOneNumber(v12)
}

func backendGeneratedCapturedPrepared(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	p1, ok := context.numberParameter(1)
	if !ok {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedCapturedPreparedBody(context, p0, p1)
}
