package ember

import (
	"fmt"
	"go/format"
	"go/token"
	"strings"
)

type backendGoNumericOptions struct {
	packageName  string
	functionName string
}

type backendGoNumericPlan struct {
	tags []backendTagMask
	used []bool
}

type backendGoNumericEmitter struct {
	ir        *backendProtoIR
	plan      backendGoNumericPlan
	body      strings.Builder
	needsMath bool
}

func emitBackendGoNumericProof(ir *backendProtoIR, options backendGoNumericOptions) ([]byte, error) {
	if err := verifyBackendProtoIR(ir); err != nil {
		return nil, fmt.Errorf("emit backend Go numeric proof: %w", err)
	}
	if !token.IsIdentifier(options.packageName) || token.Lookup(options.packageName).IsKeyword() {
		return nil, fmt.Errorf("emit backend Go numeric proof: invalid package name %q", options.packageName)
	}
	if !token.IsIdentifier(options.functionName) || token.Lookup(options.functionName).IsKeyword() {
		return nil, fmt.Errorf("emit backend Go numeric proof: invalid function name %q", options.functionName)
	}
	plan, err := buildBackendGoNumericPlan(ir)
	if err != nil {
		return nil, err
	}
	emitter := backendGoNumericEmitter{ir: ir, plan: plan}
	if err := emitter.emitBody(); err != nil {
		return nil, err
	}

	var source strings.Builder
	source.WriteString("// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.\n\n")
	fmt.Fprintf(&source, "package %s\n\n", options.packageName)
	if emitter.needsMath {
		source.WriteString("import \"math\"\n\n")
	}
	fmt.Fprintf(&source, "func %s(", options.functionName)
	for parameter := 0; parameter < ir.params; parameter++ {
		if parameter != 0 {
			source.WriteString(", ")
		}
		fmt.Fprintf(&source, "p%d float64", parameter)
	}
	source.WriteString(") (float64, bool) {\n")
	for valueIndex := range ir.values {
		if !plan.used[valueIndex] {
			continue
		}
		goType, ok := backendGoNumericType(plan.tags[valueIndex])
		if !ok {
			return nil, fmt.Errorf("emit backend Go numeric proof: SSA value %d has unsupported tags %x", valueIndex+1, plan.tags[valueIndex])
		}
		fmt.Fprintf(&source, "\tvar v%d %s\n", valueIndex+1, goType)
	}
	for parameter := 0; parameter < ir.params; parameter++ {
		id := ir.initial[parameter]
		if plan.used[id-1] {
			fmt.Fprintf(&source, "\tv%d = p%d\n", id, parameter)
		}
	}
	source.WriteString(emitter.body.String())
	source.WriteString("}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("emit backend Go numeric proof: format generated source: %w", err)
	}
	return formatted, nil
}

func buildBackendGoNumericPlan(ir *backendProtoIR) (backendGoNumericPlan, error) {
	plan := backendGoNumericPlan{
		tags: make([]backendTagMask, len(ir.values)),
		used: make([]bool, len(ir.values)),
	}
	for register, id := range ir.initial {
		if register < ir.params {
			plan.tags[id-1] = backendTagNumber
		} else {
			plan.tags[id-1] = backendTagNil
		}
	}
	for {
		changed := false
		for valueIndex := range ir.values {
			value := &ir.values[valueIndex]
			var tags backendTagMask
			switch value.kind {
			case backendValueUndef, backendValueParameter:
				continue
			case backendValuePhi:
				block := &ir.blocks[value.block]
				phi := block.phis[value.register]
				for inputIndex, input := range phi.inputs {
					if !ir.blocks[block.predecessors[inputIndex]].reachable {
						continue
					}
					tags |= plan.tags[input-1]
				}
			case backendValueOperation:
				operation := &ir.ops[value.pc]
				if !ir.blocks[operation.block].reachable {
					continue
				}
				switch operation.op {
				case opLoadConst:
					if operation.b >= 0 && int(operation.b) < len(ir.constants) {
						tags = backendTagForValueKind(ir.constants[operation.b].kind)
					}
				case opMove:
					source := backendOperationUse(operation, operation.b)
					if source != invalidBackendValueID {
						tags = plan.tags[source-1]
					}
				case opAdd, opSub, opMul, opDiv, opMod, opIDiv, opPow, opNeg,
					opAddK, opSubK, opMulK, opDivK, opModK, opIDivK,
					opNumericForLoop:
					tags = backendTagNumber
				case opEqual, opNotEqual, opLess, opLessEqual, opGreater, opGreaterEqual:
					tags = backendTagBool
				default:
					return backendGoNumericPlan{}, fmt.Errorf("emit backend Go numeric proof: PC %d writes through unsupported opcode %s", value.pc, opcodeName(operation.op))
				}
			}
			next := plan.tags[valueIndex] | tags
			if next != plan.tags[valueIndex] {
				plan.tags[valueIndex] = next
				changed = true
			}
		}
		if !changed {
			break
		}
	}
	work := make([]backendValueID, 0, len(ir.values))
	markUsed := func(id backendValueID) {
		if id == invalidBackendValueID || plan.used[id-1] {
			return
		}
		plan.used[id-1] = true
		work = append(work, id)
	}
	for blockIndex := range ir.blocks {
		block := &ir.blocks[blockIndex]
		if !block.reachable {
			continue
		}
		for pc := block.first; pc < block.last; pc++ {
			operation := &ir.ops[pc]
			if backendGoNumericPureProducer(operation.op) {
				continue
			}
			for _, use := range operation.uses {
				markUsed(use.value)
			}
			for _, definition := range operation.defs {
				markUsed(definition.value)
			}
		}
	}
	for len(work) != 0 {
		id := work[len(work)-1]
		work = work[:len(work)-1]
		value := &ir.values[id-1]
		switch value.kind {
		case backendValuePhi:
			block := &ir.blocks[value.block]
			phi := block.phis[value.register]
			for inputIndex, input := range phi.inputs {
				if ir.blocks[block.predecessors[inputIndex]].reachable {
					markUsed(input)
				}
			}
		case backendValueOperation:
			for _, use := range ir.ops[value.pc].uses {
				markUsed(use.value)
			}
		}
	}
	for blockIndex := range ir.blocks {
		block := &ir.blocks[blockIndex]
		if !block.reachable {
			continue
		}
		for pc := block.first; pc < block.last; pc++ {
			operation := &ir.ops[pc]
			if backendGoNumericOperationDead(plan, operation) {
				continue
			}
			if err := verifyBackendGoNumericOperation(ir, plan, operation); err != nil {
				return backendGoNumericPlan{}, err
			}
		}
	}
	for valueIndex, used := range plan.used {
		if !used {
			continue
		}
		if _, ok := backendGoNumericType(plan.tags[valueIndex]); !ok {
			return backendGoNumericPlan{}, fmt.Errorf("emit backend Go numeric proof: SSA value %d has nonnumeric union %x", valueIndex+1, plan.tags[valueIndex])
		}
	}
	return plan, nil
}

func backendGoNumericPureProducer(op opcode) bool {
	switch op {
	case opLoadConst, opMove,
		opAdd, opSub, opMul, opDiv, opMod, opIDiv, opPow, opNeg,
		opAddK, opSubK, opMulK, opDivK, opModK, opIDivK:
		return true
	default:
		return false
	}
}

func backendGoNumericOperationDead(plan backendGoNumericPlan, operation *backendOperationIR) bool {
	if operation == nil || !backendGoNumericPureProducer(operation.op) {
		return false
	}
	for _, definition := range operation.defs {
		if plan.used[definition.value-1] {
			return false
		}
	}
	return true
}

func verifyBackendGoNumericOperation(ir *backendProtoIR, plan backendGoNumericPlan, operation *backendOperationIR) error {
	require := func(register int32, want backendTagMask) error {
		id := backendOperationUse(operation, register)
		if id == invalidBackendValueID {
			return fmt.Errorf("emit backend Go numeric proof: PC %d register %d has no SSA use", operation.pc, register)
		}
		if plan.tags[id-1] != want {
			return fmt.Errorf("emit backend Go numeric proof: PC %d register %d has tags %x, want %x", operation.pc, register, plan.tags[id-1], want)
		}
		return nil
	}
	switch operation.op {
	case opLoadConst:
		if operation.b < 0 || int(operation.b) >= len(ir.constants) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has invalid constant", operation.pc)
		}
		switch ir.constants[operation.b].kind {
		case NumberKind, BoolKind:
			return nil
		default:
			return fmt.Errorf("emit backend Go numeric proof: PC %d loads unsupported %s constant", operation.pc, ir.constants[operation.b].kind)
		}
	case opMove:
		return nil
	case opAdd, opSub, opMul, opDiv, opMod, opIDiv, opPow:
		if err := require(operation.b, backendTagNumber); err != nil {
			return err
		}
		return require(operation.c, backendTagNumber)
	case opAddK, opSubK, opMulK, opDivK, opModK, opIDivK:
		if err := require(operation.b, backendTagNumber); err != nil {
			return err
		}
		return verifyBackendGoNumericConstant(ir, operation, operation.c)
	case opNeg:
		return require(operation.b, backendTagNumber)
	case opEqual, opNotEqual:
		left := backendOperationUse(operation, operation.b)
		right := backendOperationUse(operation, operation.c)
		if left == invalidBackendValueID || right == invalidBackendValueID ||
			plan.tags[left-1] != plan.tags[right-1] ||
			(plan.tags[left-1] != backendTagNumber && plan.tags[left-1] != backendTagBool) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported equality operands", operation.pc)
		}
		return nil
	case opLess, opLessEqual, opGreater, opGreaterEqual:
		if err := require(operation.b, backendTagNumber); err != nil {
			return err
		}
		return require(operation.c, backendTagNumber)
	case opJumpIfNotLess, opJumpIfNotGreater, opJumpIfLess, opJumpIfGreater:
		if err := require(operation.a, backendTagNumber); err != nil {
			return err
		}
		return require(operation.b, backendTagNumber)
	case opNumericForCheck:
		if err := require(operation.a, backendTagNumber); err != nil {
			return err
		}
		if err := require(operation.b, backendTagNumber); err != nil {
			return err
		}
		return require(operation.c, backendTagNumber)
	case opNumericForLoop:
		if err := require(operation.a, backendTagNumber); err != nil {
			return err
		}
		return require(operation.b, backendTagNumber)
	case opJumpIfNotEqualK, opJumpIfNotLessK, opJumpIfNotGreaterK, opJumpIfLessK, opJumpIfGreaterK:
		if err := require(operation.a, backendTagNumber); err != nil {
			return err
		}
		return verifyBackendGoNumericConstant(ir, operation, operation.b)
	case opJumpIfFalse:
		id := backendOperationUse(operation, operation.a)
		if id == invalidBackendValueID ||
			(plan.tags[id-1] != backendTagNumber && plan.tags[id-1] != backendTagBool) {
			return fmt.Errorf("emit backend Go numeric proof: PC %d has unsupported truthy operand", operation.pc)
		}
		return nil
	case opJump:
		return nil
	case opReturnOne:
		return require(operation.a, backendTagNumber)
	case opReturn:
		if operation.returnCount != 1 {
			return fmt.Errorf("emit backend Go numeric proof: PC %d returns %d values, want 1", operation.pc, operation.returnCount)
		}
		return require(operation.a, backendTagNumber)
	default:
		return fmt.Errorf("emit backend Go numeric proof: PC %d uses unsupported opcode %s", operation.pc, opcodeName(operation.op))
	}
}

func verifyBackendGoNumericConstant(ir *backendProtoIR, operation *backendOperationIR, index int32) error {
	if index < 0 || int(index) >= len(ir.constants) || ir.constants[index].kind != NumberKind {
		return fmt.Errorf("emit backend Go numeric proof: PC %d requires a numeric constant", operation.pc)
	}
	return nil
}

func backendGoNumericType(tags backendTagMask) (string, bool) {
	switch tags {
	case backendTagNumber:
		return "float64", true
	case backendTagBool:
		return "bool", true
	default:
		return "", false
	}
}

func (emitter *backendGoNumericEmitter) emitBody() error {
	for blockIndex := range emitter.ir.blocks {
		block := &emitter.ir.blocks[blockIndex]
		if !block.reachable {
			continue
		}
		if blockIndex != 0 {
			fmt.Fprintf(&emitter.body, "b%d:\n", blockIndex)
		}
		terminated := false
		for pc := block.first; pc < block.last; pc++ {
			operation := &emitter.ir.ops[pc]
			var err error
			terminated, err = emitter.emitOperation(operation, block)
			if err != nil {
				return err
			}
			if terminated {
				break
			}
		}
		if terminated {
			continue
		}
		if len(block.successors) != 1 {
			return fmt.Errorf("emit backend Go numeric proof: block %d has no terminator and %d successors", blockIndex, len(block.successors))
		}
		emitter.emitGoto(int32(blockIndex), block.successors[0], 1)
	}
	return nil
}

func (emitter *backendGoNumericEmitter) emitOperation(operation *backendOperationIR, block *backendBlockIR) (bool, error) {
	if backendGoNumericOperationDead(emitter.plan, operation) {
		return false, nil
	}
	definition := func(register int32) (backendValueID, error) {
		for _, candidate := range operation.defs {
			if candidate.register == register {
				return candidate.value, nil
			}
		}
		return invalidBackendValueID, fmt.Errorf("emit backend Go numeric proof: PC %d has no definition for register %d", operation.pc, register)
	}
	use := func(register int32) (backendValueID, error) {
		id := backendOperationUse(operation, register)
		if id == invalidBackendValueID {
			return id, fmt.Errorf("emit backend Go numeric proof: PC %d has no use for register %d", operation.pc, register)
		}
		return id, nil
	}
	switch operation.op {
	case opLoadConst:
		destination, err := definition(operation.a)
		if err != nil {
			return false, err
		}
		constant := emitter.ir.constants[operation.b]
		switch constant.kind {
		case NumberKind:
			emitter.needsMath = true
			fmt.Fprintf(&emitter.body, "\tv%d = math.Float64frombits(0x%016x)\n", destination, constant.bits)
		case BoolKind:
			fmt.Fprintf(&emitter.body, "\tv%d = %t\n", destination, constant.bits != 0)
		}
	case opMove:
		destination, err := definition(operation.a)
		if err != nil {
			return false, err
		}
		source, err := use(operation.b)
		if err != nil {
			return false, err
		}
		fmt.Fprintf(&emitter.body, "\tv%d = v%d\n", destination, source)
	case opAdd, opSub, opMul, opDiv, opMod, opIDiv, opPow:
		destination, _ := definition(operation.a)
		left, _ := use(operation.b)
		right, _ := use(operation.c)
		emitter.emitNumericBinary(destination, left, fmt.Sprintf("v%d", right), operation.op)
	case opAddK, opSubK, opMulK, opDivK, opModK, opIDivK:
		destination, _ := definition(operation.a)
		left, _ := use(operation.b)
		right := emitter.numericConstant(operation.c)
		emitter.emitNumericBinary(destination, left, right, operation.op)
	case opNeg:
		destination, _ := definition(operation.a)
		source, _ := use(operation.b)
		fmt.Fprintf(&emitter.body, "\tv%d = -v%d\n", destination, source)
	case opEqual, opNotEqual, opLess, opLessEqual, opGreater, opGreaterEqual:
		destination, _ := definition(operation.a)
		left, _ := use(operation.b)
		right, _ := use(operation.c)
		if operation.op != opEqual && operation.op != opNotEqual {
			emitter.emitNaNGuard(1, left, right)
		}
		fmt.Fprintf(&emitter.body, "\tv%d = v%d %s v%d\n", destination, left, backendGoComparisonOperator(operation.op), right)
	case opNumericForCheck:
		loop, _ := use(operation.a)
		limit, _ := use(operation.b)
		step, _ := use(operation.c)
		emitter.emitNaNGuard(1, loop, limit, step)
		condition := fmt.Sprintf("(v%d > 0 && v%d > v%d) || (v%d <= 0 && v%d < v%d)", step, loop, limit, step, loop, limit)
		emitter.emitBranch(int32(block.id), operation.targetPC, condition, 1)
		return true, nil
	case opNumericForLoop:
		destination, _ := definition(operation.a)
		loop, _ := use(operation.a)
		step, _ := use(operation.b)
		fmt.Fprintf(&emitter.body, "\tv%d = v%d + v%d\n", destination, loop, step)
		emitter.emitGoto(int32(block.id), emitter.ir.pcToBlock[operation.targetPC], 1)
		return true, nil
	case opJumpIfNotEqualK:
		left, _ := use(operation.a)
		emitter.emitBranch(int32(block.id), operation.targetPC, fmt.Sprintf("v%d != %s", left, emitter.numericConstant(operation.b)), 1)
		return true, nil
	case opJumpIfNotLessK, opJumpIfNotGreaterK, opJumpIfLessK, opJumpIfGreaterK:
		left, _ := use(operation.a)
		emitter.emitNaNGuard(1, left)
		operator := backendGoComparisonOperator(operation.op)
		condition := fmt.Sprintf("v%d %s %s", left, operator, emitter.numericConstant(operation.b))
		if operation.op == opJumpIfNotLessK || operation.op == opJumpIfNotGreaterK {
			condition = "!(" + condition + ")"
		}
		emitter.emitBranch(int32(block.id), operation.targetPC, condition, 1)
		return true, nil
	case opJumpIfNotLess, opJumpIfNotGreater, opJumpIfLess, opJumpIfGreater:
		left, _ := use(operation.a)
		right, _ := use(operation.b)
		emitter.emitNaNGuard(1, left, right)
		condition := fmt.Sprintf("v%d %s v%d", left, backendGoComparisonOperator(operation.op), right)
		if operation.op == opJumpIfNotLess || operation.op == opJumpIfNotGreater {
			condition = "!(" + condition + ")"
		}
		emitter.emitBranch(int32(block.id), operation.targetPC, condition, 1)
		return true, nil
	case opJumpIfFalse:
		condition, _ := use(operation.a)
		expression := "false"
		if emitter.plan.tags[condition-1] == backendTagBool {
			expression = fmt.Sprintf("!v%d", condition)
		}
		emitter.emitBranch(int32(block.id), operation.targetPC, expression, 1)
		return true, nil
	case opJump:
		emitter.emitGoto(int32(block.id), emitter.ir.pcToBlock[operation.targetPC], 1)
		return true, nil
	case opReturnOne, opReturn:
		result, _ := use(operation.a)
		fmt.Fprintf(&emitter.body, "\treturn v%d, true\n", result)
		return true, nil
	default:
		return false, fmt.Errorf("emit backend Go numeric proof: PC %d uses unsupported opcode %s", operation.pc, opcodeName(operation.op))
	}
	return false, nil
}

func (emitter *backendGoNumericEmitter) emitNumericBinary(destination, left backendValueID, right string, op opcode) {
	switch op {
	case opAdd, opAddK:
		fmt.Fprintf(&emitter.body, "\tv%d = v%d + %s\n", destination, left, right)
	case opSub, opSubK:
		fmt.Fprintf(&emitter.body, "\tv%d = v%d - %s\n", destination, left, right)
	case opMul, opMulK:
		fmt.Fprintf(&emitter.body, "\tv%d = v%d * %s\n", destination, left, right)
	case opDiv, opDivK:
		fmt.Fprintf(&emitter.body, "\tv%d = v%d / %s\n", destination, left, right)
	case opMod, opModK:
		emitter.needsMath = true
		fmt.Fprintf(&emitter.body, "\tv%d = v%d - math.Floor(v%d/%s)*%s\n", destination, left, left, right, right)
	case opIDiv, opIDivK:
		emitter.needsMath = true
		fmt.Fprintf(&emitter.body, "\tv%d = math.Floor(v%d / %s)\n", destination, left, right)
	case opPow:
		emitter.needsMath = true
		fmt.Fprintf(&emitter.body, "\tv%d = math.Pow(v%d, %s)\n", destination, left, right)
	}
}

func (emitter *backendGoNumericEmitter) numericConstant(index int32) string {
	emitter.needsMath = true
	return fmt.Sprintf("math.Float64frombits(0x%016x)", emitter.ir.constants[index].bits)
}

func (emitter *backendGoNumericEmitter) emitNaNGuard(indent int, values ...backendValueID) {
	emitter.needsMath = true
	prefix := strings.Repeat("\t", indent)
	for _, value := range values {
		fmt.Fprintf(&emitter.body, "%sif math.IsNaN(v%d) {\n%s\treturn 0, false\n%s}\n", prefix, value, prefix, prefix)
	}
}

func (emitter *backendGoNumericEmitter) emitBranch(from int32, targetPC int32, condition string, indent int) {
	target := emitter.ir.pcToBlock[targetPC]
	nextBlock := int32(-1)
	block := &emitter.ir.blocks[from]
	if int(block.last) < len(emitter.ir.ops) {
		nextBlock = emitter.ir.pcToBlock[block.last]
	}
	prefix := strings.Repeat("\t", indent)
	fmt.Fprintf(&emitter.body, "%sif %s {\n", prefix, condition)
	emitter.emitGoto(from, target, indent+1)
	fmt.Fprintf(&emitter.body, "%s}\n", prefix)
	emitter.emitGoto(from, nextBlock, indent)
}

func (emitter *backendGoNumericEmitter) emitGoto(from, to int32, indent int) {
	prefix := strings.Repeat("\t", indent)
	for edgeIndex := range emitter.ir.edges {
		edge := &emitter.ir.edges[edgeIndex]
		if edge.from != from || edge.to != to {
			continue
		}
		for _, copy := range edge.phiCopies {
			if !emitter.plan.used[copy.destination-1] {
				continue
			}
			fmt.Fprintf(&emitter.body, "%sv%d = v%d\n", prefix, copy.destination, copy.source)
		}
		fmt.Fprintf(&emitter.body, "%sgoto b%d\n", prefix, to)
		return
	}
	fmt.Fprintf(&emitter.body, "%sreturn 0, false\n", prefix)
}

func backendGoComparisonOperator(op opcode) string {
	switch op {
	case opEqual:
		return "=="
	case opNotEqual, opJumpIfNotEqualK:
		return "!="
	case opLess, opJumpIfLess, opJumpIfNotLess, opJumpIfLessK, opJumpIfNotLessK:
		return "<"
	case opLessEqual:
		return "<="
	case opGreater, opJumpIfGreater, opJumpIfNotGreater, opJumpIfGreaterK, opJumpIfNotGreaterK:
		return ">"
	case opGreaterEqual:
		return ">="
	default:
		return "=="
	}
}
