// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedVarargKernel(p0 float64) (float64, bool) {
	var v1 float64
	var v15 float64
	var v16 float64
	var v17 float64
	var v18 float64
	var v26 float64
	var v28 float64
	var v29 float64
	var v30 float64
	var v31 float64
	var v33 float64
	var v34 float64
	var v35 float64
	var v36 float64
	var v37 float64
	var v38 float64
	var v39 float64
	var v40 float64
	var v41 float64
	var v42 float64
	var v43 float64
	var v44 float64
	var v45 float64
	var v46 float64
	var v47 float64
	var ok21 bool
	v1 = p0
	v26 = math.Float64frombits(0x0000000000000000)
	v28 = math.Float64frombits(0x4049000000000000)
	v29 = v1
	v30 = v29 - math.Floor(v29/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v31 = v28 + v30
	v33 = math.Float64frombits(0x3ff0000000000000)
	v34 = v31 + math.Float64frombits(0x0000000000000000)
	v35 = math.Float64frombits(0x3ff0000000000000)
	v15 = v26
	v16 = v33
	v17 = v34
	v18 = v35
	goto b1
b1:
	if math.IsNaN(v16) {
		return 0, false
	}
	if math.IsNaN(v17) {
		return 0, false
	}
	if math.IsNaN(v18) {
		return 0, false
	}
	if (v18 > 0 && v16 > v17) || (v18 <= 0 && v16 < v17) {
		goto b3
	}
	goto b2
b2:
	v36 = v16
	v37 = v16
	v38 = v37 + math.Float64frombits(0x3ff0000000000000)
	v39 = v16
	v40 = v39 + math.Float64frombits(0x4000000000000000)
	v41 = v16
	v42 = v41 + math.Float64frombits(0x4008000000000000)
	v43 = v16
	v44 = v43 + math.Float64frombits(0x4010000000000000)
	v45, ok21 = backendGeneratedVarargScore(v36, v38, v40, v42, v44)
	if !ok21 {
		return 0, false
	}
	v46 = v15 + v45
	v47 = v16 + v18
	v15 = v46
	v16 = v47
	goto b1
b3:
	return v15, true
}

func backendGeneratedVarargPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v15 float64
	var v16 float64
	var v17 float64
	var v18 float64
	var v26 float64
	var v28 float64
	var v29 float64
	var v30 float64
	var v31 float64
	var v33 float64
	var v34 float64
	var v35 float64
	var v36 float64
	var v37 float64
	var v38 float64
	var v39 float64
	var v40 float64
	var v41 float64
	var v42 float64
	var v43 float64
	var v44 float64
	var v45 float64
	var v46 float64
	var v47 float64
	var ok21 bool
	v1 = p0
	v26 = math.Float64frombits(0x0000000000000000)
	v28 = math.Float64frombits(0x4049000000000000)
	v29 = v1
	v30 = v29 - math.Floor(v29/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v31 = v28 + v30
	v33 = math.Float64frombits(0x3ff0000000000000)
	v34 = v31 + math.Float64frombits(0x0000000000000000)
	v35 = math.Float64frombits(0x3ff0000000000000)
	v15 = v26
	v16 = v33
	v17 = v34
	v18 = v35
	goto b1
b1:
	if math.IsNaN(v16) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v17) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v18) {
		return machinePreparedReplayEntry()
	}
	if (v18 > 0 && v16 > v17) || (v18 <= 0 && v16 < v17) {
		goto b3
	}
	goto b2
b2:
	v36 = v16
	v37 = v16
	v38 = v37 + math.Float64frombits(0x3ff0000000000000)
	v39 = v16
	v40 = v39 + math.Float64frombits(0x4000000000000000)
	v41 = v16
	v42 = v41 + math.Float64frombits(0x4008000000000000)
	v43 = v16
	v44 = v43 + math.Float64frombits(0x4010000000000000)
	v45, ok21 = backendGeneratedVarargScore(v36, v38, v40, v42, v44)
	if !ok21 {
		return machinePreparedReplayEntry()
	}
	v46 = v15 + v45
	v47 = v16 + v18
	v15 = v46
	v16 = v47
	goto b1
b3:
	return machinePreparedReturnOneNumber(v15)
}

func backendGeneratedVarargPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchangedAt(2, 0) {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedVarargPreparedFixtureBody(context, p0)
}
