// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedCapturedTargetProto1(p0 float64) (float64, bool) {
	var v1 float64
	var v3 float64
	var v4 float64
	v1 = p0
	v3 = v1
	v4 = v3 + math.Float64frombits(0x3ff0000000000000)
	return v4, true
}
