// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedDialogueCondition(p0 float64) (float64, bool) {
	var v1 float64
	var v40 float64
	var v41 float64
	var v42 float64
	var v43 float64
	var v72 float64
	var v73 float64
	var v74 float64
	var v75 float64
	var v104 float64
	var v105 float64
	var v106 float64
	var v107 float64
	var v111 float64
	var v114 bool
	var v136 float64
	var v159 float64
	var v168 float64
	var v191 float64
	var v200 float64
	var v223 float64
	var v232 float64
	var v255 float64
	var v258 float64
	var v259 float64
	var v260 float64
	var v261 float64
	var v262 float64
	var v263 float64
	var v265 bool
	var v266 bool
	var v267 bool
	var v270 uint32
	var v273 uint32
	var v274 bool
	var v276 uint32
	var v277 float64
	var v278 float64
	var v279 uint32
	var v281 uint32
	var v284 uint32
	var v285 bool
	var v287 uint32
	var v288 float64
	var v289 float64
	var v290 uint32
	var v292 uint32
	var v295 uint32
	var v296 bool
	var v298 uint32
	var v299 float64
	var v300 float64
	var v301 uint32
	var v303 uint32
	var v306 uint32
	var v307 bool
	var v309 uint32
	var v310 float64
	var v311 float64
	var v312 uint32
	var v313 float64
	var v317 float64
	var v318 float64
	var v319 float64
	var v325 float64
	var v326 bool
	var v327 float64
	var v332 float64
	var v333 uint32
	var vp333 bool
	_ = v333
	_ = vp333
	var v335 bool
	var v336 uint32
	var vp336 bool
	_ = v336
	_ = vp336
	var v337 bool
	var vp337 bool
	_ = v337
	_ = vp337
	var v338 bool
	var vp338 bool
	_ = v338
	_ = vp338
	var v339 bool
	var v340 bool
	var v341 uint32
	var vp341 bool
	_ = v341
	_ = vp341
	var v342 float64
	var v343 float64
	var vp343 bool
	_ = v343
	_ = vp343
	var v344 bool
	var v345 bool
	var v346 uint32
	var v347 float64
	var v348 float64
	var v349 float64
	var v350 float64
	var v351 float64
	var v352 float64
	var v353 float64
	var v354 float64
	var v355 float64
	var v356 float64
	var v357 float64
	var v358 float64
	var v359 float64
	var v360 float64
	var v361 float64
	var v362 float64
	var v363 float64
	var v364 float64
	var v365 float64
	var v366 float64
	var v367 float64
	var v368 float64
	var v369 float64
	var v370 float64
	var v371 float64
	var v372 float64
	var v373 bool
	var vp373 bool
	_ = v373
	_ = vp373
	var v374 float64
	var v375 float64
	var v376 bool
	var vp376 bool
	_ = v376
	_ = vp376
	var v377 float64
	var v378 float64
	var v379 bool
	var vp379 bool
	_ = v379
	_ = vp379
	var v380 float64
	var v381 float64
	var v382 bool
	var vp382 bool
	_ = v382
	_ = vp382
	var v383 float64
	var v384 float64
	var v385 float64
	var v386 float64
	var v387 float64
	var v388 float64
	var v389 float64
	var v390 float64
	var v391 float64
	var v392 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r1_0 bool
	_ = r1_0
	var rp1_0 bool
	_ = rp1_0
	var r1_1 bool
	_ = r1_1
	var rp1_1 bool
	_ = rp1_1
	var r1_2 bool
	_ = r1_2
	var rp1_2 bool
	_ = rp1_2
	var r1_3 bool
	_ = r1_3
	var rp1_3 bool
	_ = rp1_3
	var r1_4 bool
	_ = r1_4
	var rp1_4 bool
	_ = rp1_4
	var r2_0 uint32
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 float64
	_ = r2_2
	var r2_3 uint32
	_ = r2_3
	var r3_0 uint32
	_ = r3_0
	var r3_1 bool
	_ = r3_1
	var r4_0 uint32
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r5_0 uint32
	_ = r5_0
	var r5_1 float64
	_ = r5_1
	var r5_2 float64
	_ = r5_2
	var r5_3 uint32
	_ = r5_3
	var r6_0 uint32
	_ = r6_0
	var r6_1 bool
	_ = r6_1
	var r7_0 uint32
	_ = r7_0
	var r7_1 float64
	_ = r7_1
	var r8_0 uint32
	_ = r8_0
	var r8_1 float64
	_ = r8_1
	var r8_2 float64
	_ = r8_2
	var r8_3 uint32
	_ = r8_3
	var r9_0 uint32
	_ = r9_0
	var r9_1 bool
	_ = r9_1
	var r10_0 uint32
	_ = r10_0
	var r10_1 float64
	_ = r10_1
	var r11_0 uint32
	_ = r11_0
	var r11_1 float64
	_ = r11_1
	var r11_2 float64
	_ = r11_2
	var r11_3 uint32
	_ = r11_3
	var r12_0 uint32
	_ = r12_0
	var r12_1 bool
	_ = r12_1
	var r13_0 uint32
	_ = r13_0
	var r13_1 float64
	_ = r13_1
	var ra0_0 [2]uint32
	var rap0_0 [2]bool
	var ra0_1 [2]bool
	var rap0_1 [2]bool
	var ra0_2 [2]uint32
	var rap0_2 [2]bool
	var ra0_3 [2]float64
	var rap0_3 [2]bool
	var ri0 int
	_ = ri0
	var ra1_0 [4]uint32
	var ra1_1 [4]float64
	var ra1_2 [4]float64
	var ra1_3 [4]uint32
	var ri1 int
	_ = ri1
	var ra2_0 [2]uint32
	var rap2_0 [2]bool
	var ra2_1 [2]bool
	var rap2_1 [2]bool
	var ra2_2 [2]uint32
	var rap2_2 [2]bool
	var ra2_3 [2]float64
	var rap2_3 [2]bool
	var ri2 int
	_ = ri2
	var ra3_0 [2]uint32
	var rap3_0 [2]bool
	var ra3_1 [2]bool
	var rap3_1 [2]bool
	var ra3_2 [2]uint32
	var rap3_2 [2]bool
	var ra3_3 [2]float64
	var rap3_3 [2]bool
	var ri3 int
	_ = ri3
	var ra4_0 [2]uint32
	var rap4_0 [2]bool
	var ra4_1 [2]bool
	var rap4_1 [2]bool
	var ra4_2 [2]uint32
	var rap4_2 [2]bool
	var ra4_3 [2]float64
	var rap4_3 [2]bool
	var ri4 int
	_ = ri4
	var rfi0 int
	var rfs0 int
	_ = rfi0
	_ = rfs0
	v1 = p0
	v258 = math.Float64frombits(0x4020000000000000)
	v259 = v1
	v260 = v259 - math.Floor(v259/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v261 = v258 + v260
	r0_0 = v261
	v262 = math.Float64frombits(0x4039000000000000)
	r0_1 = v262
	v263 = math.Float64frombits(0x4008000000000000)
	r0_2 = v263
	v265 = true
	r1_0 = v265
	rp1_0 = true
	v266 = false
	r1_1 = v266
	rp1_1 = true
	v267 = false
	r1_2 = v267
	rp1_2 = true
	r0_3 = 1
	v270 = uint32(8)
	r2_0 = v270
	v273 = uint32(4)
	r3_0 = v273
	v274 = true
	r3_1 = v274
	ra0_0[0] = r3_0
	rap0_0[0] = true
	ra0_1[0] = r3_1
	rap0_1[0] = true
	v276 = uint32(1)
	r4_0 = v276
	v277 = math.Float64frombits(0x4014000000000000)
	r4_1 = v277
	ra0_2[1] = r4_0
	rap0_2[1] = true
	ra0_3[1] = r4_1
	rap0_3[1] = true
	r2_1 = 1
	v278 = math.Float64frombits(0x4010000000000000)
	r2_2 = v278
	v279 = uint32(5)
	r2_3 = v279
	ra1_0[0] = r2_0
	ra1_1[0] = r2_1
	ra1_2[0] = r2_2
	ra1_3[0] = r2_3
	v281 = uint32(17)
	r5_0 = v281
	v284 = uint32(5)
	r6_0 = v284
	v285 = true
	r6_1 = v285
	ra2_0[0] = r6_0
	rap2_0[0] = true
	ra2_1[0] = r6_1
	rap2_1[0] = true
	v287 = uint32(2)
	r7_0 = v287
	v288 = math.Float64frombits(0x4028000000000000)
	r7_1 = v288
	ra2_2[1] = r7_0
	rap2_2[1] = true
	ra2_3[1] = r7_1
	rap2_3[1] = true
	r5_1 = 2
	v289 = math.Float64frombits(0x401c000000000000)
	r5_2 = v289
	v290 = uint32(6)
	r5_3 = v290
	ra1_0[1] = r5_0
	ra1_1[1] = r5_1
	ra1_2[1] = r5_2
	ra1_3[1] = r5_3
	v292 = uint32(18)
	r8_0 = v292
	v295 = uint32(6)
	r9_0 = v295
	v296 = true
	r9_1 = v296
	ra3_0[0] = r9_0
	rap3_0[0] = true
	ra3_1[0] = r9_1
	rap3_1[0] = true
	v298 = uint32(3)
	r10_0 = v298
	v299 = math.Float64frombits(0x4010000000000000)
	r10_1 = v299
	ra3_2[1] = r10_0
	rap3_2[1] = true
	ra3_3[1] = r10_1
	rap3_3[1] = true
	r8_1 = 3
	v300 = math.Float64frombits(0x4026000000000000)
	r8_2 = v300
	v301 = uint32(19)
	r8_3 = v301
	ra1_0[2] = r8_0
	ra1_1[2] = r8_1
	ra1_2[2] = r8_2
	ra1_3[2] = r8_3
	v303 = uint32(20)
	r11_0 = v303
	v306 = uint32(19)
	r12_0 = v306
	v307 = true
	r12_1 = v307
	ra4_0[0] = r12_0
	rap4_0[0] = true
	ra4_1[0] = r12_1
	rap4_1[0] = true
	v309 = uint32(1)
	r13_0 = v309
	v310 = math.Float64frombits(0x4028000000000000)
	r13_1 = v310
	ra4_2[1] = r13_0
	rap4_2[1] = true
	ra4_3[1] = r13_1
	rap4_3[1] = true
	r11_1 = 4
	v311 = math.Float64frombits(0x402a000000000000)
	r11_2 = v311
	v312 = uint32(21)
	r11_3 = v312
	ra1_0[3] = r11_0
	ra1_1[3] = r11_1
	ra1_2[3] = r11_2
	ra1_3[3] = r11_3
	v313 = math.Float64frombits(0x0000000000000000)
	v317 = math.Float64frombits(0x3ff0000000000000)
	v318 = math.Float64frombits(0x4042000000000000)
	v319 = math.Float64frombits(0x3ff0000000000000)
	v40 = v313
	v41 = v317
	v42 = v318
	v43 = v319
	goto b1
b1:
	if math.IsNaN(v41) {
		return 0, false
	}
	if math.IsNaN(v42) {
		return 0, false
	}
	if math.IsNaN(v43) {
		return 0, false
	}
	if (v43 > 0 && v41 > v42) || (v43 <= 0 && v41 < v42) {
		goto b15
	}
	goto b2
b2:
	ri1 = 0
	v72 = v40
	v73 = v41
	v74 = v42
	v75 = v43
	goto b3
b3:
	if ri1 >= 4 {
		goto b14
	}
	v325 = float64(ri1 + 1)
	ri1++
	goto b4
b4:
	v326 = true
	if v325 < 1 || v325 > 4 {
		return 0, false
	}
	v327 = ra1_1[int(v325)-1]
	if v327 < 1 || v327 > 4 || v327 != float64(int(v327)) {
		return 0, false
	}
	rfs0 = int(v327) - 1
	rfi0 = 0
	v104 = v72
	v105 = v73
	v106 = v74
	v107 = v75
	v111 = v325
	v114 = v326
	goto b5
b5:
	{
		rfl121 := 0
		switch rfs0 {
		case 0:
			rfl121 = 2
		case 1:
			rfl121 = 2
		case 2:
			rfl121 = 2
		case 3:
			rfl121 = 2
		default:
			return 0, false
		}
		if rfi0 >= rfl121 {
			goto b11
		}
		switch rfs0 {
		case 0:
			v332 = float64(0 + rfi0 + 1)
		case 1:
			v332 = float64(64 + rfi0 + 1)
		case 2:
			v332 = float64(96 + rfi0 + 1)
		case 3:
			v332 = float64(128 + rfi0 + 1)
		}
		rfi0++
	}
	goto b6
b6:
	{
		rr332 := int(v332) - 1
		if v332 < 1 || v332 > 160 || v332 != float64(int(v332)) {
			return 0, false
		}
		switch rr332 / 32 {
		case 0:
			if rr332%32 >= 2 {
				return 0, false
			}
			v333 = ra0_0[rr332%32]
			vp333 = rap0_0[rr332%32]
		case 2:
			if rr332%32 >= 2 {
				return 0, false
			}
			v333 = ra2_0[rr332%32]
			vp333 = rap2_0[rr332%32]
		case 3:
			if rr332%32 >= 2 {
				return 0, false
			}
			v333 = ra3_0[rr332%32]
			vp333 = rap3_0[rr332%32]
		case 4:
			if rr332%32 >= 2 {
				return 0, false
			}
			v333 = ra4_0[rr332%32]
			vp333 = rap4_0[rr332%32]
		default:
			return 0, false
		}
	}
	v335 = !(!vp333)
	if !v335 {
		goto b9
	}
	goto b7
b7:
	{
		rr332 := int(v332) - 1
		if v332 < 1 || v332 > 160 || v332 != float64(int(v332)) {
			return 0, false
		}
		switch rr332 / 32 {
		case 0:
			if rr332%32 >= 2 {
				return 0, false
			}
			v336 = ra0_0[rr332%32]
			vp336 = rap0_0[rr332%32]
		case 2:
			if rr332%32 >= 2 {
				return 0, false
			}
			v336 = ra2_0[rr332%32]
			vp336 = rap2_0[rr332%32]
		case 3:
			if rr332%32 >= 2 {
				return 0, false
			}
			v336 = ra3_0[rr332%32]
			vp336 = rap3_0[rr332%32]
		case 4:
			if rr332%32 >= 2 {
				return 0, false
			}
			v336 = ra4_0[rr332%32]
			vp336 = rap4_0[rr332%32]
		default:
			return 0, false
		}
	}
	if !vp336 {
		return 0, false
	}
	switch v336 {
	case uint32(4):
		v337 = r1_0
		vp337 = rp1_0
	case uint32(5):
		v337 = r1_1
		vp337 = rp1_1
	case uint32(6):
		v337 = r1_2
		vp337 = rp1_2
	case uint32(19):
		v337 = r1_3
		vp337 = rp1_3
	case uint32(21):
		v337 = r1_4
		vp337 = rp1_4
	default:
		return 0, false
	}
	{
		rr332 := int(v332) - 1
		if v332 < 1 || v332 > 160 || v332 != float64(int(v332)) {
			return 0, false
		}
		switch rr332 / 32 {
		case 0:
			if rr332%32 >= 2 {
				return 0, false
			}
			v338 = ra0_1[rr332%32]
			vp338 = rap0_1[rr332%32]
		case 2:
			if rr332%32 >= 2 {
				return 0, false
			}
			v338 = ra2_1[rr332%32]
			vp338 = rap2_1[rr332%32]
		case 3:
			if rr332%32 >= 2 {
				return 0, false
			}
			v338 = ra3_1[rr332%32]
			vp338 = rap3_1[rr332%32]
		case 4:
			if rr332%32 >= 2 {
				return 0, false
			}
			v338 = ra4_1[rr332%32]
			vp338 = rap4_1[rr332%32]
		default:
			return 0, false
		}
	}
	v339 = !(vp337 == vp338 && (!vp337 || v337 == v338))
	if !v339 {
		goto b5
	}
	goto b8
b8:
	v340 = false
	v114 = v340
	goto b5
b9:
	{
		rr332 := int(v332) - 1
		if v332 < 1 || v332 > 160 || v332 != float64(int(v332)) {
			return 0, false
		}
		switch rr332 / 32 {
		case 0:
			if rr332%32 >= 2 {
				return 0, false
			}
			v341 = ra0_2[rr332%32]
			vp341 = rap0_2[rr332%32]
		case 2:
			if rr332%32 >= 2 {
				return 0, false
			}
			v341 = ra2_2[rr332%32]
			vp341 = rap2_2[rr332%32]
		case 3:
			if rr332%32 >= 2 {
				return 0, false
			}
			v341 = ra3_2[rr332%32]
			vp341 = rap3_2[rr332%32]
		case 4:
			if rr332%32 >= 2 {
				return 0, false
			}
			v341 = ra4_2[rr332%32]
			vp341 = rap4_2[rr332%32]
		default:
			return 0, false
		}
	}
	if !vp341 {
		return 0, false
	}
	switch v341 {
	case uint32(1):
		v342 = r0_0
	case uint32(2):
		v342 = r0_1
	case uint32(3):
		v342 = r0_2
	case uint32(7):
		v342 = r0_3
	default:
		return 0, false
	}
	{
		rr332 := int(v332) - 1
		if v332 < 1 || v332 > 160 || v332 != float64(int(v332)) {
			return 0, false
		}
		switch rr332 / 32 {
		case 0:
			if rr332%32 >= 2 {
				return 0, false
			}
			v343 = ra0_3[rr332%32]
			vp343 = rap0_3[rr332%32]
		case 2:
			if rr332%32 >= 2 {
				return 0, false
			}
			v343 = ra2_3[rr332%32]
			vp343 = rap2_3[rr332%32]
		case 3:
			if rr332%32 >= 2 {
				return 0, false
			}
			v343 = ra3_3[rr332%32]
			vp343 = rap3_3[rr332%32]
		case 4:
			if rr332%32 >= 2 {
				return 0, false
			}
			v343 = ra4_3[rr332%32]
			vp343 = rap4_3[rr332%32]
		default:
			return 0, false
		}
	}
	if !vp343 {
		return 0, false
	}
	if math.IsNaN(v343) {
		return 0, false
	}
	if math.IsNaN(v342) {
		return 0, false
	}
	if !(v343 > v342) {
		goto b5
	}
	goto b10
b10:
	v344 = false
	v114 = v344
	goto b5
b11:
	if !v114 {
		goto b13
	}
	goto b12
b12:
	v345 = true
	if v111 < 1 || v111 > 4 {
		return 0, false
	}
	v346 = ra1_3[int(v111)-1]
	switch v346 {
	case uint32(4):
		r1_0 = v345
		rp1_0 = true
	case uint32(5):
		r1_1 = v345
		rp1_1 = true
	case uint32(6):
		r1_2 = v345
		rp1_2 = true
	case uint32(19):
		r1_3 = v345
		rp1_3 = true
	case uint32(21):
		r1_4 = v345
		rp1_4 = true
	default:
		return 0, false
	}
	v347 = r0_0
	if v111 < 1 || v111 > 4 {
		return 0, false
	}
	v348 = ra1_2[int(v111)-1]
	v349 = v348 - math.Floor(v348/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v350 = v347 + v349
	r0_0 = v350
	v351 = math.Float64frombits(0x3ff0000000000000)
	v352 = r0_2
	v353 = v352 + v351
	r0_2 = v353
	v354 = r0_1
	if v111 < 1 || v111 > 4 {
		return 0, false
	}
	v355 = ra1_2[int(v111)-1]
	v356 = math.Floor(v355 / math.Float64frombits(0x4008000000000000))
	v357 = v354 - v356
	r0_1 = v357
	if v111 < 1 || v111 > 4 {
		return 0, false
	}
	v358 = ra1_2[int(v111)-1]
	v359 = v104 + v358
	v360 = r0_0
	v361 = v359 + v360
	v362 = r0_2
	v363 = v361 + v362
	v72 = v363
	v73 = v105
	v74 = v106
	v75 = v107
	goto b3
b13:
	v364 = math.Float64frombits(0x3ff0000000000000)
	v365 = r0_1
	v366 = v365 + v364
	r0_1 = v366
	v367 = r0_1
	v368 = v367 - math.Floor(v367/math.Float64frombits(0x401c000000000000))*math.Float64frombits(0x401c000000000000)
	v369 = v104 + v368
	v72 = v369
	v73 = v105
	v74 = v106
	v75 = v107
	goto b3
b14:
	v370 = v73 + v75
	v40 = v72
	v41 = v370
	v42 = v74
	v43 = v75
	goto b1
b15:
	v371 = math.Float64frombits(0x0000000000000000)
	v372 = r0_3
	if v372 < 1 || v372 > 1 {
		return 0, false
	}
	switch int(v372) - 1 {
	case 0:
		v373 = r1_1
		vp373 = rp1_1
	default:
		return 0, false
	}
	if !vp373 || !v373 {
		v136 = v40
		v159 = v371
		goto b17
	}
	goto b16
b16:
	v374 = math.Float64frombits(0x4024000000000000)
	v136 = v40
	v159 = v374
	goto b17
b17:
	v375 = r0_3
	if v375 < 1 || v375 > 1 {
		return 0, false
	}
	switch int(v375) - 1 {
	case 0:
		v376 = r1_2
		vp376 = rp1_2
	default:
		return 0, false
	}
	if !vp376 || !v376 {
		v168 = v136
		v191 = v159
		goto b19
	}
	goto b18
b18:
	v377 = v159 + math.Float64frombits(0x4034000000000000)
	v168 = v136
	v191 = v377
	goto b19
b19:
	v378 = r0_3
	if v378 < 1 || v378 > 1 {
		return 0, false
	}
	switch int(v378) - 1 {
	case 0:
		v379 = r1_3
		vp379 = rp1_3
	default:
		return 0, false
	}
	if !vp379 || !v379 {
		v200 = v168
		v223 = v191
		goto b21
	}
	goto b20
b20:
	v380 = v191 + math.Float64frombits(0x403e000000000000)
	v200 = v168
	v223 = v380
	goto b21
b21:
	v381 = r0_3
	if v381 < 1 || v381 > 1 {
		return 0, false
	}
	switch int(v381) - 1 {
	case 0:
		v382 = r1_4
		vp382 = rp1_4
	default:
		return 0, false
	}
	if !vp382 || !v382 {
		v232 = v200
		v255 = v223
		goto b23
	}
	goto b22
b22:
	v383 = v223 + math.Float64frombits(0x4044000000000000)
	v232 = v200
	v255 = v383
	goto b23
b23:
	v384 = v232
	v385 = v255
	v386 = v384 + v385
	v387 = r0_1
	v388 = v386 + v387
	v389 = r0_0
	v390 = v388 + v389
	v391 = r0_2
	v392 = v390 + v391
	return v392, true
}

func backendGeneratedDialogueConditionPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v40 float64
	var v41 float64
	var v42 float64
	var v43 float64
	var v72 float64
	var v73 float64
	var v74 float64
	var v75 float64
	var v104 float64
	var v105 float64
	var v106 float64
	var v107 float64
	var v111 float64
	var v114 bool
	var v136 float64
	var v159 float64
	var v168 float64
	var v191 float64
	var v200 float64
	var v223 float64
	var v232 float64
	var v255 float64
	var v258 float64
	var v259 float64
	var v260 float64
	var v261 float64
	var v262 float64
	var v263 float64
	var v265 bool
	var v266 bool
	var v267 bool
	var v270 uint32
	var v273 uint32
	var v274 bool
	var v276 uint32
	var v277 float64
	var v278 float64
	var v279 uint32
	var v281 uint32
	var v284 uint32
	var v285 bool
	var v287 uint32
	var v288 float64
	var v289 float64
	var v290 uint32
	var v292 uint32
	var v295 uint32
	var v296 bool
	var v298 uint32
	var v299 float64
	var v300 float64
	var v301 uint32
	var v303 uint32
	var v306 uint32
	var v307 bool
	var v309 uint32
	var v310 float64
	var v311 float64
	var v312 uint32
	var v313 float64
	var v317 float64
	var v318 float64
	var v319 float64
	var v325 float64
	var v326 bool
	var v327 float64
	var v332 float64
	var v333 uint32
	var vp333 bool
	_ = v333
	_ = vp333
	var v335 bool
	var v336 uint32
	var vp336 bool
	_ = v336
	_ = vp336
	var v337 bool
	var vp337 bool
	_ = v337
	_ = vp337
	var v338 bool
	var vp338 bool
	_ = v338
	_ = vp338
	var v339 bool
	var v340 bool
	var v341 uint32
	var vp341 bool
	_ = v341
	_ = vp341
	var v342 float64
	var v343 float64
	var vp343 bool
	_ = v343
	_ = vp343
	var v344 bool
	var v345 bool
	var v346 uint32
	var v347 float64
	var v348 float64
	var v349 float64
	var v350 float64
	var v351 float64
	var v352 float64
	var v353 float64
	var v354 float64
	var v355 float64
	var v356 float64
	var v357 float64
	var v358 float64
	var v359 float64
	var v360 float64
	var v361 float64
	var v362 float64
	var v363 float64
	var v364 float64
	var v365 float64
	var v366 float64
	var v367 float64
	var v368 float64
	var v369 float64
	var v370 float64
	var v371 float64
	var v372 float64
	var v373 bool
	var vp373 bool
	_ = v373
	_ = vp373
	var v374 float64
	var v375 float64
	var v376 bool
	var vp376 bool
	_ = v376
	_ = vp376
	var v377 float64
	var v378 float64
	var v379 bool
	var vp379 bool
	_ = v379
	_ = vp379
	var v380 float64
	var v381 float64
	var v382 bool
	var vp382 bool
	_ = v382
	_ = vp382
	var v383 float64
	var v384 float64
	var v385 float64
	var v386 float64
	var v387 float64
	var v388 float64
	var v389 float64
	var v390 float64
	var v391 float64
	var v392 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r1_0 bool
	_ = r1_0
	var rp1_0 bool
	_ = rp1_0
	var r1_1 bool
	_ = r1_1
	var rp1_1 bool
	_ = rp1_1
	var r1_2 bool
	_ = r1_2
	var rp1_2 bool
	_ = rp1_2
	var r1_3 bool
	_ = r1_3
	var rp1_3 bool
	_ = rp1_3
	var r1_4 bool
	_ = r1_4
	var rp1_4 bool
	_ = rp1_4
	var r2_0 uint32
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 float64
	_ = r2_2
	var r2_3 uint32
	_ = r2_3
	var r3_0 uint32
	_ = r3_0
	var r3_1 bool
	_ = r3_1
	var r4_0 uint32
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r5_0 uint32
	_ = r5_0
	var r5_1 float64
	_ = r5_1
	var r5_2 float64
	_ = r5_2
	var r5_3 uint32
	_ = r5_3
	var r6_0 uint32
	_ = r6_0
	var r6_1 bool
	_ = r6_1
	var r7_0 uint32
	_ = r7_0
	var r7_1 float64
	_ = r7_1
	var r8_0 uint32
	_ = r8_0
	var r8_1 float64
	_ = r8_1
	var r8_2 float64
	_ = r8_2
	var r8_3 uint32
	_ = r8_3
	var r9_0 uint32
	_ = r9_0
	var r9_1 bool
	_ = r9_1
	var r10_0 uint32
	_ = r10_0
	var r10_1 float64
	_ = r10_1
	var r11_0 uint32
	_ = r11_0
	var r11_1 float64
	_ = r11_1
	var r11_2 float64
	_ = r11_2
	var r11_3 uint32
	_ = r11_3
	var r12_0 uint32
	_ = r12_0
	var r12_1 bool
	_ = r12_1
	var r13_0 uint32
	_ = r13_0
	var r13_1 float64
	_ = r13_1
	var ra0_0 [2]uint32
	var rap0_0 [2]bool
	var ra0_1 [2]bool
	var rap0_1 [2]bool
	var ra0_2 [2]uint32
	var rap0_2 [2]bool
	var ra0_3 [2]float64
	var rap0_3 [2]bool
	var ri0 int
	_ = ri0
	var ra1_0 [4]uint32
	var ra1_1 [4]float64
	var ra1_2 [4]float64
	var ra1_3 [4]uint32
	var ri1 int
	_ = ri1
	var ra2_0 [2]uint32
	var rap2_0 [2]bool
	var ra2_1 [2]bool
	var rap2_1 [2]bool
	var ra2_2 [2]uint32
	var rap2_2 [2]bool
	var ra2_3 [2]float64
	var rap2_3 [2]bool
	var ri2 int
	_ = ri2
	var ra3_0 [2]uint32
	var rap3_0 [2]bool
	var ra3_1 [2]bool
	var rap3_1 [2]bool
	var ra3_2 [2]uint32
	var rap3_2 [2]bool
	var ra3_3 [2]float64
	var rap3_3 [2]bool
	var ri3 int
	_ = ri3
	var ra4_0 [2]uint32
	var rap4_0 [2]bool
	var ra4_1 [2]bool
	var rap4_1 [2]bool
	var ra4_2 [2]uint32
	var rap4_2 [2]bool
	var ra4_3 [2]float64
	var rap4_3 [2]bool
	var ri4 int
	_ = ri4
	var rfi0 int
	var rfs0 int
	_ = rfi0
	_ = rfs0
	v1 = p0
	v258 = math.Float64frombits(0x4020000000000000)
	v259 = v1
	v260 = v259 - math.Floor(v259/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v261 = v258 + v260
	r0_0 = v261
	v262 = math.Float64frombits(0x4039000000000000)
	r0_1 = v262
	v263 = math.Float64frombits(0x4008000000000000)
	r0_2 = v263
	v265 = true
	r1_0 = v265
	rp1_0 = true
	v266 = false
	r1_1 = v266
	rp1_1 = true
	v267 = false
	r1_2 = v267
	rp1_2 = true
	r0_3 = 1
	v270 = uint32(8)
	r2_0 = v270
	v273 = uint32(4)
	r3_0 = v273
	v274 = true
	r3_1 = v274
	ra0_0[0] = r3_0
	rap0_0[0] = true
	ra0_1[0] = r3_1
	rap0_1[0] = true
	v276 = uint32(1)
	r4_0 = v276
	v277 = math.Float64frombits(0x4014000000000000)
	r4_1 = v277
	ra0_2[1] = r4_0
	rap0_2[1] = true
	ra0_3[1] = r4_1
	rap0_3[1] = true
	r2_1 = 1
	v278 = math.Float64frombits(0x4010000000000000)
	r2_2 = v278
	v279 = uint32(5)
	r2_3 = v279
	ra1_0[0] = r2_0
	ra1_1[0] = r2_1
	ra1_2[0] = r2_2
	ra1_3[0] = r2_3
	v281 = uint32(17)
	r5_0 = v281
	v284 = uint32(5)
	r6_0 = v284
	v285 = true
	r6_1 = v285
	ra2_0[0] = r6_0
	rap2_0[0] = true
	ra2_1[0] = r6_1
	rap2_1[0] = true
	v287 = uint32(2)
	r7_0 = v287
	v288 = math.Float64frombits(0x4028000000000000)
	r7_1 = v288
	ra2_2[1] = r7_0
	rap2_2[1] = true
	ra2_3[1] = r7_1
	rap2_3[1] = true
	r5_1 = 2
	v289 = math.Float64frombits(0x401c000000000000)
	r5_2 = v289
	v290 = uint32(6)
	r5_3 = v290
	ra1_0[1] = r5_0
	ra1_1[1] = r5_1
	ra1_2[1] = r5_2
	ra1_3[1] = r5_3
	v292 = uint32(18)
	r8_0 = v292
	v295 = uint32(6)
	r9_0 = v295
	v296 = true
	r9_1 = v296
	ra3_0[0] = r9_0
	rap3_0[0] = true
	ra3_1[0] = r9_1
	rap3_1[0] = true
	v298 = uint32(3)
	r10_0 = v298
	v299 = math.Float64frombits(0x4010000000000000)
	r10_1 = v299
	ra3_2[1] = r10_0
	rap3_2[1] = true
	ra3_3[1] = r10_1
	rap3_3[1] = true
	r8_1 = 3
	v300 = math.Float64frombits(0x4026000000000000)
	r8_2 = v300
	v301 = uint32(19)
	r8_3 = v301
	ra1_0[2] = r8_0
	ra1_1[2] = r8_1
	ra1_2[2] = r8_2
	ra1_3[2] = r8_3
	v303 = uint32(20)
	r11_0 = v303
	v306 = uint32(19)
	r12_0 = v306
	v307 = true
	r12_1 = v307
	ra4_0[0] = r12_0
	rap4_0[0] = true
	ra4_1[0] = r12_1
	rap4_1[0] = true
	v309 = uint32(1)
	r13_0 = v309
	v310 = math.Float64frombits(0x4028000000000000)
	r13_1 = v310
	ra4_2[1] = r13_0
	rap4_2[1] = true
	ra4_3[1] = r13_1
	rap4_3[1] = true
	r11_1 = 4
	v311 = math.Float64frombits(0x402a000000000000)
	r11_2 = v311
	v312 = uint32(21)
	r11_3 = v312
	ra1_0[3] = r11_0
	ra1_1[3] = r11_1
	ra1_2[3] = r11_2
	ra1_3[3] = r11_3
	v313 = math.Float64frombits(0x0000000000000000)
	v317 = math.Float64frombits(0x3ff0000000000000)
	v318 = math.Float64frombits(0x4042000000000000)
	v319 = math.Float64frombits(0x3ff0000000000000)
	v40 = v313
	v41 = v317
	v42 = v318
	v43 = v319
	goto b1
b1:
	if math.IsNaN(v41) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v42) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v43) {
		return machinePreparedReplayEntry()
	}
	if (v43 > 0 && v41 > v42) || (v43 <= 0 && v41 < v42) {
		goto b15
	}
	goto b2
b2:
	ri1 = 0
	v72 = v40
	v73 = v41
	v74 = v42
	v75 = v43
	goto b3
b3:
	if ri1 >= 4 {
		goto b14
	}
	v325 = float64(ri1 + 1)
	ri1++
	goto b4
b4:
	v326 = true
	if v325 < 1 || v325 > 4 {
		return machinePreparedReplayEntry()
	}
	v327 = ra1_1[int(v325)-1]
	if v327 < 1 || v327 > 4 || v327 != float64(int(v327)) {
		return machinePreparedReplayEntry()
	}
	rfs0 = int(v327) - 1
	rfi0 = 0
	v104 = v72
	v105 = v73
	v106 = v74
	v107 = v75
	v111 = v325
	v114 = v326
	goto b5
b5:
	{
		rfl121 := 0
		switch rfs0 {
		case 0:
			rfl121 = 2
		case 1:
			rfl121 = 2
		case 2:
			rfl121 = 2
		case 3:
			rfl121 = 2
		default:
			return machinePreparedReplayEntry()
		}
		if rfi0 >= rfl121 {
			goto b11
		}
		switch rfs0 {
		case 0:
			v332 = float64(0 + rfi0 + 1)
		case 1:
			v332 = float64(64 + rfi0 + 1)
		case 2:
			v332 = float64(96 + rfi0 + 1)
		case 3:
			v332 = float64(128 + rfi0 + 1)
		}
		rfi0++
	}
	goto b6
b6:
	{
		rr332 := int(v332) - 1
		if v332 < 1 || v332 > 160 || v332 != float64(int(v332)) {
			return machinePreparedReplayEntry()
		}
		switch rr332 / 32 {
		case 0:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v333 = ra0_0[rr332%32]
			vp333 = rap0_0[rr332%32]
		case 2:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v333 = ra2_0[rr332%32]
			vp333 = rap2_0[rr332%32]
		case 3:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v333 = ra3_0[rr332%32]
			vp333 = rap3_0[rr332%32]
		case 4:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v333 = ra4_0[rr332%32]
			vp333 = rap4_0[rr332%32]
		default:
			return machinePreparedReplayEntry()
		}
	}
	v335 = !(!vp333)
	if !v335 {
		goto b9
	}
	goto b7
b7:
	{
		rr332 := int(v332) - 1
		if v332 < 1 || v332 > 160 || v332 != float64(int(v332)) {
			return machinePreparedReplayEntry()
		}
		switch rr332 / 32 {
		case 0:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v336 = ra0_0[rr332%32]
			vp336 = rap0_0[rr332%32]
		case 2:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v336 = ra2_0[rr332%32]
			vp336 = rap2_0[rr332%32]
		case 3:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v336 = ra3_0[rr332%32]
			vp336 = rap3_0[rr332%32]
		case 4:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v336 = ra4_0[rr332%32]
			vp336 = rap4_0[rr332%32]
		default:
			return machinePreparedReplayEntry()
		}
	}
	if !vp336 {
		return machinePreparedReplayEntry()
	}
	switch v336 {
	case uint32(4):
		v337 = r1_0
		vp337 = rp1_0
	case uint32(5):
		v337 = r1_1
		vp337 = rp1_1
	case uint32(6):
		v337 = r1_2
		vp337 = rp1_2
	case uint32(19):
		v337 = r1_3
		vp337 = rp1_3
	case uint32(21):
		v337 = r1_4
		vp337 = rp1_4
	default:
		return machinePreparedReplayEntry()
	}
	{
		rr332 := int(v332) - 1
		if v332 < 1 || v332 > 160 || v332 != float64(int(v332)) {
			return machinePreparedReplayEntry()
		}
		switch rr332 / 32 {
		case 0:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v338 = ra0_1[rr332%32]
			vp338 = rap0_1[rr332%32]
		case 2:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v338 = ra2_1[rr332%32]
			vp338 = rap2_1[rr332%32]
		case 3:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v338 = ra3_1[rr332%32]
			vp338 = rap3_1[rr332%32]
		case 4:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v338 = ra4_1[rr332%32]
			vp338 = rap4_1[rr332%32]
		default:
			return machinePreparedReplayEntry()
		}
	}
	v339 = !(vp337 == vp338 && (!vp337 || v337 == v338))
	if !v339 {
		goto b5
	}
	goto b8
b8:
	v340 = false
	v114 = v340
	goto b5
b9:
	{
		rr332 := int(v332) - 1
		if v332 < 1 || v332 > 160 || v332 != float64(int(v332)) {
			return machinePreparedReplayEntry()
		}
		switch rr332 / 32 {
		case 0:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v341 = ra0_2[rr332%32]
			vp341 = rap0_2[rr332%32]
		case 2:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v341 = ra2_2[rr332%32]
			vp341 = rap2_2[rr332%32]
		case 3:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v341 = ra3_2[rr332%32]
			vp341 = rap3_2[rr332%32]
		case 4:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v341 = ra4_2[rr332%32]
			vp341 = rap4_2[rr332%32]
		default:
			return machinePreparedReplayEntry()
		}
	}
	if !vp341 {
		return machinePreparedReplayEntry()
	}
	switch v341 {
	case uint32(1):
		v342 = r0_0
	case uint32(2):
		v342 = r0_1
	case uint32(3):
		v342 = r0_2
	case uint32(7):
		v342 = r0_3
	default:
		return machinePreparedReplayEntry()
	}
	{
		rr332 := int(v332) - 1
		if v332 < 1 || v332 > 160 || v332 != float64(int(v332)) {
			return machinePreparedReplayEntry()
		}
		switch rr332 / 32 {
		case 0:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v343 = ra0_3[rr332%32]
			vp343 = rap0_3[rr332%32]
		case 2:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v343 = ra2_3[rr332%32]
			vp343 = rap2_3[rr332%32]
		case 3:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v343 = ra3_3[rr332%32]
			vp343 = rap3_3[rr332%32]
		case 4:
			if rr332%32 >= 2 {
				return machinePreparedReplayEntry()
			}
			v343 = ra4_3[rr332%32]
			vp343 = rap4_3[rr332%32]
		default:
			return machinePreparedReplayEntry()
		}
	}
	if !vp343 {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v343) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v342) {
		return machinePreparedReplayEntry()
	}
	if !(v343 > v342) {
		goto b5
	}
	goto b10
b10:
	v344 = false
	v114 = v344
	goto b5
b11:
	if !v114 {
		goto b13
	}
	goto b12
b12:
	v345 = true
	if v111 < 1 || v111 > 4 {
		return machinePreparedReplayEntry()
	}
	v346 = ra1_3[int(v111)-1]
	switch v346 {
	case uint32(4):
		r1_0 = v345
		rp1_0 = true
	case uint32(5):
		r1_1 = v345
		rp1_1 = true
	case uint32(6):
		r1_2 = v345
		rp1_2 = true
	case uint32(19):
		r1_3 = v345
		rp1_3 = true
	case uint32(21):
		r1_4 = v345
		rp1_4 = true
	default:
		return machinePreparedReplayEntry()
	}
	v347 = r0_0
	if v111 < 1 || v111 > 4 {
		return machinePreparedReplayEntry()
	}
	v348 = ra1_2[int(v111)-1]
	v349 = v348 - math.Floor(v348/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v350 = v347 + v349
	r0_0 = v350
	v351 = math.Float64frombits(0x3ff0000000000000)
	v352 = r0_2
	v353 = v352 + v351
	r0_2 = v353
	v354 = r0_1
	if v111 < 1 || v111 > 4 {
		return machinePreparedReplayEntry()
	}
	v355 = ra1_2[int(v111)-1]
	v356 = math.Floor(v355 / math.Float64frombits(0x4008000000000000))
	v357 = v354 - v356
	r0_1 = v357
	if v111 < 1 || v111 > 4 {
		return machinePreparedReplayEntry()
	}
	v358 = ra1_2[int(v111)-1]
	v359 = v104 + v358
	v360 = r0_0
	v361 = v359 + v360
	v362 = r0_2
	v363 = v361 + v362
	v72 = v363
	v73 = v105
	v74 = v106
	v75 = v107
	goto b3
b13:
	v364 = math.Float64frombits(0x3ff0000000000000)
	v365 = r0_1
	v366 = v365 + v364
	r0_1 = v366
	v367 = r0_1
	v368 = v367 - math.Floor(v367/math.Float64frombits(0x401c000000000000))*math.Float64frombits(0x401c000000000000)
	v369 = v104 + v368
	v72 = v369
	v73 = v105
	v74 = v106
	v75 = v107
	goto b3
b14:
	v370 = v73 + v75
	v40 = v72
	v41 = v370
	v42 = v74
	v43 = v75
	goto b1
b15:
	v371 = math.Float64frombits(0x0000000000000000)
	v372 = r0_3
	if v372 < 1 || v372 > 1 {
		return machinePreparedReplayEntry()
	}
	switch int(v372) - 1 {
	case 0:
		v373 = r1_1
		vp373 = rp1_1
	default:
		return machinePreparedReplayEntry()
	}
	if !vp373 || !v373 {
		v136 = v40
		v159 = v371
		goto b17
	}
	goto b16
b16:
	v374 = math.Float64frombits(0x4024000000000000)
	v136 = v40
	v159 = v374
	goto b17
b17:
	v375 = r0_3
	if v375 < 1 || v375 > 1 {
		return machinePreparedReplayEntry()
	}
	switch int(v375) - 1 {
	case 0:
		v376 = r1_2
		vp376 = rp1_2
	default:
		return machinePreparedReplayEntry()
	}
	if !vp376 || !v376 {
		v168 = v136
		v191 = v159
		goto b19
	}
	goto b18
b18:
	v377 = v159 + math.Float64frombits(0x4034000000000000)
	v168 = v136
	v191 = v377
	goto b19
b19:
	v378 = r0_3
	if v378 < 1 || v378 > 1 {
		return machinePreparedReplayEntry()
	}
	switch int(v378) - 1 {
	case 0:
		v379 = r1_3
		vp379 = rp1_3
	default:
		return machinePreparedReplayEntry()
	}
	if !vp379 || !v379 {
		v200 = v168
		v223 = v191
		goto b21
	}
	goto b20
b20:
	v380 = v191 + math.Float64frombits(0x403e000000000000)
	v200 = v168
	v223 = v380
	goto b21
b21:
	v381 = r0_3
	if v381 < 1 || v381 > 1 {
		return machinePreparedReplayEntry()
	}
	switch int(v381) - 1 {
	case 0:
		v382 = r1_4
		vp382 = rp1_4
	default:
		return machinePreparedReplayEntry()
	}
	if !vp382 || !v382 {
		v232 = v200
		v255 = v223
		goto b23
	}
	goto b22
b22:
	v383 = v223 + math.Float64frombits(0x4044000000000000)
	v232 = v200
	v255 = v383
	goto b23
b23:
	v384 = v232
	v385 = v255
	v386 = v384 + v385
	v387 = r0_1
	v388 = v386 + v387
	v389 = r0_0
	v390 = v388 + v389
	v391 = r0_2
	v392 = v390 + v391
	return machinePreparedReturnOneNumber(v392)
}

func backendGeneratedDialogueConditionPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedDialogueConditionPreparedFixtureBody(context, p0)
}
