// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedExactRecursiveGuestBatchTargetProto2(u0 *float64, p0 float64) (float64, bool) {
	if u0 == nil || math.IsNaN(*u0) || math.IsInf(*u0, 0) {
		return 0, false
	}
	if math.IsNaN(p0) || p0 > 24 {
		return 0, false
	}
	return backendGeneratedExactRecursiveGuestBatchTargetProto2Body(u0, p0), true
}

func backendGeneratedExactRecursiveGuestBatchTargetProto2Body(u0 *float64, p0 float64) float64 {
	var v1 float64
	var v6 float64
	var v7 float64
	var v8 float64
	var v9 float64
	var v10 float64
	var v11 float64
	var v12 float64
	var v13 float64
	var v14 float64
	var v15 float64
	var v16 float64
	v1 = p0
	v6 = math.Float64frombits(0x4000000000000000)
	v7 = *u0
	v8 = v7 - math.Floor(v7/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v9 = v6 + v8
	if !(v1 < v9) {
		goto b2
	}
	goto b1
b1:
	return v1
b2:
	v10 = v1
	v11 = v10 - math.Float64frombits(0x3ff0000000000000)
	v12 = backendGeneratedExactRecursiveGuestBatchTargetProto2Body(u0, v11)
	v13 = v1
	v14 = v13 - math.Float64frombits(0x4000000000000000)
	v15 = backendGeneratedExactRecursiveGuestBatchTargetProto2Body(u0, v14)
	v16 = v12 + v15
	return v16
}
