// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedEconomyMarket(p0 float64) (float64, bool) {
	var v1 float64
	var v57 float64
	var v58 float64
	var v59 float64
	var v60 float64
	var v106 float64
	var v107 float64
	var v108 float64
	var v109 float64
	var v155 float64
	var v156 float64
	var v157 float64
	var v158 float64
	var v162 float64
	var v204 float64
	var v205 float64
	var v206 float64
	var v207 float64
	var v211 float64
	var v217 float64
	var v220 uint32
	var v224 float64
	var v253 float64
	var v254 float64
	var v255 float64
	var v256 float64
	var v260 float64
	var v269 uint32
	var v273 float64
	var v302 float64
	var v336 float64
	var v347 float64
	var v348 float64
	var v349 float64
	var v350 float64
	var v351 float64
	var v352 float64
	var v354 float64
	var v355 float64
	var v356 float64
	var v358 float64
	var v359 float64
	var v360 float64
	var v363 float64
	var v364 float64
	var v365 float64
	var v367 float64
	var v368 float64
	var v369 float64
	var v371 float64
	var v372 float64
	var v373 float64
	var v376 float64
	var v377 float64
	var v378 float64
	var v380 float64
	var v381 float64
	var v382 float64
	var v384 float64
	var v385 float64
	var v386 float64
	var v389 uint32
	var v390 float64
	var v391 uint32
	var v393 uint32
	var v394 float64
	var v395 uint32
	var v397 uint32
	var v398 float64
	var v399 uint32
	var v401 uint32
	var v402 float64
	var v403 uint32
	var v404 float64
	var v408 float64
	var v409 float64
	var v410 float64
	var v416 float64
	var v422 float64
	var v423 uint32
	var v424 uint32
	var v425 float64
	var vp425 bool
	_ = v425
	_ = vp425
	var v426 uint32
	var v427 float64
	var vp427 bool
	_ = v427
	_ = vp427
	var v428 float64
	var v429 float64
	var v430 uint32
	var v431 float64
	var vp431 bool
	_ = v431
	_ = vp431
	var v432 float64
	var v433 float64
	var v434 float64
	var v435 uint32
	var v436 float64
	var v437 float64
	var v438 float64
	var v439 float64
	var v440 uint32
	var v441 float64
	var vp441 bool
	_ = v441
	_ = vp441
	var v442 float64
	var v443 uint32
	var v444 float64
	var vp444 bool
	_ = v444
	_ = vp444
	var v445 float64
	var v446 float64
	var v447 uint32
	var v448 float64
	var v449 float64
	var v450 float64
	var v451 float64
	var v452 float64
	var v453 float64
	var v454 float64
	var v455 float64
	var v456 uint32
	var v457 float64
	var vp457 bool
	_ = v457
	_ = vp457
	var v458 float64
	var v459 float64
	var v460 uint32
	var v461 float64
	var v462 float64
	var v463 float64
	var v464 float64
	var v465 float64
	var v466 float64
	var v467 float64
	var v468 float64
	var v469 uint32
	var v470 float64
	var v471 float64
	var v477 float64
	var v478 float64
	var v479 float64
	var vp479 bool
	_ = v479
	_ = vp479
	var v480 float64
	var v481 float64
	var v482 float64
	var vp482 bool
	_ = v482
	_ = vp482
	var v483 float64
	var v484 float64
	var v485 float64
	var v486 float64
	var vp486 bool
	_ = v486
	_ = vp486
	var v487 float64
	var v488 float64
	var v489 float64
	var v490 float64
	var r0_0 float64
	_ = r0_0
	var rp0_0 bool
	_ = rp0_0
	var r0_1 float64
	_ = r0_1
	var rp0_1 bool
	_ = rp0_1
	var r0_2 float64
	_ = r0_2
	var rp0_2 bool
	_ = rp0_2
	var r1_0 float64
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r2_0 float64
	_ = r2_0
	var rp2_0 bool
	_ = rp2_0
	var r2_1 float64
	_ = r2_1
	var rp2_1 bool
	_ = rp2_1
	var r2_2 float64
	_ = r2_2
	var rp2_2 bool
	_ = rp2_2
	var r3_0 float64
	_ = r3_0
	var rp3_0 bool
	_ = rp3_0
	var r3_1 float64
	_ = r3_1
	var rp3_1 bool
	_ = rp3_1
	var r3_2 float64
	_ = r3_2
	var rp3_2 bool
	_ = rp3_2
	var r4_0 float64
	_ = r4_0
	var rp4_0 bool
	_ = rp4_0
	var r4_1 float64
	_ = r4_1
	var rp4_1 bool
	_ = rp4_1
	var r4_2 float64
	_ = r4_2
	var rp4_2 bool
	_ = rp4_2
	var r5_0 float64
	_ = r5_0
	var r5_1 float64
	_ = r5_1
	var r5_2 float64
	_ = r5_2
	var r6_0 float64
	_ = r6_0
	var rp6_0 bool
	_ = rp6_0
	var r6_1 float64
	_ = r6_1
	var rp6_1 bool
	_ = rp6_1
	var r6_2 float64
	_ = r6_2
	var rp6_2 bool
	_ = rp6_2
	var r7_0 float64
	_ = r7_0
	var rp7_0 bool
	_ = rp7_0
	var r7_1 float64
	_ = r7_1
	var rp7_1 bool
	_ = rp7_1
	var r7_2 float64
	_ = r7_2
	var rp7_2 bool
	_ = rp7_2
	var r8_0 float64
	_ = r8_0
	var rp8_0 bool
	_ = rp8_0
	var r8_1 float64
	_ = r8_1
	var rp8_1 bool
	_ = rp8_1
	var r8_2 float64
	_ = r8_2
	var rp8_2 bool
	_ = rp8_2
	var r9_0 float64
	_ = r9_0
	var r9_1 float64
	_ = r9_1
	var r9_2 float64
	_ = r9_2
	var r10_0 float64
	_ = r10_0
	var rp10_0 bool
	_ = rp10_0
	var r10_1 float64
	_ = r10_1
	var rp10_1 bool
	_ = rp10_1
	var r10_2 float64
	_ = r10_2
	var rp10_2 bool
	_ = rp10_2
	var r11_0 float64
	_ = r11_0
	var rp11_0 bool
	_ = rp11_0
	var r11_1 float64
	_ = r11_1
	var rp11_1 bool
	_ = rp11_1
	var r11_2 float64
	_ = r11_2
	var rp11_2 bool
	_ = rp11_2
	var r12_0 uint32
	_ = r12_0
	var r12_1 float64
	_ = r12_1
	var r12_2 uint32
	_ = r12_2
	var r13_0 uint32
	_ = r13_0
	var r13_1 float64
	_ = r13_1
	var r13_2 uint32
	_ = r13_2
	var r14_0 uint32
	_ = r14_0
	var r14_1 float64
	_ = r14_1
	var r14_2 uint32
	_ = r14_2
	var r15_0 uint32
	_ = r15_0
	var r15_1 float64
	_ = r15_1
	var r15_2 uint32
	_ = r15_2
	var ra0_0 [3]float64
	var ra0_1 [3]float64
	var ra0_2 [3]float64
	var ri0 int
	_ = ri0
	var ra1_0 [4]uint32
	var ra1_1 [4]float64
	var ra1_2 [4]uint32
	var ri1 int
	_ = ri1
	v1 = p0
	v347 = math.Float64frombits(0x4044000000000000)
	v348 = v1
	v349 = v348 - math.Floor(v348/math.Float64frombits(0x401c000000000000))*math.Float64frombits(0x401c000000000000)
	v350 = v347 + v349
	r0_0 = v350
	rp0_0 = true
	v351 = math.Float64frombits(0x4032000000000000)
	r0_1 = v351
	rp0_1 = true
	v352 = math.Float64frombits(0x403e000000000000)
	r0_2 = v352
	rp0_2 = true
	r1_0 = 1
	v354 = math.Float64frombits(0x4020000000000000)
	r2_0 = v354
	rp2_0 = true
	v355 = math.Float64frombits(0x402c000000000000)
	r2_1 = v355
	rp2_1 = true
	v356 = math.Float64frombits(0x4018000000000000)
	r2_2 = v356
	rp2_2 = true
	r1_1 = 1
	v358 = math.Float64frombits(0x4008000000000000)
	r3_0 = v358
	rp3_0 = true
	v359 = math.Float64frombits(0x4022000000000000)
	r3_1 = v359
	rp3_1 = true
	v360 = math.Float64frombits(0x4010000000000000)
	r3_2 = v360
	rp3_2 = true
	r1_2 = 1
	ra0_0[0] = r1_0
	ra0_1[0] = r1_1
	ra0_2[0] = r1_2
	v363 = math.Float64frombits(0x4028000000000000)
	r4_0 = v363
	rp4_0 = true
	v364 = math.Float64frombits(0x4041800000000000)
	r4_1 = v364
	rp4_1 = true
	v365 = math.Float64frombits(0x4034000000000000)
	r4_2 = v365
	rp4_2 = true
	r5_0 = 2
	v367 = math.Float64frombits(0x402e000000000000)
	r6_0 = v367
	rp6_0 = true
	v368 = math.Float64frombits(0x4014000000000000)
	r6_1 = v368
	rp6_1 = true
	v369 = math.Float64frombits(0x4024000000000000)
	r6_2 = v369
	rp6_2 = true
	r5_1 = 2
	v371 = math.Float64frombits(0x4014000000000000)
	r7_0 = v371
	rp7_0 = true
	v372 = math.Float64frombits(0x401c000000000000)
	r7_1 = v372
	rp7_1 = true
	v373 = math.Float64frombits(0x4018000000000000)
	r7_2 = v373
	rp7_2 = true
	r5_2 = 2
	ra0_0[1] = r5_0
	ra0_1[1] = r5_1
	ra0_2[1] = r5_2
	v376 = math.Float64frombits(0x4039000000000000)
	r8_0 = v376
	rp8_0 = true
	v377 = math.Float64frombits(0x4026000000000000)
	r8_1 = v377
	rp8_1 = true
	v378 = math.Float64frombits(0x4049000000000000)
	r8_2 = v378
	rp8_2 = true
	r9_0 = 3
	v380 = math.Float64frombits(0x4024000000000000)
	r10_0 = v380
	rp10_0 = true
	v381 = math.Float64frombits(0x4032000000000000)
	r10_1 = v381
	rp10_1 = true
	v382 = math.Float64frombits(0x4010000000000000)
	r10_2 = v382
	rp10_2 = true
	r9_1 = 3
	v384 = math.Float64frombits(0x4010000000000000)
	r11_0 = v384
	rp11_0 = true
	v385 = math.Float64frombits(0x4024000000000000)
	r11_1 = v385
	rp11_1 = true
	v386 = math.Float64frombits(0x4008000000000000)
	r11_2 = v386
	rp11_2 = true
	r9_2 = 3
	ra0_0[2] = r9_0
	ra0_1[2] = r9_1
	ra0_2[2] = r9_2
	v389 = uint32(1)
	r12_0 = v389
	v390 = math.Float64frombits(0x401c000000000000)
	r12_1 = v390
	v391 = uint32(9)
	r12_2 = v391
	ra1_0[0] = r12_0
	ra1_1[0] = r12_1
	ra1_2[0] = r12_2
	v393 = uint32(2)
	r13_0 = v393
	v394 = math.Float64frombits(0x4010000000000000)
	r13_1 = v394
	v395 = uint32(9)
	r13_2 = v395
	ra1_0[1] = r13_0
	ra1_1[1] = r13_1
	ra1_2[1] = r13_2
	v397 = uint32(3)
	r14_0 = v397
	v398 = math.Float64frombits(0x4022000000000000)
	r14_1 = v398
	v399 = uint32(11)
	r14_2 = v399
	ra1_0[2] = r14_0
	ra1_1[2] = r14_1
	ra1_2[2] = r14_2
	v401 = uint32(2)
	r15_0 = v401
	v402 = math.Float64frombits(0x4008000000000000)
	r15_1 = v402
	v403 = uint32(11)
	r15_2 = v403
	ra1_0[3] = r15_0
	ra1_1[3] = r15_1
	ra1_2[3] = r15_2
	v404 = math.Float64frombits(0x0000000000000000)
	v408 = math.Float64frombits(0x3ff0000000000000)
	v409 = math.Float64frombits(0x404b000000000000)
	v410 = math.Float64frombits(0x3ff0000000000000)
	v57 = v404
	v58 = v408
	v59 = v409
	v60 = v410
	goto b1
b1:
	if math.IsNaN(v58) {
		return 0, false
	}
	if math.IsNaN(v59) {
		return 0, false
	}
	if math.IsNaN(v60) {
		return 0, false
	}
	if (v60 > 0 && v58 > v59) || (v60 <= 0 && v58 < v59) {
		goto b13
	}
	goto b2
b2:
	ri0 = 0
	v106 = v57
	v107 = v58
	v108 = v59
	v109 = v60
	goto b3
b3:
	if ri0 >= 3 {
		goto b12
	}
	v416 = float64(ri0 + 1)
	ri0++
	goto b4
b4:
	ri1 = 0
	v155 = v106
	v156 = v107
	v157 = v108
	v158 = v109
	v162 = v416
	goto b5
b5:
	if ri1 >= 4 {
		v106 = v155
		v107 = v156
		v108 = v157
		v109 = v158
		goto b3
	}
	v422 = float64(ri1 + 1)
	ri1++
	goto b6
b6:
	if v422 < 1 || v422 > 4 {
		return 0, false
	}
	v423 = ra1_0[int(v422)-1]
	v424 = v423
	if v162 < 1 || v162 > 3 {
		return 0, false
	}
	switch int(v162) - 1 {
	case 0:
		switch v424 {
		case uint32(1):
			v425 = r2_0
			vp425 = rp2_0
		case uint32(2):
			v425 = r2_1
			vp425 = rp2_1
		case uint32(3):
			v425 = r2_2
			vp425 = rp2_2
		default:
			return 0, false
		}
	case 1:
		switch v424 {
		case uint32(1):
			v425 = r6_0
			vp425 = rp6_0
		case uint32(2):
			v425 = r6_1
			vp425 = rp6_1
		case uint32(3):
			v425 = r6_2
			vp425 = rp6_2
		default:
			return 0, false
		}
	case 2:
		switch v424 {
		case uint32(1):
			v425 = r10_0
			vp425 = rp10_0
		case uint32(2):
			v425 = r10_1
			vp425 = rp10_1
		case uint32(3):
			v425 = r10_2
			vp425 = rp10_2
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	v426 = v423
	if v162 < 1 || v162 > 3 {
		return 0, false
	}
	switch int(v162) - 1 {
	case 0:
		switch v426 {
		case uint32(1):
			v427 = r0_0
			vp427 = rp0_0
		case uint32(2):
			v427 = r0_1
			vp427 = rp0_1
		case uint32(3):
			v427 = r0_2
			vp427 = rp0_2
		default:
			return 0, false
		}
	case 1:
		switch v426 {
		case uint32(1):
			v427 = r4_0
			vp427 = rp4_0
		case uint32(2):
			v427 = r4_1
			vp427 = rp4_1
		case uint32(3):
			v427 = r4_2
			vp427 = rp4_2
		default:
			return 0, false
		}
	case 2:
		switch v426 {
		case uint32(1):
			v427 = r8_0
			vp427 = rp8_0
		case uint32(2):
			v427 = r8_1
			vp427 = rp8_1
		case uint32(3):
			v427 = r8_2
			vp427 = rp8_2
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	if !vp427 {
		return 0, false
	}
	v428 = math.Floor(v427 / math.Float64frombits(0x4014000000000000))
	if !vp425 {
		return 0, false
	}
	v429 = v425 - v428
	v430 = v423
	if v162 < 1 || v162 > 3 {
		return 0, false
	}
	switch int(v162) - 1 {
	case 0:
		switch v430 {
		case uint32(1):
			v431 = r3_0
			vp431 = rp3_0
		case uint32(2):
			v431 = r3_1
			vp431 = rp3_1
		case uint32(3):
			v431 = r3_2
			vp431 = rp3_2
		default:
			return 0, false
		}
	case 1:
		switch v430 {
		case uint32(1):
			v431 = r7_0
			vp431 = rp7_0
		case uint32(2):
			v431 = r7_1
			vp431 = rp7_1
		case uint32(3):
			v431 = r7_2
			vp431 = rp7_2
		default:
			return 0, false
		}
	case 2:
		switch v430 {
		case uint32(1):
			v431 = r11_0
			vp431 = rp11_0
		case uint32(2):
			v431 = r11_1
			vp431 = rp11_1
		case uint32(3):
			v431 = r11_2
			vp431 = rp11_2
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	v432 = v429
	if !vp431 {
		return 0, false
	}
	v433 = v431 + v432
	if math.IsNaN(v433) {
		return 0, false
	}
	if !(v433 < math.Float64frombits(0x3ff0000000000000)) {
		v204 = v155
		v205 = v156
		v206 = v157
		v207 = v158
		v211 = v162
		v217 = v422
		v220 = v423
		v224 = v433
		goto b8
	}
	goto b7
b7:
	v434 = math.Float64frombits(0x3ff0000000000000)
	v204 = v155
	v205 = v156
	v206 = v157
	v207 = v158
	v211 = v162
	v217 = v422
	v220 = v423
	v224 = v434
	goto b8
b8:
	if v217 < 1 || v217 > 4 {
		return 0, false
	}
	v435 = ra1_2[int(v217)-1]
	if v435 != uint32(9) {
		goto b10
	}
	goto b9
b9:
	if v217 < 1 || v217 > 4 {
		return 0, false
	}
	v436 = ra1_1[int(v217)-1]
	v437 = v205
	v438 = v437 - math.Floor(v437/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v439 = v436 + v438
	v440 = v220
	if v211 < 1 || v211 > 3 {
		return 0, false
	}
	switch int(v211) - 1 {
	case 0:
		switch v440 {
		case uint32(1):
			v441 = r0_0
			vp441 = rp0_0
		case uint32(2):
			v441 = r0_1
			vp441 = rp0_1
		case uint32(3):
			v441 = r0_2
			vp441 = rp0_2
		default:
			return 0, false
		}
	case 1:
		switch v440 {
		case uint32(1):
			v441 = r4_0
			vp441 = rp4_0
		case uint32(2):
			v441 = r4_1
			vp441 = rp4_1
		case uint32(3):
			v441 = r4_2
			vp441 = rp4_2
		default:
			return 0, false
		}
	case 2:
		switch v440 {
		case uint32(1):
			v441 = r8_0
			vp441 = rp8_0
		case uint32(2):
			v441 = r8_1
			vp441 = rp8_1
		case uint32(3):
			v441 = r8_2
			vp441 = rp8_2
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	v442 = v439
	if !vp441 {
		return 0, false
	}
	v442 = math.Min(v442, v441)
	v443 = v220
	if v211 < 1 || v211 > 3 {
		return 0, false
	}
	switch int(v211) - 1 {
	case 0:
		switch v443 {
		case uint32(1):
			v444 = r0_0
			vp444 = rp0_0
		case uint32(2):
			v444 = r0_1
			vp444 = rp0_1
		case uint32(3):
			v444 = r0_2
			vp444 = rp0_2
		default:
			return 0, false
		}
	case 1:
		switch v443 {
		case uint32(1):
			v444 = r4_0
			vp444 = rp4_0
		case uint32(2):
			v444 = r4_1
			vp444 = rp4_1
		case uint32(3):
			v444 = r4_2
			vp444 = rp4_2
		default:
			return 0, false
		}
	case 2:
		switch v443 {
		case uint32(1):
			v444 = r8_0
			vp444 = rp8_0
		case uint32(2):
			v444 = r8_1
			vp444 = rp8_1
		case uint32(3):
			v444 = r8_2
			vp444 = rp8_2
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	v445 = v442
	if !vp444 {
		return 0, false
	}
	v446 = v444 - v445
	v447 = v220
	if v211 < 1 || v211 > 3 {
		return 0, false
	}
	switch int(v211) - 1 {
	case 0:
		switch v447 {
		case uint32(1):
			r0_0 = v446
			rp0_0 = true
		case uint32(2):
			r0_1 = v446
			rp0_1 = true
		case uint32(3):
			r0_2 = v446
			rp0_2 = true
		default:
			return 0, false
		}
	case 1:
		switch v447 {
		case uint32(1):
			r4_0 = v446
			rp4_0 = true
		case uint32(2):
			r4_1 = v446
			rp4_1 = true
		case uint32(3):
			r4_2 = v446
			rp4_2 = true
		default:
			return 0, false
		}
	case 2:
		switch v447 {
		case uint32(1):
			r8_0 = v446
			rp8_0 = true
		case uint32(2):
			r8_1 = v446
			rp8_1 = true
		case uint32(3):
			r8_2 = v446
			rp8_2 = true
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	v448 = v442
	v449 = v224
	v450 = v448 * v449
	v451 = v204 - v450
	v253 = v451
	v254 = v205
	v255 = v206
	v256 = v207
	v260 = v211
	v269 = v220
	v273 = v224
	goto b11
b10:
	if v217 < 1 || v217 > 4 {
		return 0, false
	}
	v452 = ra1_1[int(v217)-1]
	v453 = v205
	v454 = v453 - math.Floor(v453/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v455 = v452 + v454
	v456 = v220
	if v211 < 1 || v211 > 3 {
		return 0, false
	}
	switch int(v211) - 1 {
	case 0:
		switch v456 {
		case uint32(1):
			v457 = r0_0
			vp457 = rp0_0
		case uint32(2):
			v457 = r0_1
			vp457 = rp0_1
		case uint32(3):
			v457 = r0_2
			vp457 = rp0_2
		default:
			return 0, false
		}
	case 1:
		switch v456 {
		case uint32(1):
			v457 = r4_0
			vp457 = rp4_0
		case uint32(2):
			v457 = r4_1
			vp457 = rp4_1
		case uint32(3):
			v457 = r4_2
			vp457 = rp4_2
		default:
			return 0, false
		}
	case 2:
		switch v456 {
		case uint32(1):
			v457 = r8_0
			vp457 = rp8_0
		case uint32(2):
			v457 = r8_1
			vp457 = rp8_1
		case uint32(3):
			v457 = r8_2
			vp457 = rp8_2
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	v458 = v455
	if !vp457 {
		return 0, false
	}
	v459 = v457 + v458
	v460 = v220
	if v211 < 1 || v211 > 3 {
		return 0, false
	}
	switch int(v211) - 1 {
	case 0:
		switch v460 {
		case uint32(1):
			r0_0 = v459
			rp0_0 = true
		case uint32(2):
			r0_1 = v459
			rp0_1 = true
		case uint32(3):
			r0_2 = v459
			rp0_2 = true
		default:
			return 0, false
		}
	case 1:
		switch v460 {
		case uint32(1):
			r4_0 = v459
			rp4_0 = true
		case uint32(2):
			r4_1 = v459
			rp4_1 = true
		case uint32(3):
			r4_2 = v459
			rp4_2 = true
		default:
			return 0, false
		}
	case 2:
		switch v460 {
		case uint32(1):
			r8_0 = v459
			rp8_0 = true
		case uint32(2):
			r8_1 = v459
			rp8_1 = true
		case uint32(3):
			r8_2 = v459
			rp8_2 = true
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	v461 = v455
	v462 = v224
	v463 = v461 * v462
	v464 = v204 + v463
	v253 = v464
	v254 = v205
	v255 = v206
	v256 = v207
	v260 = v211
	v269 = v220
	v273 = v224
	goto b11
b11:
	v465 = v273
	v466 = v254
	v467 = v466 - math.Floor(v466/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v468 = v465 + v467
	v469 = v269
	if v260 < 1 || v260 > 3 {
		return 0, false
	}
	switch int(v260) - 1 {
	case 0:
		switch v469 {
		case uint32(1):
			r3_0 = v468
			rp3_0 = true
		case uint32(2):
			r3_1 = v468
			rp3_1 = true
		case uint32(3):
			r3_2 = v468
			rp3_2 = true
		default:
			return 0, false
		}
	case 1:
		switch v469 {
		case uint32(1):
			r7_0 = v468
			rp7_0 = true
		case uint32(2):
			r7_1 = v468
			rp7_1 = true
		case uint32(3):
			r7_2 = v468
			rp7_2 = true
		default:
			return 0, false
		}
	case 2:
		switch v469 {
		case uint32(1):
			r11_0 = v468
			rp11_0 = true
		case uint32(2):
			r11_1 = v468
			rp11_1 = true
		case uint32(3):
			r11_2 = v468
			rp11_2 = true
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	v155 = v253
	v156 = v254
	v157 = v255
	v158 = v256
	v162 = v260
	goto b5
b12:
	v470 = v107 + v109
	v57 = v106
	v58 = v470
	v59 = v108
	v60 = v109
	goto b1
b13:
	v471 = math.Float64frombits(0x0000000000000000)
	ri0 = 0
	v302 = v57
	v336 = v471
	goto b14
b14:
	if ri0 >= 3 {
		goto b16
	}
	v477 = float64(ri0 + 1)
	ri0++
	goto b15
b15:
	if v477 < 1 || v477 > 3 {
		return 0, false
	}
	v478 = ra0_0[int(v477)-1]
	if v478 < 1 || v478 > 3 {
		return 0, false
	}
	switch int(v478) - 1 {
	case 0:
		v479 = r0_0
		vp479 = rp0_0
	case 1:
		v479 = r4_0
		vp479 = rp4_0
	case 2:
		v479 = r8_0
		vp479 = rp8_0
	default:
		return 0, false
	}
	if !vp479 {
		return 0, false
	}
	v480 = v336 + v479
	if v477 < 1 || v477 > 3 {
		return 0, false
	}
	v481 = ra0_0[int(v477)-1]
	if v481 < 1 || v481 > 3 {
		return 0, false
	}
	switch int(v481) - 1 {
	case 0:
		v482 = r0_1
		vp482 = rp0_1
	case 1:
		v482 = r4_1
		vp482 = rp4_1
	case 2:
		v482 = r8_1
		vp482 = rp8_1
	default:
		return 0, false
	}
	if !vp482 {
		return 0, false
	}
	v483 = v482 * math.Float64frombits(0x4000000000000000)
	v484 = v480 + v483
	if v477 < 1 || v477 > 3 {
		return 0, false
	}
	v485 = ra0_0[int(v477)-1]
	if v485 < 1 || v485 > 3 {
		return 0, false
	}
	switch int(v485) - 1 {
	case 0:
		v486 = r0_2
		vp486 = rp0_2
	case 1:
		v486 = r4_2
		vp486 = rp4_2
	case 2:
		v486 = r8_2
		vp486 = rp8_2
	default:
		return 0, false
	}
	if !vp486 {
		return 0, false
	}
	v487 = v484 + v486
	v302 = v302
	v336 = v487
	goto b14
b16:
	v488 = v302
	v489 = v336
	v490 = v488 + v489
	return v490, true
}

func backendGeneratedEconomyMarketPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v57 float64
	var v58 float64
	var v59 float64
	var v60 float64
	var v106 float64
	var v107 float64
	var v108 float64
	var v109 float64
	var v155 float64
	var v156 float64
	var v157 float64
	var v158 float64
	var v162 float64
	var v204 float64
	var v205 float64
	var v206 float64
	var v207 float64
	var v211 float64
	var v217 float64
	var v220 uint32
	var v224 float64
	var v253 float64
	var v254 float64
	var v255 float64
	var v256 float64
	var v260 float64
	var v269 uint32
	var v273 float64
	var v302 float64
	var v336 float64
	var v347 float64
	var v348 float64
	var v349 float64
	var v350 float64
	var v351 float64
	var v352 float64
	var v354 float64
	var v355 float64
	var v356 float64
	var v358 float64
	var v359 float64
	var v360 float64
	var v363 float64
	var v364 float64
	var v365 float64
	var v367 float64
	var v368 float64
	var v369 float64
	var v371 float64
	var v372 float64
	var v373 float64
	var v376 float64
	var v377 float64
	var v378 float64
	var v380 float64
	var v381 float64
	var v382 float64
	var v384 float64
	var v385 float64
	var v386 float64
	var v389 uint32
	var v390 float64
	var v391 uint32
	var v393 uint32
	var v394 float64
	var v395 uint32
	var v397 uint32
	var v398 float64
	var v399 uint32
	var v401 uint32
	var v402 float64
	var v403 uint32
	var v404 float64
	var v408 float64
	var v409 float64
	var v410 float64
	var v416 float64
	var v422 float64
	var v423 uint32
	var v424 uint32
	var v425 float64
	var vp425 bool
	_ = v425
	_ = vp425
	var v426 uint32
	var v427 float64
	var vp427 bool
	_ = v427
	_ = vp427
	var v428 float64
	var v429 float64
	var v430 uint32
	var v431 float64
	var vp431 bool
	_ = v431
	_ = vp431
	var v432 float64
	var v433 float64
	var v434 float64
	var v435 uint32
	var v436 float64
	var v437 float64
	var v438 float64
	var v439 float64
	var v440 uint32
	var v441 float64
	var vp441 bool
	_ = v441
	_ = vp441
	var v442 float64
	var v443 uint32
	var v444 float64
	var vp444 bool
	_ = v444
	_ = vp444
	var v445 float64
	var v446 float64
	var v447 uint32
	var v448 float64
	var v449 float64
	var v450 float64
	var v451 float64
	var v452 float64
	var v453 float64
	var v454 float64
	var v455 float64
	var v456 uint32
	var v457 float64
	var vp457 bool
	_ = v457
	_ = vp457
	var v458 float64
	var v459 float64
	var v460 uint32
	var v461 float64
	var v462 float64
	var v463 float64
	var v464 float64
	var v465 float64
	var v466 float64
	var v467 float64
	var v468 float64
	var v469 uint32
	var v470 float64
	var v471 float64
	var v477 float64
	var v478 float64
	var v479 float64
	var vp479 bool
	_ = v479
	_ = vp479
	var v480 float64
	var v481 float64
	var v482 float64
	var vp482 bool
	_ = v482
	_ = vp482
	var v483 float64
	var v484 float64
	var v485 float64
	var v486 float64
	var vp486 bool
	_ = v486
	_ = vp486
	var v487 float64
	var v488 float64
	var v489 float64
	var v490 float64
	var r0_0 float64
	_ = r0_0
	var rp0_0 bool
	_ = rp0_0
	var r0_1 float64
	_ = r0_1
	var rp0_1 bool
	_ = rp0_1
	var r0_2 float64
	_ = r0_2
	var rp0_2 bool
	_ = rp0_2
	var r1_0 float64
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r2_0 float64
	_ = r2_0
	var rp2_0 bool
	_ = rp2_0
	var r2_1 float64
	_ = r2_1
	var rp2_1 bool
	_ = rp2_1
	var r2_2 float64
	_ = r2_2
	var rp2_2 bool
	_ = rp2_2
	var r3_0 float64
	_ = r3_0
	var rp3_0 bool
	_ = rp3_0
	var r3_1 float64
	_ = r3_1
	var rp3_1 bool
	_ = rp3_1
	var r3_2 float64
	_ = r3_2
	var rp3_2 bool
	_ = rp3_2
	var r4_0 float64
	_ = r4_0
	var rp4_0 bool
	_ = rp4_0
	var r4_1 float64
	_ = r4_1
	var rp4_1 bool
	_ = rp4_1
	var r4_2 float64
	_ = r4_2
	var rp4_2 bool
	_ = rp4_2
	var r5_0 float64
	_ = r5_0
	var r5_1 float64
	_ = r5_1
	var r5_2 float64
	_ = r5_2
	var r6_0 float64
	_ = r6_0
	var rp6_0 bool
	_ = rp6_0
	var r6_1 float64
	_ = r6_1
	var rp6_1 bool
	_ = rp6_1
	var r6_2 float64
	_ = r6_2
	var rp6_2 bool
	_ = rp6_2
	var r7_0 float64
	_ = r7_0
	var rp7_0 bool
	_ = rp7_0
	var r7_1 float64
	_ = r7_1
	var rp7_1 bool
	_ = rp7_1
	var r7_2 float64
	_ = r7_2
	var rp7_2 bool
	_ = rp7_2
	var r8_0 float64
	_ = r8_0
	var rp8_0 bool
	_ = rp8_0
	var r8_1 float64
	_ = r8_1
	var rp8_1 bool
	_ = rp8_1
	var r8_2 float64
	_ = r8_2
	var rp8_2 bool
	_ = rp8_2
	var r9_0 float64
	_ = r9_0
	var r9_1 float64
	_ = r9_1
	var r9_2 float64
	_ = r9_2
	var r10_0 float64
	_ = r10_0
	var rp10_0 bool
	_ = rp10_0
	var r10_1 float64
	_ = r10_1
	var rp10_1 bool
	_ = rp10_1
	var r10_2 float64
	_ = r10_2
	var rp10_2 bool
	_ = rp10_2
	var r11_0 float64
	_ = r11_0
	var rp11_0 bool
	_ = rp11_0
	var r11_1 float64
	_ = r11_1
	var rp11_1 bool
	_ = rp11_1
	var r11_2 float64
	_ = r11_2
	var rp11_2 bool
	_ = rp11_2
	var r12_0 uint32
	_ = r12_0
	var r12_1 float64
	_ = r12_1
	var r12_2 uint32
	_ = r12_2
	var r13_0 uint32
	_ = r13_0
	var r13_1 float64
	_ = r13_1
	var r13_2 uint32
	_ = r13_2
	var r14_0 uint32
	_ = r14_0
	var r14_1 float64
	_ = r14_1
	var r14_2 uint32
	_ = r14_2
	var r15_0 uint32
	_ = r15_0
	var r15_1 float64
	_ = r15_1
	var r15_2 uint32
	_ = r15_2
	var ra0_0 [3]float64
	var ra0_1 [3]float64
	var ra0_2 [3]float64
	var ri0 int
	_ = ri0
	var ra1_0 [4]uint32
	var ra1_1 [4]float64
	var ra1_2 [4]uint32
	var ri1 int
	_ = ri1
	v1 = p0
	v347 = math.Float64frombits(0x4044000000000000)
	v348 = v1
	v349 = v348 - math.Floor(v348/math.Float64frombits(0x401c000000000000))*math.Float64frombits(0x401c000000000000)
	v350 = v347 + v349
	r0_0 = v350
	rp0_0 = true
	v351 = math.Float64frombits(0x4032000000000000)
	r0_1 = v351
	rp0_1 = true
	v352 = math.Float64frombits(0x403e000000000000)
	r0_2 = v352
	rp0_2 = true
	r1_0 = 1
	v354 = math.Float64frombits(0x4020000000000000)
	r2_0 = v354
	rp2_0 = true
	v355 = math.Float64frombits(0x402c000000000000)
	r2_1 = v355
	rp2_1 = true
	v356 = math.Float64frombits(0x4018000000000000)
	r2_2 = v356
	rp2_2 = true
	r1_1 = 1
	v358 = math.Float64frombits(0x4008000000000000)
	r3_0 = v358
	rp3_0 = true
	v359 = math.Float64frombits(0x4022000000000000)
	r3_1 = v359
	rp3_1 = true
	v360 = math.Float64frombits(0x4010000000000000)
	r3_2 = v360
	rp3_2 = true
	r1_2 = 1
	ra0_0[0] = r1_0
	ra0_1[0] = r1_1
	ra0_2[0] = r1_2
	v363 = math.Float64frombits(0x4028000000000000)
	r4_0 = v363
	rp4_0 = true
	v364 = math.Float64frombits(0x4041800000000000)
	r4_1 = v364
	rp4_1 = true
	v365 = math.Float64frombits(0x4034000000000000)
	r4_2 = v365
	rp4_2 = true
	r5_0 = 2
	v367 = math.Float64frombits(0x402e000000000000)
	r6_0 = v367
	rp6_0 = true
	v368 = math.Float64frombits(0x4014000000000000)
	r6_1 = v368
	rp6_1 = true
	v369 = math.Float64frombits(0x4024000000000000)
	r6_2 = v369
	rp6_2 = true
	r5_1 = 2
	v371 = math.Float64frombits(0x4014000000000000)
	r7_0 = v371
	rp7_0 = true
	v372 = math.Float64frombits(0x401c000000000000)
	r7_1 = v372
	rp7_1 = true
	v373 = math.Float64frombits(0x4018000000000000)
	r7_2 = v373
	rp7_2 = true
	r5_2 = 2
	ra0_0[1] = r5_0
	ra0_1[1] = r5_1
	ra0_2[1] = r5_2
	v376 = math.Float64frombits(0x4039000000000000)
	r8_0 = v376
	rp8_0 = true
	v377 = math.Float64frombits(0x4026000000000000)
	r8_1 = v377
	rp8_1 = true
	v378 = math.Float64frombits(0x4049000000000000)
	r8_2 = v378
	rp8_2 = true
	r9_0 = 3
	v380 = math.Float64frombits(0x4024000000000000)
	r10_0 = v380
	rp10_0 = true
	v381 = math.Float64frombits(0x4032000000000000)
	r10_1 = v381
	rp10_1 = true
	v382 = math.Float64frombits(0x4010000000000000)
	r10_2 = v382
	rp10_2 = true
	r9_1 = 3
	v384 = math.Float64frombits(0x4010000000000000)
	r11_0 = v384
	rp11_0 = true
	v385 = math.Float64frombits(0x4024000000000000)
	r11_1 = v385
	rp11_1 = true
	v386 = math.Float64frombits(0x4008000000000000)
	r11_2 = v386
	rp11_2 = true
	r9_2 = 3
	ra0_0[2] = r9_0
	ra0_1[2] = r9_1
	ra0_2[2] = r9_2
	v389 = uint32(1)
	r12_0 = v389
	v390 = math.Float64frombits(0x401c000000000000)
	r12_1 = v390
	v391 = uint32(9)
	r12_2 = v391
	ra1_0[0] = r12_0
	ra1_1[0] = r12_1
	ra1_2[0] = r12_2
	v393 = uint32(2)
	r13_0 = v393
	v394 = math.Float64frombits(0x4010000000000000)
	r13_1 = v394
	v395 = uint32(9)
	r13_2 = v395
	ra1_0[1] = r13_0
	ra1_1[1] = r13_1
	ra1_2[1] = r13_2
	v397 = uint32(3)
	r14_0 = v397
	v398 = math.Float64frombits(0x4022000000000000)
	r14_1 = v398
	v399 = uint32(11)
	r14_2 = v399
	ra1_0[2] = r14_0
	ra1_1[2] = r14_1
	ra1_2[2] = r14_2
	v401 = uint32(2)
	r15_0 = v401
	v402 = math.Float64frombits(0x4008000000000000)
	r15_1 = v402
	v403 = uint32(11)
	r15_2 = v403
	ra1_0[3] = r15_0
	ra1_1[3] = r15_1
	ra1_2[3] = r15_2
	v404 = math.Float64frombits(0x0000000000000000)
	v408 = math.Float64frombits(0x3ff0000000000000)
	v409 = math.Float64frombits(0x404b000000000000)
	v410 = math.Float64frombits(0x3ff0000000000000)
	v57 = v404
	v58 = v408
	v59 = v409
	v60 = v410
	goto b1
b1:
	if math.IsNaN(v58) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v59) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v60) {
		return machinePreparedReplayEntry()
	}
	if (v60 > 0 && v58 > v59) || (v60 <= 0 && v58 < v59) {
		goto b13
	}
	goto b2
b2:
	ri0 = 0
	v106 = v57
	v107 = v58
	v108 = v59
	v109 = v60
	goto b3
b3:
	if ri0 >= 3 {
		goto b12
	}
	v416 = float64(ri0 + 1)
	ri0++
	goto b4
b4:
	ri1 = 0
	v155 = v106
	v156 = v107
	v157 = v108
	v158 = v109
	v162 = v416
	goto b5
b5:
	if ri1 >= 4 {
		v106 = v155
		v107 = v156
		v108 = v157
		v109 = v158
		goto b3
	}
	v422 = float64(ri1 + 1)
	ri1++
	goto b6
b6:
	if v422 < 1 || v422 > 4 {
		return machinePreparedReplayEntry()
	}
	v423 = ra1_0[int(v422)-1]
	v424 = v423
	if v162 < 1 || v162 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v162) - 1 {
	case 0:
		switch v424 {
		case uint32(1):
			v425 = r2_0
			vp425 = rp2_0
		case uint32(2):
			v425 = r2_1
			vp425 = rp2_1
		case uint32(3):
			v425 = r2_2
			vp425 = rp2_2
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v424 {
		case uint32(1):
			v425 = r6_0
			vp425 = rp6_0
		case uint32(2):
			v425 = r6_1
			vp425 = rp6_1
		case uint32(3):
			v425 = r6_2
			vp425 = rp6_2
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v424 {
		case uint32(1):
			v425 = r10_0
			vp425 = rp10_0
		case uint32(2):
			v425 = r10_1
			vp425 = rp10_1
		case uint32(3):
			v425 = r10_2
			vp425 = rp10_2
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	v426 = v423
	if v162 < 1 || v162 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v162) - 1 {
	case 0:
		switch v426 {
		case uint32(1):
			v427 = r0_0
			vp427 = rp0_0
		case uint32(2):
			v427 = r0_1
			vp427 = rp0_1
		case uint32(3):
			v427 = r0_2
			vp427 = rp0_2
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v426 {
		case uint32(1):
			v427 = r4_0
			vp427 = rp4_0
		case uint32(2):
			v427 = r4_1
			vp427 = rp4_1
		case uint32(3):
			v427 = r4_2
			vp427 = rp4_2
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v426 {
		case uint32(1):
			v427 = r8_0
			vp427 = rp8_0
		case uint32(2):
			v427 = r8_1
			vp427 = rp8_1
		case uint32(3):
			v427 = r8_2
			vp427 = rp8_2
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	if !vp427 {
		return machinePreparedReplayEntry()
	}
	v428 = math.Floor(v427 / math.Float64frombits(0x4014000000000000))
	if !vp425 {
		return machinePreparedReplayEntry()
	}
	v429 = v425 - v428
	v430 = v423
	if v162 < 1 || v162 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v162) - 1 {
	case 0:
		switch v430 {
		case uint32(1):
			v431 = r3_0
			vp431 = rp3_0
		case uint32(2):
			v431 = r3_1
			vp431 = rp3_1
		case uint32(3):
			v431 = r3_2
			vp431 = rp3_2
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v430 {
		case uint32(1):
			v431 = r7_0
			vp431 = rp7_0
		case uint32(2):
			v431 = r7_1
			vp431 = rp7_1
		case uint32(3):
			v431 = r7_2
			vp431 = rp7_2
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v430 {
		case uint32(1):
			v431 = r11_0
			vp431 = rp11_0
		case uint32(2):
			v431 = r11_1
			vp431 = rp11_1
		case uint32(3):
			v431 = r11_2
			vp431 = rp11_2
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	v432 = v429
	if !vp431 {
		return machinePreparedReplayEntry()
	}
	v433 = v431 + v432
	if math.IsNaN(v433) {
		return machinePreparedReplayEntry()
	}
	if !(v433 < math.Float64frombits(0x3ff0000000000000)) {
		v204 = v155
		v205 = v156
		v206 = v157
		v207 = v158
		v211 = v162
		v217 = v422
		v220 = v423
		v224 = v433
		goto b8
	}
	goto b7
b7:
	v434 = math.Float64frombits(0x3ff0000000000000)
	v204 = v155
	v205 = v156
	v206 = v157
	v207 = v158
	v211 = v162
	v217 = v422
	v220 = v423
	v224 = v434
	goto b8
b8:
	if v217 < 1 || v217 > 4 {
		return machinePreparedReplayEntry()
	}
	v435 = ra1_2[int(v217)-1]
	if v435 != uint32(9) {
		goto b10
	}
	goto b9
b9:
	if v217 < 1 || v217 > 4 {
		return machinePreparedReplayEntry()
	}
	v436 = ra1_1[int(v217)-1]
	v437 = v205
	v438 = v437 - math.Floor(v437/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v439 = v436 + v438
	v440 = v220
	if v211 < 1 || v211 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v211) - 1 {
	case 0:
		switch v440 {
		case uint32(1):
			v441 = r0_0
			vp441 = rp0_0
		case uint32(2):
			v441 = r0_1
			vp441 = rp0_1
		case uint32(3):
			v441 = r0_2
			vp441 = rp0_2
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v440 {
		case uint32(1):
			v441 = r4_0
			vp441 = rp4_0
		case uint32(2):
			v441 = r4_1
			vp441 = rp4_1
		case uint32(3):
			v441 = r4_2
			vp441 = rp4_2
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v440 {
		case uint32(1):
			v441 = r8_0
			vp441 = rp8_0
		case uint32(2):
			v441 = r8_1
			vp441 = rp8_1
		case uint32(3):
			v441 = r8_2
			vp441 = rp8_2
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	v442 = v439
	if !vp441 {
		return machinePreparedReplayEntry()
	}
	v442 = math.Min(v442, v441)
	v443 = v220
	if v211 < 1 || v211 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v211) - 1 {
	case 0:
		switch v443 {
		case uint32(1):
			v444 = r0_0
			vp444 = rp0_0
		case uint32(2):
			v444 = r0_1
			vp444 = rp0_1
		case uint32(3):
			v444 = r0_2
			vp444 = rp0_2
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v443 {
		case uint32(1):
			v444 = r4_0
			vp444 = rp4_0
		case uint32(2):
			v444 = r4_1
			vp444 = rp4_1
		case uint32(3):
			v444 = r4_2
			vp444 = rp4_2
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v443 {
		case uint32(1):
			v444 = r8_0
			vp444 = rp8_0
		case uint32(2):
			v444 = r8_1
			vp444 = rp8_1
		case uint32(3):
			v444 = r8_2
			vp444 = rp8_2
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	v445 = v442
	if !vp444 {
		return machinePreparedReplayEntry()
	}
	v446 = v444 - v445
	v447 = v220
	if v211 < 1 || v211 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v211) - 1 {
	case 0:
		switch v447 {
		case uint32(1):
			r0_0 = v446
			rp0_0 = true
		case uint32(2):
			r0_1 = v446
			rp0_1 = true
		case uint32(3):
			r0_2 = v446
			rp0_2 = true
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v447 {
		case uint32(1):
			r4_0 = v446
			rp4_0 = true
		case uint32(2):
			r4_1 = v446
			rp4_1 = true
		case uint32(3):
			r4_2 = v446
			rp4_2 = true
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v447 {
		case uint32(1):
			r8_0 = v446
			rp8_0 = true
		case uint32(2):
			r8_1 = v446
			rp8_1 = true
		case uint32(3):
			r8_2 = v446
			rp8_2 = true
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	v448 = v442
	v449 = v224
	v450 = v448 * v449
	v451 = v204 - v450
	v253 = v451
	v254 = v205
	v255 = v206
	v256 = v207
	v260 = v211
	v269 = v220
	v273 = v224
	goto b11
b10:
	if v217 < 1 || v217 > 4 {
		return machinePreparedReplayEntry()
	}
	v452 = ra1_1[int(v217)-1]
	v453 = v205
	v454 = v453 - math.Floor(v453/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v455 = v452 + v454
	v456 = v220
	if v211 < 1 || v211 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v211) - 1 {
	case 0:
		switch v456 {
		case uint32(1):
			v457 = r0_0
			vp457 = rp0_0
		case uint32(2):
			v457 = r0_1
			vp457 = rp0_1
		case uint32(3):
			v457 = r0_2
			vp457 = rp0_2
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v456 {
		case uint32(1):
			v457 = r4_0
			vp457 = rp4_0
		case uint32(2):
			v457 = r4_1
			vp457 = rp4_1
		case uint32(3):
			v457 = r4_2
			vp457 = rp4_2
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v456 {
		case uint32(1):
			v457 = r8_0
			vp457 = rp8_0
		case uint32(2):
			v457 = r8_1
			vp457 = rp8_1
		case uint32(3):
			v457 = r8_2
			vp457 = rp8_2
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	v458 = v455
	if !vp457 {
		return machinePreparedReplayEntry()
	}
	v459 = v457 + v458
	v460 = v220
	if v211 < 1 || v211 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v211) - 1 {
	case 0:
		switch v460 {
		case uint32(1):
			r0_0 = v459
			rp0_0 = true
		case uint32(2):
			r0_1 = v459
			rp0_1 = true
		case uint32(3):
			r0_2 = v459
			rp0_2 = true
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v460 {
		case uint32(1):
			r4_0 = v459
			rp4_0 = true
		case uint32(2):
			r4_1 = v459
			rp4_1 = true
		case uint32(3):
			r4_2 = v459
			rp4_2 = true
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v460 {
		case uint32(1):
			r8_0 = v459
			rp8_0 = true
		case uint32(2):
			r8_1 = v459
			rp8_1 = true
		case uint32(3):
			r8_2 = v459
			rp8_2 = true
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	v461 = v455
	v462 = v224
	v463 = v461 * v462
	v464 = v204 + v463
	v253 = v464
	v254 = v205
	v255 = v206
	v256 = v207
	v260 = v211
	v269 = v220
	v273 = v224
	goto b11
b11:
	v465 = v273
	v466 = v254
	v467 = v466 - math.Floor(v466/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v468 = v465 + v467
	v469 = v269
	if v260 < 1 || v260 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v260) - 1 {
	case 0:
		switch v469 {
		case uint32(1):
			r3_0 = v468
			rp3_0 = true
		case uint32(2):
			r3_1 = v468
			rp3_1 = true
		case uint32(3):
			r3_2 = v468
			rp3_2 = true
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v469 {
		case uint32(1):
			r7_0 = v468
			rp7_0 = true
		case uint32(2):
			r7_1 = v468
			rp7_1 = true
		case uint32(3):
			r7_2 = v468
			rp7_2 = true
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v469 {
		case uint32(1):
			r11_0 = v468
			rp11_0 = true
		case uint32(2):
			r11_1 = v468
			rp11_1 = true
		case uint32(3):
			r11_2 = v468
			rp11_2 = true
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	v155 = v253
	v156 = v254
	v157 = v255
	v158 = v256
	v162 = v260
	goto b5
b12:
	v470 = v107 + v109
	v57 = v106
	v58 = v470
	v59 = v108
	v60 = v109
	goto b1
b13:
	v471 = math.Float64frombits(0x0000000000000000)
	ri0 = 0
	v302 = v57
	v336 = v471
	goto b14
b14:
	if ri0 >= 3 {
		goto b16
	}
	v477 = float64(ri0 + 1)
	ri0++
	goto b15
b15:
	if v477 < 1 || v477 > 3 {
		return machinePreparedReplayEntry()
	}
	v478 = ra0_0[int(v477)-1]
	if v478 < 1 || v478 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v478) - 1 {
	case 0:
		v479 = r0_0
		vp479 = rp0_0
	case 1:
		v479 = r4_0
		vp479 = rp4_0
	case 2:
		v479 = r8_0
		vp479 = rp8_0
	default:
		return machinePreparedReplayEntry()
	}
	if !vp479 {
		return machinePreparedReplayEntry()
	}
	v480 = v336 + v479
	if v477 < 1 || v477 > 3 {
		return machinePreparedReplayEntry()
	}
	v481 = ra0_0[int(v477)-1]
	if v481 < 1 || v481 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v481) - 1 {
	case 0:
		v482 = r0_1
		vp482 = rp0_1
	case 1:
		v482 = r4_1
		vp482 = rp4_1
	case 2:
		v482 = r8_1
		vp482 = rp8_1
	default:
		return machinePreparedReplayEntry()
	}
	if !vp482 {
		return machinePreparedReplayEntry()
	}
	v483 = v482 * math.Float64frombits(0x4000000000000000)
	v484 = v480 + v483
	if v477 < 1 || v477 > 3 {
		return machinePreparedReplayEntry()
	}
	v485 = ra0_0[int(v477)-1]
	if v485 < 1 || v485 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v485) - 1 {
	case 0:
		v486 = r0_2
		vp486 = rp0_2
	case 1:
		v486 = r4_2
		vp486 = rp4_2
	case 2:
		v486 = r8_2
		vp486 = rp8_2
	default:
		return machinePreparedReplayEntry()
	}
	if !vp486 {
		return machinePreparedReplayEntry()
	}
	v487 = v484 + v486
	v302 = v302
	v336 = v487
	goto b14
b16:
	v488 = v302
	v489 = v336
	v490 = v488 + v489
	return machinePreparedReturnOneNumber(v490)
}

func backendGeneratedEconomyMarketPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchanged(150) {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedEconomyMarketPreparedFixtureBody(context, p0)
}
