// Code generated by cmd/ember-vmgen; DO NOT EDIT.
// Machine metadata sha256: c8a5c9f05a0fc041f64e4684ed0eb0d4e0a71af6104d47f841e2900d924f3e58

package ember

import "fmt"

func runGeneratedScalarMachineLoop(machine *scalarMachine) (int, error) {
	protoID := machine.activeProto
	base := machine.activeBase
	pc := 0
	for {
		if protoID < 0 || int(protoID) >= len(machine.image.prototypes) {
			return pc, fmt.Errorf("compact Machine prototype %d is out of range", protoID)
		}
		currentProto := &machine.image.prototypes[protoID]
		if pc < 0 || pc >= len(currentProto.operations) {
			return pc, errCompactMachineFellOffEnd
		}
		machine.activeProto = protoID
		machine.activeBase = base
		operation := currentProto.operations[pc]
		if machine.skipCharge != 0 {
			machine.skipCharge = 0
		} else if machine.window.controller != nil {
			if err := machine.charge(operation); err != nil {
				return pc, err
			}
		}
		rawA := int(operation.a)
		rawB := int(operation.b)
		rawC := int(operation.c)
		rawD := int(operation.d)
		a := base + rawA
		b := base + rawB
		c := base + rawC
		next := pc + 1
		switch operation.op {
		case opLoadConst:
			if err := machine.loadConstant(a, rawB); err != nil {
				return pc, err
			}

		case opLoadGlobal:
			if err := machine.loadGlobal(a, operation.globalIndex); err != nil {
				return pc, err
			}

		case opSetGlobal:
			if err := machine.storeGlobal(operation.globalIndex, b); err != nil {
				return pc, err
			}

		case opMove:
			if err := machine.move(a, b); err != nil {
				return pc, err
			}

		case opNewTable:
			if err := machine.newTableStopped(a, rawB, rawC); err != nil {
				return pc, err
			}

		case opSetField:
			if err := machine.setConstantFieldStopped(a, rawB, c); err != nil {
				return pc, err
			}

		case opSetStringField:
			if err := machine.setStringFieldStopped(a, rawB, c); err != nil {
				return pc, err
			}

		case opGetStringField:
			if err := machine.getStringField(a, b, rawC); err != nil {
				return pc, err
			}

		case opSetIndex:
			if err := machine.setIndexStopped(a, b, c); err != nil {
				return pc, err
			}

		case opGetIndex:
			if err := machine.getIndex(a, b, c); err != nil {
				return pc, err
			}

		case opClosure:
			if err := machine.makeClosure(a, operation.targetProto); err != nil {
				return pc, err
			}

		case opGetUpvalue:
			if err := machine.loadUpvalue(a, rawB); err != nil {
				return pc, err
			}

		case opSetUpvalue:
			if err := machine.storeUpvalue(rawA, b); err != nil {
				return pc, err
			}

		case opVararg:
			if err := machine.loadVarargs(a, rawB); err != nil {
				return pc, err
			}

		case opAdd, opSub, opMul, opDiv, opMod, opIDiv, opPow:
			if err := machine.binaryRegisters(operation.op, a, b, c); err != nil {
				return pc, err
			}

		case opAddK, opSubK, opMulK, opDivK, opModK, opIDivK:
			if err := machine.binaryConstant(operation.op, a, b, rawC); err != nil {
				return pc, err
			}

		case opNeg:
			if err := machine.negate(a, b); err != nil {
				return pc, err
			}

		case opEqual, opNotEqual, opLess, opLessEqual, opGreater, opGreaterEqual:
			if err := machine.storeComparison(operation.op, a, b, c); err != nil {
				return pc, err
			}

		case opNumericForCheck:
			exit, err := machine.numericForCheck(a, b, c)
			if err != nil {
				return pc, err
			}
			if exit {
				pc = rawD
				continue
			}

		case opNumericForLoop:
			if err := machine.numericForLoop(a, b); err != nil {
				return pc, err
			}
			pc = rawD
			continue

		case opJumpIfNotEqualK:
			equal, err := machine.equalityConstant(a, rawB, a)
			if err != nil {
				return pc, err
			}
			if !equal {
				pc = rawD
				continue
			}

		case opJumpIfNotLessK, opJumpIfNotGreaterK, opJumpIfLessK, opJumpIfGreaterK:
			comparison, err := machine.compareConstant(operation.op, a, rawB, a)
			if err != nil {
				return pc, err
			}
			jump := comparison
			if operation.op == opJumpIfNotLessK || operation.op == opJumpIfNotGreaterK {
				jump = !jump
			}
			if jump {
				pc = rawD
				continue
			}

		case opJumpIfNotLess, opJumpIfNotGreater, opJumpIfLess, opJumpIfGreater:
			comparison, err := machine.compare(operation.op, machine.registers[a], machine.registers[b])
			if err != nil {
				return pc, err
			}
			jump := comparison
			if operation.op == opJumpIfNotLess || operation.op == opJumpIfNotGreater {
				jump = !jump
			}
			if jump {
				pc = rawD
				continue
			}

		case opJumpIfFalse:
			if !machineTruthy(machine.registers[a]) {
				pc = rawB
				continue
			}

		case opJump:
			pc = rawB
			continue

		case opCall, opCallOne, opCallLocalOne, opCallUpvalueOne:
			targetID, targetBase, err := machine.enterCall(operation, next)
			if err != nil {
				return pc, err
			}
			if targetID < 0 {
				pc = next
				continue
			}
			protoID = targetID
			base = targetBase
			pc = 0
			continue

		case opReturnOne:
			done, nextProto, nextBase, nextPC, err := machine.returnFromCall(rawA, 1)
			if err != nil {
				return pc, err
			}
			if done {
				return -1, nil
			}
			protoID, base, pc = nextProto, nextBase, nextPC
			continue

		case opReturn:
			done, nextProto, nextBase, nextPC, err := machine.returnFromCall(rawA, int(operation.returnCount))
			if err != nil {
				return pc, err
			}
			if done {
				return -1, nil
			}
			protoID, base, pc = nextProto, nextBase, nextPC
			continue
		}
		pc = next
	}
}
