// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedSaveStateDiff(p0 float64) (float64, bool) {
	var v1 float64
	var v37 float64
	var v38 float64
	var v39 float64
	var v40 float64
	var v66 float64
	var v67 float64
	var v68 float64
	var v69 float64
	var v95 float64
	var v96 float64
	var v97 float64
	var v98 float64
	var v102 float64
	var v105 float64
	var v107 float64
	var v124 float64
	var v125 float64
	var v126 float64
	var v127 float64
	var v131 float64
	var v134 float64
	var v153 float64
	var v154 float64
	var v155 float64
	var v156 float64
	var v160 float64
	var v163 float64
	var v182 float64
	var v183 float64
	var v184 float64
	var v185 float64
	var v189 float64
	var v192 float64
	var v211 float64
	var v212 float64
	var v213 float64
	var v214 float64
	var v218 float64
	var v221 float64
	var v230 float64
	var v235 uint32
	var v236 float64
	var v237 uint32
	var v239 float64
	var v240 float64
	var v241 float64
	var v243 uint32
	var v244 float64
	var v245 uint32
	var v247 float64
	var v248 float64
	var v249 float64
	var v251 uint32
	var v252 float64
	var v253 uint32
	var v255 float64
	var v256 float64
	var v257 float64
	var v260 uint32
	var v261 float64
	var v262 uint32
	var v264 float64
	var v265 float64
	var v266 float64
	var v268 uint32
	var v269 float64
	var v270 uint32
	var v272 float64
	var v273 float64
	var v274 float64
	var v276 uint32
	var v277 float64
	var v278 uint32
	var v280 float64
	var v281 float64
	var v282 float64
	var v284 uint32
	var v285 uint32
	var v286 uint32
	var v287 float64
	var v288 float64
	var v289 float64
	var v293 float64
	var v294 float64
	var v295 float64
	var v300 float64
	var v301 float64
	var v302 float64
	var v303 float64
	var v304 float64
	var v305 float64
	var v306 bool
	var v307 float64
	var v308 float64
	var v309 float64
	var v310 float64
	var v311 float64
	var v312 float64
	var v313 float64
	var v314 float64
	var v315 float64
	var v316 uint32
	var v317 uint32
	var v318 bool
	var v319 float64
	var v325 uint32
	var v326 uint32
	var v327 float64
	var v328 uint32
	var v329 float64
	var v330 float64
	var v331 float64
	var v332 float64
	var v333 float64
	var v334 float64
	var v335 float64
	var v336 float64
	var v337 float64
	var v338 float64
	var a0 [3]uint32
	_ = a0
	var i0 int
	_ = i0
	var r0_0 uint32
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 uint32
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r1_0 float64
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r2_0 uint32
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 uint32
	_ = r2_2
	var r2_3 float64
	_ = r2_3
	var r3_0 float64
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r3_2 float64
	_ = r3_2
	var r4_0 uint32
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r4_2 uint32
	_ = r4_2
	var r4_3 float64
	_ = r4_3
	var r5_0 float64
	_ = r5_0
	var r5_1 float64
	_ = r5_1
	var r5_2 float64
	_ = r5_2
	var r6_0 uint32
	_ = r6_0
	var r6_1 float64
	_ = r6_1
	var r6_2 uint32
	_ = r6_2
	var r6_3 float64
	_ = r6_3
	var r7_0 float64
	_ = r7_0
	var r7_1 float64
	_ = r7_1
	var r7_2 float64
	_ = r7_2
	var r8_0 uint32
	_ = r8_0
	var r8_1 float64
	_ = r8_1
	var r8_2 uint32
	_ = r8_2
	var r8_3 float64
	_ = r8_3
	var r9_0 float64
	_ = r9_0
	var r9_1 float64
	_ = r9_1
	var r9_2 float64
	_ = r9_2
	var r10_0 uint32
	_ = r10_0
	var r10_1 float64
	_ = r10_1
	var r10_2 uint32
	_ = r10_2
	var r10_3 float64
	_ = r10_3
	var r11_0 float64
	_ = r11_0
	var r11_1 float64
	_ = r11_1
	var r11_2 float64
	_ = r11_2
	var ra0_0 [3]uint32
	var ra0_1 [3]float64
	var ra0_2 [3]uint32
	var ra0_3 [3]float64
	var ri0 int
	_ = ri0
	var ra1_0 [3]uint32
	var ra1_1 [3]float64
	var ra1_2 [3]uint32
	var ra1_3 [3]float64
	var ri1 int
	_ = ri1
	v1 = p0
	v235 = uint32(1)
	r0_0 = v235
	v236 = math.Float64frombits(0x4059000000000000)
	r0_1 = v236
	v237 = uint32(4)
	r0_2 = v237
	v239 = math.Float64frombits(0x4034000000000000)
	r1_0 = v239
	v240 = math.Float64frombits(0x4008000000000000)
	r1_1 = v240
	v241 = math.Float64frombits(0x0000000000000000)
	r1_2 = v241
	r0_3 = 1
	ra0_0[0] = r0_0
	ra0_1[0] = r0_1
	ra0_2[0] = r0_2
	ra0_3[0] = r0_3
	v243 = uint32(10)
	r2_0 = v243
	v244 = math.Float64frombits(0x4055400000000000)
	r2_1 = v244
	v245 = uint32(11)
	r2_2 = v245
	v247 = math.Float64frombits(0x4014000000000000)
	r3_0 = v247
	v248 = math.Float64frombits(0x0000000000000000)
	r3_1 = v248
	v249 = math.Float64frombits(0x4020000000000000)
	r3_2 = v249
	r2_3 = 2
	ra0_0[1] = r2_0
	ra0_1[1] = r2_1
	ra0_2[1] = r2_2
	ra0_3[1] = r2_3
	v251 = uint32(12)
	r4_0 = v251
	v252 = math.Float64frombits(0x4044000000000000)
	r4_1 = v252
	v253 = uint32(13)
	r4_2 = v253
	v255 = math.Float64frombits(0x4000000000000000)
	r5_0 = v255
	v256 = math.Float64frombits(0x3ff0000000000000)
	r5_1 = v256
	v257 = math.Float64frombits(0x0000000000000000)
	r5_2 = v257
	r4_3 = 3
	ra0_0[2] = r4_0
	ra0_1[2] = r4_1
	ra0_2[2] = r4_2
	ra0_3[2] = r4_3
	v260 = uint32(1)
	r6_0 = v260
	v261 = math.Float64frombits(0x4057000000000000)
	r6_1 = v261
	v262 = uint32(13)
	r6_2 = v262
	v264 = math.Float64frombits(0x4031000000000000)
	r7_0 = v264
	v265 = math.Float64frombits(0x4014000000000000)
	r7_1 = v265
	v266 = math.Float64frombits(0x0000000000000000)
	r7_2 = v266
	r6_3 = 1
	ra1_0[0] = r6_0
	ra1_1[0] = r6_1
	ra1_2[0] = r6_2
	ra1_3[0] = r6_3
	v268 = uint32(10)
	r8_0 = v268
	v269 = math.Float64frombits(0x4055400000000000)
	r8_1 = v269
	v270 = uint32(11)
	r8_2 = v270
	v272 = math.Float64frombits(0x4028000000000000)
	r9_0 = v272
	v273 = math.Float64frombits(0x0000000000000000)
	r9_1 = v273
	v274 = math.Float64frombits(0x4010000000000000)
	r9_2 = v274
	r8_3 = 2
	ra1_0[1] = r8_0
	ra1_1[1] = r8_1
	ra1_2[1] = r8_2
	ra1_3[1] = r8_3
	v276 = uint32(12)
	r10_0 = v276
	v277 = math.Float64frombits(0x0000000000000000)
	r10_1 = v277
	v278 = uint32(13)
	r10_2 = v278
	v280 = math.Float64frombits(0x4000000000000000)
	r11_0 = v280
	v281 = math.Float64frombits(0x3ff0000000000000)
	r11_1 = v281
	v282 = math.Float64frombits(0x0000000000000000)
	r11_2 = v282
	r10_3 = 3
	ra1_0[2] = r10_0
	ra1_1[2] = r10_1
	ra1_2[2] = r10_2
	ra1_3[2] = r10_3
	v284 = uint32(6)
	a0[0] = v284
	v285 = uint32(7)
	a0[1] = v285
	v286 = uint32(8)
	a0[2] = v286
	v287 = v1
	v288 = v1
	v289 = v287 - v288
	v293 = math.Float64frombits(0x3ff0000000000000)
	v294 = math.Float64frombits(0x4056800000000000)
	v295 = math.Float64frombits(0x3ff0000000000000)
	v37 = v289
	v38 = v293
	v39 = v294
	v40 = v295
	goto b1
b1:
	if math.IsNaN(v38) {
		return 0, false
	}
	if math.IsNaN(v39) {
		return 0, false
	}
	if math.IsNaN(v40) {
		return 0, false
	}
	if (v40 > 0 && v38 > v39) || (v40 <= 0 && v38 < v39) {
		goto b16
	}
	goto b2
b2:
	ri0 = 0
	v66 = v37
	v67 = v38
	v68 = v39
	v69 = v40
	goto b3
b3:
	if ri0 >= 3 {
		goto b15
	}
	v300 = float64(ri0 + 1)
	v301 = v300
	ri0++
	goto b4
b4:
	v302 = v300
	v303 = 0
	if v302 >= 1 && v302 <= 3 && v302 == math.Trunc(v302) {
		v303 = v302
	}
	if v301 < 1 || v301 > 3 {
		return 0, false
	}
	v304 = ra0_1[int(v301)-1]
	if v303 < 1 || v303 > 3 {
		return 0, false
	}
	v305 = ra1_1[int(v303)-1]
	v306 = v304 != v305
	if !v306 {
		v124 = v66
		v125 = v67
		v126 = v68
		v127 = v69
		v131 = v301
		v134 = v303
		goto b8
	}
	goto b5
b5:
	if v301 < 1 || v301 > 3 {
		return 0, false
	}
	v307 = ra0_1[int(v301)-1]
	if v303 < 1 || v303 > 3 {
		return 0, false
	}
	v308 = ra1_1[int(v303)-1]
	v309 = v307 - v308
	if math.IsNaN(v309) {
		return 0, false
	}
	if !(v309 < math.Float64frombits(0x0000000000000000)) {
		v95 = v66
		v96 = v67
		v97 = v68
		v98 = v69
		v102 = v301
		v105 = v303
		v107 = v309
		goto b7
	}
	goto b6
b6:
	v310 = -v309
	v95 = v66
	v96 = v67
	v97 = v68
	v98 = v69
	v102 = v301
	v105 = v303
	v107 = v310
	goto b7
b7:
	v311 = v107
	v312 = v95 + v311
	v313 = v96
	v314 = v313 - math.Floor(v313/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v315 = v312 + v314
	v124 = v315
	v125 = v96
	v126 = v97
	v127 = v98
	v131 = v102
	v134 = v105
	goto b8
b8:
	if v131 < 1 || v131 > 3 {
		return 0, false
	}
	v316 = ra0_2[int(v131)-1]
	if v134 < 1 || v134 > 3 {
		return 0, false
	}
	v317 = ra1_2[int(v134)-1]
	v318 = v316 != v317
	if !v318 {
		v153 = v124
		v154 = v125
		v155 = v126
		v156 = v127
		v160 = v131
		v163 = v134
		goto b10
	}
	goto b9
b9:
	v319 = v124 + math.Float64frombits(0x4031000000000000)
	v153 = v319
	v154 = v125
	v155 = v126
	v156 = v127
	v160 = v131
	v163 = v134
	goto b10
b10:
	i0 = 0
	v182 = v153
	v183 = v154
	v184 = v155
	v185 = v156
	v189 = v160
	v192 = v163
	goto b11
b11:
	if i0 >= len(a0) {
		v66 = v182
		v67 = v183
		v68 = v184
		v69 = v185
		goto b3
	}
	v325 = a0[i0]
	i0++
	goto b12
b12:
	v326 = v325
	if v189 < 1 || v189 > 3 {
		return 0, false
	}
	switch int(v189) - 1 {
	case 0:
		switch v326 {
		case uint32(6):
			v327 = r1_0
		case uint32(7):
			v327 = r1_1
		case uint32(8):
			v327 = r1_2
		default:
			return 0, false
		}
	case 1:
		switch v326 {
		case uint32(6):
			v327 = r3_0
		case uint32(7):
			v327 = r3_1
		case uint32(8):
			v327 = r3_2
		default:
			return 0, false
		}
	case 2:
		switch v326 {
		case uint32(6):
			v327 = r5_0
		case uint32(7):
			v327 = r5_1
		case uint32(8):
			v327 = r5_2
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	v328 = v325
	if v192 < 1 || v192 > 3 {
		return 0, false
	}
	switch int(v192) - 1 {
	case 0:
		switch v328 {
		case uint32(6):
			v329 = r7_0
		case uint32(7):
			v329 = r7_1
		case uint32(8):
			v329 = r7_2
		default:
			return 0, false
		}
	case 1:
		switch v328 {
		case uint32(6):
			v329 = r9_0
		case uint32(7):
			v329 = r9_1
		case uint32(8):
			v329 = r9_2
		default:
			return 0, false
		}
	case 2:
		switch v328 {
		case uint32(6):
			v329 = r11_0
		case uint32(7):
			v329 = r11_1
		case uint32(8):
			v329 = r11_2
		default:
			return 0, false
		}
	default:
		return 0, false
	}
	v330 = v327 - v329
	if math.IsNaN(v330) {
		return 0, false
	}
	if !(v330 < math.Float64frombits(0x0000000000000000)) {
		v211 = v182
		v212 = v183
		v213 = v184
		v214 = v185
		v218 = v189
		v221 = v192
		v230 = v330
		goto b14
	}
	goto b13
b13:
	v331 = -v330
	v211 = v182
	v212 = v183
	v213 = v184
	v214 = v185
	v218 = v189
	v221 = v192
	v230 = v331
	goto b14
b14:
	v332 = v230
	v333 = v212
	v334 = v333 - math.Floor(v333/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v335 = v334 + math.Float64frombits(0x3ff0000000000000)
	v336 = v332 * v335
	v337 = v211 + v336
	v182 = v337
	v183 = v212
	v184 = v213
	v185 = v214
	v189 = v218
	v192 = v221
	goto b11
b15:
	v338 = v67 + v69
	v37 = v66
	v38 = v338
	v39 = v68
	v40 = v69
	goto b1
b16:
	return v37, true
}

func backendGeneratedSaveStateDiffPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v37 float64
	var v38 float64
	var v39 float64
	var v40 float64
	var v66 float64
	var v67 float64
	var v68 float64
	var v69 float64
	var v95 float64
	var v96 float64
	var v97 float64
	var v98 float64
	var v102 float64
	var v105 float64
	var v107 float64
	var v124 float64
	var v125 float64
	var v126 float64
	var v127 float64
	var v131 float64
	var v134 float64
	var v153 float64
	var v154 float64
	var v155 float64
	var v156 float64
	var v160 float64
	var v163 float64
	var v182 float64
	var v183 float64
	var v184 float64
	var v185 float64
	var v189 float64
	var v192 float64
	var v211 float64
	var v212 float64
	var v213 float64
	var v214 float64
	var v218 float64
	var v221 float64
	var v230 float64
	var v235 uint32
	var v236 float64
	var v237 uint32
	var v239 float64
	var v240 float64
	var v241 float64
	var v243 uint32
	var v244 float64
	var v245 uint32
	var v247 float64
	var v248 float64
	var v249 float64
	var v251 uint32
	var v252 float64
	var v253 uint32
	var v255 float64
	var v256 float64
	var v257 float64
	var v260 uint32
	var v261 float64
	var v262 uint32
	var v264 float64
	var v265 float64
	var v266 float64
	var v268 uint32
	var v269 float64
	var v270 uint32
	var v272 float64
	var v273 float64
	var v274 float64
	var v276 uint32
	var v277 float64
	var v278 uint32
	var v280 float64
	var v281 float64
	var v282 float64
	var v284 uint32
	var v285 uint32
	var v286 uint32
	var v287 float64
	var v288 float64
	var v289 float64
	var v293 float64
	var v294 float64
	var v295 float64
	var v300 float64
	var v301 float64
	var v302 float64
	var v303 float64
	var v304 float64
	var v305 float64
	var v306 bool
	var v307 float64
	var v308 float64
	var v309 float64
	var v310 float64
	var v311 float64
	var v312 float64
	var v313 float64
	var v314 float64
	var v315 float64
	var v316 uint32
	var v317 uint32
	var v318 bool
	var v319 float64
	var v325 uint32
	var v326 uint32
	var v327 float64
	var v328 uint32
	var v329 float64
	var v330 float64
	var v331 float64
	var v332 float64
	var v333 float64
	var v334 float64
	var v335 float64
	var v336 float64
	var v337 float64
	var v338 float64
	var a0 [3]uint32
	_ = a0
	var i0 int
	_ = i0
	var r0_0 uint32
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 uint32
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r1_0 float64
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r2_0 uint32
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 uint32
	_ = r2_2
	var r2_3 float64
	_ = r2_3
	var r3_0 float64
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r3_2 float64
	_ = r3_2
	var r4_0 uint32
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r4_2 uint32
	_ = r4_2
	var r4_3 float64
	_ = r4_3
	var r5_0 float64
	_ = r5_0
	var r5_1 float64
	_ = r5_1
	var r5_2 float64
	_ = r5_2
	var r6_0 uint32
	_ = r6_0
	var r6_1 float64
	_ = r6_1
	var r6_2 uint32
	_ = r6_2
	var r6_3 float64
	_ = r6_3
	var r7_0 float64
	_ = r7_0
	var r7_1 float64
	_ = r7_1
	var r7_2 float64
	_ = r7_2
	var r8_0 uint32
	_ = r8_0
	var r8_1 float64
	_ = r8_1
	var r8_2 uint32
	_ = r8_2
	var r8_3 float64
	_ = r8_3
	var r9_0 float64
	_ = r9_0
	var r9_1 float64
	_ = r9_1
	var r9_2 float64
	_ = r9_2
	var r10_0 uint32
	_ = r10_0
	var r10_1 float64
	_ = r10_1
	var r10_2 uint32
	_ = r10_2
	var r10_3 float64
	_ = r10_3
	var r11_0 float64
	_ = r11_0
	var r11_1 float64
	_ = r11_1
	var r11_2 float64
	_ = r11_2
	var ra0_0 [3]uint32
	var ra0_1 [3]float64
	var ra0_2 [3]uint32
	var ra0_3 [3]float64
	var ri0 int
	_ = ri0
	var ra1_0 [3]uint32
	var ra1_1 [3]float64
	var ra1_2 [3]uint32
	var ra1_3 [3]float64
	var ri1 int
	_ = ri1
	v1 = p0
	v235 = uint32(1)
	r0_0 = v235
	v236 = math.Float64frombits(0x4059000000000000)
	r0_1 = v236
	v237 = uint32(4)
	r0_2 = v237
	v239 = math.Float64frombits(0x4034000000000000)
	r1_0 = v239
	v240 = math.Float64frombits(0x4008000000000000)
	r1_1 = v240
	v241 = math.Float64frombits(0x0000000000000000)
	r1_2 = v241
	r0_3 = 1
	ra0_0[0] = r0_0
	ra0_1[0] = r0_1
	ra0_2[0] = r0_2
	ra0_3[0] = r0_3
	v243 = uint32(10)
	r2_0 = v243
	v244 = math.Float64frombits(0x4055400000000000)
	r2_1 = v244
	v245 = uint32(11)
	r2_2 = v245
	v247 = math.Float64frombits(0x4014000000000000)
	r3_0 = v247
	v248 = math.Float64frombits(0x0000000000000000)
	r3_1 = v248
	v249 = math.Float64frombits(0x4020000000000000)
	r3_2 = v249
	r2_3 = 2
	ra0_0[1] = r2_0
	ra0_1[1] = r2_1
	ra0_2[1] = r2_2
	ra0_3[1] = r2_3
	v251 = uint32(12)
	r4_0 = v251
	v252 = math.Float64frombits(0x4044000000000000)
	r4_1 = v252
	v253 = uint32(13)
	r4_2 = v253
	v255 = math.Float64frombits(0x4000000000000000)
	r5_0 = v255
	v256 = math.Float64frombits(0x3ff0000000000000)
	r5_1 = v256
	v257 = math.Float64frombits(0x0000000000000000)
	r5_2 = v257
	r4_3 = 3
	ra0_0[2] = r4_0
	ra0_1[2] = r4_1
	ra0_2[2] = r4_2
	ra0_3[2] = r4_3
	v260 = uint32(1)
	r6_0 = v260
	v261 = math.Float64frombits(0x4057000000000000)
	r6_1 = v261
	v262 = uint32(13)
	r6_2 = v262
	v264 = math.Float64frombits(0x4031000000000000)
	r7_0 = v264
	v265 = math.Float64frombits(0x4014000000000000)
	r7_1 = v265
	v266 = math.Float64frombits(0x0000000000000000)
	r7_2 = v266
	r6_3 = 1
	ra1_0[0] = r6_0
	ra1_1[0] = r6_1
	ra1_2[0] = r6_2
	ra1_3[0] = r6_3
	v268 = uint32(10)
	r8_0 = v268
	v269 = math.Float64frombits(0x4055400000000000)
	r8_1 = v269
	v270 = uint32(11)
	r8_2 = v270
	v272 = math.Float64frombits(0x4028000000000000)
	r9_0 = v272
	v273 = math.Float64frombits(0x0000000000000000)
	r9_1 = v273
	v274 = math.Float64frombits(0x4010000000000000)
	r9_2 = v274
	r8_3 = 2
	ra1_0[1] = r8_0
	ra1_1[1] = r8_1
	ra1_2[1] = r8_2
	ra1_3[1] = r8_3
	v276 = uint32(12)
	r10_0 = v276
	v277 = math.Float64frombits(0x0000000000000000)
	r10_1 = v277
	v278 = uint32(13)
	r10_2 = v278
	v280 = math.Float64frombits(0x4000000000000000)
	r11_0 = v280
	v281 = math.Float64frombits(0x3ff0000000000000)
	r11_1 = v281
	v282 = math.Float64frombits(0x0000000000000000)
	r11_2 = v282
	r10_3 = 3
	ra1_0[2] = r10_0
	ra1_1[2] = r10_1
	ra1_2[2] = r10_2
	ra1_3[2] = r10_3
	v284 = uint32(6)
	a0[0] = v284
	v285 = uint32(7)
	a0[1] = v285
	v286 = uint32(8)
	a0[2] = v286
	v287 = v1
	v288 = v1
	v289 = v287 - v288
	v293 = math.Float64frombits(0x3ff0000000000000)
	v294 = math.Float64frombits(0x4056800000000000)
	v295 = math.Float64frombits(0x3ff0000000000000)
	v37 = v289
	v38 = v293
	v39 = v294
	v40 = v295
	goto b1
b1:
	if math.IsNaN(v38) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v39) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v40) {
		return machinePreparedReplayEntry()
	}
	if (v40 > 0 && v38 > v39) || (v40 <= 0 && v38 < v39) {
		goto b16
	}
	goto b2
b2:
	ri0 = 0
	v66 = v37
	v67 = v38
	v68 = v39
	v69 = v40
	goto b3
b3:
	if ri0 >= 3 {
		goto b15
	}
	v300 = float64(ri0 + 1)
	v301 = v300
	ri0++
	goto b4
b4:
	v302 = v300
	v303 = 0
	if v302 >= 1 && v302 <= 3 && v302 == math.Trunc(v302) {
		v303 = v302
	}
	if v301 < 1 || v301 > 3 {
		return machinePreparedReplayEntry()
	}
	v304 = ra0_1[int(v301)-1]
	if v303 < 1 || v303 > 3 {
		return machinePreparedReplayEntry()
	}
	v305 = ra1_1[int(v303)-1]
	v306 = v304 != v305
	if !v306 {
		v124 = v66
		v125 = v67
		v126 = v68
		v127 = v69
		v131 = v301
		v134 = v303
		goto b8
	}
	goto b5
b5:
	if v301 < 1 || v301 > 3 {
		return machinePreparedReplayEntry()
	}
	v307 = ra0_1[int(v301)-1]
	if v303 < 1 || v303 > 3 {
		return machinePreparedReplayEntry()
	}
	v308 = ra1_1[int(v303)-1]
	v309 = v307 - v308
	if math.IsNaN(v309) {
		return machinePreparedReplayEntry()
	}
	if !(v309 < math.Float64frombits(0x0000000000000000)) {
		v95 = v66
		v96 = v67
		v97 = v68
		v98 = v69
		v102 = v301
		v105 = v303
		v107 = v309
		goto b7
	}
	goto b6
b6:
	v310 = -v309
	v95 = v66
	v96 = v67
	v97 = v68
	v98 = v69
	v102 = v301
	v105 = v303
	v107 = v310
	goto b7
b7:
	v311 = v107
	v312 = v95 + v311
	v313 = v96
	v314 = v313 - math.Floor(v313/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v315 = v312 + v314
	v124 = v315
	v125 = v96
	v126 = v97
	v127 = v98
	v131 = v102
	v134 = v105
	goto b8
b8:
	if v131 < 1 || v131 > 3 {
		return machinePreparedReplayEntry()
	}
	v316 = ra0_2[int(v131)-1]
	if v134 < 1 || v134 > 3 {
		return machinePreparedReplayEntry()
	}
	v317 = ra1_2[int(v134)-1]
	v318 = v316 != v317
	if !v318 {
		v153 = v124
		v154 = v125
		v155 = v126
		v156 = v127
		v160 = v131
		v163 = v134
		goto b10
	}
	goto b9
b9:
	v319 = v124 + math.Float64frombits(0x4031000000000000)
	v153 = v319
	v154 = v125
	v155 = v126
	v156 = v127
	v160 = v131
	v163 = v134
	goto b10
b10:
	i0 = 0
	v182 = v153
	v183 = v154
	v184 = v155
	v185 = v156
	v189 = v160
	v192 = v163
	goto b11
b11:
	if i0 >= len(a0) {
		v66 = v182
		v67 = v183
		v68 = v184
		v69 = v185
		goto b3
	}
	v325 = a0[i0]
	i0++
	goto b12
b12:
	v326 = v325
	if v189 < 1 || v189 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v189) - 1 {
	case 0:
		switch v326 {
		case uint32(6):
			v327 = r1_0
		case uint32(7):
			v327 = r1_1
		case uint32(8):
			v327 = r1_2
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v326 {
		case uint32(6):
			v327 = r3_0
		case uint32(7):
			v327 = r3_1
		case uint32(8):
			v327 = r3_2
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v326 {
		case uint32(6):
			v327 = r5_0
		case uint32(7):
			v327 = r5_1
		case uint32(8):
			v327 = r5_2
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	v328 = v325
	if v192 < 1 || v192 > 3 {
		return machinePreparedReplayEntry()
	}
	switch int(v192) - 1 {
	case 0:
		switch v328 {
		case uint32(6):
			v329 = r7_0
		case uint32(7):
			v329 = r7_1
		case uint32(8):
			v329 = r7_2
		default:
			return machinePreparedReplayEntry()
		}
	case 1:
		switch v328 {
		case uint32(6):
			v329 = r9_0
		case uint32(7):
			v329 = r9_1
		case uint32(8):
			v329 = r9_2
		default:
			return machinePreparedReplayEntry()
		}
	case 2:
		switch v328 {
		case uint32(6):
			v329 = r11_0
		case uint32(7):
			v329 = r11_1
		case uint32(8):
			v329 = r11_2
		default:
			return machinePreparedReplayEntry()
		}
	default:
		return machinePreparedReplayEntry()
	}
	v330 = v327 - v329
	if math.IsNaN(v330) {
		return machinePreparedReplayEntry()
	}
	if !(v330 < math.Float64frombits(0x0000000000000000)) {
		v211 = v182
		v212 = v183
		v213 = v184
		v214 = v185
		v218 = v189
		v221 = v192
		v230 = v330
		goto b14
	}
	goto b13
b13:
	v331 = -v330
	v211 = v182
	v212 = v183
	v213 = v184
	v214 = v185
	v218 = v189
	v221 = v192
	v230 = v331
	goto b14
b14:
	v332 = v230
	v333 = v212
	v334 = v333 - math.Floor(v333/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v335 = v334 + math.Float64frombits(0x3ff0000000000000)
	v336 = v332 * v335
	v337 = v211 + v336
	v182 = v337
	v183 = v212
	v184 = v213
	v185 = v214
	v189 = v218
	v192 = v221
	goto b11
b15:
	v338 = v67 + v69
	v37 = v66
	v38 = v338
	v39 = v68
	v40 = v69
	goto b1
b16:
	return machinePreparedReturnOneNumber(v37)
}

func backendGeneratedSaveStateDiffPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedSaveStateDiffPreparedFixtureBody(context, p0)
}
