// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedArrayIterationFixture(p0 float64) (float64, bool) {
	var v1 float64
	var v14 float64
	var v20 float64
	var v21 float64
	var v22 float64
	var v23 float64
	var v24 float64
	var v25 float64
	var v26 float64
	var v27 float64
	var v28 float64
	var v29 float64
	var v30 float64
	var v31 float64
	var v39 float64
	var v40 float64
	var v41 float64
	var v42 float64
	var v43 float64
	var a0 [8]float64
	_ = a0
	var i0 int
	_ = i0
	v1 = p0
	v20 = math.Float64frombits(0x3ff0000000000000)
	v21 = v1
	v22 = v21 - math.Floor(v21/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v23 = v20 + v22
	a0[0] = v23
	v24 = math.Float64frombits(0x4000000000000000)
	a0[1] = v24
	v25 = math.Float64frombits(0x4008000000000000)
	a0[2] = v25
	v26 = math.Float64frombits(0x4010000000000000)
	a0[3] = v26
	v27 = math.Float64frombits(0x4014000000000000)
	a0[4] = v27
	v28 = math.Float64frombits(0x4018000000000000)
	a0[5] = v28
	v29 = math.Float64frombits(0x401c000000000000)
	a0[6] = v29
	v30 = math.Float64frombits(0x4020000000000000)
	a0[7] = v30
	v31 = math.Float64frombits(0x0000000000000000)
	i0 = 0
	v14 = v31
	goto b1
b1:
	if i0 >= len(a0) {
		goto b3
	}
	v39 = a0[i0]
	i0++
	goto b2
b2:
	v40 = v39
	v41 = v39
	v42 = v40 * v41
	v43 = v14 + v42
	v14 = v43
	goto b1
b3:
	return v14, true
}

func backendGeneratedArrayIterationPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v14 float64
	var v20 float64
	var v21 float64
	var v22 float64
	var v23 float64
	var v24 float64
	var v25 float64
	var v26 float64
	var v27 float64
	var v28 float64
	var v29 float64
	var v30 float64
	var v31 float64
	var v39 float64
	var v40 float64
	var v41 float64
	var v42 float64
	var v43 float64
	var a0 [8]float64
	_ = a0
	var i0 int
	_ = i0
	v1 = p0
	v20 = math.Float64frombits(0x3ff0000000000000)
	v21 = v1
	v22 = v21 - math.Floor(v21/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v23 = v20 + v22
	a0[0] = v23
	v24 = math.Float64frombits(0x4000000000000000)
	a0[1] = v24
	v25 = math.Float64frombits(0x4008000000000000)
	a0[2] = v25
	v26 = math.Float64frombits(0x4010000000000000)
	a0[3] = v26
	v27 = math.Float64frombits(0x4014000000000000)
	a0[4] = v27
	v28 = math.Float64frombits(0x4018000000000000)
	a0[5] = v28
	v29 = math.Float64frombits(0x401c000000000000)
	a0[6] = v29
	v30 = math.Float64frombits(0x4020000000000000)
	a0[7] = v30
	v31 = math.Float64frombits(0x0000000000000000)
	i0 = 0
	v14 = v31
	goto b1
b1:
	if i0 >= len(a0) {
		goto b3
	}
	v39 = a0[i0]
	i0++
	goto b2
b2:
	v40 = v39
	v41 = v39
	v42 = v40 * v41
	v43 = v14 + v42
	v14 = v43
	goto b1
b3:
	return machinePreparedReturnOneNumber(v14)
}

func backendGeneratedArrayIterationPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedArrayIterationPreparedFixtureBody(context, p0)
}
