// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedNumericExitFixture(p0 float64) (float64, bool) {
	var v1 float64
	var v4 float64
	var v5 float64
	var v6 float64
	var v7 float64
	v1 = p0
	v4 = v1
	v5 = v4 + math.Float64frombits(0x3ff0000000000000)
	if math.IsNaN(v5) {
		return 0, false
	}
	if !(v5 < math.Float64frombits(0x4024000000000000)) {
		goto b2
	}
	goto b1
b1:
	return v5, true
b2:
	v6 = v5
	v7 = v6 * math.Float64frombits(0x4000000000000000)
	return v7, true
}

func backendGeneratedNumericExitPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v4 float64
	var v5 float64
	var v6 float64
	var v7 float64
	v1 = p0
	v4 = v1
	v5 = v4 + math.Float64frombits(0x3ff0000000000000)
	if math.IsNaN(v5) {
		exit := context.replayBeforeOperation(2, 1)
		context.spillNumber(0, 1, v5)
		return exit
	}
	if !(v5 < math.Float64frombits(0x4024000000000000)) {
		goto b2
	}
	goto b1
b1:
	return machinePreparedReturnOneNumber(v5)
b2:
	v6 = v5
	v7 = v6 * math.Float64frombits(0x4000000000000000)
	return machinePreparedReturnOneNumber(v7)
}

func backendGeneratedNumericExitPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedNumericExitPreparedFixtureBody(context, p0)
}
