// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedCommandRouter(p0 float64) (float64, bool) {
	var v1 float64
	var v36 float64
	var v37 float64
	var v38 float64
	var v39 float64
	var v65 float64
	var v66 float64
	var v67 float64
	var v68 float64
	var v89 float64
	var v90 float64
	var v91 float64
	var v92 float64
	var v93 float64
	var v97 uint32
	var v98 float64
	var v99 float64
	var v100 float64
	var v102 uint32
	var v103 float64
	var v104 float64
	var v105 float64
	var v107 uint32
	var v108 float64
	var v109 float64
	var v110 float64
	var v112 uint32
	var v113 float64
	var v114 float64
	var v115 float64
	var v116 float64
	var v118 float64
	var v119 float64
	var v120 float64
	var v121 float64
	var v123 float64
	var v124 float64
	var v125 float64
	var v131 float64
	var v133 float64
	var v134 uint32
	var v135 float64
	var v136 float64
	var v137 float64
	var v138 float64
	var v139 float64
	var v140 float64
	var v141 float64
	var v142 float64
	var v143 float64
	var v144 float64
	var v145 float64
	var v146 float64
	var v147 float64
	var v148 float64
	var v149 float64
	var v150 float64
	var v151 float64
	var v152 float64
	var v154 float64
	var v155 float64
	var v156 float64
	var v157 float64
	var v158 float64
	var v159 float64
	var v160 float64
	var v161 float64
	var v162 float64
	var v163 float64
	var v164 float64
	var v165 float64
	var v166 float64
	var v167 float64
	var v168 float64
	var v169 float64
	var v170 float64
	var v171 float64
	var v172 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r1_0 uint32
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r1_3 float64
	_ = r1_3
	var r2_0 uint32
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 float64
	_ = r2_2
	var r2_3 float64
	_ = r2_3
	var r3_0 uint32
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r3_2 float64
	_ = r3_2
	var r3_3 float64
	_ = r3_3
	var r4_0 uint32
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r4_2 float64
	_ = r4_2
	var r4_3 float64
	_ = r4_3
	var ra0_0 [4]uint32
	var ra0_1 [4]float64
	var ra0_2 [4]float64
	var ra0_3 [4]float64
	var ri0 int
	_ = ri0
	var ok78 bool
	var m78_0 float64
	var m78_1 float64
	var m78_2 float64
	var m78_3 float64
	v1 = p0
	v89 = v1
	v90 = v89 - math.Floor(v89/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	r0_0 = v90
	v91 = math.Float64frombits(0x0000000000000000)
	r0_1 = v91
	v92 = math.Float64frombits(0x0000000000000000)
	r0_2 = v92
	v93 = math.Float64frombits(0x4024000000000000)
	r0_3 = v93
	v97 = uint32(5)
	r1_0 = v97
	v98 = math.Float64frombits(0x3ff0000000000000)
	r1_1 = v98
	v99 = math.Float64frombits(0x4000000000000000)
	r1_2 = v99
	v100 = math.Float64frombits(0x0000000000000000)
	r1_3 = v100
	ra0_0[0] = r1_0
	ra0_1[0] = r1_1
	ra0_2[0] = r1_2
	ra0_3[0] = r1_3
	v102 = uint32(6)
	r2_0 = v102
	v103 = math.Float64frombits(0x4008000000000000)
	r2_1 = v103
	v104 = math.Float64frombits(0x4010000000000000)
	r2_2 = v104
	v105 = math.Float64frombits(0x4014000000000000)
	r2_3 = v105
	ra0_0[1] = r2_0
	ra0_1[1] = r2_1
	ra0_2[1] = r2_2
	ra0_3[1] = r2_3
	v107 = uint32(7)
	r3_0 = v107
	v108 = math.Float64frombits(0x4018000000000000)
	r3_1 = v108
	v109 = math.Float64frombits(0x0000000000000000)
	r3_2 = v109
	v110 = math.Float64frombits(0x0000000000000000)
	r3_3 = v110
	ra0_0[2] = r3_0
	ra0_1[2] = r3_1
	ra0_2[2] = r3_2
	ra0_3[2] = r3_3
	v112 = uint32(8)
	r4_0 = v112
	v113 = math.Float64frombits(0x0000000000000000)
	r4_1 = v113
	v114 = math.Float64frombits(0x0000000000000000)
	r4_2 = v114
	v115 = math.Float64frombits(0x0000000000000000)
	r4_3 = v115
	ra0_0[3] = r4_0
	ra0_1[3] = r4_1
	ra0_2[3] = r4_2
	ra0_3[3] = r4_3
	v116 = math.Float64frombits(0x0000000000000000)
	v118 = math.Float64frombits(0x404e000000000000)
	v119 = v1
	v120 = v119 - math.Floor(v119/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v121 = v118 + v120
	v123 = math.Float64frombits(0x3ff0000000000000)
	v124 = v121 + math.Float64frombits(0x0000000000000000)
	v125 = math.Float64frombits(0x3ff0000000000000)
	v36 = v116
	v37 = v123
	v38 = v124
	v39 = v125
	goto b1
b1:
	if math.IsNaN(v37) {
		return 0, false
	}
	if math.IsNaN(v38) {
		return 0, false
	}
	if math.IsNaN(v39) {
		return 0, false
	}
	if (v39 > 0 && v37 > v38) || (v39 <= 0 && v37 < v38) {
		goto b6
	}
	goto b2
b2:
	ri0 = 0
	v65 = v36
	v66 = v37
	v67 = v38
	v68 = v39
	goto b3
b3:
	if ri0 >= 4 {
		goto b5
	}
	v131 = float64(ri0 + 1)
	ri0++
	goto b4
b4:
	v133 = math.Float64frombits(0x3ff0000000000000)
	if v131 < 1 || v131 > 4 {
		return 0, false
	}
	v134 = ra0_0[int(v131)-1]
	v135 = math.Float64frombits(0x4000000000000000)
	if v131 < 1 || v131 > 4 {
		return 0, false
	}
	v136 = ra0_1[int(v131)-1]
	v137 = v66
	v138 = v137 - math.Floor(v137/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v139 = v136 + v138
	v140 = math.Float64frombits(0x4008000000000000)
	if v131 < 1 || v131 > 4 {
		return 0, false
	}
	v141 = ra0_2[int(v131)-1]
	v142 = math.Float64frombits(0x4010000000000000)
	if v131 < 1 || v131 > 4 {
		return 0, false
	}
	v143 = ra0_3[int(v131)-1]
	m78_0 = r0_0
	m78_1 = r0_1
	m78_2 = r0_3
	m78_3 = r0_2
	v144, v145, v146, ok78 = backendGeneratedCommandApply(&m78_0, &m78_1, &m78_2, &m78_3, v134, v139, v141, v143)
	if !ok78 {
		return 0, false
	}
	r0_0 = m78_0
	r0_1 = m78_1
	r0_3 = m78_2
	r0_2 = m78_3
	v147 = v141
	_ = v147
	v148 = v143
	_ = v148
	v149 = v133
	_ = v149
	v150 = v135
	_ = v150
	v151 = v140
	_ = v151
	v152 = v142
	_ = v152
	v154 = v144
	v155 = v145
	v156 = v146
	v157 = v154
	v158 = v65 + v157
	v159 = v155
	v160 = v158 + v159
	v161 = v156
	v162 = v160 + v161
	v65 = v162
	goto b3
b5:
	v163 = v66 + v68
	v36 = v65
	v37 = v163
	v38 = v67
	v39 = v68
	goto b1
b6:
	v164 = v36
	v165 = r0_0
	v166 = v164 + v165
	v167 = r0_1
	v168 = v166 + v167
	v169 = r0_2
	v170 = v168 + v169
	v171 = r0_3
	v172 = v170 + v171
	return v172, true
}

func backendGeneratedCommandRouterPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v36 float64
	var v37 float64
	var v38 float64
	var v39 float64
	var v65 float64
	var v66 float64
	var v67 float64
	var v68 float64
	var v89 float64
	var v90 float64
	var v91 float64
	var v92 float64
	var v93 float64
	var v97 uint32
	var v98 float64
	var v99 float64
	var v100 float64
	var v102 uint32
	var v103 float64
	var v104 float64
	var v105 float64
	var v107 uint32
	var v108 float64
	var v109 float64
	var v110 float64
	var v112 uint32
	var v113 float64
	var v114 float64
	var v115 float64
	var v116 float64
	var v118 float64
	var v119 float64
	var v120 float64
	var v121 float64
	var v123 float64
	var v124 float64
	var v125 float64
	var v131 float64
	var v133 float64
	var v134 uint32
	var v135 float64
	var v136 float64
	var v137 float64
	var v138 float64
	var v139 float64
	var v140 float64
	var v141 float64
	var v142 float64
	var v143 float64
	var v144 float64
	var v145 float64
	var v146 float64
	var v147 float64
	var v148 float64
	var v149 float64
	var v150 float64
	var v151 float64
	var v152 float64
	var v154 float64
	var v155 float64
	var v156 float64
	var v157 float64
	var v158 float64
	var v159 float64
	var v160 float64
	var v161 float64
	var v162 float64
	var v163 float64
	var v164 float64
	var v165 float64
	var v166 float64
	var v167 float64
	var v168 float64
	var v169 float64
	var v170 float64
	var v171 float64
	var v172 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r1_0 uint32
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r1_3 float64
	_ = r1_3
	var r2_0 uint32
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 float64
	_ = r2_2
	var r2_3 float64
	_ = r2_3
	var r3_0 uint32
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r3_2 float64
	_ = r3_2
	var r3_3 float64
	_ = r3_3
	var r4_0 uint32
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var r4_2 float64
	_ = r4_2
	var r4_3 float64
	_ = r4_3
	var ra0_0 [4]uint32
	var ra0_1 [4]float64
	var ra0_2 [4]float64
	var ra0_3 [4]float64
	var ri0 int
	_ = ri0
	var ok78 bool
	var m78_0 float64
	var m78_1 float64
	var m78_2 float64
	var m78_3 float64
	v1 = p0
	v89 = v1
	v90 = v89 - math.Floor(v89/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	r0_0 = v90
	v91 = math.Float64frombits(0x0000000000000000)
	r0_1 = v91
	v92 = math.Float64frombits(0x0000000000000000)
	r0_2 = v92
	v93 = math.Float64frombits(0x4024000000000000)
	r0_3 = v93
	v97 = uint32(5)
	r1_0 = v97
	v98 = math.Float64frombits(0x3ff0000000000000)
	r1_1 = v98
	v99 = math.Float64frombits(0x4000000000000000)
	r1_2 = v99
	v100 = math.Float64frombits(0x0000000000000000)
	r1_3 = v100
	ra0_0[0] = r1_0
	ra0_1[0] = r1_1
	ra0_2[0] = r1_2
	ra0_3[0] = r1_3
	v102 = uint32(6)
	r2_0 = v102
	v103 = math.Float64frombits(0x4008000000000000)
	r2_1 = v103
	v104 = math.Float64frombits(0x4010000000000000)
	r2_2 = v104
	v105 = math.Float64frombits(0x4014000000000000)
	r2_3 = v105
	ra0_0[1] = r2_0
	ra0_1[1] = r2_1
	ra0_2[1] = r2_2
	ra0_3[1] = r2_3
	v107 = uint32(7)
	r3_0 = v107
	v108 = math.Float64frombits(0x4018000000000000)
	r3_1 = v108
	v109 = math.Float64frombits(0x0000000000000000)
	r3_2 = v109
	v110 = math.Float64frombits(0x0000000000000000)
	r3_3 = v110
	ra0_0[2] = r3_0
	ra0_1[2] = r3_1
	ra0_2[2] = r3_2
	ra0_3[2] = r3_3
	v112 = uint32(8)
	r4_0 = v112
	v113 = math.Float64frombits(0x0000000000000000)
	r4_1 = v113
	v114 = math.Float64frombits(0x0000000000000000)
	r4_2 = v114
	v115 = math.Float64frombits(0x0000000000000000)
	r4_3 = v115
	ra0_0[3] = r4_0
	ra0_1[3] = r4_1
	ra0_2[3] = r4_2
	ra0_3[3] = r4_3
	v116 = math.Float64frombits(0x0000000000000000)
	v118 = math.Float64frombits(0x404e000000000000)
	v119 = v1
	v120 = v119 - math.Floor(v119/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v121 = v118 + v120
	v123 = math.Float64frombits(0x3ff0000000000000)
	v124 = v121 + math.Float64frombits(0x0000000000000000)
	v125 = math.Float64frombits(0x3ff0000000000000)
	v36 = v116
	v37 = v123
	v38 = v124
	v39 = v125
	goto b1
b1:
	if math.IsNaN(v37) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v38) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v39) {
		return machinePreparedReplayEntry()
	}
	if (v39 > 0 && v37 > v38) || (v39 <= 0 && v37 < v38) {
		goto b6
	}
	goto b2
b2:
	ri0 = 0
	v65 = v36
	v66 = v37
	v67 = v38
	v68 = v39
	goto b3
b3:
	if ri0 >= 4 {
		goto b5
	}
	v131 = float64(ri0 + 1)
	ri0++
	goto b4
b4:
	v133 = math.Float64frombits(0x3ff0000000000000)
	if v131 < 1 || v131 > 4 {
		return machinePreparedReplayEntry()
	}
	v134 = ra0_0[int(v131)-1]
	v135 = math.Float64frombits(0x4000000000000000)
	if v131 < 1 || v131 > 4 {
		return machinePreparedReplayEntry()
	}
	v136 = ra0_1[int(v131)-1]
	v137 = v66
	v138 = v137 - math.Floor(v137/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v139 = v136 + v138
	v140 = math.Float64frombits(0x4008000000000000)
	if v131 < 1 || v131 > 4 {
		return machinePreparedReplayEntry()
	}
	v141 = ra0_2[int(v131)-1]
	v142 = math.Float64frombits(0x4010000000000000)
	if v131 < 1 || v131 > 4 {
		return machinePreparedReplayEntry()
	}
	v143 = ra0_3[int(v131)-1]
	m78_0 = r0_0
	m78_1 = r0_1
	m78_2 = r0_3
	m78_3 = r0_2
	v144, v145, v146, ok78 = backendGeneratedCommandApply(&m78_0, &m78_1, &m78_2, &m78_3, v134, v139, v141, v143)
	if !ok78 {
		return machinePreparedReplayEntry()
	}
	r0_0 = m78_0
	r0_1 = m78_1
	r0_3 = m78_2
	r0_2 = m78_3
	v147 = v141
	_ = v147
	v148 = v143
	_ = v148
	v149 = v133
	_ = v149
	v150 = v135
	_ = v150
	v151 = v140
	_ = v151
	v152 = v142
	_ = v152
	v154 = v144
	v155 = v145
	v156 = v146
	v157 = v154
	v158 = v65 + v157
	v159 = v155
	v160 = v158 + v159
	v161 = v156
	v162 = v160 + v161
	v65 = v162
	goto b3
b5:
	v163 = v66 + v68
	v36 = v65
	v37 = v163
	v38 = v67
	v39 = v68
	goto b1
b6:
	v164 = v36
	v165 = r0_0
	v166 = v164 + v165
	v167 = r0_1
	v168 = v166 + v167
	v169 = r0_2
	v170 = v168 + v169
	v171 = r0_3
	v172 = v170 + v171
	return machinePreparedReturnOneNumber(v172)
}

func backendGeneratedCommandRouterPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchangedAt(2, 50) {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedCommandRouterPreparedFixtureBody(context, p0)
}
