package ember

import (
	"bytes"
	"context"
	"os"
	"testing"
)

const externalPreparedFixtureSource = `
return {
    update = function(value)
        return value + 1
    end,
}
`

const externalPreparedFixtureUpdateEnvironment = "EMBER_UPDATE_EXTERNAL_PREPARED_FIXTURE"

func TestExternalPreparedFixtureIsFresh(t *testing.T) {
	generated := externalPreparedFixtureGeneratedSource(t)
	if os.Getenv(externalPreparedFixtureUpdateEnvironment) == "1" {
		if err := os.WriteFile("internal/preparedfixture/prepared_generated.go", generated, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	onDisk, err := os.ReadFile("internal/preparedfixture/prepared_generated.go")
	if err != nil {
		t.Fatalf("read external prepared fixture: %v\nexpected source:\n%s", err, generated)
	}
	if !bytes.Equal(generated, onDisk) {
		t.Fatalf("external prepared fixture is stale\nexpected source:\n%s", generated)
	}
}

func TestAssemblePreparedGoSourceAlwaysImportsBundleABI(t *testing.T) {
	generated, err := assemblePreparedGoSource(
		"preparedfixture",
		&backendProgramIR{},
		[]backendGoNumericModule{{functions: []string{""}}},
		nil,
	)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(generated, []byte(`emberapi "github.com/besmpl/ember"`)) {
		t.Fatalf("generated bundle source lacks Ember ABI import:\n%s", generated)
	}
}

func externalPreparedFixtureGeneratedSource(t *testing.T) []byte {
	t.Helper()
	module := LogicalModule("prepared/external")
	program, _, err := LoadProgram(context.Background(), machineRuntimeTestLoader{
		module.String(): externalPreparedFixtureSource,
	}, ProgramOptions{Entrypoints: []Entrypoint{{Name: "main", Module: module}}, Parallelism: 1})
	if err != nil {
		t.Fatal(err)
	}
	var generated bytes.Buffer
	if err := program.WritePreparedGo(&generated, PreparedGoOptions{Package: "preparedfixture"}); err != nil {
		t.Fatal(err)
	}
	return generated.Bytes()
}
