// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedArrayHoleCompaction(p0 float64) (float64, bool) {
	var v1 float64
	var v25 float64
	var v27 float64
	var v28 float64
	var v29 float64
	var v49 float64
	var v58 float64
	var v59 float64
	var v60 float64
	var v61 float64
	var v73 float64
	var v82 float64
	var v83 float64
	var v84 float64
	var v85 float64
	var v86 float64
	var v97 float64
	var v106 float64
	var v107 float64
	var v108 float64
	var v109 float64
	var v123 float64
	var v124 float64
	var v125 float64
	var v126 float64
	var v128 float64
	var v129 float64
	var v130 float64
	var v132 float64
	var v133 float64
	var v134 float64
	var v135 float64
	var v136 float64
	var v137 bool
	var v138 float64
	var v139 float64
	var v140 float64
	var v141 float64
	var v142 float64
	var v143 float64
	var v144 float64
	var v145 float64
	var v146 float64
	var v147 float64
	var v148 float64
	var v150 float64
	var v151 float64
	var v152 float64
	var v153 float64
	var v154 float64
	var v155 float64
	var v156 float64
	var v157 float64
	var v158 float64
	var v159 float64
	var v160 float64
	var v161 float64
	var v163 float64
	var v165 float64
	var v166 float64
	var v169 float64
	var v170 float64
	var v171 float64
	var v172 float64
	var v173 bool
	var v175 float64
	var v176 float64
	var v178 float64
	var v179 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 bool
	_ = r0_1
	var r1_0 float64
	_ = r1_0
	var r1_1 bool
	_ = r1_1
	var ra0_0 [104]float64
	var ra0_1 [104]bool
	var ri0 int
	_ = ri0
	var rn0 = 0
	_ = rn0
	v1 = p0
	v123 = math.Float64frombits(0x403e000000000000)
	v124 = v1
	v125 = v124 - math.Floor(v124/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v126 = v123 + v125
	v128 = math.Float64frombits(0x3ff0000000000000)
	v129 = v126 + math.Float64frombits(0x0000000000000000)
	v130 = math.Float64frombits(0x3ff0000000000000)
	v25 = v1
	v27 = v128
	v28 = v129
	v29 = v130
	goto b1
b1:
	if math.IsNaN(v27) {
		return 0, false
	}
	if math.IsNaN(v28) {
		return 0, false
	}
	if math.IsNaN(v29) {
		return 0, false
	}
	if (v29 > 0 && v27 > v28) || (v29 <= 0 && v27 < v28) {
		goto b3
	}
	goto b2
b2:
	v132 = v27
	v133 = v132 * math.Float64frombits(0x4008000000000000)
	v134 = v25
	v135 = v134 - math.Floor(v134/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v136 = v133 + v135
	r0_0 = v136
	v137 = true
	r0_1 = v137
	v138 = v27
	if v138 != float64(rn0+1) || v138 != math.Trunc(v138) || rn0 >= 104 {
		return 0, false
	}
	ra0_0[rn0] = r0_0
	ra0_1[rn0] = r0_1
	rn0++
	v139 = v27 + v29
	v25 = v25
	v27 = v139
	v28 = v28
	v29 = v29
	goto b1
b3:
	v140 = math.Float64frombits(0x0000000000000000)
	v141 = math.Float64frombits(0x4051800000000000)
	v142 = v25
	v143 = v142 - math.Floor(v142/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v144 = v141 + v143
	v145 = math.Float64frombits(0x3ff0000000000000)
	v146 = v144 + math.Float64frombits(0x0000000000000000)
	v147 = math.Float64frombits(0x3ff0000000000000)
	v49 = v25
	v58 = v140
	v59 = v145
	v60 = v146
	v61 = v147
	goto b4
b4:
	if math.IsNaN(v59) {
		return 0, false
	}
	if math.IsNaN(v60) {
		return 0, false
	}
	if math.IsNaN(v61) {
		return 0, false
	}
	if (v61 > 0 && v59 > v60) || (v61 <= 0 && v59 < v60) {
		goto b13
	}
	goto b5
b5:
	v148 = math.Float64frombits(0x3ff0000000000000)
	v73 = v49
	v82 = v58
	v83 = v59
	v84 = v60
	v85 = v61
	v86 = v148
	goto b6
b6:
	v150 = float64(rn0)
	v151 = v150
	if math.IsNaN(v86) {
		return 0, false
	}
	if math.IsNaN(v151) {
		return 0, false
	}
	if v86 > v151 {
		goto b10
	}
	goto b7
b7:
	v152 = v86
	v153 = 0
	if v152 >= 1 && v152 <= float64(rn0) && v152 == math.Trunc(v152) {
		v153 = v152
	}
	if v153 < 1 || v153 > float64(rn0) {
		return 0, false
	}
	v154 = ra0_0[int(v153)-1]
	v155 = v83
	v156 = v155 - math.Floor(v155/math.Float64frombits(0x4018000000000000))*math.Float64frombits(0x4018000000000000)
	v157 = v154 + v156
	if v153 < 1 || v153 > float64(rn0) {
		return 0, false
	}
	ra0_0[int(v153)-1] = v157
	if v153 < 1 || v153 > float64(rn0) {
		return 0, false
	}
	v158 = ra0_0[int(v153)-1]
	v159 = v82 + v158
	if v153 < 1 || v153 > float64(rn0) {
		return 0, false
	}
	v160 = ra0_0[int(v153)-1]
	v161 = v160 - math.Floor(v160/math.Float64frombits(0x402a000000000000))*math.Float64frombits(0x402a000000000000)
	if v161 != math.Float64frombits(0x0000000000000000) {
		goto b9
	}
	goto b8
b8:
	v163 = v86
	if v163 < 1 || v163 > float64(rn0) || v163 != math.Trunc(v163) {
		return 0, false
	}
	for rrm51 := int(v163) - 1; rrm51 < rn0-1; rrm51++ {
		ra0_0[rrm51] = ra0_0[rrm51+1]
		ra0_1[rrm51] = ra0_1[rrm51+1]
	}
	rn0--
	v73 = v73
	v82 = v159
	v83 = v83
	v84 = v84
	v85 = v85
	v86 = v86
	goto b6
b9:
	v165 = v86 + math.Float64frombits(0x3ff0000000000000)
	v73 = v73
	v82 = v159
	v83 = v83
	v84 = v84
	v85 = v85
	v86 = v165
	goto b6
b10:
	v166 = v83 - math.Floor(v83/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	if v166 != math.Float64frombits(0x0000000000000000) {
		v97 = v73
		v106 = v82
		v107 = v83
		v108 = v84
		v109 = v85
		goto b12
	}
	goto b11
b11:
	v169 = v83
	v170 = v73
	v171 = v170 - math.Floor(v170/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v172 = v169 + v171
	r1_0 = v172
	v173 = true
	r1_1 = v173
	if rn0 >= 104 {
		return 0, false
	}
	ra0_0[rn0] = r1_0
	ra0_1[rn0] = r1_1
	rn0++
	v97 = v73
	v106 = v82
	v107 = v83
	v108 = v84
	v109 = v85
	goto b12
b12:
	v175 = v107 + v109
	v49 = v97
	v58 = v106
	v59 = v175
	v60 = v108
	v61 = v109
	goto b4
b13:
	v176 = v58
	v178 = float64(rn0)
	v179 = v176 + v178
	return v179, true
}

func backendGeneratedArrayHoleCompactionPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v25 float64
	var v27 float64
	var v28 float64
	var v29 float64
	var v49 float64
	var v58 float64
	var v59 float64
	var v60 float64
	var v61 float64
	var v73 float64
	var v82 float64
	var v83 float64
	var v84 float64
	var v85 float64
	var v86 float64
	var v97 float64
	var v106 float64
	var v107 float64
	var v108 float64
	var v109 float64
	var v123 float64
	var v124 float64
	var v125 float64
	var v126 float64
	var v128 float64
	var v129 float64
	var v130 float64
	var v132 float64
	var v133 float64
	var v134 float64
	var v135 float64
	var v136 float64
	var v137 bool
	var v138 float64
	var v139 float64
	var v140 float64
	var v141 float64
	var v142 float64
	var v143 float64
	var v144 float64
	var v145 float64
	var v146 float64
	var v147 float64
	var v148 float64
	var v150 float64
	var v151 float64
	var v152 float64
	var v153 float64
	var v154 float64
	var v155 float64
	var v156 float64
	var v157 float64
	var v158 float64
	var v159 float64
	var v160 float64
	var v161 float64
	var v163 float64
	var v165 float64
	var v166 float64
	var v169 float64
	var v170 float64
	var v171 float64
	var v172 float64
	var v173 bool
	var v175 float64
	var v176 float64
	var v178 float64
	var v179 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 bool
	_ = r0_1
	var r1_0 float64
	_ = r1_0
	var r1_1 bool
	_ = r1_1
	var ra0_0 [104]float64
	var ra0_1 [104]bool
	var ri0 int
	_ = ri0
	var rn0 = 0
	_ = rn0
	v1 = p0
	v123 = math.Float64frombits(0x403e000000000000)
	v124 = v1
	v125 = v124 - math.Floor(v124/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v126 = v123 + v125
	v128 = math.Float64frombits(0x3ff0000000000000)
	v129 = v126 + math.Float64frombits(0x0000000000000000)
	v130 = math.Float64frombits(0x3ff0000000000000)
	v25 = v1
	v27 = v128
	v28 = v129
	v29 = v130
	goto b1
b1:
	if math.IsNaN(v27) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v28) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v29) {
		return machinePreparedReplayEntry()
	}
	if (v29 > 0 && v27 > v28) || (v29 <= 0 && v27 < v28) {
		goto b3
	}
	goto b2
b2:
	v132 = v27
	v133 = v132 * math.Float64frombits(0x4008000000000000)
	v134 = v25
	v135 = v134 - math.Floor(v134/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v136 = v133 + v135
	r0_0 = v136
	v137 = true
	r0_1 = v137
	v138 = v27
	if v138 != float64(rn0+1) || v138 != math.Trunc(v138) || rn0 >= 104 {
		return machinePreparedReplayEntry()
	}
	ra0_0[rn0] = r0_0
	ra0_1[rn0] = r0_1
	rn0++
	v139 = v27 + v29
	v25 = v25
	v27 = v139
	v28 = v28
	v29 = v29
	goto b1
b3:
	v140 = math.Float64frombits(0x0000000000000000)
	v141 = math.Float64frombits(0x4051800000000000)
	v142 = v25
	v143 = v142 - math.Floor(v142/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v144 = v141 + v143
	v145 = math.Float64frombits(0x3ff0000000000000)
	v146 = v144 + math.Float64frombits(0x0000000000000000)
	v147 = math.Float64frombits(0x3ff0000000000000)
	v49 = v25
	v58 = v140
	v59 = v145
	v60 = v146
	v61 = v147
	goto b4
b4:
	if math.IsNaN(v59) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v60) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v61) {
		return machinePreparedReplayEntry()
	}
	if (v61 > 0 && v59 > v60) || (v61 <= 0 && v59 < v60) {
		goto b13
	}
	goto b5
b5:
	v148 = math.Float64frombits(0x3ff0000000000000)
	v73 = v49
	v82 = v58
	v83 = v59
	v84 = v60
	v85 = v61
	v86 = v148
	goto b6
b6:
	v150 = float64(rn0)
	v151 = v150
	if math.IsNaN(v86) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v151) {
		return machinePreparedReplayEntry()
	}
	if v86 > v151 {
		goto b10
	}
	goto b7
b7:
	v152 = v86
	v153 = 0
	if v152 >= 1 && v152 <= float64(rn0) && v152 == math.Trunc(v152) {
		v153 = v152
	}
	if v153 < 1 || v153 > float64(rn0) {
		return machinePreparedReplayEntry()
	}
	v154 = ra0_0[int(v153)-1]
	v155 = v83
	v156 = v155 - math.Floor(v155/math.Float64frombits(0x4018000000000000))*math.Float64frombits(0x4018000000000000)
	v157 = v154 + v156
	if v153 < 1 || v153 > float64(rn0) {
		return machinePreparedReplayEntry()
	}
	ra0_0[int(v153)-1] = v157
	if v153 < 1 || v153 > float64(rn0) {
		return machinePreparedReplayEntry()
	}
	v158 = ra0_0[int(v153)-1]
	v159 = v82 + v158
	if v153 < 1 || v153 > float64(rn0) {
		return machinePreparedReplayEntry()
	}
	v160 = ra0_0[int(v153)-1]
	v161 = v160 - math.Floor(v160/math.Float64frombits(0x402a000000000000))*math.Float64frombits(0x402a000000000000)
	if v161 != math.Float64frombits(0x0000000000000000) {
		goto b9
	}
	goto b8
b8:
	v163 = v86
	if v163 < 1 || v163 > float64(rn0) || v163 != math.Trunc(v163) {
		return machinePreparedReplayEntry()
	}
	for rrm51 := int(v163) - 1; rrm51 < rn0-1; rrm51++ {
		ra0_0[rrm51] = ra0_0[rrm51+1]
		ra0_1[rrm51] = ra0_1[rrm51+1]
	}
	rn0--
	v73 = v73
	v82 = v159
	v83 = v83
	v84 = v84
	v85 = v85
	v86 = v86
	goto b6
b9:
	v165 = v86 + math.Float64frombits(0x3ff0000000000000)
	v73 = v73
	v82 = v159
	v83 = v83
	v84 = v84
	v85 = v85
	v86 = v165
	goto b6
b10:
	v166 = v83 - math.Floor(v83/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	if v166 != math.Float64frombits(0x0000000000000000) {
		v97 = v73
		v106 = v82
		v107 = v83
		v108 = v84
		v109 = v85
		goto b12
	}
	goto b11
b11:
	v169 = v83
	v170 = v73
	v171 = v170 - math.Floor(v170/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v172 = v169 + v171
	r1_0 = v172
	v173 = true
	r1_1 = v173
	if rn0 >= 104 {
		return machinePreparedReplayEntry()
	}
	ra0_0[rn0] = r1_0
	ra0_1[rn0] = r1_1
	rn0++
	v97 = v73
	v106 = v82
	v107 = v83
	v108 = v84
	v109 = v85
	goto b12
b12:
	v175 = v107 + v109
	v49 = v97
	v58 = v106
	v59 = v175
	v60 = v108
	v61 = v109
	goto b4
b13:
	v176 = v58
	v178 = float64(rn0)
	v179 = v176 + v178
	return machinePreparedReturnOneNumber(v179)
}

func backendGeneratedArrayHoleCompactionPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchanged(34) {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchanged(51) {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchanged(66) {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchanged(70) {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedArrayHoleCompactionPreparedFixtureBody(context, p0)
}
