package ember

import (
	"context"
	"errors"
	"math"
	"reflect"
	"testing"
)

func TestMachineToStringMatchesOldVMScalars(t *testing.T) {
	arena := new(machineStringArena)
	textID, err := arena.internStringStopped("already-text")
	if err != nil {
		t.Fatal(err)
	}
	textSlot, err := slotPackHandle(slotTagString, uint32(textID), 1)
	if err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		name      string
		operand   machineScalarOperand
		old       Value
		wantKind  machineStringActionKind
		generated bool
	}{
		{name: "nil", operand: machineScalarOperand{value: slotNil}, old: NilValue(), wantKind: machineStringActionIntern},
		{name: "false", operand: machineScalarOperand{value: slotBool(false)}, old: BoolValue(false), wantKind: machineStringActionIntern},
		{name: "true", operand: machineScalarOperand{value: slotBool(true)}, old: BoolValue(true), wantKind: machineStringActionIntern},
		{name: "string", operand: machineScalarOperand{value: textSlot}, old: StringValue("already-text"), wantKind: machineStringActionReuse},
	}
	for _, number := range []float64{0, math.Copysign(0, -1), 25, -17.5, math.NaN(), math.Inf(1), math.Inf(-1)} {
		tests = append(tests, struct {
			name      string
			operand   machineScalarOperand
			old       Value
			wantKind  machineStringActionKind
			generated bool
		}{name: formatLuauNumber(number), operand: machineTestScalarNumber(t, number), old: NumberValue(number), wantKind: machineStringActionIntern, generated: true})
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			scratch, action, err := machinePrepareToString([]byte("prefix:"), test.operand, arena)
			if err != nil {
				t.Fatal(err)
			}
			if action.kind != test.wantKind {
				t.Fatalf("action kind = %v, want %v", action.kind, test.wantKind)
			}
			text, err := machineStringActionBytes(action, scratch, arena)
			if err != nil {
				t.Fatal(err)
			}
			if got, want := string(text), valueToString(test.old); got != want {
				t.Fatalf("text = %q, want %q", got, want)
			}
			wantGenerated := uint64(0)
			if test.generated {
				wantGenerated = uint64(len(text))
			}
			if action.generatedBytes != wantGenerated {
				t.Fatalf("generated bytes = %d, want %d", action.generatedBytes, wantGenerated)
			}
		})
	}
}

func TestMachineConcatAndChainMatchOldVM(t *testing.T) {
	arena := new(machineStringArena)
	stringOperand := func(text string) machineScalarOperand {
		id, err := arena.internStringStopped(text)
		if err != nil {
			t.Fatal(err)
		}
		value, err := slotPackHandle(slotTagString, uint32(id), 1)
		if err != nil {
			t.Fatal(err)
		}
		return machineScalarOperand{value: value}
	}

	left := stringOperand("hp:")
	right := machineTestScalarNumber(t, math.Copysign(0, -1))
	scratch, action, err := machinePrepareConcat([]byte("keep"), left, right, arena)
	if err != nil {
		t.Fatal(err)
	}
	text, err := machineStringActionBytes(action, scratch, arena)
	if err != nil {
		t.Fatal(err)
	}
	want, err := valuesConcat(StringValue("hp:"), NumberValue(math.Copysign(0, -1)))
	if err != nil {
		t.Fatal(err)
	}
	if string(text) != want || action.generatedBytes != uint64(len(want)) {
		t.Fatalf("concat = %q/%d, want %q/%d", text, action.generatedBytes, want, len(want))
	}

	operands := []machineScalarOperand{
		stringOperand("hp"), stringOperand(":"), machineTestScalarNumber(t, 25),
		stringOperand("/"), machineTestScalarNumber(t, math.Inf(1)),
	}
	scratch, action, err = machinePrepareConcatChain(nil, operands, arena)
	if err != nil {
		t.Fatal(err)
	}
	text, err = machineStringActionBytes(action, scratch, arena)
	if err != nil {
		t.Fatal(err)
	}
	old := []Value{StringValue("hp"), StringValue(":"), NumberValue(25), StringValue("/"), NumberValue(math.Inf(1))}
	want, ok, err := valuesConcatRawChain(old)
	if err != nil || !ok {
		t.Fatalf("old VM concat = %q, %t, %v", want, ok, err)
	}
	if string(text) != want || action.generatedBytes != uint64(len(want)) {
		t.Fatalf("chain = %q/%d, want %q/%d", text, action.generatedBytes, want, len(want))
	}
}

func TestMachineConcatReturnsEffectWithoutMutatingScratch(t *testing.T) {
	prefix := []byte("preserve")
	scratch, action, err := machinePrepareConcat(prefix, machineScalarOperand{value: slotBool(true)}, machineTestScalarNumber(t, 1), nil)
	if err != nil {
		t.Fatal(err)
	}
	if action.kind != machineStringActionEffect || action.operand != 0 {
		t.Fatalf("action = %#v, want left-operand effect", action)
	}
	if _, oldErr := concatOperandString(BoolValue(true), "left"); oldErr == nil || oldErr.Error() != "concat left operand is boolean, want string or number" {
		t.Fatalf("old-VM concat error = %v", oldErr)
	}
	if string(scratch) != "preserve" {
		t.Fatalf("scratch = %q, want unchanged", scratch)
	}

	scratch, action, err = machinePrepareConcatChain(prefix, []machineScalarOperand{
		machineTestScalarNumber(t, 1),
		{value: slotBool(false)},
		machineTestScalarNumber(t, 2),
	}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if action.kind != machineStringActionEffect || action.operand != 1 || string(scratch) != "preserve" {
		t.Fatalf("chain action/scratch = %#v/%q", action, scratch)
	}
}

func TestMachineStringHelpersDoNotInternOrGrowOwnerArenas(t *testing.T) {
	arena := new(machineStringArena)
	id, err := arena.internStringStopped("left")
	if err != nil {
		t.Fatal(err)
	}
	leftSlot, err := slotPackHandle(slotTagString, uint32(id), 1)
	if err != nil {
		t.Fatal(err)
	}
	records, bytes, index := len(arena.records), len(arena.data), len(arena.index)
	scratch := make([]byte, 0, 32)
	scratch, action, err := machinePrepareConcat(scratch,
		machineScalarOperand{value: leftSlot}, machineTestScalarNumber(t, 25), arena)
	if err != nil {
		t.Fatal(err)
	}
	if action.kind != machineStringActionIntern || string(scratch) != "left25" {
		t.Fatalf("prepared = %#v/%q", action, scratch)
	}
	if len(arena.records) != records || len(arena.data) != bytes || len(arena.index) != index {
		t.Fatalf("helper mutated string arena: records %d->%d bytes %d->%d index %d->%d",
			records, len(arena.records), bytes, len(arena.data), index, len(arena.index))
	}
}

func TestMachineGeneratedStringAccountingIsStoppedAndInternAware(t *testing.T) {
	controller, err := newExecutionController(context.Background(), ExecutionLimits{MaxGeneratedStringBytes: 4})
	if err != nil {
		t.Fatal(err)
	}
	action := machineStringAction{kind: machineStringActionIntern, generatedBytes: 4}
	if err := machineChargeGeneratedStringStopped(controller, action, false); err != nil {
		t.Fatalf("exact limit: %v", err)
	}
	if err := machineChargeGeneratedStringStopped(controller, action, true); err != nil {
		t.Fatalf("interned repeat charged: %v", err)
	}
	if got := controller.generatedStringBytes; got != 4 {
		t.Fatalf("used = %d, want 4", got)
	}
	if err := machineChargeGeneratedStringStopped(controller, machineStringAction{kind: machineStringActionIntern, generatedBytes: 1}, false); err == nil {
		t.Fatal("over-limit charge succeeded")
	} else {
		var limit *LimitError
		if !errors.As(err, &limit) || limit.Kind != LimitGeneratedStringBytes || limit.Limit != 4 || limit.Used != 5 {
			t.Fatalf("limit = %#v (%v)", limit, err)
		}
	}
	if got := controller.generatedStringBytes; got != 4 {
		t.Fatalf("failed charge mutated used = %d", got)
	}
}

func TestMachineStringActionIsPointerFree(t *testing.T) {
	if machineTestTypeContainsPointers(reflect.TypeOf(machineStringAction{})) || machineTestTypeContainsPointers(reflect.TypeOf(machineScalarOperand{})) {
		t.Fatal("machine string action or operand contains pointers")
	}
}
