// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedPrototypeFallback(p0 float64) (float64, bool) {
	var v1 float64
	var v33 float64
	var v43 float64
	var v44 float64
	var v45 float64
	var v46 float64
	var v61 float64
	var v71 float64
	var v72 float64
	var v73 float64
	var v74 float64
	var v89 float64
	var v99 float64
	var v100 float64
	var v101 float64
	var v102 float64
	var v106 float64
	var v109 float64
	var v114 float64
	var v115 float64
	var v116 float64
	var v117 float64
	var v118 float64
	var v119 float64
	var v120 float64
	var v125 float64
	var v126 float64
	var v127 float64
	var v128 float64
	var v133 float64
	var v134 float64
	var v139 float64
	var v140 float64
	var v144 float64
	var v146 float64
	var v147 float64
	var v148 float64
	var v149 float64
	var v151 float64
	var v152 float64
	var v153 float64
	var v159 float64
	var v160 float64
	var v161 float64
	var v162 float64
	var v163 float64
	var v164 float64
	var v165 float64
	var v166 float64
	var v167 float64
	var v168 float64
	var v169 float64
	var v170 float64
	var v171 float64
	var v172 float64
	var v173 float64
	var v174 float64
	var v175 float64
	var v176 float64
	var v177 float64
	var v178 float64
	var v179 float64
	var v180 float64
	var v181 float64
	var v182 float64
	var v183 float64
	var v184 float64
	var v185 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r1_0 float64
	_ = r1_0
	var r2_0 float64
	_ = r2_0
	var r3_0 float64
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r4_0 float64
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var ra0_0 [3]float64
	var rap0_0 [3]bool
	var ra0_1 [3]float64
	var rap0_1 [3]bool
	var ra0_2 [3]float64
	var rap0_2 [3]bool
	var ra0_3 [3]float64
	var rap0_3 [3]bool
	var ri0 int
	_ = ri0
	var ok57 bool
	var ok58 bool
	var ok60 bool
	var ok62 bool
	var ok64 bool
	var ok68 bool
	var ok72 bool
	var ok79 bool
	var ok81 bool
	v1 = p0
	v114 = math.Float64frombits(0x4034000000000000)
	v115 = v1
	v116 = v115 - math.Floor(v115/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v117 = v114 + v116
	r0_0 = v117
	v118 = math.Float64frombits(0x4014000000000000)
	r0_1 = v118
	v119 = math.Float64frombits(0x4000000000000000)
	r0_2 = v119
	v120 = math.Float64frombits(0x0000000000000000)
	v125 = math.Float64frombits(0x4054000000000000)
	v126 = v1
	v127 = v126 - math.Floor(v126/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v128 = v125 + v127
	r2_0 = v128
	ra0_0[0] = r2_0
	rap0_0[0] = true
	v133 = math.Float64frombits(0x402e000000000000)
	r3_0 = v133
	v134 = math.Float64frombits(0x4010000000000000)
	r3_1 = v134
	ra0_1[1] = r3_0
	rap0_1[1] = true
	ra0_2[1] = r3_1
	rap0_2[1] = true
	v139 = math.Float64frombits(0x4046800000000000)
	r4_0 = v139
	v140 = math.Float64frombits(0x4022000000000000)
	r4_1 = v140
	ra0_0[2] = r4_0
	rap0_0[2] = true
	ra0_3[2] = r4_1
	rap0_3[2] = true
	v144 = math.Float64frombits(0x0000000000000000)
	v146 = math.Float64frombits(0x4054000000000000)
	v147 = v1
	v148 = v147 - math.Floor(v147/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v149 = v146 + v148
	v151 = math.Float64frombits(0x3ff0000000000000)
	v152 = v149 + math.Float64frombits(0x0000000000000000)
	v153 = math.Float64frombits(0x3ff0000000000000)
	v33 = v120
	v43 = v144
	v44 = v151
	v45 = v152
	v46 = v153
	goto b1
b1:
	if math.IsNaN(v44) {
		return 0, false
	}
	if math.IsNaN(v45) {
		return 0, false
	}
	if math.IsNaN(v46) {
		return 0, false
	}
	if (v46 > 0 && v44 > v45) || (v46 <= 0 && v44 < v45) {
		goto b9
	}
	goto b2
b2:
	ri0 = 0
	v61 = v33
	v71 = v43
	v72 = v44
	v73 = v45
	v74 = v46
	goto b3
b3:
	if ri0 >= 3 {
		goto b8
	}
	v159 = float64(ri0 + 1)
	ri0++
	goto b4
b4:
	if v159 < 1 || v159 > 3 {
		return 0, false
	}
	if rap0_0[int(v159)-1] {
		v160 = ra0_0[int(v159)-1]
	} else {
		v160, ok57 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(1))
		if !ok57 {
			return 0, false
		}
	}
	if v159 < 1 || v159 > 3 {
		return 0, false
	}
	if rap0_1[int(v159)-1] {
		v161 = ra0_1[int(v159)-1]
	} else {
		v161, ok58 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(2))
		if !ok58 {
			return 0, false
		}
	}
	v162 = v160 + v161
	if v159 < 1 || v159 > 3 {
		return 0, false
	}
	if rap0_3[int(v159)-1] {
		v163 = ra0_3[int(v159)-1]
	} else {
		v163, ok60 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(5))
		if !ok60 {
			return 0, false
		}
	}
	v164 = v162 + v163
	if v159 < 1 || v159 > 3 {
		return 0, false
	}
	if rap0_2[int(v159)-1] {
		v165 = ra0_2[int(v159)-1]
	} else {
		v165, ok62 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(3))
		if !ok62 {
			return 0, false
		}
	}
	if math.IsNaN(v165) {
		return 0, false
	}
	if !(v165 > math.Float64frombits(0x4008000000000000)) {
		goto b6
	}
	goto b5
b5:
	if v159 < 1 || v159 > 3 {
		return 0, false
	}
	if rap0_0[int(v159)-1] {
		v166 = ra0_0[int(v159)-1]
	} else {
		v166, ok64 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(1))
		if !ok64 {
			return 0, false
		}
	}
	v167 = v72
	v168 = v167 - math.Floor(v167/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v169 = v166 + v168
	if v159 < 1 || v159 > 3 {
		return 0, false
	}
	if rap0_2[int(v159)-1] {
		v170 = ra0_2[int(v159)-1]
	} else {
		v170, ok68 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(3))
		if !ok68 {
			return 0, false
		}
	}
	v171 = v169 - v170
	if v159 < 1 || v159 > 3 {
		return 0, false
	}
	ra0_0[int(v159)-1] = v171
	rap0_0[int(v159)-1] = true
	v89 = v61
	v99 = v71
	v100 = v72
	v101 = v73
	v102 = v74
	v106 = v159
	v109 = v164
	goto b7
b6:
	if v159 < 1 || v159 > 3 {
		return 0, false
	}
	if rap0_1[int(v159)-1] {
		v172 = ra0_1[int(v159)-1]
	} else {
		v172, ok72 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(2))
		if !ok72 {
			return 0, false
		}
	}
	v173 = v72
	v174 = v173 - math.Floor(v173/math.Float64frombits(0x4010000000000000))*math.Float64frombits(0x4010000000000000)
	v175 = v172 + v174
	if v159 < 1 || v159 > 3 {
		return 0, false
	}
	ra0_1[int(v159)-1] = v175
	rap0_1[int(v159)-1] = true
	v89 = v61
	v99 = v71
	v100 = v72
	v101 = v73
	v102 = v74
	v106 = v159
	v109 = v164
	goto b7
b7:
	v176 = v109
	v177 = v99 + v176
	if v106 < 1 || v106 > 3 {
		return 0, false
	}
	if rap0_0[int(v106)-1] {
		v178 = ra0_0[int(v106)-1]
	} else {
		v178, ok79 = backendGeneratedPrototypeIndex(&v89, &r0_0, &r0_1, &r0_2, uint32(1))
		if !ok79 {
			return 0, false
		}
	}
	v179 = v177 + v178
	if v106 < 1 || v106 > 3 {
		return 0, false
	}
	if rap0_1[int(v106)-1] {
		v180 = ra0_1[int(v106)-1]
	} else {
		v180, ok81 = backendGeneratedPrototypeIndex(&v89, &r0_0, &r0_1, &r0_2, uint32(2))
		if !ok81 {
			return 0, false
		}
	}
	v181 = v179 + v180
	v61 = v89
	v71 = v181
	v72 = v100
	v73 = v101
	v74 = v102
	goto b3
b8:
	v182 = v72 + v74
	v33 = v61
	v43 = v71
	v44 = v182
	v45 = v73
	v46 = v74
	goto b1
b9:
	v183 = v43
	v184 = v33
	v185 = v183 + v184
	return v185, true
}

func backendGeneratedPrototypeFallbackPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v33 float64
	var v43 float64
	var v44 float64
	var v45 float64
	var v46 float64
	var v61 float64
	var v71 float64
	var v72 float64
	var v73 float64
	var v74 float64
	var v89 float64
	var v99 float64
	var v100 float64
	var v101 float64
	var v102 float64
	var v106 float64
	var v109 float64
	var v114 float64
	var v115 float64
	var v116 float64
	var v117 float64
	var v118 float64
	var v119 float64
	var v120 float64
	var v125 float64
	var v126 float64
	var v127 float64
	var v128 float64
	var v133 float64
	var v134 float64
	var v139 float64
	var v140 float64
	var v144 float64
	var v146 float64
	var v147 float64
	var v148 float64
	var v149 float64
	var v151 float64
	var v152 float64
	var v153 float64
	var v159 float64
	var v160 float64
	var v161 float64
	var v162 float64
	var v163 float64
	var v164 float64
	var v165 float64
	var v166 float64
	var v167 float64
	var v168 float64
	var v169 float64
	var v170 float64
	var v171 float64
	var v172 float64
	var v173 float64
	var v174 float64
	var v175 float64
	var v176 float64
	var v177 float64
	var v178 float64
	var v179 float64
	var v180 float64
	var v181 float64
	var v182 float64
	var v183 float64
	var v184 float64
	var v185 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r1_0 float64
	_ = r1_0
	var r2_0 float64
	_ = r2_0
	var r3_0 float64
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r4_0 float64
	_ = r4_0
	var r4_1 float64
	_ = r4_1
	var ra0_0 [3]float64
	var rap0_0 [3]bool
	var ra0_1 [3]float64
	var rap0_1 [3]bool
	var ra0_2 [3]float64
	var rap0_2 [3]bool
	var ra0_3 [3]float64
	var rap0_3 [3]bool
	var ri0 int
	_ = ri0
	var ok57 bool
	var ok58 bool
	var ok60 bool
	var ok62 bool
	var ok64 bool
	var ok68 bool
	var ok72 bool
	var ok79 bool
	var ok81 bool
	v1 = p0
	v114 = math.Float64frombits(0x4034000000000000)
	v115 = v1
	v116 = v115 - math.Floor(v115/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v117 = v114 + v116
	r0_0 = v117
	v118 = math.Float64frombits(0x4014000000000000)
	r0_1 = v118
	v119 = math.Float64frombits(0x4000000000000000)
	r0_2 = v119
	v120 = math.Float64frombits(0x0000000000000000)
	v125 = math.Float64frombits(0x4054000000000000)
	v126 = v1
	v127 = v126 - math.Floor(v126/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v128 = v125 + v127
	r2_0 = v128
	ra0_0[0] = r2_0
	rap0_0[0] = true
	v133 = math.Float64frombits(0x402e000000000000)
	r3_0 = v133
	v134 = math.Float64frombits(0x4010000000000000)
	r3_1 = v134
	ra0_1[1] = r3_0
	rap0_1[1] = true
	ra0_2[1] = r3_1
	rap0_2[1] = true
	v139 = math.Float64frombits(0x4046800000000000)
	r4_0 = v139
	v140 = math.Float64frombits(0x4022000000000000)
	r4_1 = v140
	ra0_0[2] = r4_0
	rap0_0[2] = true
	ra0_3[2] = r4_1
	rap0_3[2] = true
	v144 = math.Float64frombits(0x0000000000000000)
	v146 = math.Float64frombits(0x4054000000000000)
	v147 = v1
	v148 = v147 - math.Floor(v147/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	v149 = v146 + v148
	v151 = math.Float64frombits(0x3ff0000000000000)
	v152 = v149 + math.Float64frombits(0x0000000000000000)
	v153 = math.Float64frombits(0x3ff0000000000000)
	v33 = v120
	v43 = v144
	v44 = v151
	v45 = v152
	v46 = v153
	goto b1
b1:
	if math.IsNaN(v44) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v45) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v46) {
		return machinePreparedReplayEntry()
	}
	if (v46 > 0 && v44 > v45) || (v46 <= 0 && v44 < v45) {
		goto b9
	}
	goto b2
b2:
	ri0 = 0
	v61 = v33
	v71 = v43
	v72 = v44
	v73 = v45
	v74 = v46
	goto b3
b3:
	if ri0 >= 3 {
		goto b8
	}
	v159 = float64(ri0 + 1)
	ri0++
	goto b4
b4:
	if v159 < 1 || v159 > 3 {
		return machinePreparedReplayEntry()
	}
	if rap0_0[int(v159)-1] {
		v160 = ra0_0[int(v159)-1]
	} else {
		v160, ok57 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(1))
		if !ok57 {
			return machinePreparedReplayEntry()
		}
	}
	if v159 < 1 || v159 > 3 {
		return machinePreparedReplayEntry()
	}
	if rap0_1[int(v159)-1] {
		v161 = ra0_1[int(v159)-1]
	} else {
		v161, ok58 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(2))
		if !ok58 {
			return machinePreparedReplayEntry()
		}
	}
	v162 = v160 + v161
	if v159 < 1 || v159 > 3 {
		return machinePreparedReplayEntry()
	}
	if rap0_3[int(v159)-1] {
		v163 = ra0_3[int(v159)-1]
	} else {
		v163, ok60 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(5))
		if !ok60 {
			return machinePreparedReplayEntry()
		}
	}
	v164 = v162 + v163
	if v159 < 1 || v159 > 3 {
		return machinePreparedReplayEntry()
	}
	if rap0_2[int(v159)-1] {
		v165 = ra0_2[int(v159)-1]
	} else {
		v165, ok62 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(3))
		if !ok62 {
			return machinePreparedReplayEntry()
		}
	}
	if math.IsNaN(v165) {
		return machinePreparedReplayEntry()
	}
	if !(v165 > math.Float64frombits(0x4008000000000000)) {
		goto b6
	}
	goto b5
b5:
	if v159 < 1 || v159 > 3 {
		return machinePreparedReplayEntry()
	}
	if rap0_0[int(v159)-1] {
		v166 = ra0_0[int(v159)-1]
	} else {
		v166, ok64 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(1))
		if !ok64 {
			return machinePreparedReplayEntry()
		}
	}
	v167 = v72
	v168 = v167 - math.Floor(v167/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v169 = v166 + v168
	if v159 < 1 || v159 > 3 {
		return machinePreparedReplayEntry()
	}
	if rap0_2[int(v159)-1] {
		v170 = ra0_2[int(v159)-1]
	} else {
		v170, ok68 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(3))
		if !ok68 {
			return machinePreparedReplayEntry()
		}
	}
	v171 = v169 - v170
	if v159 < 1 || v159 > 3 {
		return machinePreparedReplayEntry()
	}
	ra0_0[int(v159)-1] = v171
	rap0_0[int(v159)-1] = true
	v89 = v61
	v99 = v71
	v100 = v72
	v101 = v73
	v102 = v74
	v106 = v159
	v109 = v164
	goto b7
b6:
	if v159 < 1 || v159 > 3 {
		return machinePreparedReplayEntry()
	}
	if rap0_1[int(v159)-1] {
		v172 = ra0_1[int(v159)-1]
	} else {
		v172, ok72 = backendGeneratedPrototypeIndex(&v61, &r0_0, &r0_1, &r0_2, uint32(2))
		if !ok72 {
			return machinePreparedReplayEntry()
		}
	}
	v173 = v72
	v174 = v173 - math.Floor(v173/math.Float64frombits(0x4010000000000000))*math.Float64frombits(0x4010000000000000)
	v175 = v172 + v174
	if v159 < 1 || v159 > 3 {
		return machinePreparedReplayEntry()
	}
	ra0_1[int(v159)-1] = v175
	rap0_1[int(v159)-1] = true
	v89 = v61
	v99 = v71
	v100 = v72
	v101 = v73
	v102 = v74
	v106 = v159
	v109 = v164
	goto b7
b7:
	v176 = v109
	v177 = v99 + v176
	if v106 < 1 || v106 > 3 {
		return machinePreparedReplayEntry()
	}
	if rap0_0[int(v106)-1] {
		v178 = ra0_0[int(v106)-1]
	} else {
		v178, ok79 = backendGeneratedPrototypeIndex(&v89, &r0_0, &r0_1, &r0_2, uint32(1))
		if !ok79 {
			return machinePreparedReplayEntry()
		}
	}
	v179 = v177 + v178
	if v106 < 1 || v106 > 3 {
		return machinePreparedReplayEntry()
	}
	if rap0_1[int(v106)-1] {
		v180 = ra0_1[int(v106)-1]
	} else {
		v180, ok81 = backendGeneratedPrototypeIndex(&v89, &r0_0, &r0_1, &r0_2, uint32(2))
		if !ok81 {
			return machinePreparedReplayEntry()
		}
	}
	v181 = v179 + v180
	v61 = v89
	v71 = v181
	v72 = v100
	v73 = v101
	v74 = v102
	goto b3
b8:
	v182 = v72 + v74
	v33 = v61
	v43 = v71
	v44 = v182
	v45 = v73
	v46 = v74
	goto b1
b9:
	v183 = v43
	v184 = v33
	v185 = v183 + v184
	return machinePreparedReturnOneNumber(v185)
}

func backendGeneratedPrototypeFallbackPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchanged(22) {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchanged(31) {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchanged(40) {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedPrototypeFallbackPreparedFixtureBody(context, p0)
}
