package ember_test

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"testing"

	"github.com/besmpl/ember"
)

const preparedWorkerParityFixtureUpdateEnvironment = "EMBER_UPDATE_PREPARED_WORKER_PARITY_FIXTURE"

func TestPreparedWorkerParityFixtureIsFresh(t *testing.T) {
	artifact := preparedWorkerParityArtifact(t, parityDefaultFixtureVariant)
	var generated bytes.Buffer
	if _, err := artifact.WriteTo(&generated); err != nil {
		t.Fatal(err)
	}
	const path = "internal/preparedworkerparity/generated/prepared_generated.go"
	if os.Getenv(preparedWorkerParityFixtureUpdateEnvironment) == "1" {
		if err := os.WriteFile(path, generated.Bytes(), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	onDisk, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(onDisk, generated.Bytes()) {
		t.Fatalf(
			"prepared worker parity fixture is stale; rerun with %s=1",
			preparedWorkerParityFixtureUpdateEnvironment,
		)
	}
	identity := artifact.Identity()
	if len(identity.Bundle.ProtoCounts) != 37 || identity.ProgramRecipeDigest == ([32]byte{}) {
		t.Fatalf("prepared worker parity identity = %#v, want 37 modules and a recipe", identity)
	}
}

func preparedWorkerParityArtifact(
	t testing.TB,
	variant parityFixtureVariant,
) *ember.PreparedGoArtifact {
	t.Helper()
	program := preparedWorkerParityProgram(t, variant)
	artifact, err := program.GeneratePreparedGo(ember.PreparedGoOptions{
		Package: "preparedworkerparitygenerated", EmbedProgramRecipe: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	return artifact
}

func preparedWorkerParityProgram(
	t testing.TB,
	variant parityFixtureVariant,
) *ember.Program {
	t.Helper()
	entries := parityCaseManifest()
	modules := make([]ember.PreparedProgramModule, len(entries))
	entrypoints := make([]ember.Entrypoint, len(entries))
	for index, entry := range entries {
		programSource, _, err := runtimeParityGuestBatchProgram(entry.Case.source, variant)
		if err != nil {
			t.Fatalf("%s/%s: %v", entry.Corpus, entry.Name, err)
		}
		module := ember.LogicalModule(fmt.Sprintf("prepared-worker-parity/case-%02d", index))
		modules[index] = ember.PreparedProgramModule{
			Module:     module,
			SourceName: "parity:" + entry.Corpus + "/" + entry.Name,
			SourceText: programSource + "return { run = " + variant.batchName + " }\n",
		}
		entrypoints[index] = ember.Entrypoint{
			Name: entry.Corpus + "/" + entry.Name, Module: module,
		}
	}
	recipe, err := ember.NewPreparedProgramRecipe(modules, entrypoints)
	if err != nil {
		t.Fatal(err)
	}
	program, _, err := recipe.Load(context.Background(), ember.ProgramOptions{Parallelism: 1})
	if err != nil {
		t.Fatal(err)
	}
	return program
}
