package ember_test

import (
	"bytes"
	"context"
	"crypto/sha256"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"reflect"
	"strings"
	"testing"

	"github.com/besmpl/ember"
	"github.com/besmpl/ember/preparedsource"
)

func TestProgramGeneratePreparedGoBindsDetachedSourceAndIdentity(t *testing.T) {
	program := loadPreparedGoProgram(t, `return {update = function() return 42 end}`)
	options := ember.PreparedGoOptions{
		Package:            "artifactfixture",
		EmbedProgramRecipe: true,
	}
	artifact, err := program.GeneratePreparedGo(options)
	if err != nil {
		t.Fatal(err)
	}
	identity := artifact.Identity()
	if identity.Bundle.ABIVersion != 2 || identity.Bundle.SemanticVersion == 0 ||
		identity.Bundle.ProgramHash == ([sha256.Size]byte{}) || len(identity.Bundle.ProtoCounts) == 0 ||
		identity.ProgramRecipeDigest == ([sha256.Size]byte{}) ||
		identity.GeneratedDigest == ([sha256.Size]byte{}) {
		t.Fatalf("generated identity is incomplete: %#v", identity)
	}
	sources := artifact.Sources()
	if sources.IsZero() || sources.PackageName() != options.Package {
		t.Fatalf("generated Sources = %#v", sources)
	}
	files := sources.Files()
	if len(files) != 1 || files[0].Name != "prepared_generated.go" || files[0].Kind != preparedsource.GoFile {
		t.Fatalf("generated files = %#v", files)
	}

	var generated bytes.Buffer
	written, err := artifact.WriteTo(&generated)
	if err != nil {
		t.Fatal(err)
	}
	if written != int64(generated.Len()) {
		t.Fatalf("WriteTo bytes = %d, want %d", written, generated.Len())
	}
	if got := sha256.Sum256(generated.Bytes()); got != identity.GeneratedDigest {
		t.Fatalf("generated digest = %x, want %x", identity.GeneratedDigest, got)
	}
	if files[0].Content != generated.String() {
		t.Fatal("Sources and legacy writer differ")
	}
	if sources.Digest() == identity.GeneratedDigest {
		t.Fatal("framed source Set digest unexpectedly equals the legacy raw-source digest")
	}
	var legacy bytes.Buffer
	if err := program.WritePreparedGo(&legacy, options); err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(generated.Bytes(), legacy.Bytes()) {
		t.Fatal("generated artifact and WritePreparedGo differ")
	}

	identity.Bundle.ProtoCounts[0]++
	fresh := artifact.Identity()
	if fresh.Bundle.ProtoCounts[0] == identity.Bundle.ProtoCounts[0] {
		t.Fatalf("mutated identity escaped into artifact: %#v", fresh)
	}
}

func TestPreparedGoArtifactWriteToValidatesBoundary(t *testing.T) {
	var missing *ember.PreparedGoArtifact
	if sources := missing.Sources(); !sources.IsZero() {
		t.Fatalf("nil artifact Sources = %#v, want zero Set", sources)
	}
	if _, err := missing.WriteTo(&bytes.Buffer{}); err == nil {
		t.Fatal("nil artifact WriteTo succeeded")
	}
	program := loadPreparedGoProgram(t, `return 42`)
	artifact, err := program.GeneratePreparedGo(ember.PreparedGoOptions{Package: "artifactfixture"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := artifact.WriteTo(nil); err == nil {
		t.Fatal("nil writer succeeded")
	}
	if _, err := artifact.WriteTo(preparedGoShortWriter{}); err == nil || !strings.Contains(err.Error(), "short write") {
		t.Fatalf("short writer error = %v", err)
	}
}

func TestProgramWritePreparedGoIsDeterministicAndSelfContained(t *testing.T) {
	program := loadPreparedGoProgram(t, `
local function add(value)
    return value + 1
end
return {
    first = function() return add(40) end,
    second = function() return add(41) end,
}
`)

	var first bytes.Buffer
	if err := program.WritePreparedGo(&first, ember.PreparedGoOptions{Package: "generatedfixture"}); err != nil {
		t.Fatal(err)
	}
	var second bytes.Buffer
	if err := program.WritePreparedGo(&second, ember.PreparedGoOptions{Package: "generatedfixture"}); err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first.Bytes(), second.Bytes()) {
		t.Fatal("WritePreparedGo output is not deterministic")
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "prepared_generated.go", first.Bytes(), parser.AllErrors); err != nil {
		t.Fatalf("parse generated source: %v\n%s", err, first.Bytes())
	}
	source := first.String()
	for _, required := range []string{
		"package generatedfixture",
		`emberapi "github.com/besmpl/ember"`,
		"context emberapi.PreparedContext",
		"if !context.Continue()",
		"var Bundle = emberapi.NewPreparedBundle(",
	} {
		if !strings.Contains(source, required) {
			t.Fatalf("generated source lacks %q", required)
		}
	}
	for _, forbidden := range []string{
		"machinePrepared",
		"go:linkname",
		"plugin",
	} {
		if strings.Contains(source, forbidden) {
			t.Fatalf("generated source contains forbidden marker %q", forbidden)
		}
	}
	if got := strings.Count(source, "func emberPreparedM0Proto1("); got != 1 {
		t.Fatalf("shared helper body count = %d, want 1", got)
	}
	if got := strings.Count(source, "emberPreparedM0Proto1("); got != 5 {
		t.Fatalf("shared helper definition/call count = %d, want 5", got)
	}
}

func TestProgramWritePreparedGoThreadsCancellationThroughDirectLoopGraph(t *testing.T) {
	program := loadPreparedGoProgram(t, `
local function sum(limit)
    local total = 0
    for index = 1, limit do
        total = total + index
    end
    return total
end
return {
    update = function(limit) return sum(limit) end,
}
`)
	var output bytes.Buffer
	if err := program.WritePreparedGo(&output, ember.PreparedGoOptions{Package: "cancellationfixture"}); err != nil {
		t.Fatal(err)
	}
	file, err := parser.ParseFile(token.NewFileSet(), "prepared_generated.go", output.Bytes(), parser.AllErrors)
	if err != nil {
		t.Fatalf("parse generated source: %v\n%s", err, output.Bytes())
	}

	direct := make(map[string]struct{})
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || !strings.HasPrefix(function.Name.Name, "emberPreparedM0Proto") {
			continue
		}
		direct[function.Name.Name] = struct{}{}
		fields := function.Type.Params.List
		if len(fields) == 0 || len(fields[len(fields)-1].Names) != 1 || fields[len(fields)-1].Names[0].Name != "context" {
			t.Fatalf("direct helper %s does not end in the shared prepared context", function.Name.Name)
		}
	}
	if len(direct) < 2 {
		t.Fatalf("direct helper inventory = %d, want a caller and loop helper\n%s", len(direct), output.Bytes())
	}

	directCalls := 0
	safePoints := 0
	ast.Inspect(file, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok {
			return true
		}
		if identifier, ok := call.Fun.(*ast.Ident); ok {
			if _, isDirect := direct[identifier.Name]; isDirect {
				directCalls++
				if len(call.Args) == 0 {
					t.Fatalf("direct helper call %s has no prepared context", identifier.Name)
				}
				contextArgument, ok := call.Args[len(call.Args)-1].(*ast.Ident)
				if !ok || contextArgument.Name != "context" {
					t.Fatalf("direct helper call %s does not forward the shared prepared context", identifier.Name)
				}
			}
		}
		selector, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || selector.Sel.Name != "Continue" {
			return true
		}
		receiver, ok := selector.X.(*ast.Ident)
		if ok && receiver.Name == "context" {
			safePoints++
		}
		return true
	})
	if directCalls == 0 {
		t.Fatalf("generated direct graph has no helper edges\n%s", output.Bytes())
	}
	if safePoints < 3 {
		t.Fatalf("generated cancellation safe points = %d, want function entries plus a loop backedge\n%s", safePoints, output.Bytes())
	}
}

func TestProgramWritePreparedGoOwnsStructuralStringKeyRepresentation(t *testing.T) {
	program := loadPreparedGoProgram(t, `
local function cellKey(x, y)
    return tostring(x) .. ":" .. tostring(y)
end
return {
    update = function()
        return cellKey(1, 2) == "1:2" and 1 or 0
    end,
}
`)
	var output bytes.Buffer
	if err := program.WritePreparedGo(&output, ember.PreparedGoOptions{Package: "keyfixture"}); err != nil {
		t.Fatal(err)
	}
	source := output.String()
	if !strings.Contains(source, "backendPreparedStringKey") {
		t.Fatalf("fixture did not exercise the structural string-key representation:\n%s", source)
	}
	if !strings.Contains(source, "type backendPreparedStringKey struct") {
		t.Fatalf("generated package depends on a structural string-key type it does not own:\n%s", source)
	}
}

func TestProgramWritePreparedGoIdentityAndLimits(t *testing.T) {
	firstProgram := loadPreparedGoProgram(t, `return {update = function() return 40 end}`)
	secondProgram := loadPreparedGoProgram(t, `return {update = function() return 41 end}`)
	generate := func(program *ember.Program) []byte {
		t.Helper()
		var output bytes.Buffer
		if err := program.WritePreparedGo(&output, ember.PreparedGoOptions{Package: "identityfixture"}); err != nil {
			t.Fatal(err)
		}
		return output.Bytes()
	}
	first := generate(firstProgram)
	second := generate(secondProgram)
	if bytes.Equal(first, second) {
		t.Fatal("distinct Program identities generated equal source")
	}

	var limited bytes.Buffer
	limited.WriteString("unchanged")
	err := firstProgram.WritePreparedGo(&limited, ember.PreparedGoOptions{
		Package:  "identityfixture",
		MaxBytes: len(first) - 1,
	})
	if err == nil || !strings.Contains(err.Error(), "exceeds MaxBytes") {
		t.Fatalf("limited generation error = %v, want MaxBytes rejection", err)
	}
	if limited.String() != "unchanged" {
		t.Fatalf("limited generation mutated writer: %q", limited.String())
	}
}

func TestProgramWritePreparedGoCanEmbedReconstructibleProgramRecipe(t *testing.T) {
	program := loadPreparedGoProgram(t, `return {update = function() return 42 end}`)
	var output bytes.Buffer
	if err := program.WritePreparedGo(&output, ember.PreparedGoOptions{
		Package:            "recipefixture",
		EmbedProgramRecipe: true,
	}); err != nil {
		t.Fatal(err)
	}
	source := output.String()
	for _, marker := range []string{
		`"context"`,
		"func LoadProgram(ctx context.Context, options emberapi.ProgramOptions)",
		"emberapi.NewPreparedProgramRecipe(",
		"var ProgramRecipeDigest = [32]byte{",
		"return {update = function() return 42 end}",
	} {
		if !strings.Contains(source, marker) {
			t.Fatalf("reconstructible generated source lacks %q:\n%s", marker, source)
		}
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "prepared_generated.go", output.Bytes(), parser.AllErrors); err != nil {
		t.Fatalf("parse reconstructible generated source: %v", err)
	}
}

func TestPreparedBundleIdentityIsDetached(t *testing.T) {
	hash := [32]byte{1, 2, 3}
	bundle := ember.NewPreparedBundle(7, 9, hash, [][]ember.PreparedFunction{{nil}, {nil, nil}})
	identity := bundle.Identity()
	if identity.ABIVersion != 7 || identity.SemanticVersion != 9 || identity.ProgramHash != hash {
		t.Fatalf("bundle identity = %#v", identity)
	}
	if got, want := identity.ProtoCounts, []uint32{1, 2}; !reflect.DeepEqual(got, want) {
		t.Fatalf("Proto counts = %#v, want %#v", got, want)
	}
	identity.ProtoCounts[0] = 99
	if fresh := bundle.Identity(); fresh.ProtoCounts[0] != 1 {
		t.Fatalf("mutated identity escaped into bundle: %#v", fresh)
	}
}

func TestProgramWritePreparedGoValidatesPublicBoundary(t *testing.T) {
	program := loadPreparedGoProgram(t, `return {update = function() return 40 end}`)
	for _, test := range []struct {
		name    string
		writer  *bytes.Buffer
		options ember.PreparedGoOptions
	}{
		{name: "missing package", writer: &bytes.Buffer{}},
		{name: "keyword package", writer: &bytes.Buffer{}, options: ember.PreparedGoOptions{Package: "func"}},
		{name: "noncanonical package", writer: &bytes.Buffer{}, options: ember.PreparedGoOptions{Package: "Generated"}},
		{name: "negative limit", writer: &bytes.Buffer{}, options: ember.PreparedGoOptions{Package: "valid", MaxBytes: -1}},
		{name: "nil writer", writer: nil, options: ember.PreparedGoOptions{Package: "valid"}},
	} {
		t.Run(test.name, func(t *testing.T) {
			if err := program.WritePreparedGo(test.writer, test.options); err == nil {
				t.Fatal("WritePreparedGo succeeded")
			}
		})
	}

	var nilProgram *ember.Program
	if err := nilProgram.WritePreparedGo(&bytes.Buffer{}, ember.PreparedGoOptions{Package: "valid"}); err == nil {
		t.Fatal("nil Program WritePreparedGo succeeded")
	}
	if err := program.WritePreparedGo(preparedGoShortWriter{}, ember.PreparedGoOptions{Package: "valid"}); err == nil || !strings.Contains(err.Error(), "short write") {
		t.Fatalf("short writer error = %v, want short write", err)
	}
}

func TestProgramWritePreparedGoUsesCanonicalFallbackForMutableFunctionUpvalue(t *testing.T) {
	program := loadPreparedGoProgram(t, `
local add = function(value) return value + 1 end
return {
    update = function()
        add = function(value) return value + 2 end
        return add(40)
    end,
}
`)
	var output bytes.Buffer
	if err := program.WritePreparedGo(&output, ember.PreparedGoOptions{Package: "mutablefixture"}); err != nil {
		t.Fatalf("write prepared Go: %v", err)
	}
	if source := output.String(); !strings.Contains(source, "var Bundle = emberapi.NewPreparedBundle(") || !strings.Contains(source, "nil") {
		t.Fatalf("generated source lacks canonical fallback:\n%s", source)
	}
}

func TestProgramWritePreparedGoUsesCanonicalFallbackForUnsupportedProto(t *testing.T) {
	program := loadPreparedGoProgram(t, `
return {
    update = function(value)
        return hostAdd(value)
    end,
}
`)
	var output bytes.Buffer
	if err := program.WritePreparedGo(&output, ember.PreparedGoOptions{Package: "fallbackfixture"}); err != nil {
		t.Fatalf("write prepared Go with unsupported Proto: %v", err)
	}
	source := output.String()
	if !strings.Contains(source, "var Bundle = emberapi.NewPreparedBundle(") {
		t.Fatalf("generated source lacks exact bundle:\n%s", source)
	}
	if !strings.Contains(source, "[][]emberapi.PreparedFunction{{nil, nil}}") {
		t.Fatalf("generated source lacks canonical fallback inventory:\n%s", source)
	}
}

func TestProgramWritePreparedGoSiblingGrowthIsLinear(t *testing.T) {
	generate := func(count int) []byte {
		t.Helper()
		program := loadPreparedGoProgram(t, preparedGoSiblingSource(count))
		var output bytes.Buffer
		if err := program.WritePreparedGo(&output, ember.PreparedGoOptions{Package: "growthfixture"}); err != nil {
			t.Fatal(err)
		}
		if got := strings.Count(output.String(), "func emberPreparedM0Proto1("); got != 1 {
			t.Fatalf("%d siblings emitted %d shared helper bodies, want 1", count, got)
		}
		direct, preparedBodies, preparedEntries := preparedGoFunctionInventory(t, output.Bytes())
		wantFunctions := count + 1 // one shared helper plus one function per sibling
		if direct != wantFunctions || preparedBodies != wantFunctions || preparedEntries != wantFunctions {
			t.Fatalf(
				"%d siblings generated function inventory = direct %d, prepared body %d, prepared entry %d; want %d each",
				count, direct, preparedBodies, preparedEntries, wantFunctions,
			)
		}
		return output.Bytes()
	}
	sixteen := generate(16)
	thirtyTwo := generate(32)
	if len(thirtyTwo) >= len(sixteen)*5/2 {
		t.Fatalf("generated growth = %d -> %d bytes, want bounded linear growth", len(sixteen), len(thirtyTwo))
	}
}

func preparedGoFunctionInventory(t *testing.T, source []byte) (direct, preparedBodies, preparedEntries int) {
	t.Helper()
	file, err := parser.ParseFile(token.NewFileSet(), "prepared_generated.go", source, parser.AllErrors)
	if err != nil {
		t.Fatal(err)
	}
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok {
			continue
		}
		name := function.Name.Name
		switch {
		case strings.HasPrefix(name, "emberPreparedM0Proto"):
			direct++
		case strings.HasPrefix(name, "emberPreparedM0PreparedProto") && strings.HasSuffix(name, "Body"):
			preparedBodies++
		case strings.HasPrefix(name, "emberPreparedM0PreparedProto"):
			preparedEntries++
		}
	}
	return direct, preparedBodies, preparedEntries
}

func loadPreparedGoProgram(t *testing.T, source string) *ember.Program {
	t.Helper()
	module := ember.LogicalModule("prepared/generate")
	program, _, err := ember.LoadProgram(context.Background(), externalPreparedLoader{
		module.String(): source,
	}, ember.ProgramOptions{Entrypoints: []ember.Entrypoint{{Name: "main", Module: module}}, Parallelism: 1})
	if err != nil {
		t.Fatal(err)
	}
	return program
}

func preparedGoSiblingSource(count int) string {
	var source strings.Builder
	source.WriteString("local function add(value) return value + 1 end\nreturn {\n")
	for index := 0; index < count; index++ {
		fmt.Fprintf(&source, "hook%d = function() return add(%d) end,\n", index, index)
	}
	source.WriteString("}\n")
	return source.String()
}

type preparedGoShortWriter struct{}

func (preparedGoShortWriter) Write(buffer []byte) (int, error) {
	return len(buffer) - 1, nil
}
