// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedDirtyMetatableIndex(r0 *float64, r1 *float64, r2 *float64, r3 *float64, r4 *float64, p1 uint32) (float64, bool) {
	if r0 == nil {
		return 0, false
	}
	if r1 == nil {
		return 0, false
	}
	if r2 == nil {
		return 0, false
	}
	if r3 == nil {
		return 0, false
	}
	if r4 == nil {
		return 0, false
	}
	var v2 uint32
	var v7 float64
	var v10 uint32
	var v11 float64
	var vp11 bool
	_ = v11
	_ = vp11
	var v12 float64
	v2 = p1
	v10 = v2
	vp11 = false
	switch v10 {
	case uint32(1):
		v11 = *r0
		vp11 = true
	case uint32(2):
		v11 = *r1
		vp11 = true
	case uint32(3):
		v11 = *r2
		vp11 = true
	case uint32(4):
		v11 = *r3
		vp11 = true
	case uint32(5):
		v11 = *r4
		vp11 = true
	}
	if !vp11 {
		goto b2
	}
	goto b1
b1:
	v7 = v11
	goto b3
b2:
	v12 = math.Float64frombits(0x0000000000000000)
	v7 = v12
	goto b3
b3:
	return v7, true
}
