// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

func backendGeneratedCounterBody(u0 *float64, p0 float64) (float64, bool) {
	if u0 == nil {
		return 0, false
	}
	var v1 float64
	var v5 float64
	var v6 float64
	var v7 float64
	var v8 float64
	v1 = p0
	v5 = *u0
	v6 = v1
	v7 = v5 + v6
	*u0 = v7
	v8 = *u0
	return v8, true
}
