// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedRecursiveFib(p0 float64) (float64, bool) {
	if math.IsNaN(p0) || p0 > 24 {
		return 0, false
	}
	return backendGeneratedRecursiveFibBody(p0), true
}

func backendGeneratedRecursiveFibBody(p0 float64) float64 {
	var v1 float64
	var v4 float64
	var v5 float64
	var v6 float64
	var v7 float64
	var v8 float64
	var v9 float64
	var v10 float64
	v1 = p0
	if !(v1 < math.Float64frombits(0x4000000000000000)) {
		goto b2
	}
	goto b1
b1:
	return v1
b2:
	v4 = v1
	v5 = v4 - math.Float64frombits(0x3ff0000000000000)
	v6 = backendGeneratedRecursiveFibBody(v5)
	v7 = v1
	v8 = v7 - math.Float64frombits(0x4000000000000000)
	v9 = backendGeneratedRecursiveFibBody(v8)
	v10 = v6 + v9
	return v10
}
