// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedMethodKernel(p0 float64) (float64, bool) {
	var v1 float64
	var v16 float64
	var v17 float64
	var v18 float64
	var v19 float64
	var v24 float64
	var v25 float64
	var v27 float64
	var v31 float64
	var v32 float64
	var v33 float64
	var v34 float64
	var v35 float64
	var v36 float64
	var v38 float64
	var v39 float64
	var f0 float64
	_ = f0
	var ok16 bool
	var m16_0 float64
	v1 = p0
	v24 = v1
	v25 = v24 - math.Floor(v24/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	f0 = v25
	v27 = math.Float64frombits(0x0000000000000000)
	v31 = math.Float64frombits(0x3ff0000000000000)
	v32 = math.Float64frombits(0x4051800000000000)
	v33 = math.Float64frombits(0x3ff0000000000000)
	v16 = v27
	v17 = v31
	v18 = v32
	v19 = v33
	goto b1
b1:
	if math.IsNaN(v17) {
		return 0, false
	}
	if math.IsNaN(v18) {
		return 0, false
	}
	if math.IsNaN(v19) {
		return 0, false
	}
	if (v19 > 0 && v17 > v18) || (v19 <= 0 && v17 < v18) {
		goto b3
	}
	goto b2
b2:
	v34 = v17
	v35 = v34 - math.Floor(v34/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	m16_0 = f0
	v36, ok16 = backendGeneratedCounterAdd(&m16_0, v35)
	if !ok16 {
		return 0, false
	}
	f0 = m16_0
	v38 = v16 + v36
	v39 = v17 + v19
	v16 = v38
	v17 = v39
	v18 = v18
	v19 = v19
	goto b1
b3:
	return v16, true
}

func backendGeneratedMethodPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v16 float64
	var v17 float64
	var v18 float64
	var v19 float64
	var v24 float64
	var v25 float64
	var v27 float64
	var v31 float64
	var v32 float64
	var v33 float64
	var v34 float64
	var v35 float64
	var v36 float64
	var v38 float64
	var v39 float64
	var f0 float64
	_ = f0
	var ok16 bool
	var m16_0 float64
	v1 = p0
	v24 = v1
	v25 = v24 - math.Floor(v24/math.Float64frombits(0x4000000000000000))*math.Float64frombits(0x4000000000000000)
	f0 = v25
	v27 = math.Float64frombits(0x0000000000000000)
	v31 = math.Float64frombits(0x3ff0000000000000)
	v32 = math.Float64frombits(0x4051800000000000)
	v33 = math.Float64frombits(0x3ff0000000000000)
	v16 = v27
	v17 = v31
	v18 = v32
	v19 = v33
	goto b1
b1:
	if math.IsNaN(v17) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v18) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v19) {
		return machinePreparedReplayEntry()
	}
	if (v19 > 0 && v17 > v18) || (v19 <= 0 && v17 < v18) {
		goto b3
	}
	goto b2
b2:
	v34 = v17
	v35 = v34 - math.Floor(v34/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	m16_0 = f0
	v36, ok16 = backendGeneratedCounterAdd(&m16_0, v35)
	if !ok16 {
		return machinePreparedReplayEntry()
	}
	f0 = m16_0
	v38 = v16 + v36
	v39 = v17 + v19
	v16 = v38
	v17 = v39
	v18 = v18
	v19 = v19
	goto b1
b3:
	return machinePreparedReturnOneNumber(v16)
}

func backendGeneratedMethodPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedMethodPreparedFixtureBody(context, p0)
}
