// Code generated by Ember's private prepared proof compiler; DO NOT EDIT.

package ember

import "math"

func backendGeneratedCombatTick(p0 float64) (float64, bool) {
	var v1 float64
	var v26 float64
	var v27 float64
	var v28 float64
	var v29 float64
	var v46 float64
	var v47 float64
	var v48 float64
	var v49 float64
	var v66 float64
	var v67 float64
	var v68 float64
	var v69 float64
	var v73 float64
	var v76 float64
	var v83 float64
	var v84 float64
	var v85 float64
	var v86 float64
	var v87 float64
	var v88 float64
	var v89 float64
	var v90 bool
	var v92 float64
	var v93 float64
	var v94 float64
	var v95 float64
	var v96 bool
	var v98 float64
	var v99 float64
	var v100 float64
	var v101 float64
	var v102 bool
	var v104 float64
	var v105 float64
	var v106 float64
	var v107 float64
	var v108 bool
	var v109 float64
	var v113 float64
	var v114 float64
	var v115 float64
	var v121 float64
	var v122 bool
	var v123 float64
	var v124 float64
	var v125 float64
	var v126 float64
	var v127 float64
	var v128 float64
	var v129 float64
	var v130 float64
	var v131 float64
	var v132 float64
	var v133 float64
	var v134 float64
	var v135 float64
	var v136 float64
	var v137 float64
	var v138 float64
	var v139 float64
	var v140 float64
	var v141 float64
	var v142 bool
	var v143 float64
	var v144 float64
	var v145 float64
	var v146 float64
	var v147 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r0_4 bool
	_ = r0_4
	var r1_0 float64
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r1_3 float64
	_ = r1_3
	var r1_4 bool
	_ = r1_4
	var r2_0 float64
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 float64
	_ = r2_2
	var r2_3 float64
	_ = r2_3
	var r2_4 bool
	_ = r2_4
	var r3_0 float64
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r3_2 float64
	_ = r3_2
	var r3_3 float64
	_ = r3_3
	var r3_4 bool
	_ = r3_4
	var ra0_0 [4]float64
	var ra0_1 [4]float64
	var ra0_2 [4]float64
	var ra0_3 [4]float64
	var ra0_4 [4]bool
	var ri0 int
	_ = ri0
	v1 = p0
	v83 = math.Float64frombits(0x405e000000000000)
	v84 = v1
	v85 = v84 - math.Floor(v84/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v86 = v83 + v85
	r0_0 = v86
	v87 = math.Float64frombits(0x4028000000000000)
	r0_1 = v87
	v88 = math.Float64frombits(0x4000000000000000)
	r0_2 = v88
	v89 = math.Float64frombits(0x402a000000000000)
	r0_3 = v89
	v90 = true
	r0_4 = v90
	ra0_0[0] = r0_0
	ra0_1[0] = r0_1
	ra0_2[0] = r0_2
	ra0_3[0] = r0_3
	ra0_4[0] = r0_4
	v92 = math.Float64frombits(0x4057c00000000000)
	r1_0 = v92
	v93 = math.Float64frombits(0x4038000000000000)
	r1_1 = v93
	v94 = math.Float64frombits(0x3ff0000000000000)
	r1_2 = v94
	v95 = math.Float64frombits(0x4020000000000000)
	r1_3 = v95
	v96 = true
	r1_4 = v96
	ra0_0[1] = r1_0
	ra0_1[1] = r1_1
	ra0_2[1] = r1_2
	ra0_3[1] = r1_3
	ra0_4[1] = r1_4
	v98 = math.Float64frombits(0x4064000000000000)
	r2_0 = v98
	v99 = math.Float64frombits(0x4014000000000000)
	r2_1 = v99
	v100 = math.Float64frombits(0x4008000000000000)
	r2_2 = v100
	v101 = math.Float64frombits(0x4031000000000000)
	r2_3 = v101
	v102 = true
	r2_4 = v102
	ra0_0[2] = r2_0
	ra0_1[2] = r2_1
	ra0_2[2] = r2_2
	ra0_3[2] = r2_3
	ra0_4[2] = r2_4
	v104 = math.Float64frombits(0x4054000000000000)
	r3_0 = v104
	v105 = math.Float64frombits(0x403e000000000000)
	r3_1 = v105
	v106 = math.Float64frombits(0x0000000000000000)
	r3_2 = v106
	v107 = math.Float64frombits(0x4026000000000000)
	r3_3 = v107
	v108 = true
	r3_4 = v108
	ra0_0[3] = r3_0
	ra0_1[3] = r3_1
	ra0_2[3] = r3_2
	ra0_3[3] = r3_3
	ra0_4[3] = r3_4
	v109 = math.Float64frombits(0x0000000000000000)
	v113 = math.Float64frombits(0x3ff0000000000000)
	v114 = math.Float64frombits(0x403e000000000000)
	v115 = math.Float64frombits(0x3ff0000000000000)
	v26 = v109
	v27 = v113
	v28 = v114
	v29 = v115
	goto b1
b1:
	if math.IsNaN(v27) {
		return 0, false
	}
	if math.IsNaN(v28) {
		return 0, false
	}
	if math.IsNaN(v29) {
		return 0, false
	}
	if (v29 > 0 && v27 > v28) || (v29 <= 0 && v27 < v28) {
		goto b11
	}
	goto b2
b2:
	ri0 = 0
	v46 = v26
	v47 = v27
	v48 = v28
	v49 = v29
	goto b3
b3:
	if ri0 >= 4 {
		goto b10
	}
	v121 = float64(ri0 + 1)
	ri0++
	goto b4
b4:
	if v121 < 1 || v121 > 4 {
		return 0, false
	}
	v122 = ra0_4[int(v121)-1]
	if !v122 {
		goto b3
	}
	goto b5
b5:
	if v121 < 1 || v121 > 4 {
		return 0, false
	}
	v123 = ra0_3[int(v121)-1]
	v124 = v47
	v125 = v124 - math.Floor(v124/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v126 = v123 + v125
	if v121 < 1 || v121 > 4 {
		return 0, false
	}
	v127 = ra0_1[int(v121)-1]
	if math.IsNaN(v127) {
		return 0, false
	}
	if !(v127 > math.Float64frombits(0x0000000000000000)) {
		v66 = v46
		v67 = v47
		v68 = v48
		v69 = v49
		v73 = v121
		v76 = v126
		goto b7
	}
	goto b6
b6:
	if v121 < 1 || v121 > 4 {
		return 0, false
	}
	v128 = ra0_1[int(v121)-1]
	v129 = v126
	v130 = v128
	v130 = math.Min(v130, v129)
	v131 = v130
	if v121 < 1 || v121 > 4 {
		return 0, false
	}
	v132 = ra0_1[int(v121)-1]
	v133 = v132 - v131
	if v121 < 1 || v121 > 4 {
		return 0, false
	}
	ra0_1[int(v121)-1] = v133
	v134 = v130
	v135 = v126 - v134
	v66 = v46
	v67 = v47
	v68 = v48
	v69 = v49
	v73 = v121
	v76 = v135
	goto b7
b7:
	if v73 < 1 || v73 > 4 {
		return 0, false
	}
	v136 = ra0_0[int(v73)-1]
	v137 = v76
	v138 = v136 - v137
	if v73 < 1 || v73 > 4 {
		return 0, false
	}
	v139 = ra0_2[int(v73)-1]
	v140 = v138 + v139
	if v73 < 1 || v73 > 4 {
		return 0, false
	}
	ra0_0[int(v73)-1] = v140
	if v73 < 1 || v73 > 4 {
		return 0, false
	}
	v141 = ra0_0[int(v73)-1]
	if math.IsNaN(v141) {
		return 0, false
	}
	if v141 > math.Float64frombits(0x0000000000000000) {
		goto b9
	}
	goto b8
b8:
	v142 = false
	if v73 < 1 || v73 > 4 {
		return 0, false
	}
	ra0_4[int(v73)-1] = v142
	v46 = v66
	v47 = v67
	v48 = v68
	v49 = v69
	goto b3
b9:
	if v73 < 1 || v73 > 4 {
		return 0, false
	}
	v143 = ra0_0[int(v73)-1]
	v144 = v66 + v143
	if v73 < 1 || v73 > 4 {
		return 0, false
	}
	v145 = ra0_1[int(v73)-1]
	v146 = v144 + v145
	v46 = v146
	v47 = v67
	v48 = v68
	v49 = v69
	goto b3
b10:
	v147 = v47 + v49
	v26 = v46
	v27 = v147
	v28 = v48
	v29 = v49
	goto b1
b11:
	return v26, true
}

func backendGeneratedCombatTickPreparedFixtureBody(context machinePreparedContext, p0 float64) machinePreparedExit {
	var v1 float64
	var v26 float64
	var v27 float64
	var v28 float64
	var v29 float64
	var v46 float64
	var v47 float64
	var v48 float64
	var v49 float64
	var v66 float64
	var v67 float64
	var v68 float64
	var v69 float64
	var v73 float64
	var v76 float64
	var v83 float64
	var v84 float64
	var v85 float64
	var v86 float64
	var v87 float64
	var v88 float64
	var v89 float64
	var v90 bool
	var v92 float64
	var v93 float64
	var v94 float64
	var v95 float64
	var v96 bool
	var v98 float64
	var v99 float64
	var v100 float64
	var v101 float64
	var v102 bool
	var v104 float64
	var v105 float64
	var v106 float64
	var v107 float64
	var v108 bool
	var v109 float64
	var v113 float64
	var v114 float64
	var v115 float64
	var v121 float64
	var v122 bool
	var v123 float64
	var v124 float64
	var v125 float64
	var v126 float64
	var v127 float64
	var v128 float64
	var v129 float64
	var v130 float64
	var v131 float64
	var v132 float64
	var v133 float64
	var v134 float64
	var v135 float64
	var v136 float64
	var v137 float64
	var v138 float64
	var v139 float64
	var v140 float64
	var v141 float64
	var v142 bool
	var v143 float64
	var v144 float64
	var v145 float64
	var v146 float64
	var v147 float64
	var r0_0 float64
	_ = r0_0
	var r0_1 float64
	_ = r0_1
	var r0_2 float64
	_ = r0_2
	var r0_3 float64
	_ = r0_3
	var r0_4 bool
	_ = r0_4
	var r1_0 float64
	_ = r1_0
	var r1_1 float64
	_ = r1_1
	var r1_2 float64
	_ = r1_2
	var r1_3 float64
	_ = r1_3
	var r1_4 bool
	_ = r1_4
	var r2_0 float64
	_ = r2_0
	var r2_1 float64
	_ = r2_1
	var r2_2 float64
	_ = r2_2
	var r2_3 float64
	_ = r2_3
	var r2_4 bool
	_ = r2_4
	var r3_0 float64
	_ = r3_0
	var r3_1 float64
	_ = r3_1
	var r3_2 float64
	_ = r3_2
	var r3_3 float64
	_ = r3_3
	var r3_4 bool
	_ = r3_4
	var ra0_0 [4]float64
	var ra0_1 [4]float64
	var ra0_2 [4]float64
	var ra0_3 [4]float64
	var ra0_4 [4]bool
	var ri0 int
	_ = ri0
	v1 = p0
	v83 = math.Float64frombits(0x405e000000000000)
	v84 = v1
	v85 = v84 - math.Floor(v84/math.Float64frombits(0x4008000000000000))*math.Float64frombits(0x4008000000000000)
	v86 = v83 + v85
	r0_0 = v86
	v87 = math.Float64frombits(0x4028000000000000)
	r0_1 = v87
	v88 = math.Float64frombits(0x4000000000000000)
	r0_2 = v88
	v89 = math.Float64frombits(0x402a000000000000)
	r0_3 = v89
	v90 = true
	r0_4 = v90
	ra0_0[0] = r0_0
	ra0_1[0] = r0_1
	ra0_2[0] = r0_2
	ra0_3[0] = r0_3
	ra0_4[0] = r0_4
	v92 = math.Float64frombits(0x4057c00000000000)
	r1_0 = v92
	v93 = math.Float64frombits(0x4038000000000000)
	r1_1 = v93
	v94 = math.Float64frombits(0x3ff0000000000000)
	r1_2 = v94
	v95 = math.Float64frombits(0x4020000000000000)
	r1_3 = v95
	v96 = true
	r1_4 = v96
	ra0_0[1] = r1_0
	ra0_1[1] = r1_1
	ra0_2[1] = r1_2
	ra0_3[1] = r1_3
	ra0_4[1] = r1_4
	v98 = math.Float64frombits(0x4064000000000000)
	r2_0 = v98
	v99 = math.Float64frombits(0x4014000000000000)
	r2_1 = v99
	v100 = math.Float64frombits(0x4008000000000000)
	r2_2 = v100
	v101 = math.Float64frombits(0x4031000000000000)
	r2_3 = v101
	v102 = true
	r2_4 = v102
	ra0_0[2] = r2_0
	ra0_1[2] = r2_1
	ra0_2[2] = r2_2
	ra0_3[2] = r2_3
	ra0_4[2] = r2_4
	v104 = math.Float64frombits(0x4054000000000000)
	r3_0 = v104
	v105 = math.Float64frombits(0x403e000000000000)
	r3_1 = v105
	v106 = math.Float64frombits(0x0000000000000000)
	r3_2 = v106
	v107 = math.Float64frombits(0x4026000000000000)
	r3_3 = v107
	v108 = true
	r3_4 = v108
	ra0_0[3] = r3_0
	ra0_1[3] = r3_1
	ra0_2[3] = r3_2
	ra0_3[3] = r3_3
	ra0_4[3] = r3_4
	v109 = math.Float64frombits(0x0000000000000000)
	v113 = math.Float64frombits(0x3ff0000000000000)
	v114 = math.Float64frombits(0x403e000000000000)
	v115 = math.Float64frombits(0x3ff0000000000000)
	v26 = v109
	v27 = v113
	v28 = v114
	v29 = v115
	goto b1
b1:
	if math.IsNaN(v27) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v28) {
		return machinePreparedReplayEntry()
	}
	if math.IsNaN(v29) {
		return machinePreparedReplayEntry()
	}
	if (v29 > 0 && v27 > v28) || (v29 <= 0 && v27 < v28) {
		goto b11
	}
	goto b2
b2:
	ri0 = 0
	v46 = v26
	v47 = v27
	v48 = v28
	v49 = v29
	goto b3
b3:
	if ri0 >= 4 {
		goto b10
	}
	v121 = float64(ri0 + 1)
	ri0++
	goto b4
b4:
	if v121 < 1 || v121 > 4 {
		return machinePreparedReplayEntry()
	}
	v122 = ra0_4[int(v121)-1]
	if !v122 {
		goto b3
	}
	goto b5
b5:
	if v121 < 1 || v121 > 4 {
		return machinePreparedReplayEntry()
	}
	v123 = ra0_3[int(v121)-1]
	v124 = v47
	v125 = v124 - math.Floor(v124/math.Float64frombits(0x4014000000000000))*math.Float64frombits(0x4014000000000000)
	v126 = v123 + v125
	if v121 < 1 || v121 > 4 {
		return machinePreparedReplayEntry()
	}
	v127 = ra0_1[int(v121)-1]
	if math.IsNaN(v127) {
		return machinePreparedReplayEntry()
	}
	if !(v127 > math.Float64frombits(0x0000000000000000)) {
		v66 = v46
		v67 = v47
		v68 = v48
		v69 = v49
		v73 = v121
		v76 = v126
		goto b7
	}
	goto b6
b6:
	if v121 < 1 || v121 > 4 {
		return machinePreparedReplayEntry()
	}
	v128 = ra0_1[int(v121)-1]
	v129 = v126
	v130 = v128
	v130 = math.Min(v130, v129)
	v131 = v130
	if v121 < 1 || v121 > 4 {
		return machinePreparedReplayEntry()
	}
	v132 = ra0_1[int(v121)-1]
	v133 = v132 - v131
	if v121 < 1 || v121 > 4 {
		return machinePreparedReplayEntry()
	}
	ra0_1[int(v121)-1] = v133
	v134 = v130
	v135 = v126 - v134
	v66 = v46
	v67 = v47
	v68 = v48
	v69 = v49
	v73 = v121
	v76 = v135
	goto b7
b7:
	if v73 < 1 || v73 > 4 {
		return machinePreparedReplayEntry()
	}
	v136 = ra0_0[int(v73)-1]
	v137 = v76
	v138 = v136 - v137
	if v73 < 1 || v73 > 4 {
		return machinePreparedReplayEntry()
	}
	v139 = ra0_2[int(v73)-1]
	v140 = v138 + v139
	if v73 < 1 || v73 > 4 {
		return machinePreparedReplayEntry()
	}
	ra0_0[int(v73)-1] = v140
	if v73 < 1 || v73 > 4 {
		return machinePreparedReplayEntry()
	}
	v141 = ra0_0[int(v73)-1]
	if math.IsNaN(v141) {
		return machinePreparedReplayEntry()
	}
	if v141 > math.Float64frombits(0x0000000000000000) {
		goto b9
	}
	goto b8
b8:
	v142 = false
	if v73 < 1 || v73 > 4 {
		return machinePreparedReplayEntry()
	}
	ra0_4[int(v73)-1] = v142
	v46 = v66
	v47 = v67
	v48 = v68
	v49 = v69
	goto b3
b9:
	if v73 < 1 || v73 > 4 {
		return machinePreparedReplayEntry()
	}
	v143 = ra0_0[int(v73)-1]
	v144 = v66 + v143
	if v73 < 1 || v73 > 4 {
		return machinePreparedReplayEntry()
	}
	v145 = ra0_1[int(v73)-1]
	v146 = v144 + v145
	v46 = v146
	v47 = v67
	v48 = v68
	v49 = v69
	goto b3
b10:
	v147 = v47 + v49
	v26 = v46
	v27 = v147
	v28 = v48
	v29 = v49
	goto b1
b11:
	return machinePreparedReturnOneNumber(v26)
}

func backendGeneratedCombatTickPreparedFixture(context machinePreparedContext) machinePreparedExit {
	p0, ok := context.numberParameter(0)
	if !ok {
		return machinePreparedReplayEntry()
	}
	if !context.intrinsicUnchanged(73) {
		return machinePreparedReplayEntry()
	}
	return backendGeneratedCombatTickPreparedFixtureBody(context, p0)
}
