// Command ember-vmgen regenerates the direct-frame dispatch source.
//
// The command deliberately uses only the standard library.  The semantic
// inventory lives in vm_dispatch_spec.go; the loop template is kept as a
// checked-in .tmpl file so generated output is reproducible and reviewable.
package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

const (
	specFile            = "vm_dispatch_spec.go"
	templateFile        = "vm_dispatch_template.go.tmpl"
	outputFile          = "vm_dispatch_generated.go"
	machineTemplateFile = "runtime_machine_template.go.tmpl"
	machineOutputFile   = "runtime_machine_generated.go"
)

func main() {
	if len(os.Args) == 2 && os.Args[1] == "-check" {
		wantDispatch, err := render()
		if err == nil {
			err = checkGenerated(outputFile, wantDispatch)
		}
		if err == nil {
			wantMachine, renderErr := renderMachine()
			if renderErr != nil {
				err = renderErr
			} else {
				err = checkGenerated(machineOutputFile, wantMachine)
			}
		}
		if err != nil {
			fmt.Fprintln(os.Stderr, "ember-vmgen:", err)
			os.Exit(1)
		}
		return
	}
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, "ember-vmgen:", err)
		os.Exit(1)
	}
}

func generate() error {
	formatted, err := render()
	if err != nil {
		return err
	}
	if err := os.WriteFile(outputFile, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputFile, err)
	}
	machine, err := renderMachine()
	if err != nil {
		return err
	}
	if err := os.WriteFile(machineOutputFile, machine, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", machineOutputFile, err)
	}
	return nil
}

func checkGenerated(name string, want []byte) error {
	got, err := os.ReadFile(name)
	if err != nil {
		return fmt.Errorf("read %s: %w", name, err)
	}
	if !bytes.Equal(got, want) {
		return fmt.Errorf("%s is stale; run go generate ./...", name)
	}
	return nil
}

func renderMachine() ([]byte, error) {
	metadata, err := os.ReadFile("bytecode.go")
	if err != nil {
		return nil, fmt.Errorf("read bytecode.go: %w", err)
	}
	want, err := opcodeNamesFromList("machineEligibleOpcodes")
	if err != nil {
		return nil, err
	}
	template, err := os.ReadFile(machineTemplateFile)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", machineTemplateFile, err)
	}
	if err := verifyMachineTemplateCases(template, want); err != nil {
		return nil, err
	}
	hashInput := append(append([]byte{}, metadata...), template...)
	hash := sha256.Sum256(hashInput)
	body := bytes.TrimPrefix(template, []byte("package ember\n\n"))
	body = bytes.Replace(body, []byte("func runScalarMachineLoop"), []byte("func runGeneratedScalarMachineLoop"), 1)
	header := fmt.Sprintf("// Code generated by cmd/ember-vmgen; DO NOT EDIT.\n// Machine metadata sha256: %x\n\npackage ember\n\n", hash)
	formatted, err := format.Source(append([]byte(header), body...))
	if err != nil {
		return nil, fmt.Errorf("format generated Machine source: %w", err)
	}
	return formatted, nil
}

func render() ([]byte, error) {
	specText, err := os.ReadFile(specFile)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", specFile, err)
	}
	semanticNames, err := opcodeNamesFromMetadata()
	if err != nil {
		return nil, err
	}
	template, err := os.ReadFile(templateFile)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", templateFile, err)
	}
	template = bytes.TrimPrefix(template, []byte("package ember\n\n"))
	if err := verifyTemplateCases(append([]byte("package ember\n\n"), template...), semanticNames); err != nil {
		return nil, err
	}

	// Hash the complete semantic input and canonical case template. The
	// generated test compares this stamp against both checked-in sources.
	hashInput := append(append([]byte{}, specText...), template...)
	hash := sha256.Sum256(hashInput)
	header := fmt.Sprintf("// Code generated by cmd/ember-vmgen; DO NOT EDIT.\n// dispatch spec sha256: %x\n\n", hash)
	if !bytes.Contains(template, []byte("func runDirectFrameProductionLoop")) {
		return nil, fmt.Errorf("template is missing runDirectFrameProductionLoop")
	}
	output := append([]byte(header), []byte("package ember\n\n")...)
	production, err := renderVariant(template, false)
	if err != nil {
		return nil, fmt.Errorf("render production variant: %w", err)
	}
	instrumented, err := renderVariant(template, true)
	if err != nil {
		return nil, fmt.Errorf("render instrumented variant: %w", err)
	}
	importsBlock := []byte(nil)
	for _, source := range []*[]byte{&production, &instrumented} {
		imports := bytes.Index(*source, []byte("import ("))
		if imports < 0 {
			return nil, fmt.Errorf("rendered variant is missing import block")
		}
		end := bytes.Index((*source)[imports:], []byte(")\n\n"))
		if end < 0 {
			return nil, fmt.Errorf("rendered variant has unterminated import block")
		}
		end += imports + len(")\n\n")
		if importsBlock == nil {
			importsBlock = append([]byte(nil), (*source)[imports:end]...)
		}
		*source = append((*source)[:imports], (*source)[end:]...)
	}
	output = append(output, importsBlock...)
	output = append(output, '\n')
	if bytes.Count(production, []byte("func runDirectFrameProductionLoop")) != 1 || bytes.Count(instrumented, []byte("func runDirectFrameProductionLoop")) != 1 {
		return nil, fmt.Errorf("rendered variants must each contain one canonical loop function")
	}
	production = bytes.Replace(production, []byte("func runDirectFrameProductionLoop"), []byte("func runGeneratedDirectFrameProductionLoop"), 1)
	instrumented = bytes.Replace(instrumented, []byte("func runDirectFrameProductionLoop"), []byte("func runGeneratedDirectFrameInstrumentedLoop"), 1)
	output = append(output, instrumented...)
	output = append(output, '\n', '\n')
	output = append(output, production...)
	formatted, err := format.Source(output)
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func renderVariant(template []byte, instrumented bool) ([]byte, error) {
	text := string(template)
	if got := strings.Count(text, ", instrumented bool"); got != 1 {
		return nil, fmt.Errorf("canonical loop parameter marker occurs %d times, want one", got)
	}
	text = strings.ReplaceAll(text, ", instrumented bool", "")
	const policyMarkerCount = 37
	if instrumented {
		var err error
		text, err = replaceAllExact(text, "instrumented", "true", policyMarkerCount)
		if err != nil {
			return nil, err
		}
		for _, rewrite := range []struct {
			old, new string
			count    int
		}{
			{"fieldCache.write(table, value)", "fieldCache.writeCounted(table, value, picCounts)", 1},
			{"fieldCache.resolveWrite(table, key, keyValue.stringBox(), value, thread.controller)", "fieldCache.resolveWriteCounted(table, key, keyValue.stringBox(), value, picCounts, thread.controller)", 1},
			{"fieldCache.get(table)", "fieldCache.getCounted(table, picCounts)", 3},
			{"fieldCache.resolve(table, firstKey, firstBox)", "fieldCache.resolveCounted(table, firstKey, firstBox, picCounts)", 2},
			{"fieldCache.resolve(table, keyText, key.stringBox())", "fieldCache.resolveCounted(table, keyText, key.stringBox(), picCounts)", 1},
			{"cache.getValue(table, key)", "cache.getValueCounted(table, key, picCounts)", 2},
			{"cache.getValue(nextTable, key)", "cache.getValueCounted(nextTable, key, picCounts)", 1},
			{"thread.pushFrameRecord(record)\n", "thread.pushFrameRecord(record)\n\t\t\t\t\tthread.directFramePICCounts.addFixedCallTrampolineEntry()\n", 10},
		} {
			text, err = replaceAllExact(text, rewrite.old, rewrite.new, rewrite.count)
			if err != nil {
				return nil, err
			}
		}
	} else {
		var err error
		text, err = replaceAllExact(text, "instrumented", "false", policyMarkerCount)
		if err != nil {
			return nil, err
		}
		markerCounts := map[string]int{
			"if false && valueNativeID": 1,
			"if false {":                34,
			"if runLineHook {":          1,
			"if runCountHook {":         1,
		}
		for marker, want := range markerCounts {
			if got := strings.Count(text, marker); got != want {
				return nil, fmt.Errorf("production marker %q occurs %d times, want %d", marker, got, want)
			}
		}
		for marker := range markerCounts {
			var err error
			text, err = stripGoBlock(text, marker)
			if err != nil {
				return nil, err
			}
		}
		productionRewrites := []struct {
			old, new string
			count    int
		}{
			{"\t\tpicCounts         *directFramePICCounts\n", "", 1},
			{"\t\trunLineHook       bool\n", "", 1},
			{"\t\trunCountHook      bool\n", "", 1},
			{"\tpicCounts = nil\n", "", 1},
			{"\trunLineHook = false && thread.debugHook != nil && thread.debugLineHook\n", "", 1},
			{"\trunCountHook = false && thread.debugCountInterval > 0 && thread.debugHook != nil\n", "", 1},
			{"value, ok, hit := thread.globals.getSlot", "value, ok, _ := thread.globals.getSlot", 1},
			{"directFrameBinaryArithmeticValue(\n\t\t\t\t\tpicCounts,\n", "directFrameBinaryArithmeticValueUncounted(\n", 13},
			{"directFrameUnaryArithmeticValue(picCounts, ", "directFrameUnaryArithmeticValueUncounted(", 1},
			{"directFrameLessForBranch(picCounts, ", "directFrameLessForBranchUncounted(", 8},
			{"cache.writeValueCounted(table, keyValue, value, picCounts)", "cache.writeValue(table, keyValue, value)", 2},
			{"cache.writeValueCounted(nextTable, key, value, picCounts)", "cache.writeValue(nextTable, key, value)", 1},
			{"cache.writeValueCounted(table, key, value, picCounts)", "cache.writeValue(table, key, value)", 1},
			{"thread.runDirectFastCall(frame, nativeFuncID(b), a, c, d, picCounts)", "thread.runDirectFastCall(frame, nativeFuncID(b), a, c, d, nil)", 1},
		}
		for _, rewrite := range productionRewrites {
			var err error
			text, err = replaceAllExact(text, rewrite.old, rewrite.new, rewrite.count)
			if err != nil {
				return nil, err
			}
		}
	}
	if strings.Contains(text, "instrumented") {
		return nil, fmt.Errorf("variant still contains instrumented marker")
	}
	variant := []byte(text)
	if _, err := parser.ParseFile(token.NewFileSet(), "generated-variant.go", append([]byte("package ember\n\n"), variant...), 0); err != nil {
		return nil, fmt.Errorf("parse rendered variant: %w", err)
	}
	if instrumented {
		for _, marker := range []string{"picCounts", "getCounted", "resolveCounted", "writeCounted", "addFixedCallTrampolineEntry"} {
			if !strings.Contains(text, marker) {
				return nil, fmt.Errorf("instrumented variant is missing %s policy", marker)
			}
		}
	} else {
		for _, marker := range []string{"picCounts", "runLineHook", "runCountHook", "Counted", "addFixedCallTrampolineEntry", "if false", "if true"} {
			if strings.Contains(text, marker) {
				return nil, fmt.Errorf("production variant retains instrumentation marker %s", marker)
			}
		}
	}
	return variant, nil
}

func replaceAllExact(source, old, replacement string, want int) (string, error) {
	got := strings.Count(source, old)
	if got != want {
		return source, fmt.Errorf("rewrite %q occurs %d times, want %d", old, got, want)
	}
	return strings.ReplaceAll(source, old, replacement), nil
}

func stripGoBlock(source, marker string) (string, error) {
	for {
		start := findCodeMarker(source, marker)
		if start < 0 {
			return source, nil
		}
		open := strings.Index(source[start:], "{") + start
		if open < start {
			return source, fmt.Errorf("marker %q has no opening brace", marker)
		}
		end, ok := matchingBrace(source, open)
		if !ok {
			return source, fmt.Errorf("marker %q has unbalanced braces", marker)
		}
		if end < len(source) && source[end] == '\n' {
			end++
		}
		source = source[:start] + source[end:]
	}
}

func findCodeMarker(source, marker string) int {
	for index := 0; index < len(source); {
		switch source[index] {
		case '"', '\'', '`':
			index = skipGoString(source, index)
		case '/':
			if index+1 < len(source) && source[index+1] == '/' {
				index = skipLineComment(source, index)
			} else if index+1 < len(source) && source[index+1] == '*' {
				index = skipBlockComment(source, index)
			} else {
				index++
			}
		default:
			if strings.HasPrefix(source[index:], marker) {
				return index
			}
			index++
		}
	}
	return -1
}

func matchingBrace(source string, open int) (int, bool) {
	depth := 0
	for index := open; index < len(source); {
		switch source[index] {
		case '"', '\'', '`':
			index = skipGoString(source, index)
			continue
		case '/':
			if index+1 < len(source) && source[index+1] == '/' {
				index = skipLineComment(source, index)
				continue
			}
			if index+1 < len(source) && source[index+1] == '*' {
				index = skipBlockComment(source, index)
				continue
			}
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return index + 1, true
			}
		}
		index++
	}
	return 0, false
}

func skipGoString(source string, start int) int {
	delimiter := source[start]
	if delimiter == '`' {
		if end := strings.IndexByte(source[start+1:], delimiter); end >= 0 {
			return start + end + 2
		}
		return len(source)
	}
	for index := start + 1; index < len(source); index++ {
		if source[index] == '\\' {
			index++
			continue
		}
		if source[index] == delimiter {
			return index + 1
		}
	}
	return len(source)
}

func skipLineComment(source string, start int) int {
	if end := strings.IndexByte(source[start:], '\n'); end >= 0 {
		return start + end + 1
	}
	return len(source)
}

func skipBlockComment(source string, start int) int {
	if end := strings.Index(source[start+2:], "*/"); end >= 0 {
		return start + end + 4
	}
	return len(source)
}

func opcodeNamesFromMetadata() ([]string, error) {
	return opcodeNamesFromList("allOpcodes")
}

func opcodeNamesFromList(listName string) ([]string, error) {
	source, err := os.ReadFile("bytecode.go")
	if err != nil {
		return nil, fmt.Errorf("read bytecode.go: %w", err)
	}
	file, err := parser.ParseFile(token.NewFileSet(), "bytecode.go", source, 0)
	if err != nil {
		return nil, fmt.Errorf("parse bytecode.go: %w", err)
	}
	var names []string
	declarations := 0
	for _, declaration := range file.Decls {
		gen, ok := declaration.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			continue
		}
		for _, spec := range gen.Specs {
			value, ok := spec.(*ast.ValueSpec)
			if !ok || len(value.Names) != 1 || value.Names[0].Name != listName {
				continue
			}
			declarations++
			if len(value.Values) != 1 {
				return nil, fmt.Errorf("bytecode.go %s must have one initializer", listName)
			}
			composite, ok := value.Values[0].(*ast.CompositeLit)
			if !ok {
				return nil, fmt.Errorf("bytecode.go %s initializer must be a composite literal", listName)
			}
			for _, element := range composite.Elts {
				identifier, ok := element.(*ast.Ident)
				if !ok {
					return nil, fmt.Errorf("bytecode.go %s contains non-identifier element", listName)
				}
				if identifier.Name == "" {
					return nil, fmt.Errorf("bytecode.go %s contains empty opcode name", listName)
				}
				names = append(names, identifier.Name)
			}
		}
	}
	if declarations != 1 {
		return nil, fmt.Errorf("bytecode.go must define %s exactly once, found %d", listName, declarations)
	}
	if len(names) == 0 {
		return nil, fmt.Errorf("bytecode.go %s is empty or unreadable", listName)
	}
	seen := make(map[string]struct{}, len(names))
	for _, name := range names {
		if _, ok := seen[name]; ok {
			return nil, fmt.Errorf("bytecode.go %s contains duplicate %s", listName, name)
		}
		seen[name] = struct{}{}
	}
	return names, nil
}

func verifyMachineTemplateCases(template []byte, want []string) error {
	file, err := parser.ParseFile(token.NewFileSet(), machineTemplateFile, template, 0)
	if err != nil {
		return fmt.Errorf("parse %s: %w", machineTemplateFile, err)
	}
	wantSet := make(map[string]bool, len(want))
	for _, name := range want {
		wantSet[name] = true
	}
	seen := make(map[string]int, len(want))
	functions := 0
	switches := 0
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Name.Name != "runScalarMachineLoop" {
			continue
		}
		functions++
		ast.Inspect(function.Body, func(node ast.Node) bool {
			switchStatement, ok := node.(*ast.SwitchStmt)
			if !ok {
				return true
			}
			selector, ok := switchStatement.Tag.(*ast.SelectorExpr)
			if !ok || selector.Sel.Name != "op" {
				return true
			}
			switches++
			for _, statement := range switchStatement.Body.List {
				clause := statement.(*ast.CaseClause)
				for _, expression := range clause.List {
					identifier, ok := expression.(*ast.Ident)
					if ok && wantSet[identifier.Name] {
						seen[identifier.Name]++
					}
				}
			}
			return false
		})
	}
	if functions != 1 || switches != 1 {
		return fmt.Errorf("%s must contain one runScalarMachineLoop opcode switch", machineTemplateFile)
	}
	for _, name := range want {
		if seen[name] != 1 {
			return fmt.Errorf("%s has %d semantic cases for %s, want one", machineTemplateFile, seen[name], name)
		}
	}
	return nil
}

func verifyTemplateCases(template []byte, want []string) error {
	file, err := parser.ParseFile(token.NewFileSet(), templateFile, template, 0)
	if err != nil {
		return fmt.Errorf("parse %s: %w", templateFile, err)
	}
	wantSet := make(map[string]struct{}, len(want))
	for _, name := range want {
		wantSet[name] = struct{}{}
	}
	seen := make(map[string]int, len(want))
	functions := 0
	switches := 0
	invalidCase := false
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Name.Name != "runDirectFrameProductionLoop" {
			continue
		}
		functions++
		ast.Inspect(function.Body, func(node ast.Node) bool {
			switchStatement, ok := node.(*ast.SwitchStmt)
			if !ok {
				return true
			}
			tag, ok := switchStatement.Tag.(*ast.Ident)
			if !ok || tag.Name != "op" {
				return true
			}
			switches++
			for _, statement := range switchStatement.Body.List {
				clause, ok := statement.(*ast.CaseClause)
				if !ok {
					continue
				}
				for _, expression := range clause.List {
					identifier, ok := expression.(*ast.Ident)
					if !ok {
						invalidCase = true
						return false
					}
					if _, known := wantSet[identifier.Name]; !known {
						seen[identifier.Name]++
						continue
					}
					seen[identifier.Name]++
				}
			}
			return false
		})
	}
	if functions != 1 {
		return fmt.Errorf("template must define runDirectFrameProductionLoop exactly once, found %d", functions)
	}
	if switches != 1 {
		return fmt.Errorf("template must contain exactly one direct switch on op, found %d", switches)
	}
	if invalidCase {
		return fmt.Errorf("template direct opcode switch contains a non-identifier case")
	}
	for _, name := range want {
		if seen[name] != 1 {
			return fmt.Errorf("template has %d semantic cases for %s, want one", seen[name], name)
		}
	}
	if len(seen) != len(want) {
		return fmt.Errorf("template has %d opcode cases, want %d", len(seen), len(want))
	}
	return nil
}
