// Code generated by internal/sprigproof. DO NOT EDIT.
package counter

import (
	"context"
	"errors"
	"fmt"
	sprig_math "math"
)

type Reading struct {
	Value   int64
	Divisor int64
}
type ResultTag uint8

const (
	ResultOK ResultTag = iota + 1
	ResultError
)

type DomainCode int64

const (
	DomainOverflow     DomainCode = 1
	DomainDivideByZero DomainCode = 2
)

type Result struct {
	Tag      ResultTag
	Total    int64
	Rejected []int64
	Code     DomainCode
}

var ErrStepLimit = errors.New("sprig: step limit exceeded")
var ErrListLimit = errors.New("sprig: list element limit exceeded")

type sprig_step struct {
	tag  uint8
	by   int64
	code int64
}

const (
	sprig_step_add uint8 = iota + 1
	sprig_step_reject
)

func sprig_poll(ctx context.Context, remaining *uint64) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if *remaining == 0 {
		return ErrStepLimit
	}
	*remaining--
	return nil
}
func sprig_checked_add(a, b int64) (int64, bool) {
	sum := a + b
	return sum, (b > 0 && sum < a) || (b < 0 && sum > a)
}

func sprig_p2_d1(sprig_b1 int64, sprig_b2 int64) (int64, DomainCode) {
	sprigpure_divisor1 := sprig_b2
	if sprigpure_divisor1 == 0 {
		return 0, DomainDivideByZero
	}
	if sprig_b1 == sprig_math.MinInt64 && sprigpure_divisor1 == -1 {
		return 0, DomainOverflow
	}
	return (sprig_b1 / sprigpure_divisor1), 0
}

func sprig_p2_d2(sprig_b3 int64, sprig_b4 int64) (int64, DomainCode) {
	sprigpure_sum2, sprigpure_overflow3 := sprig_checked_add(sprig_b3, sprig_b4)
	if sprigpure_overflow3 {
		return 0, DomainOverflow
	}
	return sprigpure_sum2, 0
}

func Reduce(sprig_ctx context.Context, sprig_b1 []Reading, sprig_limit uint64) (Result, error) {
	if sprig_ctx == nil {
		return Result{}, errors.New("sprig: nil context")
	}
	sprig_remaining := sprig_limit
	_ = int64(sprig_math.MinInt64)
	if err := sprig_poll(sprig_ctx, &sprig_remaining); err != nil {
		return Result{}, err
	}
	if len(sprig_b1) > 4096 {
		return Result{}, fmt.Errorf("sprig: input length %d exceeds limit %d", len(sprig_b1), 4096)
	}
	var sprig_b2 int64 = 0
	_ = sprig_b2
	sprig_b3 := []int64(nil)
	_ = sprig_b3
	for _, sprig_b4 := range sprig_b1 {
		_ = sprig_b4
		var sprig_b5 sprig_step
		if sprig_b4.Divisor == 0 {
			sprig_b5 = sprig_step{tag: sprig_step_reject, code: 7}
		} else {
			sprigcall4, sprigdomain5 := sprig_p2_d1(sprig_b4.Value, sprig_b4.Divisor)
			if sprigdomain5 != 0 {
				return Result{Tag: ResultError, Code: sprigdomain5}, nil
			}
			sprigcall6, sprigdomain7 := sprig_p2_d2(sprigcall4, 0)
			if sprigdomain7 != 0 {
				return Result{Tag: ResultError, Code: sprigdomain7}, nil
			}
			sprig_b5 = sprig_step{tag: sprig_step_add, by: sprigcall6}
		}
		_ = sprig_b5
		switch sprig_b5.tag {
		case sprig_step_add:
			sprig_b6 := sprig_b5.by
			_ = sprig_b6
			sprigsum8, sprigoverflow9 := sprig_checked_add(sprig_b2, sprig_b6)
			if sprigoverflow9 {
				return Result{Tag: ResultError, Code: DomainOverflow}, nil
			}
			sprig_b2 = sprigsum8
		case sprig_step_reject:
			sprig_b7 := sprig_b5.code
			_ = sprig_b7
			spriglist10 := append([]int64(nil), sprig_b3...)
			if len(spriglist10) >= 4096 {
				return Result{}, ErrListLimit
			}
			spriglist10 = append(spriglist10, sprig_b7)
			sprig_b3 = spriglist10
		}
		if err := sprig_poll(sprig_ctx, &sprig_remaining); err != nil {
			return Result{}, err
		}
	}
	return Result{Tag: ResultOK, Total: sprig_b2, Rejected: sprig_b3}, nil
}
