//go:build cgo && !race && (darwin || freebsd || linux)

package preparedplugin_test

import (
	"bytes"
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime/debug"
	"strings"
	"sync/atomic"
	"testing"

	"github.com/besmpl/ember"
	"github.com/besmpl/ember/preparedplugin"
)

func TestOpenLoadsChangedPreparedGenerationWithoutDisturbingActiveRuntime(t *testing.T) {
	skipPluginIntegrationWithIncompatibleInstrumentation(t)
	firstProgram := loadPluginTestProgram(t, 41)
	secondProgram := loadPluginTestProgram(t, 42)
	firstArtifact := buildPreparedPlugin(t, firstProgram)
	secondArtifact := buildPreparedPlugin(t, secondProgram)

	firstBundle, err := preparedplugin.Open(firstArtifact)
	if err != nil {
		t.Fatal(err)
	}
	reopened, err := preparedplugin.Open(firstArtifact)
	if err != nil {
		t.Fatal(err)
	}
	if reopened != firstBundle {
		t.Fatal("reopening one content-addressed artifact returned another bundle")
	}
	var slot ember.PreparedRuntimeSlot
	first, err := slot.Prepare(firstProgram, ember.RuntimeOptions{Prepared: firstBundle})
	if err != nil {
		t.Fatal(err)
	}
	if err := slot.Activate(first); err != nil {
		t.Fatal(err)
	}
	if got := pluginTestResult(t, &slot); got != 41 {
		t.Fatalf("first plugin result = %v, want 41", got)
	}
	if bundle, err := preparedplugin.Open(filepath.Join(t.TempDir(), "missing.so")); bundle != nil || err == nil {
		t.Fatalf("Open missing artifact = (%v, %v), want nil error bundle", bundle, err)
	}
	if got := pluginTestResult(t, &slot); got != 41 {
		t.Fatalf("active result after failed load = %v, want 41", got)
	}

	secondBundle, err := preparedplugin.Open(secondArtifact)
	if err != nil {
		t.Fatal(err)
	}
	wrong, err := slot.Prepare(firstProgram, ember.RuntimeOptions{Prepared: secondBundle})
	if wrong != nil || err == nil {
		t.Fatalf("cross-bind = (%v, %v), want nil typed mismatch", wrong, err)
	}
	var mismatch *ember.PreparedBundleError
	if !errors.As(err, &mismatch) {
		t.Fatalf("cross-bind error = %T %v, want *PreparedBundleError", err, err)
	}
	if got := pluginTestResult(t, &slot); got != 41 {
		t.Fatalf("active result after failed cross-bind = %v, want 41", got)
	}

	second, err := slot.Prepare(secondProgram, ember.RuntimeOptions{Prepared: secondBundle})
	if err != nil {
		t.Fatal(err)
	}
	defer second.Close()
	if got := pluginTestResult(t, &slot); got != 41 {
		t.Fatalf("active result before activation = %v, want 41", got)
	}
	if err := slot.Activate(second); err != nil {
		t.Fatal(err)
	}
	if got := pluginTestResult(t, &slot); got != 42 {
		t.Fatalf("second plugin result = %v, want 42", got)
	}
	if err := slot.Close(); err != nil {
		t.Fatal(err)
	}
}

func skipPluginIntegrationWithIncompatibleInstrumentation(t *testing.T) {
	t.Helper()
	info, ok := debug.ReadBuildInfo()
	if !ok {
		t.Fatal("read test build info")
	}
	for _, setting := range info.Settings {
		if setting.Key == "-gcflags" && strings.Contains(setting.Value, "checkptr") {
			t.Skip("Go plugins require matching package instrumentation; checkptr is covered by the portable slot tests")
		}
	}
}

type pluginTestLoader map[string]ember.Source

var pluginTestBuildSequence atomic.Uint64

func (loader pluginTestLoader) LoadModule(_ context.Context, module ember.ModuleID) (ember.Source, error) {
	source, ok := loader[module.String()]
	if !ok {
		return ember.Source{}, fmt.Errorf("missing module %s", module)
	}
	return source, nil
}

func loadPluginTestProgram(t *testing.T, result int) *ember.Program {
	t.Helper()
	module := ember.LogicalModule("prepared/plugin")
	program, _, err := ember.LoadProgram(context.Background(), pluginTestLoader{
		module.String(): {
			Name: "prepared/plugin",
			Text: fmt.Sprintf("return { update = function() return %d end }", result),
		},
	}, ember.ProgramOptions{
		Entrypoints: []ember.Entrypoint{{Name: "main", Module: module}},
		Parallelism: 1,
	})
	if err != nil {
		t.Fatal(err)
	}
	return program
}

func buildPreparedPlugin(t *testing.T, program *ember.Program) string {
	t.Helper()
	var generated bytes.Buffer
	if err := program.WritePreparedGo(&generated, ember.PreparedGoOptions{Package: "main"}); err != nil {
		t.Fatal(err)
	}
	sourceDigest := sha256.Sum256(generated.Bytes())
	directory := t.TempDir()
	workingDirectory, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	repositoryRoot := filepath.Clean(filepath.Join(workingDirectory, ".."))
	sequence := pluginTestBuildSequence.Add(1)
	module := fmt.Sprintf("example.com/ember-prepared-plugin/%x/run%d", sourceDigest[:], sequence)
	goModule := fmt.Sprintf("module %s\n\ngo 1.26\n\nrequire github.com/besmpl/ember v0.0.0\n\nreplace github.com/besmpl/ember => %s\n", module, repositoryRoot)
	if err := os.WriteFile(filepath.Join(directory, "go.mod"), []byte(goModule), 0o600); err != nil {
		t.Fatal(err)
	}
	moduleSums, err := os.ReadFile(filepath.Join(repositoryRoot, "go.sum"))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(directory, "go.sum"), moduleSums, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(directory, "prepared_generated.go"), generated.Bytes(), 0o600); err != nil {
		t.Fatal(err)
	}
	artifactIdentity := sha256.New()
	_, _ = artifactIdentity.Write(generated.Bytes())
	_, _ = artifactIdentity.Write([]byte(module))
	artifact := filepath.Join(directory, fmt.Sprintf("%x.so", artifactIdentity.Sum(nil)))
	command := exec.CommandContext(context.Background(), "go", "build", "-mod=mod", "-buildmode=plugin", "-o", artifact, ".")
	command.Dir = directory
	command.Env = append(os.Environ(), "GOWORK=off", "CGO_ENABLED=1")
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("build prepared plugin: %v\n%s", err, output)
	}
	return artifact
}

func pluginTestResult(t *testing.T, slot *ember.PreparedRuntimeSlot) float64 {
	t.Helper()
	var result float64
	err := slot.Use(func(runtime *ember.Runtime) error {
		values, err := runtime.Invoke(context.Background(), ember.Invocation{
			Module: ember.LogicalModule("prepared/plugin"),
			Export: "update",
		})
		if err != nil {
			return err
		}
		var ok bool
		if len(values) == 1 {
			result, ok = values[0].Number()
		}
		if !ok {
			return fmt.Errorf("Invoke values = %v, want one number", values)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return result
}
