// Code generated by internal/sprigproof. DO NOT EDIT.
package math

import sprig_math "math"

type DomainCode int64

const (
	DomainOverflow     DomainCode = 1
	DomainDivideByZero DomainCode = 2
)

func sprig_checked_add(a, b int64) (int64, bool) {
	sum := a + b
	return sum, (b > 0 && sum < a) || (b < 0 && sum > a)
}

var _ = sprig_math.MinInt64

func Add(sprig_b3 int64, sprig_b4 int64) (int64, DomainCode) {
	sprigpure_sum1, sprigpure_overflow2 := sprig_checked_add(sprig_b3, sprig_b4)
	if sprigpure_overflow2 {
		return 0, DomainOverflow
	}
	return sprigpure_sum1, 0
}

func Divide(sprig_b1 int64, sprig_b2 int64) (int64, DomainCode) {
	sprigpure_divisor3 := sprig_b2
	if sprigpure_divisor3 == 0 {
		return 0, DomainDivideByZero
	}
	if sprig_b1 == sprig_math.MinInt64 && sprigpure_divisor3 == -1 {
		return 0, DomainOverflow
	}
	return (sprig_b1 / sprigpure_divisor3), 0
}
