package sprigproof_test

import (
	"context"
	"errors"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"sync"
	"testing"

	"github.com/besmpl/ember/internal/sprigproof"
	projectgenerated "github.com/besmpl/ember/internal/sprigproof/generatedproject/counter"
)

func proofProject(t testing.TB) sprigproof.Project {
	t.Helper()
	project, diagnostics := sprigproof.CompileProject(sprigproof.ProofProjectSources())
	if len(diagnostics) != 0 {
		t.Fatalf("compile project: %v", diagnostics)
	}
	return project
}

func packageEntries(project sprigproof.Project) []sprigproof.PackageID {
	packages := project.Packages()
	entries := make([]sprigproof.PackageID, len(packages))
	for i, pkg := range packages {
		entries[i] = pkg.ID()
	}
	return entries
}

func TestProjectGeneratedFixturesAreFresh(t *testing.T) {
	project := proofProject(t)
	prepared, err := project.PrepareStandalone(packageEntries(project))
	if err != nil {
		t.Fatal(err)
	}
	for _, item := range prepared {
		path := filepath.Join("generatedproject", string(item.Package().ID()), item.Set().Files()[0].Name)
		want := item.Set().Files()[0].Content
		if os.Getenv("EMBER_UPDATE_SPRIG_PROJECT_FIXTURE") != "" {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != want {
			t.Fatalf("project fixture %s is stale", path)
		}
	}
}

func TestProjectPermutationIdentityAndImportedCallAgreement(t *testing.T) {
	project := proofProject(t)
	reversed := sprigproof.ProofProjectSources()
	slices.Reverse(reversed)
	other, diagnostics := sprigproof.CompileProject(reversed)
	if len(diagnostics) != 0 || project.Identity() != other.Identity() {
		t.Fatalf("permutation identity=%x/%x diagnostics=%v", project.Identity(), other.Identity(), diagnostics)
	}
	preparedA, err := project.PrepareStandalone(packageEntries(project))
	if err != nil {
		t.Fatal(err)
	}
	preparedB, err := other.PrepareStandalone(packageEntries(other))
	if err != nil || !reflect.DeepEqual(preparedA, preparedB) {
		t.Fatalf("permutation prepared results differ: %v/%v", preparedA, preparedB)
	}
	packages := project.Packages()
	if len(packages) != 2 || packages[0].ID() != "counter" || packages[1].ID() != "math" {
		t.Fatalf("canonical packages=%v", packages)
	}
	program, ok := project.Program("counter")
	if !ok {
		t.Fatal("counter Reduce missing")
	}
	got, err := program.Reduce(context.Background(), []sprigproof.Reading{{Value: 12, Divisor: 3}, {Value: 1, Divisor: 0}}, 3)
	want := sprigproof.Result{Tag: sprigproof.ResultOK, Total: 4, Rejected: []int64{7}}
	if err != nil || !reflect.DeepEqual(got, want) {
		t.Fatalf("project evaluator=%#v,%v want %#v", got, err, want)
	}
	prepared, err := project.PrepareStandalone([]sprigproof.PackageID{"counter", "math"})
	if err != nil || len(prepared) != 2 {
		t.Fatalf("prepared=%v,%v", prepared, err)
	}
	counter := prepared[0].Set().Files()[0].Content
	math := prepared[1].Set().Files()[0].Content
	if strings.Contains(counter, `"example.com`) || strings.Contains(counter, "sprigproof") && !strings.Contains(counter, "Code generated by internal/sprigproof") {
		t.Fatalf("counter retained dependency:\n%s", counter)
	}
	if !strings.Contains(counter, "func sprig_p2_d1") || !strings.Contains(counter, "func sprig_p2_d2") || !strings.Contains(counter, "sprig_p2_d1(") || !strings.Contains(counter, "sprig_p2_d2(") {
		t.Fatalf("counter omitted privately lowered imported call:\n%s", counter)
	}
	if !strings.Contains(math, "func Divide(") || !strings.Contains(math, "func Add(") || strings.Contains(math, "counter") {
		t.Fatalf("standalone math package is not independent:\n%s", math)
	}
}

func TestPrepareStandaloneEmitsOnlyRequestedClosuresInCanonicalOrder(t *testing.T) {
	project, diagnostics := sprigproof.CompileProject(transitiveProjectSources())
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	entries := []sprigproof.PackageID{"math", "counter"}
	before := slices.Clone(entries)
	prepared, err := project.PrepareStandalone(entries)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(entries, before) {
		t.Fatalf("PrepareStandalone mutated caller input: %v", entries)
	}
	if len(prepared) != 2 || prepared[0].Package().ID() != "counter" || prepared[1].Package().ID() != "math" {
		t.Fatalf("prepared entries=%v", prepared)
	}
	for _, item := range prepared {
		if item.Package().ID() == "spare" || item.Package().ID() == "util" {
			t.Fatalf("unrequested package emitted: %s", item.Package().ID())
		}
	}
	if content := prepared[0].Set().Files()[0].Content; !strings.Contains(content, "func sprig_p4_d1") {
		t.Fatalf("counter entry omitted reachable util closure:\n%s", content)
	}

	reversedProjectSources := transitiveProjectSources()
	slices.Reverse(reversedProjectSources)
	reversedProject, diagnostics := sprigproof.CompileProject(reversedProjectSources)
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	other, err := reversedProject.PrepareStandalone([]sprigproof.PackageID{"counter", "math"})
	if err != nil || !reflect.DeepEqual(prepared, other) {
		t.Fatalf("requested entry preparation changed with input order: %v", err)
	}
}

func TestPrepareStandaloneFailsClosed(t *testing.T) {
	project := proofProject(t)
	tests := []struct {
		name    string
		entries []sprigproof.PackageID
		want    string
	}{
		{"empty", nil, "no package entries"},
		{"unknown", []sprigproof.PackageID{"missing"}, "unknown package entry"},
		{"duplicate", []sprigproof.PackageID{"math", "counter", "math"}, "duplicate package entry"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			prepared, err := project.PrepareStandalone(test.entries)
			if err == nil || !strings.Contains(err.Error(), test.want) || prepared != nil {
				t.Fatalf("PrepareStandalone(%v)=%v,%v", test.entries, prepared, err)
			}
		})
	}
	if prepared, err := (sprigproof.Project{}).PrepareStandalone([]sprigproof.PackageID{"counter"}); err == nil || !strings.Contains(err.Error(), "zero project") || prepared != nil {
		t.Fatalf("zero Project PrepareStandalone=%v,%v", prepared, err)
	}
}

func TestPrepareLinkedEmitsOnlyReachableApplicationBoundPackages(t *testing.T) {
	sources := transitiveProjectSources()
	project, diagnostics := sprigproof.CompileProject(sources)
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	bindings := []sprigproof.PackageBinding{
		{ID: "util", ImportPath: "example.com/application/generated/util"},
		{ID: "counter", ImportPath: "example.com/application/generated/counter"},
		{ID: "math", ImportPath: "example.com/application/generated/math"},
	}
	before := slices.Clone(bindings)
	prepared, err := project.PrepareLinked([]sprigproof.PackageID{"counter"}, bindings)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(bindings, before) {
		t.Fatalf("PrepareLinked mutated caller bindings: %v", bindings)
	}
	if len(prepared) != 3 || prepared[0].Package().ID() != "counter" || prepared[1].Package().ID() != "math" || prepared[2].Package().ID() != "util" {
		t.Fatalf("linked packages=%v", prepared)
	}
	counter := prepared[0].Set().Files()[0].Content
	mathSource := prepared[1].Set().Files()[0].Content
	util := prepared[2].Set().Files()[0].Content
	if !strings.Contains(counter, `"example.com/application/generated/math"`) || strings.Contains(counter, `"example.com/application/generated/util"`) || strings.Contains(counter, "func sprig_p2_d") {
		t.Fatalf("counter did not link only its direct dependency:\n%s", counter)
	}
	if !strings.Contains(mathSource, `"example.com/application/generated/util"`) || strings.Contains(mathSource, "func sprig_p4_d") {
		t.Fatalf("math did not link util without copying it:\n%s", mathSource)
	}
	if strings.Contains(util, `"example.com/application/generated/`) {
		t.Fatalf("leaf package acquired an application dependency:\n%s", util)
	}
	for _, item := range prepared {
		if item.Package().ID() == "spare" {
			t.Fatal("unrelated package was emitted")
		}
	}
	projectWide := append(slices.Clone(bindings), sprigproof.PackageBinding{ID: "spare", ImportPath: "example.com/application/generated/spare"})
	withUnreachableBinding, err := project.PrepareLinked([]sprigproof.PackageID{"counter"}, projectWide)
	if err != nil || !reflect.DeepEqual(prepared, withUnreachableBinding) {
		t.Fatalf("known project-wide binding changed requested closure: %v", err)
	}

	reversed := slices.Clone(sources)
	slices.Reverse(reversed)
	other, diagnostics := sprigproof.CompileProject(reversed)
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	reversedBindings := slices.Clone(bindings)
	slices.Reverse(reversedBindings)
	permuted, err := other.PrepareLinked([]sprigproof.PackageID{"counter"}, reversedBindings)
	if err != nil || !reflect.DeepEqual(prepared, permuted) {
		t.Fatalf("linked preparation changed with input permutation: %v", err)
	}
}

func TestPrepareLinkedBindingChangesAffectOnlyDirectImportingSets(t *testing.T) {
	project, diagnostics := sprigproof.CompileProject(transitiveProjectSources())
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	baseBindings := []sprigproof.PackageBinding{
		{ID: "counter", ImportPath: "example.com/base/counter"},
		{ID: "math", ImportPath: "example.com/base/math"},
		{ID: "util", ImportPath: "example.com/base/util"},
	}
	base, err := project.PrepareLinked([]sprigproof.PackageID{"counter"}, baseBindings)
	if err != nil {
		t.Fatal(err)
	}
	mathMovedBindings := slices.Clone(baseBindings)
	mathMovedBindings[1].ImportPath = "example.com/moved/math"
	mathMoved, err := project.PrepareLinked([]sprigproof.PackageID{"counter"}, mathMovedBindings)
	if err != nil {
		t.Fatal(err)
	}
	for i := range base {
		if base[i].Identity() != mathMoved[i].Identity() {
			t.Fatalf("application placement changed checked identity for %s", base[i].Package().ID())
		}
		changed := base[i].Set().Digest() != mathMoved[i].Set().Digest()
		if changed != (base[i].Package().ID() == "counter") {
			t.Fatalf("math path change attribution for %s: changed=%v", base[i].Package().ID(), changed)
		}
	}
	utilMovedBindings := slices.Clone(baseBindings)
	utilMovedBindings[2].ImportPath = "example.com/moved/util"
	utilMoved, err := project.PrepareLinked([]sprigproof.PackageID{"counter"}, utilMovedBindings)
	if err != nil {
		t.Fatal(err)
	}
	for i := range base {
		changed := base[i].Set().Digest() != utilMoved[i].Set().Digest()
		if changed != (base[i].Package().ID() == "math") {
			t.Fatalf("util path change attribution for %s: changed=%v", base[i].Package().ID(), changed)
		}
	}
}

func TestPrepareLinkedExportsNominalWrapperForLowercaseTarget(t *testing.T) {
	sources := sprigproof.ProofProjectSources()
	sources[0].Source = strings.Replace(sources[0].Source, "m.Divide", "m.divide", 1)
	sources[1].Source = strings.Replace(sources[1].Source, "func Divide", "func divide", 1)
	project, diagnostics := sprigproof.CompileProject(sources)
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	prepared, err := project.PrepareLinked(
		[]sprigproof.PackageID{"counter"},
		[]sprigproof.PackageBinding{
			{ID: "counter", ImportPath: "example.com/application/counter"},
			{ID: "math", ImportPath: "example.com/application/math"},
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	counter := prepared[0].Set().Files()[0].Content
	mathSource := prepared[1].Set().Files()[0].Content
	if !strings.Contains(counter, ".SprigLinkD1(") || !strings.Contains(mathSource, "func SprigLinkD1(") || !strings.Contains(mathSource, "return divide(") {
		t.Fatalf("lowercase nominal link wrapper missing:\n--- counter ---\n%s\n--- math ---\n%s", counter, mathSource)
	}
}

func TestPrepareLinkedFailsClosed(t *testing.T) {
	project, diagnostics := sprigproof.CompileProject(transitiveProjectSources())
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	valid := []sprigproof.PackageBinding{
		{ID: "counter", ImportPath: "example.com/application/counter"},
		{ID: "math", ImportPath: "example.com/application/math"},
		{ID: "util", ImportPath: "example.com/application/util"},
	}
	tests := []struct {
		name     string
		entries  []sprigproof.PackageID
		bindings []sprigproof.PackageBinding
		want     string
	}{
		{"empty entries", nil, valid, "no package entries"},
		{"unknown entry", []sprigproof.PackageID{"missing"}, valid, "unknown package entry"},
		{"duplicate entry", []sprigproof.PackageID{"counter", "counter"}, valid, "duplicate package entry"},
		{"missing", []sprigproof.PackageID{"counter"}, valid[:2], "missing package binding \"util\""},
		{"duplicate binding", []sprigproof.PackageID{"counter"}, append(slices.Clone(valid), valid[0]), "duplicate package binding \"counter\""},
		{"unknown binding", []sprigproof.PackageID{"counter"}, append(slices.Clone(valid), sprigproof.PackageBinding{ID: "unknown", ImportPath: "example.com/application/unknown"}), "unknown package binding \"unknown\""},
		{"duplicate path", []sprigproof.PackageID{"counter"}, []sprigproof.PackageBinding{{ID: "counter", ImportPath: "example.com/shared"}, {ID: "math", ImportPath: "example.com/shared"}, {ID: "util", ImportPath: "example.com/util"}}, "bound to both"},
		{"empty path", []sprigproof.PackageID{"counter"}, []sprigproof.PackageBinding{{ID: "counter"}, {ID: "math", ImportPath: "example.com/math"}, {ID: "util", ImportPath: "example.com/util"}}, "invalid Go import path"},
		{"reserved path", []sprigproof.PackageID{"counter"}, []sprigproof.PackageBinding{{ID: "counter", ImportPath: "example.com/counter"}, {ID: "math", ImportPath: "math"}, {ID: "util", ImportPath: "example.com/util"}}, "invalid Go import path"},
		{"dot component", []sprigproof.PackageID{"counter"}, []sprigproof.PackageBinding{{ID: "counter", ImportPath: "example.com/counter"}, {ID: "math", ImportPath: "example.com/../math"}, {ID: "util", ImportPath: "example.com/util"}}, "invalid Go import path"},
		{"invalid character", []sprigproof.PackageID{"counter"}, []sprigproof.PackageBinding{{ID: "counter", ImportPath: "example.com/counter"}, {ID: "math", ImportPath: "example.com/math?bad"}, {ID: "util", ImportPath: "example.com/util"}}, "invalid Go import path"},
		{"too long", []sprigproof.PackageID{"counter"}, []sprigproof.PackageBinding{{ID: "counter", ImportPath: "example.com/counter"}, {ID: "math", ImportPath: "example.com/" + strings.Repeat("x", 512)}, {ID: "util", ImportPath: "example.com/util"}}, "invalid Go import path"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			beforeEntries := slices.Clone(test.entries)
			beforeBindings := slices.Clone(test.bindings)
			prepared, err := project.PrepareLinked(test.entries, test.bindings)
			if err == nil || !strings.Contains(err.Error(), test.want) || prepared != nil {
				t.Fatalf("PrepareLinked=%v,%v; want %q", prepared, err, test.want)
			}
			if !slices.Equal(test.entries, beforeEntries) || !reflect.DeepEqual(test.bindings, beforeBindings) {
				t.Fatal("PrepareLinked mutated invalid caller input")
			}
		})
	}
	if prepared, err := (sprigproof.Project{}).PrepareLinked([]sprigproof.PackageID{"counter"}, valid); err == nil || !strings.Contains(err.Error(), "zero project") || prepared != nil {
		t.Fatalf("zero Project PrepareLinked=%v,%v", prepared, err)
	}
}

func TestProjectImportedCallsPreserveDomainsLimitsAndConcurrency(t *testing.T) {
	project := proofProject(t)
	program, ok := project.Program("counter")
	if !ok {
		t.Fatal("counter Reduce missing")
	}
	tests := []struct {
		name  string
		input []sprigproof.Reading
		limit uint64
		want  sprigproof.Result
	}{
		{"empty", nil, 1, sprigproof.Result{Tag: sprigproof.ResultOK}},
		{"positive and reject", []sprigproof.Reading{{Value: 12, Divisor: 3}, {Value: 1, Divisor: 0}}, 3, sprigproof.Result{Tag: sprigproof.ResultOK, Total: 4, Rejected: []int64{7}}},
		{"imported division overflow", []sprigproof.Reading{{Value: math.MinInt64, Divisor: -1}}, 2, sprigproof.Result{Tag: sprigproof.ResultError, Code: sprigproof.DomainOverflow}},
		{"post-import addition overflow", []sprigproof.Reading{{Value: math.MaxInt64, Divisor: 1}, {Value: 1, Divisor: 1}}, 3, sprigproof.Result{Tag: sprigproof.ResultError, Code: sprigproof.DomainOverflow}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			got, err := program.Reduce(context.Background(), test.input, test.limit)
			if err != nil || !reflect.DeepEqual(got, test.want) {
				t.Fatalf("evaluator=%#v,%v want %#v", got, err, test.want)
			}
			input := make([]projectgenerated.Reading, len(test.input))
			for i, reading := range test.input {
				input[i] = projectgenerated.Reading{Value: reading.Value, Divisor: reading.Divisor}
			}
			native, nativeErr := projectgenerated.Reduce(context.Background(), input, test.limit)
			projection := sprigproof.Result{Tag: sprigproof.ResultTag(native.Tag), Total: native.Total, Rejected: slices.Clone(native.Rejected), Code: sprigproof.DomainCode(native.Code)}
			if nativeErr != nil || !reflect.DeepEqual(projection, got) {
				t.Fatalf("generated=%#v,%v evaluator=%#v,%v", native, nativeErr, got, err)
			}
		})
	}
	canceled, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := program.Reduce(canceled, nil, 0); err != context.Canceled || !errors.Is(err, context.Canceled) {
		t.Fatalf("evaluator cancellation=%v", err)
	}
	if _, err := projectgenerated.Reduce(canceled, nil, 0); err != context.Canceled || !errors.Is(err, context.Canceled) {
		t.Fatalf("generated cancellation=%v", err)
	}
	if _, err := program.Reduce(context.Background(), []sprigproof.Reading{{Value: 4, Divisor: 2}}, 1); !errors.Is(err, sprigproof.ErrStepLimit) {
		t.Fatalf("evaluator limit=%v", err)
	}
	if _, err := projectgenerated.Reduce(context.Background(), []projectgenerated.Reading{{Value: 4, Divisor: 2}}, 1); !errors.Is(err, projectgenerated.ErrStepLimit) {
		t.Fatalf("generated limit=%v", err)
	}
	const workers = 16
	var wg sync.WaitGroup
	errs := make(chan error, workers)
	for range workers {
		wg.Add(1)
		go func() {
			defer wg.Done()
			result, err := program.Reduce(context.Background(), []sprigproof.Reading{{Value: 8, Divisor: 2}}, 2)
			if err != nil || result.Total != 4 {
				errs <- errors.New("concurrent imported evaluation failed")
				return
			}
			native, err := projectgenerated.Reduce(context.Background(), []projectgenerated.Reading{{Value: 8, Divisor: 2}}, 2)
			if err != nil || native.Total != 4 {
				errs <- errors.New("concurrent imported generation failed")
			}
		}()
	}
	wg.Wait()
	close(errs)
	for err := range errs {
		t.Fatal(err)
	}
}

func TestProjectRootOnlyChangePreservesIndependentPackage(t *testing.T) {
	base := proofProject(t)
	changedSources := sprigproof.ProofProjectSources()
	changedSources[0].Source = strings.Replace(changedSources[0].Source, "let total = 0", "let total = 10", 1)
	changed, diagnostics := sprigproof.CompileProject(changedSources)
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	basePrepared, _ := base.PrepareStandalone([]sprigproof.PackageID{"counter", "math"})
	changedPrepared, _ := changed.PrepareStandalone([]sprigproof.PackageID{"counter", "math"})
	if basePrepared[0].Identity() == changedPrepared[0].Identity() || basePrepared[0].Set().Digest() == changedPrepared[0].Set().Digest() {
		t.Fatal("counter identity did not change")
	}
	if basePrepared[1].Identity() != changedPrepared[1].Identity() || basePrepared[1].Set().Digest() != changedPrepared[1].Set().Digest() || basePrepared[1].Set().Files()[0].Content != changedPrepared[1].Set().Files()[0].Content {
		t.Fatal("independent math package changed with counter")
	}
	if basePrepared[0].Package().SourceIdentity() == changedPrepared[0].Package().SourceIdentity() || basePrepared[1].Package().SourceIdentity() != changedPrepared[1].Package().SourceIdentity() {
		t.Fatal("source identities do not attribute root-only change")
	}
}

func TestDependencyChangeEntersRootClosureIdentity(t *testing.T) {
	base := proofProject(t)
	sources := sprigproof.ProofProjectSources()
	sources[1].Source = strings.Replace(sources[1].Source, "return left + right", "return left + right + 0", 1)
	changed, diagnostics := sprigproof.CompileProject(sources)
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	a, _ := base.PrepareStandalone([]sprigproof.PackageID{"counter", "math"})
	b, _ := changed.PrepareStandalone([]sprigproof.PackageID{"counter", "math"})
	if a[1].Identity() == b[1].Identity() || a[1].Set().Digest() == b[1].Set().Digest() {
		t.Fatal("math change missing from math identity")
	}
	if a[0].Package().SourceIdentity() != b[0].Package().SourceIdentity() {
		t.Fatal("counter source identity changed")
	}
	if a[0].Identity() == b[0].Identity() || a[0].Set().Digest() == b[0].Set().Digest() {
		t.Fatal("math change missing from counter entry closure")
	}
}

func TestTransitiveImportedClosureIsSelfContainedAndChangeAttributed(t *testing.T) {
	baseSources := transitiveProjectSources()
	base, diagnostics := sprigproof.CompileProject(baseSources)
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	prepared, err := base.PrepareStandalone(packageEntries(base))
	if err != nil || len(prepared) != 4 {
		t.Fatalf("prepared=%v,%v", prepared, err)
	}
	byID := make(map[sprigproof.PackageID]sprigproof.PreparedPackage, len(prepared))
	for _, item := range prepared {
		byID[item.Package().ID()] = item
	}
	counter := byID["counter"].Set().Files()[0].Content
	mathSource := byID["math"].Set().Files()[0].Content
	if !strings.Contains(counter, "func sprig_p2_d3") || !strings.Contains(counter, "func sprig_p4_d1") {
		t.Fatalf("counter omitted transitive imported closure:\n%s", counter)
	}
	if !strings.Contains(mathSource, "func sprig_p4_d1") {
		t.Fatalf("math omitted imported closure:\n%s", mathSource)
	}
	reversed := slices.Clone(baseSources)
	slices.Reverse(reversed)
	permuted, diagnostics := sprigproof.CompileProject(reversed)
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	permutedPrepared, err := permuted.PrepareStandalone(packageEntries(permuted))
	if err != nil || !reflect.DeepEqual(prepared, permutedPrepared) {
		t.Fatal("input permutation changed transitive Sets")
	}
	changedSources := transitiveProjectSources()
	for i := range changedSources {
		if changedSources[i].ID == "util" {
			changedSources[i].Source = strings.Replace(changedSources[i].Source, "return value / divisor", "return value / divisor + 0", 1)
		}
	}
	changed, diagnostics := sprigproof.CompileProject(changedSources)
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	changedPrepared, err := changed.PrepareStandalone(packageEntries(changed))
	if err != nil {
		t.Fatal(err)
	}
	changedByID := make(map[sprigproof.PackageID]sprigproof.PreparedPackage, len(changedPrepared))
	for _, item := range changedPrepared {
		changedByID[item.Package().ID()] = item
	}
	for _, id := range []sprigproof.PackageID{"util", "math", "counter"} {
		if byID[id].Identity() == changedByID[id].Identity() || byID[id].Set().Digest() == changedByID[id].Set().Digest() {
			t.Fatalf("transitive change did not reach %s", id)
		}
	}
	if byID["spare"].Identity() != changedByID["spare"].Identity() || byID["spare"].Set().Digest() != changedByID["spare"].Set().Digest() || byID["spare"].Set().Files()[0].Content != changedByID["spare"].Set().Files()[0].Content {
		t.Fatal("transitive change reached unrelated package")
	}
}

func TestGeneratedTopLevelNamesAreHygienic(t *testing.T) {
	source := `package names
func sprig_math(value i64) i64 { return value / 1 }
func sprig_checked_add(left i64, right i64) i64 { return left + right }
func sprig_p1_d1(value i64) i64 { return value }
`
	project, diagnostics := sprigproof.CompileProject([]sprigproof.SourcePackage{{ID: "names", Source: source}})
	if len(diagnostics) != 0 {
		t.Fatal(diagnostics)
	}
	prepared, err := project.PrepareStandalone([]sprigproof.PackageID{"names"})
	if err != nil {
		t.Fatal(err)
	}
	content := prepared[0].Set().Files()[0].Content
	for _, want := range []string{`sprig_math_2 "math"`, "func sprig_checked_add_2", "func sprig_math(", "func sprig_checked_add(", "func sprig_p1_d1("} {
		if !strings.Contains(content, want) {
			t.Fatalf("generated name hygiene omitted %q:\n%s", want, content)
		}
	}
}

func transitiveProjectSources() []sprigproof.SourcePackage {
	counter := strings.Replace(sprigproof.ProjectCounterSource, "m.Add(m.Divide(reading.value, reading.divisor), 0)", "m.Ordered(reading.value, reading.divisor)", 1)
	return []sprigproof.SourcePackage{
		{ID: "spare", Source: "package spare\nfunc Identity(value i64) i64 { return value }\n"},
		{ID: "math", Source: `package math
import u util
func Divide(value i64, divisor i64) i64 { return u.Divide(value, divisor) }
func Add(left i64, right i64) i64 { return left + right }
func Ordered(value i64, divisor i64) i64 { return u.Divide(value, divisor) + u.Divide(1, value / 5) }
`},
		{ID: "counter", Source: counter},
		{ID: "util", Source: "package util\nfunc Divide(value i64, divisor i64) i64 { return value / divisor }\n"},
	}
}

func TestGeneratedPrivateNamesIgnoreUserSupportSpellings(t *testing.T) {
	sources := sprigproof.ProofProjectSources()
	replacer := strings.NewReplacer("readings []Reading", "ctx []Reading", "for reading in readings", "for remaining in ctx", "reading.divisor", "remaining.divisor", "reading.value", "remaining.value", "let total", "let poll", "total = total + by", "poll = poll + by", "total: total", "total: poll")
	sources[0].Source = replacer.Replace(sources[0].Source)
	project, diagnostics := sprigproof.CompileProject(sources)
	if len(diagnostics) != 0 {
		t.Fatalf("support-spelling program rejected: %v", diagnostics)
	}
	prepared, err := project.PrepareStandalone([]sprigproof.PackageID{"counter"})
	if err != nil {
		t.Fatal(err)
	}
	content := prepared[0].Set().Files()[0].Content
	if strings.Contains(content, "for _, remaining") || strings.Contains(content, "var poll") {
		t.Fatalf("user private spelling leaked into Go names:\n%s", content)
	}
}

func TestProjectBoundaryDiagnosticsAreDeterministicAndFailClosed(t *testing.T) {
	tests := []struct {
		name    string
		sources []sprigproof.SourcePackage
		want    string
	}{
		{"noncanonical ID", []sprigproof.SourcePackage{{ID: "Counter", Source: sprigproof.ProjectCounterSource}}, "invalid canonical PackageID"},
		{"Go keyword ID", []sprigproof.SourcePackage{{ID: "type", Source: "package type\nfunc Value(x i64) i64 { return x }\n"}}, "invalid canonical PackageID"},
		{"non-importable Go package ID", []sprigproof.SourcePackage{{ID: "main", Source: "package main\nfunc Value(x i64) i64 { return x }\n"}}, "invalid canonical PackageID"},
		{"header mismatch", []sprigproof.SourcePackage{{ID: "other", Source: sprigproof.MathSource}}, "does not match PackageID"},
		{"missing import", []sprigproof.SourcePackage{{ID: "counter", Source: sprigproof.ProjectCounterSource}}, "unknown import \"math\""},
		{"unknown alias", []sprigproof.SourcePackage{{ID: "counter", Source: strings.Replace(sprigproof.ProjectCounterSource, "m.Add", "x.Add", 1)}, {ID: "math", Source: sprigproof.MathSource}}, "unknown import alias \"x\""},
		{"duplicate alias", []sprigproof.SourcePackage{{ID: "counter", Source: strings.Replace(sprigproof.ProjectCounterSource, "import m math", "import m math\nimport m math", 1)}, {ID: "math", Source: sprigproof.MathSource}}, "duplicate import alias \"m\""},
		{"wrong arity", []sprigproof.SourcePackage{{ID: "counter", Source: strings.Replace(sprigproof.ProjectCounterSource, "m.Divide(reading.value, reading.divisor)", "m.Divide(reading.value)", 1)}, {ID: "math", Source: sprigproof.MathSource}}, "has 1 arguments, want 2"},
		{"wrong argument type", []sprigproof.SourcePackage{{ID: "counter", Source: strings.Replace(sprigproof.ProjectCounterSource, "m.Divide(reading.value, reading.divisor)", "m.Divide(readings, reading.divisor)", 1)}, {ID: "math", Source: sprigproof.MathSource}}, "argument 1 has type []Reading, want i64"},
		{"generated ABI collision", []sprigproof.SourcePackage{{ID: "math", Source: "package math\nfunc DomainCode(value i64) i64 { return value }\n"}}, "conflicts with generated package ABI"},
		{"Go init function", []sprigproof.SourcePackage{{ID: "math", Source: "package math\nfunc init(value i64) i64 { return value }\n"}}, "cannot be represented by the generated package ABI"},
		{"cycle", []sprigproof.SourcePackage{{ID: "counter", Source: strings.Replace(sprigproof.ProjectCounterSource, "import m math", "import m math\nimport loop cycle", 1)}, {ID: "math", Source: sprigproof.MathSource}, {ID: "cycle", Source: "package cycle\nimport root counter\nfunc Value(x i64) i64 { return x }\n"}}, "import cycle"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			first, d1 := sprigproof.CompileProject(test.sources)
			second, d2 := sprigproof.CompileProject(slices.Clone(test.sources))
			if !first.IsZero() || !second.IsZero() {
				t.Fatal("invalid project was published")
			}
			if !reflect.DeepEqual(d1, d2) {
				t.Fatalf("diagnostics unstable: %v/%v", d1, d2)
			}
			found := false
			for _, d := range d1 {
				if strings.Contains(d.Message, test.want) {
					found = true
				}
			}
			if !found {
				t.Fatalf("missing %q in %v", test.want, d1)
			}
		})
	}
}

func TestDuplicateProjectPackageDiagnosticIgnoresInputPermutation(t *testing.T) {
	sources := []sprigproof.SourcePackage{
		{ID: "math", Source: sprigproof.MathSource},
		{ID: "math", Source: "package math\nfunc Other(value i64) i64 { return value }\n"},
	}
	_, first := sprigproof.CompileProject(sources)
	slices.Reverse(sources)
	_, second := sprigproof.CompileProject(sources)
	if !reflect.DeepEqual(first, second) || len(first) != 1 || !strings.Contains(first[0].Message, "duplicate project package") {
		t.Fatalf("duplicate diagnostics changed with input order: %v/%v", first, second)
	}
}
